### ISSUE TITLE
Include more backtrace information when using include_examples

### ISSUE THREAD

**Issue by aripollak** [rspec/rspec-core#1209]
Currently, when using `it_behaves_like` for a shared example and one of the examples fails, the error message helpfully includes the "Shared Example Group" line with the exact place that the shared example was called from. However, no such output occurs when using `include_examples` - it only includes the line of the shared example failure.. Would it be possible to add similar output to `include_examples`? Sometimes it's more natural to use `include_examples` instead, but I don't want to lose useful backtrace information.

**Comment by contentfree** [comment]
@myronmarston Almost nine years later but wanted to check before creating a _new_ issue: Is the expectation that the backtrace includes frames _inside_ the shared example group? I currently have a failure inside a shared example group and all of that info is left out, with the top-most frame being "Shared Example Group: "my group" called from /path/to/spec". Ideally, the backtrace would include the frames inside the shared example group, too.

**Comment by pirj** [comment]
Would you like to send a PR with a red spec describing how you see the output, @contentfree ?

**Comment by JonRowe** [comment]
@contentfree this issue was about the line which included the shared examples, not the backtrace frame inside the shared example group, which I'd expect to be included by default I don't think we filter them, you can check wether your setup is filtering them by using `--backtrace`
