### ISSUE TITLE
About output_stream setting

### ISSUE THREAD

**Issue by untidy-hair** [rspec/rspec-core#1235]
Hi, I had an small issue with the combination of rspec + spork (and have a workaround) as on here:
https://github.com/sporkrb/spork/issues/248

I saw the changes about "output_stream" in rspec-core and also read the discussions like #1127 , #1128 , #1142.

The original spork code is:

``` ruby
::RSpec::Core::CommandLine.new(argv).run(stderr, stdout)
```

It doesn't work well because $stdout value changes between when 'spork'ing and when 'rspec'ing, so my workaround is:

``` ruby
configuration = ::RSpec::configuration
configuration.output_stream = stdout
::RSpec::Core::CommandLine.new(argv, configuration).run(stderr, stdout)
```

I understand now we should set up io streams with RSpec::Core::Configuration and I think that's a great idea.

But maybe we should make Core::CommandLine#run arguments options(or remove?), too, so that we don't have to repeat specifying 'stdout' above?

Thanks!

**Comment by agis-** [comment]
Same issue here, after upgrading to rspec 2.99.0 and using spork 0.9.2. @untidy-hair have you dig any further into it?
