### ISSUE TITLE
Achieve 100% doc coverage

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1334]
SemVer requires your public API be documented.  I'd like us to be _actually_ SemVer compliant starting with RSpec 3 rather than just "moving towards SemVer compliance" as we've been in 2.x, so we need every public API documented for 3.0.  The docs don't have to be great, but we do need public APIs to be labeled as such and APIs we don't intend to be public labeled as non-public.

It would be good to add something to the build to enforce 100% doc coverage.  Might be worth using [yardstick](https://github.com/dkubb/yardstick) for this, or we can use a simple rake task like [I have in VCR](https://github.com/vcr/vcr/blob/f227c0a07e99f037a6260f29422bfed73e62a399/Rakefile#L27-L36).

**Comment by pirj** [comment]
Done again in #3086

**Comment by nevinera** [comment]
(@pirj - it looks like we already had 100% documentation coverage before that PR - I think we enforce 100% doc-coverage in CI. Grep for `documentation_enforced` and `check_documentation_coverage` for the bits that do that work - locally you can check it with `yard stats --list-undoc`)

**Comment by pirj** [comment]
My bad, this ticket seems unrelated to the recent pr 🙈

**Comment by JonRowe** [comment]
> I find the build process for rspec-core a bit of a maze though, it might be nice to break some of these checks out into their own actions at some point?

The build process pre-dates our switch to Github actions as Travis had a matrix of Rubies but not really extra jobs when we first constructed it, plus there was the intent to allow us to run it locally as one job. When the monorepo work is finished it will be a shared action or set of actions which is run by each repo against a matrix. 

It would be nice to produce a "cli esque" build where each part is breakable out but its beyond scope atm.

(Also apologies Myron for any notification spam received from these old issues 😂)
