### ISSUE TITLE
Pending Shared Example

### ISSUE THREAD

**Issue by andyl** [rspec/rspec-core#1583]
I've got a collection of duck-type classes that all implement a set of methods.
I'm able to build a shared example group that describes a these methods.

``` ruby
shared_examples_for "a duck type" do
  it { should respond_to(:method1) }
end
describe Class1 do
  it_should_behave_like "a duck type"
end
describe Class2 do
  it_should_behave_like "a duck type"
end
```

In my situation, I have implemented `Class1#method1`, but `Class2#method1` is pending.

I'd like the ability to say:

``` ruby
describe Class2 do
    it_should_behave_like "a duck type", :pending
end
```

I can apply `pending` to a shared example, but not to `it_should_behave_like`.  This is sub-optimal when working with a collection of duck-types where some class implementations are complete and others are pending.

Enhancement requests:
1) enable the `:pending` attribute for `it_should_behave_like` 
2) enable the `:skip` attribute for `it_should_behave_like`
3) add `xit_should_behave_like`

**Comment by Startouf** [comment]
I believe the issue should be reopened and one of the following stuff should be done
- Either allow marking all examples as pending by wrapping them around pending blocks 
```
pending('Reason for pending') do 
  it_behaves_like '...'
  context do 
     ...
  end
end
```

- Or enhance the RSpec core deocumentation with the trick from TimMoore https://github.com/rspec/rspec-core/issues/1583#issuecomment-59687572 

@andyl

**Comment by JonRowe** [comment]
Happy to accept a PR to improve the documentation if you'd like to attempt it, but I don't feel the api should be expanded to change this behaviour.
