### ISSUE TITLE
Fix limitation related to filtering tags by name:value pairs

### ISSUE THREAD

**Issue by maxlinc** [rspec/rspec-core#1621]
A limitation was added to the documentation in #1618. That limitation is:
> If you try to exclude `:name => 'foo'` and `:name => 'bar'`, you will only end up excluding `:name => 'bar'`.

It would be nice if the filtering implementation is improved so that limitation no longer applies, and that using those excludes (equivalent to `--tag ~name:foo --tag ~name:bar` on the CLI) then rspec excludes tests that are tagged with `:name => 'foo'` or `:name => 'bar'`. rather than just `:name => 'bar'`.

**Comment by samphippen** [comment]
@maxlinc is this a dup of https://github.com/rspec/rspec-core/issues/1622?

**Comment by JonRowe** [comment]
I'm going to say yes and close as a duplicate, especially given the conversation is being held there :)
