### ISSUE TITLE
Consider processing `--format` option before `--require`

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1669]
If `--require` loads code that issues a deprecation, it'll cause the default formatters to be setup (due to how deprecations are issued via the reporter), which can be confusing if the user has a `--format` option.  For example, see #1668.  I think that if we change `configuration_options.rb` to process `--format` before `--require` it'll fix this problem.

/cc @JonRowe

**Comment by xaviershay** [comment]
Maybe https://github.com/rspec/rspec-core/pull/2243 or something like it could address?

**Comment by myronmarston** [comment]
Honestly, my instinct is to close this.  Doesn't seem an important issue and I forget the details that made me suggest this in the first place.  Closing, but anyone from  @rspec/rspec can reopen :).
