### ISSUE TITLE
Improve the project initialization to take configuration options

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-core#1688]
This comes out of [this convo](https://github.com/rspec/rspec-rails/pull/1163#discussion_r16882392) on rspec-rails. It would be nice make the project initialization a public API. It should be able to take some form of configuration object.

Some ideas for things that could be configured:
- opt-in to settings
- change setting value
- remove setting

**Comment by xaviershay** [comment]
Closing only because I can't figure out what's actually being asked for, I suspect it could be legitimate though. (I think the discussion link no longer works.) Please do reopen if able to clarify!
