### ISSUE TITLE
RSpec 3.1 command line failed to run test when the path includes '\t' and with :line_number, "All examples were filtered out"

### ISSUE THREAD

**Issue by zhimin** [rspec/rspec-core#1709]
After upgraded to RSpec 3.1, the following command failed to run specific test case with provided line number when the file path includes "**\t**"

>rspec C:\work\testwise-commmunity\samples\agiletravel-rwebspec\spec\login_spec.rb:17
Run options: include {:locations=>{".commmunity/samples/agiletravel-rwebspec/spec/login_spec.rb"=>[1
7]}}

All examples were filtered out

**OK when without line number**
>rspec C:\work\testwise-commmunity\samples\agiletravel-rwebspec\spec\login_spec.rb

**OK when changing 'work\test' to 'work\zest'**
>rspec C:\work\zestwisecommmunity\samples\agiletravel-rwebspec\spec\login_spec.rb:17

Regards,
Zhimin

**Comment by myronmarston** [comment]
@zhimin do you still need something from us here or can we close this?  Unfortunately we're not much help on Windows since none of us actively use it...
