### ISSUE TITLE
Feature idea: new `--bisect` flag

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1767]
The [minitest-bisect](https://github.com/seattlerb/minitest-bisect) project looks really useful for use on minitest-based projects.  I'd like to see something similar in RSpec.  It could be a separate gem (as it is for minitest) but I think it would fit well in rspec-core.  Bisect isn't a feature you normally need or use on an ongoing basis -- it's just when you suddenly hit an order dependency you didn't know you had that RSpec's random ordering has surfaced.  In such a situation, it's sub-optimal to have to install another gem, and you may not even be able to (such as if you run into this situation when you are offline).  Having it built in to rspec-core will keep it available when you need it without you having to plan ahead to have the gem available.

Ideally, the output of the `--bisect` flag would provide you with a command you can run to reproduce the failure with the smallest number of examples that triggers the error.  One thing that would help is a way to select specific examples from the command line.  We have the `-e` flag now that selects examples with matching doc strings, and we have the `file:line_number` syntax, but those are not workable solutions to selecting a specific examples in some situations. Consider that we allow multiple examples to be defined with the same doc string (ruling out `-e`) and the same line can define multiple examples, if you use a loop, ruling out `file:line_number`.  Instead, I was thinking we could introduce a new `--ids` option, which would take a form like:

``` ruby
rspec --ids 2:14,3:1:20,4:2:1:5
```

...which would run the 14th example defined in the 2nd example group, the 20th example from the first example group nested within the 3rd global example group, and the 5th example from the 1st group within the 2nd group within the 4th global example group.

**Comment by jrafanie** [comment]
Have you seen https://github.com/shelbyd/rspec-bisect ? It works pretty well: https://twitter.com/jrafanie/status/555021108769214464

**Comment by myronmarston** [comment]
I had seen it a while ago but forgotten about it.  Thanks for the reminder.  We'll probably use it for ideas (in addition to minitest-bisect).

**Comment by myronmarston** [comment]
Getting started on this.  Hope to have some part (probably the example ids piece) ready to push soonish.

**Comment by JoshCheek** [comment]
Potential problem with `--ids` format:

* A user won't know the order their tests are declared/run, so they won't be able to use this flag without a tool generating the invocation for them.
* A user can't read it and know which examples it refers to. Further compounded by the default formatter only telling them the name/file/line of the failing test, so they may have a lot of difficulty figuring out which ones are running, but this is probably relevant to their debugging.
* It won't work if the same files aren't loaded e.g. those indexes would change if the user required all the code when running `--bisect`, but only ran the failing file while fixing it (e.g. failing tests could run sub-second, except indexes are incorrect unless `spec/rails_helper.rb` is loaded).
* May depend on order files are loaded.

But, I'm not sure it's necessary since we can already say:

```sh
$ rspec spec1.rb:3 spec2.rb:10
# >> Run options: include {:locations=>{"./spec1.rb"=>[3], "./spec2.rb"=>[10]}}
```

**Comment by myronmarston** [comment]
Thanks for jumping in here, @JoshCheek.  It's always nice to vet our ideas by more users before we implement them :+1:.

> I'm not sure it's necessary since we can already say:

Problem is, specifying a line number is not always sufficient to select a particular example.  Consider this case:

``` ruby
RSpec.describe MyModel do
  context "validations" do
    %w[ email name ].each do |attr_name|
      it "requires a value for #{attr_name}" do
        record = MyModel.new(valid_attributes.merge(attr_name => nil))
        expect(record).not_to be_valid
      end
    end
  end
end
```

In this spec file, two examples are defined on line 4, and `rspec path/to/spec_file.rb:4` would run both.

A more common example is using shared example groups.  Given a shared example group with 3 examples that is included in 4 host groups, if the 2nd shared example fails only when included in the 4th host group, there is no way to specify a line number for that one example.  You could specify the line number from the declaration site of the example, but that line number corresponds to 4 different examples at run time (one per shared group inclusion).  Or you could specify the line number for where the shared example group is included in the 4th host group, but that would match 3 examples (all 3 shared examples created for that one host group).

Line number is an extremely useful feature of RSpec but it's simply not sufficient to identify a single example.

> * A user won't know the order their tests are declared/run, so they won't be able to use this flag without a tool generating the invocation for them.

I intend this to be specifically for cases where a tool would generate the invocation for them.  3 specific use cases I have in mind:

* The output of the new `--bisect` option would use this in order to specify the _exact_ smallest set of examples to re-run to reproduce a spec failing with a specific seed.
* I'm thinking we may add a new `--rerun-failed` flag that would rerun all of the examples that failed on the previous run, and again, it would use these ids as a means to identify which examples to re-run.
* For the failed-example re-run command printed in the summary, we currently print `rspec path/to/spec.rb:line_number` as the re-run command, which is the best we've had so far.  I'm thinking we might switch to using the example id in the re-run command, at least for situations where the line number would specify multiple examples.

> * The indexes would change if the user required all the code when running --bisect, but omitted spec/rails_helper.rb when debugging.
> * May depend on order files are loaded.

Yep, these are definitely big issues.  I thought of them after opening this issue but forgot to update this with a mention of them and my thoughts for solution.  The solution I've thought of is to make the example ids include a file name in them, e.g.:

```
path/to/some/spec_file.rb:2:14
```

...which would be the 14th example of the 2nd example group defined in `path/to/some/spec_file.rb`.  By scoping the ids to a particular file, it ensures that it doesn't matter if the order of loaded files changes, or a different set of files is loaded; as long as no new example groups or examples have been added, or remove, or re-arranged, the ids will be consistent.

In fact, the example ID would be _more_ consistent than line numbers.  One issue with line numbers is that they change as you refactor and extract helper methods, etc.  @tenderlove touched on this in his [recent blog post](http://tenderlovemaking.com/2015/01/23/my-experience-with-minitest-and-rspec.html):

> Another thing that bugs me is that if I do try to refactor my RSpec tests, and I change any lines, then the line that I copy and pasted to run just the one test won’t work anymore. I have to figure out the new line. I can use the name of the test by specifying the -e flag on RSpec, but then I lose the “copy, paste, run” feature that I love so much.

Using example ids for the re-run command wouldn't completely solve this (as you may move examples around while refactoring) but for simpler refactorings like extracting a helper method, moving code into or out of a `before` hook, etc the example id would remain consistent and could be used to consistently re-run while the line number couldn't.

> A user can't read it and know which examples it refers to. Further compounded by the default formatter only providing the info of the failing test, so they may have a lot of difficulty figuring out which ones are running, which they'll need as part of the debugging.

I think that with the id containing the spec file (as described above) it's easier to see which example it refers to.  Of course, `path/to/spec_files.rb:87:23:15` would still be hard, but if you have 87 example groups, and 23 nested within that, and 15 examples in that...you probably have bigger problems.

Overall, I think this is far from perfect (it does carry some downsides) but it's a useful tool in the box for when RSpec wants to be able to give you commands that are guaranteed to reference specific examples in the face of shared example groups, loops, etc.

**Comment by JoshCheek** [comment]
> In this spec file, two examples are defined on line 4, and rspec path/to/spec_file.rb:4 would run both.

Oh, yeah, good point.

> The solution I've thought of is to make the example ids include a file name in them, e.g.:
> ```
> path/to/some/spec_file.rb:2:14
> ```

Oh nice, that's a good solution.

> [...] the line that I copy and pasted to run just the one test won’t work anymore. I have to figure out the new line. 

Interesting that this is @tenderlove's favourite part as I don't use that feature at all (only tagging you, b/c this approach may be helpful, the rest of my comment is irrelevant). I glance at it to see the file/line, then open it in my editor and run the specific failure I'm working on: `it 'does something', t:true do` and then run `rspec -t t` This has worked well for me, but I only occasionally declare specs in a loop. I omit the obvious space, b/c then I can type `f,dE` in vim to remove it. Also, regardless of which suite I'm using, once I've put in the work for a command-line invocation, I often make an alias for it (I use `r` as in "run")

![tagged-spec](https://cloud.githubusercontent.com/assets/77495/6202275/a8321d3a-b49c-11e4-86fd-c971128781fc.gif)

**Comment by myronmarston** [comment]
Closing in favor of #1917.
