### ISSUE TITLE
XDG base directory support for configuration file

### ISSUE THREAD

**Issue by jasonkarns** [rspec/rspec-core#1773]
I would love to see XDG base directory support for the user-specific ~/.rspec config file. The [XDG spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines `$XDG_CONFIG_HOME` as the environment variable in which to place configuration files/directories. So in rspec's case, `~/.rspec` would become `$XDG_CONFIG_HOME/rspec/config`. (note: `$XDG_CONFIG_HOME` defaults to `~/.config`)

This results in a number of benefits:
- configuration directory is user-configurable without monkeying with $HOME
- home directory is less cluttered
- configuration data is separated from app data and cache data (pre XDG support blindly mixes all types in `~`)
- eases backups/versioning/sharing (when config data is separated from app and cache data, this becomes easier)

The general migration path with other tools that are beginning to support the XDG spec usually involves first checking for the legacy file (`~/.rspec`) and if it doesn't exist, looking for `$XDG_CONFIG_HOME/rspec/config` and then `~/.config/rspec/config`. (The [xdg gem](http://rubygems.org/gems/xdg) could be used to handle XDG lookup and defaults)

**Comment by samphippen** [comment]
This hasn't been touched since november 2014. Close as stale?

**Comment by myronmarston** [comment]
> This hasn't been touched since november 2014. Close as stale?

Yep.  This is one of those that I can't see an of us core contributors ever getting to.  We'd still welcome a PR implementing it from @jasonkarns or anyone else but keeping the issue open doesn't help make the PR happen and is just noise in our issue tracker.

**Comment by jasonkarns** [comment]
Closing this issue is likely *just enough* of a boost to get me to actually submit a PR. maybe :)
