### ISSUE TITLE
Allow introspecting tags

### ISSUE THREAD

**Issue by dwt** [rspec/rspec-core#1793]
I'd love to be able to use rspec in a meta mode that allows us to introspect what tags are available in the repository.

Please let me explain the use case: We have a repository with an app that has customer specific plugins. Those plugins also have acceptance tests (written in rspec, steak style) - but are exclusive to each other. To run those tests, the app needs to be restarted with different settings (activating the plugin in question).

To do that, we're considering several approaches on our integration server, and so far we favor the approach of iterating over the plugins, changing the settings, restating the app and then running the relevant tests. This can be neatly achieved by tagging, but the iteration would have to be over something else. Now if we could ask rspec what tags are used, something like `rspec --list-tags -tag=plugin,~wip` which would list all the tags used together with the plugin tags, ideally giving us a list of `customer1\ncustomer2\ncustomer3` - ready to iterate over.

Sure there are other ways to solve this - as we could also iterate over the actual plugins in the repo (though not all of them are substantial enough to warrant their own acceptance tests). But getting this kind of insight into rspec and what tags are actually used would be really nice.

What do you think?

**Comment by jezus-nunez** [comment]
I would use this thing with --list-tags :) +1

**Comment by hasmanyguitars** [comment]
I modified the example above from @myronmarston a bit so that you can see the values of each tag:

```
  if ENV['LIST_TAGS']
    def tags_in(groups)
      groups.flatten.inject({}) do |h, g|
        (g.metadata.keys + tags_in(g.children).keys - RSpec::Core::Metadata::RESERVED_KEYS).each do |k|
          h[k] ||= []
          h[k] |= [g.metadata[k].presence].compact
        end
        h
      end
    end

    config.before(:suite) do
      tags = tags_in(RSpec.world.example_groups)
      puts "\n\n"
      puts "***************"
      puts "* TAGS IN USE *"
      puts "***************"
      puts "\n"
      tags.each do |tag, values|
        puts "#{tag}: #{values.join(', ')}\n"
      end
      exit(0)
    end
  end
```
