### ISSUE TITLE
rspec fails to find backtrace information when using rspec/autorun

### ISSUE THREAD

**Issue by vincentwoo** [rspec/rspec-core#1827]
```
vwoo:coderpad.io vwoo$ rspec --version
3.1.7
vwoo:coderpad.io vwoo$ ruby test.rb
F

Failures:

  1) test fails here
     Failure/Error: Unable to find matching line from backtrace

       expected: 2
            got: 1

       (compared using ==)
     # test.rb:5:in `block (2 levels) in <main>'

Finished in 0.00091 seconds (files took 0.09247 seconds to load)
1 example, 1 failure

Failed examples:

rspec test.rb:4 # test fails here
```

The contents of `test.rb` are simply:

``` ruby
require 'rspec/autorun'

RSpec.describe 'test' do
  it 'fails here' do
    expect(1).to eq(2)
  end
end
```

Commenting out the `require` and just doing `rspec test.rb` seems to work fine:

```
vwoo:coderpad.io vwoo$ rspec test.rb
F

Failures:

  1) test fails here
     Failure/Error: expect(1).to eq(2)

       expected: 2
            got: 1

       (compared using ==)
     # ./test.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.00078 seconds (files took 0.11179 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./test.rb:4 # test fails here
```

This seems unlikely to be intended behavior. Can anyone help me figure out what's wrong? I feel like this use case used to work.

**Comment by myronmarston** [comment]
> @myronmarston do you have any tips on how to install the patched rspec-core in the meantime? Trying to use a Gemfile with the branch pointed to yours gives me tricky dependency errors.

The trick is that you have to use the `master` branch from github for all of the rspec gems if you are going to use it for one of them.  So in your gemfile, you could do:

``` ruby
%w[ core expectations mocks support rails ].each do |lib| # remove rails if you're not using rspec-rails
  gem "rspec-#{lib}", github: "rspec/rspec-#{lib}"
end
```

**Comment by vincentwoo** [comment]
@myronmarston Cool, that should tide me over for a while. Know when the linked patch will make it to a new release?

Also, thanks for your hard work. Happy new year.

**Comment by myronmarston** [comment]
> @myronmarston Cool, that should tide me over for a while. Know when the linked patch will make it to a new release?

Hopefully in the next couple weeks, but no promises.  We're trying to coordinate a few things in tandem with the 3.2 release but hopefully it'll be out soon.

**Comment by vincentwoo** [comment]
Gotcha, thanks!
