### ISSUE TITLE
Feature request: .and

### ISSUE THREAD

**Issue by Dorian** [rspec/rspec-core#1833]
I have some specs that take a long time to build, so I would like to combine the checks, eg:

```
it { expect { subject }.to change  { user.reload.state }.to('subscriber') }
it { expect { subject }.to change  { user.reload.credit_cards.size }.to(1) }
it { expect { subject }.to change  { user.reload.shipping_addreses.size }.to(1) }
# ...
```

To:

```
it "let the user subscribe" do
  expect { subject }.to change  {
    user.reload.state
  }.to('subscriber').and {
    user.reload.credit_cards.size
  }.to(1).and change  {
    user.reload.shipping_addreses.size
  }.to(1)
end
```

It would be awesome if it was in default syntax, or having a gem for that, or defining it is easy?

PS: I don't know how it would handle the function matching ruby-wise, eg: does `a b{}.and c{}.and d{}.and e{}` work

**Comment by myronmarston** [comment]
`and` is already available in rspec-expectations:

https://relishapp.com/rspec/rspec-expectations/v/3-1/docs/compound-expectations

Here's how you would write that:

``` ruby
expect { subject }.to change {
  user.reload.state
}.to('subscriber').and change {
  user.reload.credit_cards.size
}.to(1).and change  {
  user.reload.shipping_addreses.size
}.to(1)
```

(It's nearly identical to what you asked for but you were missing a `change` in there).

**Comment by Dorian** [comment]
Oh! I couldn't find it on google and assumed it didn't exist :D, thanks

**Comment by Dorian** [comment]
BTW, how can I mix `to` and `not_to` with `and/or`?

eg: `expect  { subject }.to change  { product.reload.inventory }.and not_to change  { other_product.reload.inventory }`

(right now I'm doing `change { }.by(0)` but it's not as readable and doesn't work with other cases (eg: arrays))

**Comment by myronmarston** [comment]
> @myronmarston, BTW, how can I mix `to` and `not_to` with `and/or`?

You can achieve this by defining a negated form of the matcher you want to negate.  For example:

```ruby
# in spec_helper.rb or some other setup file
RSpec::Matchers.define_negated_matcher :avoid_changing, :change
```

``` ruby
expect { subject  }
  .to change { product.reload.inventory }
  .and avoid_changing { other_product.reload.inventory }
```

**Comment by Dorian** [comment]
@myronmarston Pretty cool, thanks a lot!
