### ISSUE TITLE
Exceptions in `before(:all)`

### ISSUE THREAD

**Issue by tom025** [rspec/rspec-core#1849]
We've been experiencing an issue where we have a very expensive setup procedure defined in a before(:all) block. When this fails, RSpec will correctly fail the test suite. However, we are unable to capture the error in an after(:all) block as example group which is passed to the after(:all) block does not contain the exception. This makes it very difficult to record the state of the system that may have caused the exception to aide future diagnosis.

```ruby
def boot_skynet
  raise 'Skynet is down'
end

def save_skynet_info
end

RSpec.describe 'Skynet' do
  before(:all) do
    boot_skynet
  end

  it 'is aware' { expect(true).to be(true) }

  after(:all) do |example_group|
    # Will fail as no exception method available
    # no clear to find this out another way
    save_skynet_info if example_group.exception 
  end
end
```
\cc @theozaurus

**Comment by myronmarston** [comment]
We can look into making an improvement here, although in general, `after` hooks are not a reliable way to gain access to example states and exceptions.  See https://groups.google.com/forum/#!topic/rspec/44-bISoLmlo for a prior discussion about why this is.

Instead, here are two ways you can achieve what you want w/o waiting for a possible change.

First, instance variables written in `before(:all)` hooks are available in `after(:all)` hooks, so you could do the following:

``` ruby
module RecordedException
  attr_reader :recorded_exception

  def recording_exceptions
    yield
  rescue Exception => ex
    @recorded_exception = ex
    raise
  end
end

RSpec.describe 'Skynet' do
  include RecordedException

  before(:all) do
    recording_exceptions { boot_skynet }
  end

  it 'is aware' do
    expect(true).to be(true)
  end

  after(:all) do |example_group|
    save_skynet_info if recorded_exception
  end
end
```

You could use `config.include RecordedExceptions` to make that functionality available in all example groups.

Secondly, given that you are specifically trying to capture the `before(:all)` exception (and not any other example exception or hook exception), why not handle that directly in `before(:all)`?  Like so:

``` ruby
def boot_skynet
  raise 'Skynet is down'
end

def save_skynet_info(e)
  puts "Error: #{e}"
end

RSpec.describe 'Skynet' do
  def on_error_save_skynet
    yield
  rescue Exception => e
    save_skynet_info(e)
    raise
  end

  before(:all) do
    on_error_save_skynet { boot_skynet }
  end

  it 'is aware' do
    expect(true).to be(true)
  end
end
```

Delaying the handling of the error to `after(:all)` doesn't seem to buy you anything so why bother with `after(:all)` at all?

Does either of those suggestions meet your needs sufficiently?

**Comment by samphippen** [comment]
@myronmarston close because stale?

**Comment by myronmarston** [comment]
Yep, closing due to lack of response from @tom025.  We can reopen if he later responds and wants to continue the conversation.

**Comment by TIMBERings** [comment]
@myronmarston 

I'm using spec_helper to always run some steps in all of my tests.  I'm also using the before :all hook in each test to run steps specific to my specs.  If an exception can be thrown in either `config.before :all` or `spec.before :all`, how can I handle catching it in one big net? 

`config.before :all` clearly runs and completes prior to `spec.before :all`  This is where I run into trouble.

There is an example at: https://github.com/TIMBERings/rspec_questions/tree/master/spec

**Comment by myronmarston** [comment]
@TIMBERings -- I don't understand what you are asking. I cloned your repo and ran it but it's not clear to me what isn't working like you expect.  Can you open a new issue (since comments on closed issues can get lost since the issue is no longer open) describing how RSpec's behavior differs from what you expect?

**Comment by TIMBERings** [comment]
@myronmarston 
RSpec works as I expected, I was just trying to figure out how to handle either of the two Exceptions noted in the sample repo.  I think I found out how to do what I want to do though.

I just wanted to know how to detect if the `before :all` block failed within the `after :all` block.  I didn't want to have to put `begin/rescue` blocks in all of my specs.

```
example_exceptions = []
RSpec.world.example_groups.each do |example_group|
  example_group.examples.each do |example|
    example_exceptions << !example.exception.nil?
    end
  end
example_exceptions.any? {|exception| exception}
```

**Comment by myronmarston** [comment]
When a `before(:all)` block has an exception, it immediately fails the specs in the group and does not run them...so why would you have to put `beging/rescue` in all your specs?
