### ISSUE TITLE
Shared context name cannot be identical to a shared examples name

### ISSUE THREAD

**Issue by barelyknown** [rspec/rspec-core#1867]
I named a shared context the same as the shared example group and saw these warnings and test failures.
```text
$ bin/rspec
WARNING: Shared example group 'a policy of a buyer's child' has been previously defined at:
  spec/support/shared_context/shared_context_for_buyer_children.rb:1
...and you are now defining it at:
  spec/support/shared_examples/shared_examples_for_buyer_children.rb:1
The new definition will overwrite the original one.
```

**Comment by myronmarston** [comment]
There's no difference between a shared context and a shared example group: we support both simply to express the intended use (e.g. for one you're expressing it has common setup or helper code and for the other you're expressing it has some shared specs).  The implementation is actually just a ruby method alias:

https://github.com/rspec/rspec-core/blob/v3.2.0/lib/rspec/core/shared_example_group.rb#L81-L92

Given that, the behavior you reported is expected and intended.
