### ISSUE TITLE
Feature request: configurable `--fail-fast`

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec-core#1874]
It would be nice to be able to configure the number of failures before rspec exits out, so something like `--fail-fast 5`, so that I can get 5 failing tests at a time instead of having to choose between either one or all of them.

**Comment by JonRowe** [comment]
If you'd like to take a stab at implementing that we'd welcome it :)

**Comment by mockdeep** [comment]
Ha, okay, I'll see what I can do.

**Comment by bsvin33t** [comment]
If nobody is onto this, I would love to give it a shot.

**Comment by mockdeep** [comment]
By all means, have at it.

**Comment by bsvin33t** [comment]
Awesome :smile:

**Comment by akshaysmurthy** [comment]
Hey @bsvin33t Any updates on this? :)

**Comment by bsvin33t** [comment]
@akshaysmurthy none at all! Pick up the issue if you wanna work on it.

**Comment by akshaysmurthy** [comment]
@bsvin33t Sure! Will give it a shot over the weekend

**Comment by SoldierCoder** [comment]
I'm looking into it as well, hope everyone is cool with that.

**Comment by JonRowe** [comment]
Go for it :)

**Comment by jackscotti** [comment]
I have a pull request almost ready for this. Just need some refactoring. 
https://github.com/jackscotti/rspec-core/tree/configurable-fail-fast

Go for it anyway :)

**Comment by myronmarston** [comment]
Closed by #2065.
