### ISSUE TITLE
How can I make only one request for multiple examples?

### ISSUE THREAD

**Issue by whithajess** [rspec/rspec-core#1876]
So I ran into this problem with Testing our API.

The problem is the get request is called multiple times based on examples. e.g this code below will run `get 'test'` twice.

```ruby
require 'rails_helper'

describe API::TestController, type: controller do
  before do
     get 'test'
  end

  it { expect(response).to be_ok }
  it { expect(response.body).to eq('test code')
end
```

This is a problem when you start to have more `expect` statements in terms of performance. As far as I know there is no good workarounds for examples to re use the same response. The guide here http://betterspecs.org/#single talks about putting multiple expects into the `it` statement, this seems to go against getting good failure responses.

Using a `before(:all)`  you get an error like so
```ruby
Failure/Error: get 'test'
     RuntimeError:
       @routes is nil: make sure you set it in your tests setup method.
```

Is there a way to send only one request without ruining the failure responses?
(or if you like use memoization over multiple examples)

I did find you could use a global variable but this seems like the worst code ever.
```ruby
require 'rails_helper'

describe API::TestController, type: controller do
  it 'makes a single request' do
    get 'test'
    $stupid_global = response
  end
  it { expect($stupid_global).to be_ok }
  it { expect($stupid_global.body).to eq('test code')
end
```

**Comment by JonRowe** [comment]
This conundrum (shared state vs performance is one of the reasons we added compound matchers to RSpec 3.2, so you can now do: 

```Ruby
it { expect(response).to be_ok.and eq 'test code' }
```

This isn't a complete solution of course but we don't want to advocate shared state across examples.

Incidentally Github issues are not the place to request support, please use the mailing list / google group (https://groups.google.com/forum/#!forum/rspec) and/or #rspec on freenode.

**Comment by whithajess** [comment]
Thanks for that have posted to the mailing list for more discussion cheers.
