### ISSUE TITLE
Shared context is not working for rspec-core 2.13.1

### ISSUE THREAD

**Issue by sunloverz** [rspec/rspec-core#1877]
```
describe "group that includes a shared context using 'include_context'" do
  include_context "shared stuff"

  it "has access to methods defined in shared context" do
    shared_method.should eq("it works")
  end
end


 Failure/Error: include_context "it works"
  NoMethodError:
    undefined method `include_context' for #<RSpec::Core::ExampleGroup::Nested_1:0x0000000aa4b668>
```

**Comment by JonRowe** [comment]
As per the mailing list there is not enough details her to replicate this, and you should upgrade to the latest version of RSpec, following http://rspec.info/upgrading-from-rspec-2/ should suffice.

**Comment by sunloverz** [comment]
@JonRowe Thanks for quick reply! I am using rspec-rails, it seems their issue

**Comment by myronmarston** [comment]
I can't repro.  I put together a gist using your exact example (plus the actual definition of the shared context), and it clearly works:

https://gist.github.com/myronmarston/2592f819d139f76031a4

Clone that, `bundle install` and `bundle exec rspec example_spec.rb` and you'll see that it works.

If you can come up with a runnable example (e.g. a gist like I made) that reproduces your issue, we'll take a look.

As Jon said, we recommend upgrading. We put a tremendous amount of effort into making the upgrade from RSpec 2 to 3 as easy as possible, and we are no longer supporting RSpec 2 unless there were some serious security vulnerabilities reported.  As an all volunteer project we don't have the bandwidth to support both.

**Comment by sunloverz** [comment]
@myronmarston roger that, thank you very much for your attention, really appreciate it
