### ISSUE TITLE
"Top N Slowest Example Group" from `--profile` does not account for time spent in `before(:context)` hooks

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1878]
The implementation calculates the total example group time by summing the time of each individual example.  Problem is, the time in before/after `:context` hooks is not included in individual example times so it's completely ignored.  This should be fixed, because if you are using `:context` hooks it may be because of a slow operation and you wouldn't want it ignored when trying to find the slowest example groups.

**Comment by denislaliberte** [comment]
Hi, i wrote this feature... i think it's describing the bug you would like to be fixed, I am right ?

https://gist.github.com/denislaliberte/a20c543120d97d60f785

**Comment by myronmarston** [comment]
Yes, that describes the issue.

**Comment by denislaliberte** [comment]
I tried to help with that issue but I think I'm stuck.

I think I can't put the run time in a instance variable of example_group, should I use the metadata to store this variable ? 

Maybe there is something realy simple that I dont understand? If anyone have advice for the direction to take, I be glad to try again.

https://gist.github.com/denislaliberte/78ef80c014a39eb70cf5

**Comment by myronmarston** [comment]
Each example gets its own instance of the example group class of which its a part -- so you don't want to store the time at the _instance_ level of the example group.  Instead, you want to store the time at the _class_ level of the example group.  It can go in an instance variable of the class, though (e.g. one set and accessed by a class method rather than an instance method).

I'd also recommend measuring the runtime of the group as a whole (by measuring the duration of [ExampleGroup.run](https://github.com/rspec/rspec-core/blob/c4dbf1bef8bb7d663c70c1acec7a5c742e41fc96/lib/rspec/core/example_group.rb#L508-L527)) rather than simply measuring the runtime of `before(:context)` hooks.  There are `after(:context)` hooks to think about as well, and it's simpler just to capture the total run time of the group than to capture the run time for the `:context` hooks and each individual example, and then sum it all up.  "Summing it all up" is what we're [doing now](https://github.com/rspec/rspec-core/blob/c4dbf1bef8bb7d663c70c1acec7a5c742e41fc96/lib/rspec/core/notifications.rb#L611-L632) but that could be greatly simplified by tracking the runtime of the group as a whole.

Alternately, we could update the [profile formatter](https://github.com/rspec/rspec-core/blob/c4dbf1bef8bb7d663c70c1acec7a5c742e41fc96/lib/rspec/core/formatters/profile_formatter.rb) so that it tracks the run time of each group by handling `example_group_started` and `example_group_finished` events.  Actually, the more I think about that, the more it appeals to me: then there's no need for extra logic or state on the example group itself, and users don't pay the runtime cost of the extra code for this unless they are actually using the `--profile` option.

Does that make sense?

**Comment by denislaliberte** [comment]
Thanks for the feed back @myronmarston , I like the idea of using the profile formatter and events, I will try to implement it this week.

**Comment by JonRowe** [comment]
This would be a nice way to handle it, let me know if you have any questions about the formatter protocol.

**Comment by denislaliberte** [comment]
Thanks for the offer @JonRowe, I think i'm on the right path, I'll come back for advice if I encounter issues.

**Comment by denislaliberte** [comment]
I'd like some comments on this branch, it's not ready but I think it's a step in the right direction. [issue-1878-wip](https://github.com/rspec/rspec-core/compare/master...denislaliberte:issue-1878-wip)

Maybe the new code in the profile_formatter.rb should be in it's own class, maybe someting like 'profiler.rb' so we could reuse it in the [json_formatter.rb](https://github.com/denislaliberte/rspec-core/blob/issue-1878-wip/lib/rspec/core/formatters/json_formatter.rb#L76) and also move some logic from the notifications.rb to this new class. 

And the features don't pass but the when I run the same code from a rspec ( `$ bundle exec rspec spec/test_spec.rb --profile`) file it's working.

**Comment by JonRowe** [comment]
I left some feedback on the code but realise I didn't address your questions, so here goes:

> Maybe the new code in the profile_formatter.rb should be in it's own class, maybe someting like 'profiler.rb' so we could reuse it in the json_formatter.rb and also move some logic from the notifications.rb to this new class.

Well `ProfileNotification` is the profiler in this case, I'd be ok with moving more of the logic into that class.



> And the features don't pass but the when I run the same code from a rspec ( $ bundle exec rspec spec/test_spec.rb --profile) file it's working.

This is a reason why it's useful just to open a PR (tagging it WIP or leaving a comment to that effect if necessary) rather than asking for feedback on a branch. Not only is it easier to leave inline comments but it kicks off Travis which gives us the output easily! In this case I can't help without some of the output :)

**Comment by denislaliberte** [comment]
Thanks, I will do a little clean-up and submit a pull request.
