### ISSUE TITLE
Potential regression in RSpec 3.1 or 3.2: line number filter ignored when tag passed as well

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1889]
As reported by @reconstructions in rspec/rspec-rails#1326:

> If you specify a tag ( --tag footag ) AND a line number in your rSpec call using version 3.2, the line number is ignored, which was not the behavior in rSpec 3.0.

I haven't created a repro case yet but wanted to open this so we don't lose track.

**Comment by reconstructions** [comment]
Here are the exact strings I am using:

Runs selected lines;
```
'operating_system='' browser='firefox' browser_version='' rspec --require ./spec/selenium/local_config.rb --order random  spec/selenium/spec/band_spec.rb:51 -fd'
=>include {:locations=>{"./spec/selenium/spec/band_spec.rb"=>[51]}
```
Runs all lines:
```
 'operating_system='' browser='firefox' browser_version='' rspec --require ./spec/selenium/local_config.rb --order random --tag selenium spec/selenium/spec/band_spec.rb:51 -fd'
=> include {:selenium=>true, :locations=>{"./spec/selenium/spec/band_spec.rb"=>[51]}}
```

**Comment by myronmarston** [comment]
I've put together a repro case in a gist:

https://gist.github.com/myronmarston/9c327730915a113b7b9d

**Comment by myronmarston** [comment]
I used `git bisect` to discover that the source of the regression is 35137e0c9691f75fd9ad1aa7627698fbaba6c4f1 from #1841.  Not sure on what a fix will be yet.
