### ISSUE TITLE
shared context parameters are not reset for each example

### ISSUE THREAD

**Issue by kianw** [rspec/rspec-core#1892]
Example:
```ruby
require 'spec_helper'

shared_context "set it up" do |foo: nil|
  before(:example) do
    puts "foo: #{foo.inspect}"
    puts "setting foo to 'bar'"
    foo ||= "bar"
  end
end

describe "something" do
  include_context "set it up"

  it "does something once" do
    puts "something once"
  end

  it "does another thing" do
    puts "another thing"
  end
end
```

Output:
```
something
foo: nil
setting foo to 'bar'
another thing
  does another thing
foo: "bar"
setting foo to 'bar'
something once
  does something once
```

Is this the desired behavior? Examining foo in the before block, it's a local variable, and thus I would have expected it to be reset to nil for each example, instead of retaining the value from the previous iteration through the before.

**Comment by JonRowe** [comment]
This is peculiar but is probably a side effect of how the closure works, as it's not RSpec's doing...

**Comment by myronmarston** [comment]
> Is this the desired behavior?

I would say yes, this is desired behavior...to behave differently would be to violate the ways that local variables in closures work in Ruby, which is something we don't have control over, and, even if we did have control, I wouldn't want us to change how they work.  A shared context is just a block of code that is later evaluated in the context of one or more groups when it is included...so what you have there is the equivalent of:

``` ruby
require 'spec_helper'

describe "something" do
  foo = nil

  before(:example) do
    puts "foo: #{foo.inspect}"
    puts "setting foo to 'bar'"
    foo ||= "bar"
  end

  it "does something once" do
    puts "something once"
  end

  it "does another thing" do
    puts "another thing"
  end
end
```

Local variables are purely lexically scoped, so the `before` block and `it` blocks all can access the same local variable.  `foo ||= 'bar'` sets it to `'bar'` when the `before` hook fires for the first example, and then leaves the value unchanged when the second example runs.

One of the reasons `let` exists is to provide a simple way to have test objects/parameters that are reset for each example.  Passing arguments to a shared context is still useful as a way to parameterize it but it's best to treat the passed args as immutable (or even stick with simple immutable primitives!).

**Comment by kianw** [comment]
That makes sense. I suppose I didn't realize how shared contexts worked, and supposed that the parameters were reset for each example, but now that I think about it, it makes sense that the shared_context is only called once per include_context, not once per example. So a word to the wise -- don't modify your shared-context parameters inside a before (or after) block! Perhaps a short note in the documentation might help...  

`let` is probably a much better option in this situation; the only issue I have with using `let` is that it's not clear in the include_context call or the shared_context declaration that you're using a particular object defined by a `let`.  So from a code documentation perspective, it's less attractive.

It's interesting to note in your example that the examples would have access to the same local variable, which I hadn't realized either. 

Thanks for the quick response.
