### ISSUE TITLE
Use a runner with params

### ISSUE THREAD

**Issue by florrain** [rspec/rspec-core#1893]
Hey,

I'm trying to run a specific group example but I'm not sure I'm using the correct way to do it. I'd also like to pass a param which would be accessible from inside the group example.

```
  it "should get an item" do
    @test_item = FactoryGirl.create(:item)
    get "/item/#{@test_item.id}"

    RSpec::Core::Runner.run(['spec/api/file_spec.rb'], { param1: value1 })
  end
```

Then from a test inside file_spec.rb I'd like to access the param.

Do you think it's possible?

Thanks!

**Comment by JonRowe** [comment]
Why are you trying to run specs from inside a spec? Why not use a shared example group or similar?

**Comment by florrain** [comment]
Nevermind.

I'm using Grape and I was trying to set up an architecture for testing regression between versions of an API. 

I'll first reach out their people before coming back here if needed.

Sorry about this.

TGIF
