### ISSUE TITLE
Different values returned for shared_examples arguments in let and it

### ISSUE THREAD

**Issue by fabn** [rspec/rspec-core#1901]
I don't know if this is a real issue or I'm doing something wrong. In my project I wrote a parameterized shared example and when I call it in the same describe block with different parameters I get a different value in `it` and `let` blocks. Here is a minimal example to reproduce the issue:

```ruby
# file rspec_issue.rb
require 'rspec'

RSpec.shared_examples "a collection" do |number|
  let(:collection) do
    puts "Number in let is #{number}"
    described_class.new([number, 2, 4])
  end

  it "includes the passed number #{number}" do
    puts "Number in it is #{number}"
    expect(collection).to include(number)
  end
end

RSpec.describe Array do
  include_examples "a collection", 5
  include_examples "a collection", 6
end
```

Tested with both rspec 3.1.0 and latest released gems:

```
$ bundle show
Gems included by the bundle:
  * bundler (1.7.3)
  * diff-lcs (1.2.5)
  * rspec (3.2.0)
  * rspec-core (3.2.2)
  * rspec-expectations (3.2.0)
  * rspec-mocks (3.2.1)
  * rspec-support (3.2.2)
```

Here's rspec output

```
$ rspec rspec_issue.rb
Run options: exclude {:slow=>true}
Number in it is 5
Number in let is 6
FNumber in it is 6
Number in let is 6
.

Failures:

  1) Array includes the passed number 5
     Failure/Error: expect(collection).to include(number)
       expected [6, 2, 4] to include 5
     Shared Example Group: "a collection" called from ./rspec_bug.rb:16
     # ./rspec_bug.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.00175 seconds (files took 0.11272 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./rspec_bug.rb:9 # Array includes the passed number 5
```

**Comment by myronmarston** [comment]
This is by design.  A shared example group simply stores the block for alter execution, and when `include_examples` is called, it evaluates it in the host group.  So your spec file is the equivalent of:

``` ruby
# file rspec_issue.rb
require 'rspec'

RSpec.describe Array do
  # Naming the `number` local `number_1` and `number_2` so these are
  # treated as separate variables, to mirror the semantics of block
  # locals used in the shared example group.
  number_1 = 5

  let(:collection) do
    puts "Number in let is #{number_1}"
    described_class.new([number_1, 2, 4])
  end

  it "includes the passed number #{number_1}" do
    puts "Number in it is #{number_1}"
    expect(collection).to include(number_1)
  end

  number_2 = 6

  let(:collection) do
    puts "Number in let is #{number_2}"
    described_class.new([number_2, 2, 4])
  end

  it "includes the passed number #{number_2}" do
    puts "Number in it is #{number_2}"
    expect(collection).to include(number_2)
  end
end
```

This is by design -- `include_examples` is documented to include the shared groups contents directly in the host group:

http://rspec.info/documentation/3.2/rspec-core/RSpec/Core/ExampleGroup.html#include_examples-class_method

The solution, as the docs mention, is to use `it_behaves_like` rather than `include_examples`, which creates a nested group and evals the block in that group, so as to provide isolation from the host group:

``` ruby
RSpec.describe Array do
  it_behaves_like "a collection", 5
  it_behaves_like "a collection", 6
end
```

...which is the equivalent of:

``` ruby
RSpec.describe Array do
  context "behaves like a collection" do
    number = 5

    let(:collection) do
      puts "Number in let is #{number}"
      described_class.new([number, 2, 4])
    end

    it "includes the passed number #{number}" do
      puts "Number in it is #{number}"
      expect(collection).to include(number)
    end
  end

  context "behaves like a collection" do
    number = 6

    let(:collection) do
      puts "Number in let is #{number}"
      described_class.new([number, 2, 4])
    end

    it "includes the passed number #{number}" do
      puts "Number in it is #{number}"
      expect(collection).to include(number)
    end
  end
end
```

The nesting provides isolation from the host group (and from other included shared example groups) and is thus "safer" and generally recommended.  OTOH, it changes the documentation (to include the "behaves like a collection" line) and it may not always be desirable, so we offer both.

I think maybe our documentation should be more clear about this pitfall of `include_examples`.  Would you want to work up a PR for that?

**Comment by myronmarston** [comment]
BTW, to elaborate a bit more: `let` just defines a method, so you wind up with two definitions of `collection` in the same scope, and the latter "wins", so the former never gets hit.

This actually makes me think of a potential improvement here....maybe we should make `let` warn if it is redefining an existing method on the same example group class?  For bonus points, we could perhaps detect that this is happening within a shared group included via `include_examples` and suggest the user use `it_behaves_like` instead.

**Comment by fabn** [comment]
Ok, now I think I got it. In your "expanded" example (the first one) when `it` blocks are actually executed they both refer to latest `let(:collection)` declaration thus the issue happens.

For your proposal `let` warn would be great, it could be a source of nasty issues as in this case, however I don't know rspec internals and I think I won't be able to code that.

For the PR about missing doc if you tell me where is appropriate to do that I'try to submit a PR.

**Comment by fabn** [comment]
I took a look in the code and it could be simpler than I believed , I think your proposal should be implemented [here](https://github.com/rspec/rspec-core/blob/7c5d508bebf64c7f00b9d7d63ad1114ef481914c/lib/rspec/core/memoized_helpers.rb#L234)

What about something like this after the first check

```ruby
raise "#let or #subject called with an existing method #{name}" if respond_to?(name) #
```

If that's fine I'll try to code something and submit a PR with a spec for it.

**Comment by myronmarston** [comment]
> For the PR about missing doc if you tell me where is appropriate to do that I'try to submit a PR.

Two spots:

https://github.com/rspec/rspec-core/blob/master/features/example_groups/shared_examples.feature

https://github.com/rspec/rspec-core/blob/1e483f6de33a56bb93d8846644cf73e42d307596/lib/rspec/core/example_group.rb#L322-L340

The former is published on relishapp; the latter is in our self-hosting API docs.

**Comment by myronmarston** [comment]
> What about something like this after the first check

That's the right spot to do it.  A couple suggestions, though:

* Raising would be a breaking change, so we should only warn, I think.  While it's generally undesirable to stomp an existing method def, that's not always the case.
* It's insufficient to check `respond_to?`.  If the method is defined in a super class (e.g. a parent example group or included module), then it may be entirely intentional -- such as to have a default value for the top-level example group in the file, and then override it in a nested group.  Instead, you should check if there's an instance method with the same owner.  (`SomeClass.instance_method(:some_method).owner` will tell you in what class or module a method is defined).

Thanks for being willing to jump in and help improve things for everyone!

**Comment by JonRowe** [comment]
I think a lot of people deliberately override let definitions in child example groups, we should make sure this warning is suppressible or we may end up with a lot of complaints!  Alternatively we could only warn when it's overridden in the sample example group...

**Comment by myronmarston** [comment]
> I think a lot of people deliberately override let definitions in child example groups, (hell we even have specs for this scenario, and allow the use of super), so we should make sure this warning is suppressible or we may end up with a lot of complaints! Alternatively we could only warn when it's overridden in the same example group...

Yep.  This was what I was trying to say with my last point above :).

**Comment by fabn** [comment]
@myronmarston I sketched something [here](https://github.com/fabn/rspec-core/commit/fb8fd3452c2c0ab353d5d23390e5640bb10732b4).

Let me know what do you think.

**Comment by myronmarston** [comment]
It's a good start.  Can you open a PR?  It's easier to do a code review and provide feedback when it's in a PR.

**Comment by fabn** [comment]
Done, closing this.

**Comment by myronmarston** [comment]
Are you also planning to update the docs as discussed above?

**Comment by fabn** [comment]
I don't know, I took a look on existing documentation you pointed me to and I think that my initial example case is an edge case and maybe it's not appropriate for a short doc block because it may be too verbose.

Also I run the original example against the PR code and now I get this useful warning 

```
$ rspec rspec_issue.rb
WARNING: method :collection defined multiple times through let in the same context. Called from /Users/fabio/Downloads/rspec-issue/rspec_issue.rb:5:in `block in <top (required)>'.
...
```

Maybe I can add a `@see` tag which points here in `include_context` docblock or another paragraph in the feature file in [this point](https://github.com/rspec/rspec-core/blob/master/features/example_groups/shared_examples.feature#L22) which describe the potential issue when declaring (parameterized) let blocks into a non nested shared example.
