### ISSUE TITLE
(follow Up)Facing issues in executing different spec files in desired order with rspec #1899

### ISSUE THREAD

**Issue by chandanaGollapudi** [rspec/rspec-core#1902]
thanks your quick response( to request no 1900).I have gone through link that you suggested.i have few clarifications on below provided code.
Could you please provide your answers on below points.

1.In which file i need to add below provided code( is it spec_helper.rb or new spec file)?
1.1 if it is spec_helper,now different scrum team using same spec_helper file. will it affect others execution,if so how to handle it?

1.2  can archive  same by  creating new spec file and add below code to that.will it execute all other spec files in desired order by running new spec?

2.what is the significance of numerics in below code? as per my understanding groups execution order will be based on tags and the order will be feature,request and model.

3. lets say i have  3 test under each spec file . can the below code support in executing test in written order ? if not, could tell me how to that?

4. Could you point me  to the link that gives detailed info about rspec for beginners?

RSpec.configure do |config|
config.register_ordering(:global) do |items|
items.sort_by do |group|
case group.metadata[:type]
when :feature then 50
when :request then 40
when :model then 10
else 20
end
end
end
end

thanks in advance,
Chandana

**Comment by myronmarston** [comment]
Please do not open new duplicates for your issues.  Please respond to the one where we've had the conversation (#1900) and I'll be happy to answer there.  Creating new threads just creates noise in our issue tracker.

**Comment by chandanaGollapudi** [comment]
sure..will do that. apologies for inconvenience.
