### ISSUE TITLE
RSpec raises error when trying to `idempotently_define_singleton_method` if a kernel method with the same name exists

### ISSUE THREAD

**Issue by rupurt** [rspec/rspec-core#1906]
This issue can be seen with the `its-it` gem.

`its-it` defines the method `it` on `Kernel`, when `rspec/core/example_group` is required it will check `method_defined?` which checks not only the given module but also it's ancestors (`Kernel`) and will see that `it` is defined, then will try to remove the method a method that does not exist from the singleton.

https://github.com/rspec/rspec-core/blob/f98223d3dadae9a5180df7f209a2c0110539ddd6/lib/rspec/core/example_group.rb#L40

If you believe this an edge case and shouldn't be fixed (I agree `it` should not be defined on `Kernel`) feel free to close this issue.

If you do want to prevent this case in the future and have a true `idempotently_define_singleton_method` then you could see if the method is included in `Object#methods(false)` which lists only the defined methods on that object or to use the `#method(:it)` and check to see if the `#owner` is the same as the module being defined on.

cc/ @ryanong

**Comment by myronmarston** [comment]
I think it's reasonable to fix this.  I'd prefer the `method(:it).owner == self` solution as that should be constant time compared to `Object#method(false).include?` being linear.

Want to make a PR to fix it?

**Comment by rupurt** [comment]
Sure

**Comment by rupurt** [comment]
`method(:it)` raises an error when the method is not found. Would you prefer us to use `begin/rescue` or do the `method(false).include?`

**Comment by myronmarston** [comment]
> method(:it) raises an error when the method is not found. Would you prefer us to use begin/rescue or do the method(false).include?

Neither....what about this?

``` ruby
method_defined?(:it) && instance_method(:it).owner == self
```

That shouldn't raise.

**Comment by rupurt** [comment]
:+1:
