### ISSUE TITLE
Improve `inspect` output of `RSpec::Core::Example`

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1922]
It's pretty messy right now.

**Comment by JoshCheek** [comment]
I assume RSpec's own test suite is the only one that needs this feature. In that case, the pretty print output looks pretty good (pry has coloured it as well, but the structure is the structure for normal pretty printed objects). Could possibly override its inspect, in the spec helper, to delegate to pretty_inspect.

![screen shot 2015-04-27 at 8 37 50 pm](https://cloud.githubusercontent.com/assets/77495/7361862/a8d64b08-ed1d-11e4-8b51-56017703bdb8.png)



```ruby
> puts example.pretty_inspect;
#<RSpec::Core::Example:0x007fefb5ed88c8
 @clock=RSpec::Core::Time,
 @example_block=
  #<Proc:0x007fefb5ed8990@/Users/josh/code/britney/json_stack_overflow/spec/post_spec.rb:32>,
 @example_group_class=RSpec::ExampleGroups::SOPost,
 @example_group_instance=
  #<RSpec::ExampleGroups::SOPost "knows the score, last_edit_date, last_activity_date, creation_date, post_type, post_id, and link" (./spec/post_spec.rb:32)>,
 @exception=nil,
 @metadata=
  {:execution_result=>
    #<RSpec::Core::Example::ExecutionResult:0x007fefb5ed8710
     @started_at=2015-04-27 20:35:30 -0600>,
   :block=>
    #<Proc:0x007fefb5ed8990@/Users/josh/code/britney/json_stack_overflow/spec/post_spec.rb:32>,
   :description_args=>
    ["knows the score, last_edit_date, last_activity_date, creation_date, post_type, post_id, and link"],
   :description=>
    "knows the score, last_edit_date, last_activity_date, creation_date, post_type, post_id, and link",
   :full_description=>
    "SO::Post knows the score, last_edit_date, last_activity_date, creation_date, post_type, post_id, and link",
   :described_class=>SO::Post,
   :file_path=>"./spec/post_spec.rb",
   :line_number=>32,
   :location=>"./spec/post_spec.rb:32",
   :absolute_file_path=>
    "/Users/josh/code/britney/json_stack_overflow/spec/post_spec.rb",
   :example_group=>
    {:execution_result=>
      #<RSpec::Core::Example::ExecutionResult:0x007fefb5ed9ed0>,
     :block=>
      #<Proc:0x007fefb4084e58@/Users/josh/code/britney/json_stack_overflow/spec/post_spec.rb:10>,
     :description_args=>[SO::Post],
     :description=>"SO::Post",
     :full_description=>"SO::Post",
     :described_class=>SO::Post,
     :file_path=>"./spec/post_spec.rb",
     :line_number=>10,
     :location=>"./spec/post_spec.rb:10",
     :absolute_file_path=>
      "/Users/josh/code/britney/json_stack_overflow/spec/post_spec.rb"},
   :shared_group_inclusion_backtrace=>[]}>

> example.method(:pretty_inspect).owner
=> Kernel
```

**Comment by myronmarston** [comment]
You're right that a single, individual example looks OK in pry.  The case I ran into that prompted me to open this was a failing spec that included the example's `inspect` output in the failure output, and multiple examples were involved.  As a result, my screen was filled with tons of excessive detail when I really would have preferred something short like `#<RSpec::Core::Example "does cool stuff">`.  When inspecting an array of examples it really helps to have the `inspect` output short like this.

> I assume RSpec's own test suite is the only one that needs this feature.

It's the main use case, but it could be useful for other projects that extend RSpec and deal with `RSpec::Core::Example` objects as well.

**Comment by JonRowe** [comment]
Yeah I think a shorter description would be good.
