### ISSUE TITLE
JSON formatter doesn't include pending_message

### ISSUE THREAD

**Issue by daneandersen** [rspec/rspec-core#1924]
The json formatter doesn't include the pending_message:

```ruby
describe 'JSON output' do
  it 'should have a pending reason' do
    pending 'so we can see the reason'
    fail
  end
end
```

```
*

Pending:
  JSON output should have a pending reason
    # so we can see the reason
    # ./my_spec.rb:4

Finished in 0 seconds (files took 0.125 seconds to load)
1 example, 0 failures, 1 pending
```

```json
{
   "examples":[
      {
         "description":"should have a pending reason",
         "full_description":"JSON output should have a pending  reason",
         "status":"pending",
         "file_path":"./my_spec.rb",
         "line_number":4,
         "run_time":0.0
      }
   ],
   "summary":{
      "duration":0.0,
      "example_count":1,
      "failure_count":0,
      "pending_count":1
   },
   "summary_line":"1 example, 0 failures, 1 pending"
}
```

the pending_message of 'so we can see the reason' shows up in the default formatter, but not the json.

**Comment by myronmarston** [comment]
Thanks for reporting this.  I'm not terribly surprised the JSON formatter is lacking -- AFAIK, none of the core team use it. It was contributed by a contributor and we generally don't think about it when adding new features to other formatters.

Want to take a stab at adding it?

**Comment by daneandersen** [comment]
Yeah, I'll definitely take a crack at it. Actually it brings up an interesting question. Is there any source of truth about the pieces of information that should come out of a formatter of a test run? I know it would be hard to formalize and test, but at least an approximate list of features. If I'm going to be in there to fix this, it might be worth checking if anything else is left out.

**Comment by myronmarston** [comment]
> Is there any source of truth about the pieces of information that should come out of a formatter of a test run?

Nope.  The point of custom formatters is to be able to emit more or less information as desired by the user.  In addition, formatters are a generalized system for receiving notifications about events, and some formatters aren't intended to be your primary formatter.  For example, RSpec ships with a `ProfileFormatter` (activated when you use `--profile`), which only deals with profiling info.
