### ISSUE TITLE
Failure filtering runs all examples when there are no failures

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1941]
When you have `config.run_all_when_everything_filtered = true` set and you use `--only-failures` or `--next-failure` and there are no failures in the persistence file, the current behavior is to run _all_ examples.  This is counterintuitive because you've told RSpec to run only failures but instead it runs only successes (which happens to be all examples).  This is a consequence of the fact that failure filtering is implemented using the general filtering mechanism, and `run_all_when_everything_filtered` kicks in in this case.

Ideally, if you used `--only-failures` or `--next-failure` and there were none, RSpec would abort quickly with a message stating there are no failures.  If we do that, one open question is what status code to use: on the one hand, the command kinda failed (it failed to find any failures to run) so maybe it should be non-zero.  Also, exiting with a zero status code when no examples were even run seems potentially problematic.  OTOH, I could see someone repeatedly running `rspec --next-failure && say "done"` (or similar -- idea inspired by [this tweet](https://twitter.com/pragdave/status/570774584695218176)), and for this use case it would be important for RSpec to exit with a 0 status when it hits a point where there are no more failures to run.

Thoughts on what status code should be used for this?

We're also discussing phasing out `run_all_when_everything_filtered` in #1920 in favor of a new `ignore_unmatched_filters` option, so that should be taken into account for whatever solution we decide upon.

/cc @rspec/rspec

**Comment by xaviershay** [comment]
Exit 0 when all the specs are successful seems good to me.

```
irb(main):002:0> [].all?
=> true
```

**Comment by JonRowe** [comment]
I agree we should `exit 0`

**Comment by myronmarston** [comment]
Sounds good. Anyone want to take a stab at this?

**Comment by myronmarston** [comment]
Addressed by #1945.
