### ISSUE TITLE
Around hooks should warn or raise if `example.run` is never called

### ISSUE THREAD

**Issue by derekprior** [rspec/rspec-core#1953]
Twice in the last couple of months I've seen `around` hooks that forget to call `example.run`. In this case, all of your tests pass because they're not actually run. If you weren't expecting a failure (like say you are refactoring some setup to an around hook), then this is really simple to miss.

Then someone writes a test they expect to fail and can't for the life of them figure out why `expect(true).to eq false` is passing and they begin to question the very existence of the universe itself.

Would it be possible or appropriate to warn or raise an error if an `around` hook is executed without running the example? I'm willing to look into this myself (source diving now). I'm just wondering if this is a change that would be welcomed.

**Comment by myronmarston** [comment]
We implemented this awhile ago in #1660, which was released in 3.1.  With that change, examples that are not run from an `around` hooks are marked as pending with a message explaining the around hook did not run it.

What version of RSpec are you on?

**Comment by rickreilly** [comment]
This has affected me as well. RSpec version is 3.0.4

**Comment by myronmarston** [comment]
@rickreilly -- is there anything holding you back from upgrading to RSpec 3.1, where we've already addressed this?

**Comment by derekprior** [comment]
Yeah, I just found the test cases for this in the source and that's what made me realize we weren't on 3.1 just yet. No reason not to upgrade in my case.

**Comment by rickreilly** [comment]
@myronmarston nope -- like I said, I'll upgrade. Thanks!
