### ISSUE TITLE
Find a more performant way to detect anonymous classes and modules

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1954]
Apparently calling `name` on an anonymous class or module is incredibly slow:

https://bugs.ruby-lang.org/issues/11119

We hit this in a few places:
- https://github.com/rspec/rspec-core/blob/c712c90c5855ac0a675830391a5696525bda829a/lib/rspec/core/notifications.rb#L228-L232
- https://github.com/rspec/rspec-mocks/blob/4cc6d619436355e65458916197d403909d4bdd23/lib/rspec/mocks/object_reference.rb#L30-L39

Those are the only two places I can find where we are trying to detect if a class or module is anonymous, but there may be others where we don't consider if it's anonymous and call `name` on it or `inspect` on an instance of it anyway.  I have no idea if there's a more performant way to tell if a module or class is anonymous, but if there is, we should switch to using it.

**Comment by csmuc** [comment]
fyi, https://github.com/rails/rails/issues/24248

**Comment by xaviershay** [comment]
I don't think we should care about the second instance - it's literally called once during source loading to detect ruby support. (Could change to a RUBY_VERSION check if we really cared though.)

The first will only be an issue if a) many errors, and b) those errors are anonymous classes. That seems pretty rare. I'm inclined to close this on similar logic to #2194. Reopen if you disagree or provide benchmarks.
