### ISSUE TITLE
Problem with RSpec + Mutant + Loops.  Need a way to "wait" for a test to finish.

### ISSUE THREAD

**Issue by elliotweiser** [rspec/rspec-core#1960]
I'm not sure that this the correct `rspec` repo under which to open this issue, but I'll be happy to recreate in the appropriate place.

When running mutation tests with `mutant` on code that involved while loops, I observed some interesting behavior:

Here is the code I'm testing with RSpec:
```ruby
module MyModule
  module MyClass
    def poll_for_success
      timeout = DEFAULTS[:timeout]
      while timeout > 0
        return true if check_for_success
        timeout = sleep_for_interval_and_decrement_timeout(timeout)
      end
      false
    end
  end
end
```

Here is the RSpec test
```ruby
describe MyModule::MyClass do
  context '#poll_for_success' do
    let(:actual) do
      subject.poll_for_success
    end
    it 'should call :sleep_for_interval_and_decrement_timeout twice and return false' do
      MyModule::DEFAULTS[:timeout] = 0.02
      MyModule::DEFAULTS[:interval] = 0.01
      expect(subject)
        .to receive(:sleep_for_interval_and_decrement_timeout)
        .with(0.02).and_return(0.01).ordered
      expect(subject)
        .to receive(:sleep_for_interval_and_decrement_timeout)
        .with(0.01).and_return(0).ordered
      expect(actual).to be false
    end
  end
end
```

I found that running mutant while targeting `MyModule::MyClass#poll_for_success` resulted in an infinite loop.  Conveniently, `mutant` exposes exactly which mutations it makes, but only _after_ it finishes testing against those mutations.

Fortunately, It wasn't difficult to guess that among the mutations being made, the line containing `:sleep_for_interval_and_decrement_timeout` was being deleted, resulting in an infinite loop. Since test success/failure is determined after the method being executed completes, the above test was not sufficient.  

I added the following function to my `spec_helper.rb`:

```ruby
def wait_for_test(timeout: 10, signal: 'SIGTERM')
  pid = fork do
    yield
  end
  sleep(timeout)
  result, status = Process.waitpid2(pid, Process::WNOHANG)
  if result.nil?
    Process.kill(signal, pid)
    fail 'Test did not complete in time...'
  end
  fail 'Tests failed' if status.exitstatus != 0
end
```

Now, instead of calling `expect` directly, I run my test within a `wait_for_test { }` block, specifying exactly how long to wait for it, and which signal to send to the process in the event of exceeding the timeout.

Rather than hogging this information for myself, I'd like to be a good citizen and I figured the RSpec community (and indeed active `mutant` users) may appreciate this bit of code.  Unfortunately, I don't have enough time to dive into the RSpec codebase, figure out where to put this, test it, and then PR.  I would appreciate it (if you guys are up for it) that this feature be added to the codebase.

**Comment by myronmarston** [comment]
IMO, this doesn't belong in RSpec.  It's not RSpec-specific (there's nothing about `wait_for_test` that depends upon of uses any RSpec APIs) and it's not even test-specific: you could use this anywhere.  In addition, it won't work on platforms that don't support `fork` (such as windows and JRuby), which RSpec supports.  You could certainly put this in a gem and publish it to share it with the community.

**Comment by elliotweiser** [comment]
That didn't even occur to me.  I suppose my preference would be to create a gem that is platform agnostic. I'll chase that instead; thanks for the input!

**Comment by mbj** [comment]
@myronmarston This is nothing rspec should be concerned about. I agree. I'll discuss this on the mutant side.
