### ISSUE TITLE
RSpec matcher for alias_method.

### ISSUE THREAD

**Issue by u2** [rspec/rspec-core#1962]
Is there any matcher for `alias_method`?What about add a matcher for `alias_method`.
```ruby
# RSpec matcher for alias_method.
# Usage:
#
#     describe User do
#       it { should alias_from(:username).to(:email) }
#     end

RSpec::Matchers.define :alias_from do |alias_method|
  match do |subject|
    begin
      subject.send(alias_method)
    rescue NoMethodError
      raise "expected alias_method from #{alias_method} to #{@original_method} but #{alias_method} is not defined"
    end

    subject.method(alias_method).should eq(subject.method(@original_method))
  end

  description do
    "RSpec matcher for alias_method"
  end

  failure_message_when_negated do |text|
    "expected alias_method from #{alias_method} to #{@original_method}"
  end

  failure_message do |text|
    "do not expected alias_method from #{alias_method} to #{@original_method}"
  end

  chain(:to) { |original_method| @original_method = original_method }
end
```

**Comment by myronmarston** [comment]
No, there's no matcher for method aliasing built-in to RSpec.  You can certainly write one yourself, although there are a few issues:

* Your matcher only works for methods that take no arguments.  If the method takes arguments or requires a block it won't work.  The matcher can't guess what arguments to pass, obviously.
* The fact that the methods return the same value does not guarantee they are method aliases.  Consider a case like `Person = Struct.new(:name, :age); person = Person.new`: `person.name` and `person.age` both return `nil`, and your matcher would say they are aliases but they are not.
* On the flip side, methods that are aliases may not always return the same value.  Consider if you alias `rand` or `Time.now`: each time you call them, it would produce a different value and your matcher would fail.
* IMO, testing that a method is an alias of another is testing the _implementation_, not the _behavior_.  The important thing is what the method does, and not the fact that it uses `alias_method` to achieve that behavior.  I would recommend against using a matcher like this even if it was easy to make one that solved the other issues.  Instead consider using a shared example group to test both aliases.  Or reconsider whether you need the alias...a small interface is a more easily maintained (and tested) one.

(BTW, in the future please open matcher suggestions and issues in the rspec-expectations repo).

**Comment by u2** [comment]
Thanks.
