### ISSUE TITLE
controller tests do not return correct Content-Type

### ISSUE THREAD

**Issue by joelpresence** [rspec/rspec-core#1965]
Hi,

When I run rails and perform a certain request, I get a response with:

```
Content-Type: application/json; charset=utf-8
```

However, when performing an Rspec controller test against that same controller, the `response.content_type` is just `application/json` which is not correct.  Somehow, rspec is splitting off charset into `response.charset` which comes back as `utf-8`.  This feels odd to do this since the actual header name where the charset is returned is `Content-Type`.

I'm not sure which code is doing this and obviously not breaking a bunch of existing tests is a concern, but this seems like a mismatch to me ...

Thoughts?

Thanks!

**Comment by JonRowe** [comment]
It's not us doing this but the Rails test helpers, `rspec-rails` provides a thin shim integrating the Rails test helpers into RSpec.

For future reference this is the wrong repo to open issues like this, in future please open them against `rspec/rspec-rails`.

**Comment by joelpresence** [comment]
OK, I'll file this against rspec-rails, thanks.

**Comment by JonRowe** [comment]
No don't, it's not an rspec-rails issue as I said, it's a rails one.
