### ISSUE TITLE
shared_example_group edge case

### ISSUE THREAD

**Issue by mooreniemi** [rspec/rspec-core#1967]
Failure/Error: Unable to find matching line from backtrace
     LocalJumpError:
       no block given

This is where I started, while working on rspec-console. And falling down the rabbit hole, I saw that:

     class Registry
        def add(context, name, *metadata_args, &block)
          [snip]
          return if metadata_args.empty?
          RSpec.configuration.include SharedExampleGroupModule.new(name, block), *metadata_args
        end

If `return if metadata_args.empty?` is called on `[nil]` by accident, it will return false and 

    class SharedExampleGroupModule < Module
      def initialize(description, definition)

will fail to be properly defined. Causing a failure further down when `@description` is called as a block, and is empty.

Don't ask me why I was able to pass `[nil]` in there -- I'm trying to work with [rspec_console](https://github.com/mooreniemi/rspec-console/tree/rspec_3_support) and my spec suite for it creates weird cases. But if you slap good ol' `compact` in ala `return if metadata_args.compact.empty?` you can prevent the edge case I am seeing.

**Comment by myronmarston** [comment]
Can you provide a code snippet that calls a public RSpec API to get `[nil]` to reach there?  If so, we'll happily address this (or we'll be happy to merge a PR from you addressing it).  Although, there might be a different location before it gets here from the public API that is a more appropriate place to fix it.

If there's no way to get here with `[nil]` via a call to a public RSpec API then I'd recommend sticking to just public APIs :).  We can always add additional APIs that you may need.

**Comment by mooreniemi** [comment]
@myronmarston FWIW, this is where I managed to do it:

`::RSpec.world.shared_example_group_registry.add()`

You can see _why_ I'm doing this nonsense if you want here: https://github.com/mooreniemi/rspec-console/blob/rspec_3_support/lib/rspec-console/config_cache.rb

**Comment by JonRowe** [comment]
So if you're calling that method would a group then we should error at you there, I wouldn't recommend we no op on `nil`, that method expects a shared example group so...

**Comment by JonRowe** [comment]
I'd say you should run a compact on your array before checking it's empty... or just avoid adding nils to it in the first place if possible...

**Comment by mooreniemi** [comment]
@JonRowe I've already resolved my issue on my end. (Without doing anything to RSpec core.) This was just a heads up to you, in case you wanted to do anything with it.

**Comment by JonRowe** [comment]
I don't think we should, garbage in garbage out etc... Thanks for the heads up :)
