### ISSUE TITLE
rspec should not run in RAILS_ENV=production by default

### ISSUE THREAD

**Issue by mauriciogracia** [rspec/rspec-core#1973]
rspec should be configured by default to not be run on RAILS_ENV=production

the file spec_helper.rb should contain some similar to this

```
raise "Not in test" unless ENV['RAILS_ENV'] == "test"

I suggest this since many tests start by truncating all the tables and if you by mistake run this on the production environment, well all your data will be lost

Hope someone else finds this useful and decides to include some default measures to avoid this from happening to somebody else

**Comment by myronmarston** [comment]
rspec-core knows nothing about `RAILS_ENV` or rails at all, and we're going to keep it that way.  Your request is reasonable for rspec-rails, though...do you mind re-opening your issue there since that's where any change would be?
