### ISSUE TITLE
Shared examples are ran even when specifying a line number from CLI. (>= 3.2.2)

### ISSUE THREAD

**Issue by jhirn** [rspec/rspec-core#1975]
Hello. I know there are a few issues around filtering shared_examples (#1837, #1485). I'm not sure if this is related but we're having an issue where specifying a single spec is running that spec plus all shared examples in the file are ran. I've boiled this down to a change from 3.2.1 to 3.2.2 (by adding `gem rspec-core 3.2.1/3.2.2`). It's also occurring in 3.2.3 where we first noticed it. 

The shared example must be declared in an external file. When it was in the same file it was not happening. 

I can set up a whole example project to recreate but here is the smallest example I can provide. Sorry for bleeding in the fact I'm obviously using rspec-rails and in a client project. 

```
#spec/support/sharing_is_caring.rb

shared_examples "sharing is caring" do
  describe "a context" do
    it "is a sample test" do
      expect(true).to be true
    end
  end
end
```
```
#spec/controllers/test_spec.rb

require 'rails_helper'

describe "test runner runs tests" do
  it "has a its own test too" do
    expect(true).to be true
  end

  it_behaves_like "sharing is caring"
end
```

In with rspec-core >= 3.2.3 I get the following output.

```
jhirn@MacBook-Pro ~/s/d/mme (consolidate_mentor_group_user_association)> bundle exec rspec ./spec/controllers/test_spec.rb:4
Run options: include {:locations=>{"./spec/controllers/test_spec.rb"=>[4]}}
 2/2 |======================================================= 100 ========================================================>| Time: 00:00:00

Finished in 0.20333 seconds (files took 3.31 seconds to load)
2 examples, 0 failures
```

As you can see, two tests are executed rather than the `it "has a its own test too" do` spec which is on line 4 .

Let me know what other information I can provide and thank you for your time.

**Comment by JonRowe** [comment]
Hi, this is already fixed in an upcoming release, see #1961 and #1963

**Comment by jhirn** [comment]
I really really tried to find an issue to avoid opening a dupe. Sorry for the troubles. 

Glad to hear it's getting fixed. Thank you for everything!

**Comment by JonRowe** [comment]
No worries ;)
