### ISSUE TITLE
If no formatter is registered that handles the `message` event, UX can be confusing

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1978]
Just had a weird experience where passing `--only-failures` was causing RSpec to exit with no message whatsoever.  I tracked it down to the fact that the fivemat formatter (which I was using) wasn't handling the `message` event.  RSpec was trying to notify that `--only-failures` wasn't configured properly yet:

https://github.com/rspec/rspec-core/blob/5375dcdfdb5460a51d5003de76eb124997fa26ea/lib/rspec/core/world.rb#L170-L174

...which notifies via `message`:

https://github.com/rspec/rspec-core/blob/5375dcdfdb5460a51d5003de76eb124997fa26ea/lib/rspec/core/reporter.rb#L181-L185

...but since the formatter didn't listen to that message it silently exited.

This was bad UX.

I'm not sure what the best solution is here.  I have a PR out to fix the fivemat formatter (tpope/fivemat#24) but there may be other formatters that don't support `message` properly.  Maybe we should treat `message` as special and if no formatter handles that message fall back to `$stdout.puts` so that no message ever drops on the floor?

**Comment by JonRowe** [comment]
Maybe like we do for the deprecation formatter?

**Comment by myronmarston** [comment]
Remind me...what do we do for the deprecation formatter?  I don't remember.

**Comment by JonRowe** [comment]
Ah I'm actually thinking of the ProfileFormatter, which is inserted when profiling is enabled but only if there isn't a formatter that already implements `dump_profile`....

**Comment by myronmarston** [comment]
Sounds good to me.
