### ISSUE TITLE
Spec with 'feature' or 'features' in directory name are ignored

### ISSUE THREAD

**Issue by tompesman** [rspec/rspec-core#1982]
Specs in directories with the name 'feature' or 'features' are ignored when I run:
`bundle exec spec`

But if I add a pattern the specs are executed:
`bundle exec rspec --pattern 'spec/**/feature/*_spec.rb,spec/**/features/*_spec.rb'`

When I combine it with the other specs the specs in the feature/features directory are ignored:
`bundle exec rspec --pattern 'spec/**/feature/*_spec.rb,spec/**/features/*_spec.rb,spec/**/*_spec.rb'`

I understand that the directory name feature has a special function, but these directories are not at the root of the spec directory. Like: `spec/services/feature/*_spec.rb`

What can I do to get the specs executed all at once?

**Comment by JonRowe** [comment]
Are you using rspec-rails? because features has no special meaning in rspec itself

**Comment by tompesman** [comment]
Yes, i'm using rspec-rails.

**Comment by JonRowe** [comment]
Any chance you could try this without `rspec-rails` temporarily (comment it out your Gemfile or such) and see if the specs will run (they'll fail but they should run) I think this might be specific to `rspec-rails`

**Comment by tompesman** [comment]
Replaced `rspec-rails` with `rspec` and `bundle exec rspec` tries to run the missing specs. So i'm probably in the wrong repo?

**Comment by JonRowe** [comment]
I think so, must be something to do with the spec type inference

**Comment by tompesman** [comment]
Ok, I'll head over to that repo! Thanks!
