### ISSUE TITLE
Duplicate summary ("rspec running twice")

### ISSUE THREAD

**Issue by dentarg** [rspec/rspec-core#1987]
Getting duplicate summary output, like #1929.

Code has one `config.formatter = :documentation` and my `~/.rspec` has `--format d`. Removing either one of them solves the problem of getting duplicate summary.

Could it be possible for rspec to be smart about this?

**Comment by dentarg** [comment]
Using ruby 2.2.2p95 and rspec-core 3.2.3.

**Comment by JonRowe** [comment]
Your instructing us to add two formatters here, given we support multiple formatters this is the expected behaviour, you can check in your config that formatters are empty before adding the `:documentation` formatter via code.

**Comment by myronmarston** [comment]
Actually, this feels like #1144 resurfacing, which was supposedly solved by #1206.  @JonRowe does this not seem like a regression to you?

**Comment by dentarg** [comment]
Thanks @JonRowe

**Comment by JonRowe** [comment]
Oh I see whats happening, we actually have specs for this but they're not correct
