### ISSUE TITLE
Profiling changes from #1971 are buggy

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1989]
I  just noticed this output from our spec suite:

``` 
Top 5 slowest example groups:
  Migrations
    Inf seconds average (13.52 seconds / 0 examples) RSpec::ExampleGroups::Migrations::Sharded::TestingAllRecentMigrations
  Migrations
    Inf seconds average (25.85 seconds / 0 examples) RSpec::ExampleGroups::Migrations::Sharded
  Migrations
    Inf seconds average (0.68397 seconds / 0 examples) RSpec::ExampleGroups::Migrations::NonSharded
  the current generated schema dump
    12.06 seconds average (12.06 seconds / 1 example) RSpec::ExampleGroups::TheCurrentGeneratedSchemaDump
  Migrations
    8.85 seconds average (26.54 seconds / 3 examples) RSpec::ExampleGroups::Migrations
```

"Inf" seconds!

The problem is that `float / 0` returns infinity, and the example count is 0 due to a mismatch in the [profiler](https://github.com/rspec/rspec-core/blob/5778abd5d389d7a20592b047d8f967951838b89d/lib/rspec/core/profiler.rb).  The `example_started` notification only counts the example against the outermost example group, whereas the other notifications update the hash entry for the innermost example group.  As a result, there are entries in the hash that have an example count of 0.

I think we only want to consider the outer example group for the purposes of group comparison anyway, right?  So I'm thinking we will want to use the outer example group for all of those methods.  @JonRowe can you work up a fix?  I think we should hold off releasing 3.3 until this is fixed.

**Comment by JonRowe** [comment]
So this logic was cribbed from the original PR, but you're slightly incorrect on how this works from my view point, all the groups should receive start / end, so I think `example_started` should increment the count for all it's parent groups?

**Comment by myronmarston** [comment]
> So this logic was cribbed from the original PR, but you're slightly incorrect on how this works from my view point, all the groups should receive start / end, so I think example_started should increment the count for all it's parent groups?

That would fix the `Inf` issue but there's something else I'm realizing here: the logic in [3.2 and before](https://github.com/rspec/rspec-core/blob/v3.2.3/lib/rspec/core/notifications.rb#L556-L564) only considered top-level groups.  Inner example groups were not even considered.  Limiting it to just top-level groups dates back to the original PR adding the feature (#887).  Apparently that changed in this revision of example group profiling.

Was that an intentional change on your part?  I certainly didn't realize that was happening with our changes so it probably just slipped in unnoticed?

It might be useful to consider nested groups for listing in the profile output but that's a larger change that needs more thought.  Considering them adds some weirdness in that the groups we'd sort and print aren't completely disjoint -- there'd be overlap and one can imagine us printing both a group and its nested group in the profile output if we consider both.  So at least for now I'm thinking the simplest solution is to add a `return unless notification.group.top_level?` guard clause to the `example_group_started` and `example_group_finished` methods.

If we wanted to support nested groups I'm thinking we'd want to prevent overlapping groups from printing...so once the slowest group has been identified its child and parent groups would be eliminated from consideration for positions (2..n), and likewise for all the positions.

**Comment by myronmarston** [comment]
I'm working on a fix for this.  I actually found another bug in the output :(.  I'll tackle both at the same time.
