### ISSUE TITLE
Getting "Unable to find matching line from backtrace" from expectation in spec support file

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#1991]
Currently our [logic that looks for a matching line in the backtrace](https://github.com/rspec/rspec-core/blob/9eba761472a3447b4746a1e3fe0a9daabbfc4aca/lib/rspec/core/formatters/exception_presenter.rb#L130-L136) limits its search to backtrace lines from the file where the example is defined.  This fails if you have a shared context in `spec_helper` or a support file that defines an `after` hook that has a failing expectation.  It's not a good experience to get "Unable to find matching line from backtrace".   We should fix this, but it's not obvious what the right fix is.

Ultimately, "Unable to find matching line form backtrace" is really sub-optimal so I think it's worth having some fallback logic.  Here's one idea of how to do that:

* Look through the backtrace to find the first line from the definition file.
* If that fails, look again to find the first line from a file in your project (e.g. a file that does not contain `/gem/` in its path or similar...).
* If that fails, take the first line.

Thoughts?

**Comment by JonRowe** [comment]
Don't see any harm in that strategy
