### ISSUE TITLE
Is there a built-in way to raise an exception if no expectation is called?

### ISSUE THREAD

**Issue by barelyknown** [rspec/rspec-core#1996]
I searched through the documentation and didn't find anything.

Is there a configuration setting (or other way) to have RSpec raise an exception if no expectations are called in a test? This would help detect tests that accidentally do nothing.

**Comment by myronmarston** [comment]
It's on the road map -- see #759.  http://blog.sorah.jp/2012/12/17/rspec-warn-for-no-expectations shows one way to accomplish this kind of thing for now since we don't yet directly support it.  Maybe it'll be in 3.4 :).

**Comment by barelyknown** [comment]
Thanks for the info. The solution in that post is old and relies on private methods that are no longer available, so I'll just wait until its supported directly.
