### ISSUE TITLE
Specifying multiple pattern arguments the last one hides the others

### ISSUE THREAD

**Issue by rbu** [rspec/rspec-core#2000]
I've only recently discovered that when you specify multiple include patterns, they are not automatically joined, but *ignored silently* by rspec.

Consider the following spec file:
```
--pattern features/*_spec.rb
--pattern features/plugins/*_spec.rb
```

My assumption was that this behaves identical to ```--pattern features/*_spec.rb,features/plugins/*_spec.rb```.
Instead, it silently ingnores the ```features/*_spec.rb``` files. This is contra-intuitive to how most other tools parse file-level arguments.

Rspec should either bail out when it ignores an include pattern it would ignore, or (preferably) join the patterns.

**Comment by dwt** [comment]
I'd like to add, that if both these options are not acceptable (and I am strongly in favor of just joining the patterns), the command line should at *least* loudly tell that an argument is ignored, else this is really hard to spot.

**Comment by JonRowe** [comment]
Next release will treat multiple `--pattern` as one joined by `,` feel free to try out master in the meantime

**Comment by rbu** [comment]
@JonRowe, Thanks for the fast fix. Awesome!
