### ISSUE TITLE
Turn RSpec warnings into errors via configuration

### ISSUE THREAD

**Issue by danielsdeleo** [rspec/rspec-core#2005]
In my code base, I'm getting a ton of `warn_about_potential_false_positives` warnings. I would like to be able to configure RSpec to make these into errors, like with the deprecation warnings from 2.x -> 3.x to help me clean them all up and prevent future occurrences of this kind of usage.

I didn't see any option for this in the configuration code (here or in rspec-expectations) and `raise_errors_for_deprecations!` doesn't do this, my apologies if I've missed something.

Thanks for your time.

**Comment by cupakromer** [comment]
:blue_heart: @danielsdeleo for this suggestion. I really like it :+1: do you want to try submitting a PR? (no pressure, if you don't that's totally fine :sunglasses: - I'm happy to help either way)

**Comment by danielsdeleo** [comment]
Not sure if I'll have time to make a PR any time soon, just got back to work from a short vacation and need to see what's going on with that. I'll update this ticket if I intend to make one.

**Comment by cupakromer** [comment]
Sounds good. I'll plan on a PR for it over the weekend if we don't hear back from you before then. :smile_cat:

**Comment by danascheider** [comment]
Is somebody still working on this? If not, I can make a PR, just wanted to check first.

**Comment by myronmarston** [comment]
As far as I know, no one is working on this.

**Comment by danascheider** [comment]
Cool, I'm on it

**Comment by samphippen** [comment]
@danascheider did you get a chance to work on this? We'd love to see a PR ^_^

**Comment by JonRowe** [comment]
I got a chance to implement something for this in #2052 and rspec/rspec-support#234

**Comment by danascheider** [comment]
I'm sorry! I only just now saw @samphippen's comment! Things got hectic and I was about to work on it some more but it looks like Jon beat me to the punch.

**Comment by JonRowe** [comment]
Closed by #2052

**Comment by danielsdeleo** [comment]
Thanks so much to everyone who contributed to this, it will be much appreciated :100:
