### ISSUE TITLE
Consider adding an `example_finished` event to the notifications system

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#2012]
In writing up an example of how to observe the status of every example via a formatter for #2011, I noticed that there's no `example_finished` event, so I had to listen to 3 events (`example_passed`, `example_pending` and `example_failed`) and use aliases to have them go through the same logic.

It would be nice if there was also an `example_finished` event that was notified when an example finishes regardless of the status.

/cc @JonRowe

**Comment by chris1248** [comment]
Would have saved me much confusion yesterday.
