### ISSUE TITLE
Aruba Update

### ISSUE THREAD

**Issue by maxmeyer** [rspec/rspec-core#2016]
@myronmarston @JonRowe I updated aruba and added quite a few deprecation warnings. This breaks your test suite! Anything I can do to help you with this or what we can do better on deprecations not to break your setup? Or does it make sense to release a pre-release?

@mattwynne
Ping

**Comment by myronmarston** [comment]
> This breaks your test suite!

Does that imply you're doing a major version bump in the next release?  Or are we relying upon private APIs that are not subject to SemVer?  Or does that imply regressions in aruba?

> Anything I can do to help you with this

You're welcome to open PRs on the rspec repos updating aruba and fixing our use usage of the deprecated APIs :).

> Or does it make sense to release a pre-release?

It doesn't hurt to do a pre-release, although I personally don't think I have the time to try it out.

**Comment by maxmeyer** [comment]
> Does that imply you're doing a major version bump in the next release? Or are we relying upon private APIs that are not subject to SemVer? Or does that imply regressions in aruba?

I think there will some more minor release before the major one. 

> You're welcome to open PRs on the rspec repos updating aruba and fixing our use usage of the deprecated APIs :).

Mmmh...Some time in the future ;-) Now its aruba time. Unfortunately there' will some more deprecations in the next minor updates. So please keep me informed if some more things break. I will try and keep you up to date.

**Comment by JonRowe** [comment]
Depreciations in minor versions shouldn't be breaking our test suite unless
you're not following semver or we are using private apis, we'd appreciate
feedback so that future minor release won't break us...

>

**Comment by maxmeyer** [comment]
The problem is that you're checking stdout/stderr. How should we inform users about deprecations?

**Comment by maxmeyer** [comment]
I did not remote any method it's just the output of the deprecation warnings which break your setup.

**Comment by maxmeyer** [comment]
```
Failure/Error: Unable to find matching line from backtrace
RuntimeError:
 Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
 The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
 The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
```

**Comment by maxmeyer** [comment]
I'm not sure how we could handle this differently.

**Comment by JonRowe** [comment]
Provide a configurable warnings change that defaults to stderr? We also
might need to look why that's breaking us I thought we excluding 3rd party
warnings from those checks!
>
>

**Comment by myronmarston** [comment]
Thanks for the clarification.  I'd agree that adding new warning is not a breaking API change.  We just care a lot about keeping things warning free and therefore have our build configured to fail any examples that generate warnings.  So I think it's fine for you to add those warnings.

> Provide a configurable warnings change that defaults to stderr?

I don't think that's necessary, honestly.

> We also might need to look why that's breaking us I thought we excluding 3rd party
warnings from those checks!

Nope.  I assume you are thinking of [this line](https://github.com/rspec/rspec-support/blob/ae75b3ecb4cc3665e3451f1f5bcc39ef71c88537/lib/rspec/support/spec/stderr_splitter.rb#L39)?  That justs ignores _ruby_ warning originating from other gems but does nothing about `Kernel.warn` calls from other gems.

Historically, we haven't always kept current with aruba and cucumber and there's no particular need to start now.  The existing versions we are using meet our needs quite well.  It'd be nice to upgrade at some  point but I don't see it as urgent.

**Comment by maxmeyer** [comment]
> The existing versions we are using meet our needs quite well. It'd be nice to upgrade at some point but I don't see it as urgent.

Then better stay on 0.6.5 for now. I'm going to refactor the api in the upcoming version once more.

**Comment by JonRowe** [comment]
Thanks for the heads up anyway :)
