### ISSUE TITLE
The term 'filter' in documentation contradicts the common usage of the term

### ISSUE THREAD

**Issue by ian-kelling** [rspec/rspec-core#2017]
m-w.com defines the verb filter

1:  to subject to the action of a filter
2:  to remove by means of a filter 

From https://relishapp.com/rspec/rspec-core/v/3-3/docs/command-line/tag-option
"The tag can be a simple name or a name:value pair. In the first case,
examples with :name => true will be filtered."

So I expect examples with :name => true to be removed or subjected to a filter. What actually happens is that examples with :name => true are run and no other examples are run.

So the documentation would make sense to say something like "the examples will be subject to a filter which includes only :name => true."

This usage is also repeated throughout the linked document. It's very confusing on the first read, and even after that, I have to continually remind myself whenever I see it.

**Comment by myronmarston** [comment]
I think "filter" can still be used, but we should phrase it as:

> The tag can be a simple name or a name:value pair. In the first case,
the examples will be filtered to those with `:name => true`."

...but obviously there are other ways to phrase it.  We'd gladly accept a PR to improve our docs.  Want to take a stab at it?

**Comment by ian-kelling** [comment]
Sure. I'll give it shot this weekend.

**Comment by myronmarston** [comment]
:+1: Thanks in advance!

**Comment by samphippen** [comment]
@ian-kelling do you still have some time to do this? It'd be great if you could open a PR ^_^

**Comment by myronmarston** [comment]
Addressed by #2090.

**Comment by ian-kelling** [comment]
Thanks to creature for fixing this. Unfortunately I did not get time to do it.

**Comment by ian-kelling** [comment]
Thanks to creature for fixing this. Unfortunately I did not get time to do it.

**Comment by creature** [comment]
No problem! Glad I could help out. :)
