### ISSUE TITLE
remove ANSICON colors= warning; ANSICON is not required to get colored output on windows

### ISSUE THREAD

**Issue by weedySeaDragon** [rspec/rspec-core#2020]
<code>colors=</code> on a Windows system will output a warning if the utility ANSICON is not being used (or at least there isn't an ENV for it). The warning says *"You must use ANSICON 1.31 or later to use colour on Windows."*  This simply isn't correct:  You don't have to use ANSICON to get colored output on Windows.  I don't use ANSICON; I've found other utilities/ways to get colors just fine.  I don't use ANSICON because it wouldn't work on my system (Winx64) when I first tried to use it so I had to find an alternative.
*(Note that right now, RSpec::Support is not correctly reporting that a system is a Windows system.  But once it is, more people will be seeing this warning.)*

Not only is the warning not correct, but there's no way to silence it!  It's really tiresome to have it show up all of the time when it simply doesn't apply.  My system is operating correctly and yet I'll never be able to get rid of this warning.  (Unless I add cruft to my ENV vars just to shut it up.) It's not appropriate to generate a warning that you can only turn off if you (a) use exactly that tool, or -- if that tool won't work for you or if you hve a different alternative -- you add unnecessary trash to your system (meaning an ENV entry that I don't need or use).

This information really belongs in **documentation.**  

The documentation can explain that there are different tools and utilities out there that can be used on Windows systems so that RSpec generated output shows up in color.  ANSICON can be listed as one of the options (but not *the* option, of course).

**Comment by myronmarston** [comment]
Thanks for reporting this.  I wasn't involved in the decision to add that warning (it predates my time) but I'm not surprised it's no longer accurate.  Windows has changed but none of the core RSpec devs uses windows so we don't know about these things.

Can you open a PR with you suggested changes?  Given that none of us core RSpec devs know what the right way to handle this on windows is...None of us are going to be able to come up with improved logic/warnings/docs for this.

**Comment by weedySeaDragon** [comment]
I'll do the PR.  
(And I suspected you weren't involved with the decision to add that warning.)

**Comment by samphippen** [comment]
@weedySeaDragon did you get a chance to look at this, it'd be great if you could help us out ^_^

**Comment by weedySeaDragon** [comment]
thanks for the nudge @samphippen.  I'll get on this.

**Comment by myronmarston** [comment]
Addressed by #2038.
