### ISSUE TITLE
Feature request: focus on an arbitrarily-defined set of specs

### ISSUE THREAD

**Issue by geeksam** [rspec/rspec-core#2024]
As someone who spends a lot of time working in legacy codebases, here's something I do with some regularity:

  1. Raise an exception in some code I wish to refactor
  2. Run the entire spec suite
  3. Mark all examples that failed as "relevant to my interests"
  4. Rerun all examples in that set repeatedly while refactoring
  5. Undo step 3

Currently, I can accomplish step 3 by manually prepending 'f' to the 'it' or 'specify' of all failing examples, and step 5 by clever use of Git, but this process can be somewhat tedious.  The recent advent of the --only-failures CLI option suggests that a similar effect could be achieved by some clever manipulation of the file at ```example_status_persistence_file_path```...?

**Comment by myronmarston** [comment]
You can certainly edit the `example_status_persistence_file_path` to do whatever you want (such as editing the `status` column).   Just be aware that RSpec probably won't give you very friendly errors if your edits mess with it's ability to parse it.

Do you have any specific ideas for anything else we could do to facilitate this work flow?

I also wonder if something like this could be handled by RSpec some day:

http://tenderlovemaking.com/2015/02/13/predicting-test-failues.html

While mapping implementations to tests that execute it seems prone to many problems (e.g. add one comment line at the top of the file and now your data is all off-by-one-line) a course-grained approach of mapping implementation files to test files could be useful and could perhaps approximate what you're trying to achieve with less effort.  Of course, that's only possible with the ruby patch @tenderlove discussed in his blog post so it's not even possible yet.

**Comment by JonRowe** [comment]
I'm wondering if adding something like a `--freeze-failures` command would help, so that we don't update the status and allow you to keep running them as `--only-failures`

**Comment by myronmarston** [comment]
One other idea -- instead of using `fit` and `fspecify` to leverage RSpec's `focus` feature, you might think about using arbitrary tags.  For example, if you're working on issue #xyz, you could tag all the specs with a tag to indicate they are related to that issue:

``` ruby
it 'does something', issue: xyz do
end
```

...and then you could run all the specs for that issue with:

``` ruby
rspec --tag issue:xyz
```

`fit`/`fspecify` is obviously important to undo when you are done but these tags could stick around -- after all, it's potentially useful metadata to have on the specs, so there's no need to delete the tags.

**Comment by geeksam** [comment]
@JonRowe: ```--freeze-failures``` would be perfect.

@myronmarston: that would work as well, but requires me to come up with a meaningful tag. (Not that that's a bad thing, mind you.) :)

**Comment by myronmarston** [comment]
I think this would work:

``` ruby
RSpec.configure do |rspec|
  rspec.example_status_persistence_file_path = 'spec/examples.txt'

  if ENV['FREEZE_FAILURES']
    FileUtils.cp("spec/examples.txt", "spec/examples.txt.backup")
    at_exit { FileUtils.mv("spec/examples.txt.backup", "spec/examples.txt") }
  end
end
```

```
FREEZE_FAILURES=1 rspec --only-failures
```

**Comment by geeksam** [comment]
Nice! Let me give that a try...

**Comment by geeksam** [comment]
@myronmarston: yes, that works quite nicely, and also avoids the potential trap of forgetting to unfreeze those failures.  (I've accidentally committed more than one 'fit' just in the last month, d'oh!)  Thank you!

If a ```--freeze-failures``` option were to be added, that's exactly the behavior (if not necessarily the implementation) it should have.  I have no idea whether anybody else might want this feature, though.  Should I close this?  (I might take a stab at implementing it anyway, just for my own edutainment.)

**Comment by myronmarston** [comment]
Given how easy it is for users to implement with a few lines of config...my instinct is to not add it yet, but if there's significant user demand we can revisit.

**Comment by geeksam** [comment]
Yeah, that's the call I'd make, too.  Thanks again!
