### ISSUE TITLE
2.99 does not warn properly when using an inner `describe :symbol`

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#2025]
See rspec/rspec-rails#1415 for an example user report.  2.99 should warn for this case but it does not.  The problem is here:

https://github.com/rspec/rspec-core/blob/v2.99.2/lib/rspec/core/metadata.rb#L184

It still treats symbols as a special case like strings.  Compare to:

https://github.com/rspec/rspec-core/blob/v3.3.1/lib/rspec/core/metadata.rb#L298

...which does not treat symbols as a special case.

**Comment by xaviershay** [comment]
Appropriate warning for this would be https://github.com/rspec/rspec-core/blob/v2.99.2/lib/rspec/core/metadata.rb#L139, right?

**Comment by xaviershay** [comment]
A warning is triggered currently _only_ if `subject` is used. So the following _will_ issue a warning (and we have a test case for exactly this):

```
describe String do
  describe :create do
    it 'works' do
      subject
    end
  end
end
```

But if you remove `subject` it does not warn... but also it works just fine in RSpec 3. So I see a couple of options here:

1. Minimal repro provided in https://github.com/rspec/rspec-rails/issues/1415 is not correct and this is actually a different problem. @jeffheifetz might be too long ago for you to care/remember, but tagging you in case some other context occurs to you.
2. `rspec-rails` is doing something weird to trigger it. I'm not sure how to get a set up to test this within a reasonable amount of time.

If no-one has any bright ideas, I recommend closing this as "cannot reproduce".

@myronmarston @JonRowe 

(Thanks to @salvatoret who helped me look into this.)

**Comment by JonRowe** [comment]
> rspec-rails is doing something weird to trigger it. I'm not sure how to get a set up to test this within a reasonable amount of time.

How about `described_class`?

**Comment by xaviershay** [comment]
https://github.com/rspec/rspec-core/blob/2-99-maintenance/spec/rspec/core/example_group_spec.rb#L360 suggests that `described_class` warnings are working as intended.

**Comment by myronmarston** [comment]
I was on vacation Wednesday until today so I haven't had a chance to look into this yet.  I hope to in the next day or so.

**Comment by myronmarston** [comment]
I think you're right that this is handled properly.  My confusion was comparing https://github.com/rspec/rspec-core/blob/v2.99.2/lib/rspec/core/metadata.rb#L184 vs https://github.com/rspec/rspec-core/blob/v3.3.1/lib/rspec/core/metadata.rb#L298 -- it looks like 2.99 is wrongly treating `Symbol` as a special case in that method.  Looking more into it, the `Symbol` case is handled here instead:

https://github.com/rspec/rspec-core/blob/v2.99.2/lib/rspec/core/example_group.rb#L327-L331

I agree with closing this, barring a clear repro case of a situation where 2.99 does not warn but should.
