### ISSUE TITLE
Segmentation fault for repeated definition

### ISSUE THREAD

**Issue by JochenFromm** [rspec/rspec-core#2031]
Rspec causes in some cases of repeated definitions a segmentation fault, for example if you define a variable with `let!` two times with the same name. This can produce a `vm_call_cfunc - cfp consistency error` in the RSpec core, a Ruby Crash Report and a `Segmentation fault: 11`

```
let!(:some_var) { "Some value" }

describe '.method' do
  ...
  let!(:some_var) { "Some other value" }
end
```

(Ruby version 2.2.2, RSpec-core 3.2.3)

**Comment by JochenFromm** [comment]
Turns out the bug was more caused by a recursive let definition

```
let!(:some_var) { create(:model, some_var: some_var) }
```

**Comment by myronmarston** [comment]
Yep, known bug in Ruby.  Nothing we can do about it, sadly :(.  Thanks for reporting anyway!
