### ISSUE TITLE
Example inside shared_context causes the failure of controller and view spec

### ISSUE THREAD

**Issue by jiajiawang** [rspec/rspec-core#2034]
I'm trying to use shared_context to DRY my api specs.
Here is one of the sample:
```
RSpec.shared_context "authenticated api request", :auth do
  let(:user) { create(:user) }
  before :each do
    login_as(user)
  end

  after :each do
    Warden.test_reset!
  end

  context 'when not authenticated' do
    before :each do
      logout
      send(method, url)
    end
    it 'returns authentication error' do
      expect(json["errors"]).to eq(
        ["You need to sign in or sign up before continuing"])
    end
  end
end
```
It works well.
Both the api specs and controller specs will all pass if I run them separately.
`rspec spec/apiv1/`
`rspec spec/controllers/`

However, when I run them together `rspec spec/apiv1/ spec/controllers`, if controller specs are executed after api specs, then controller specs will fail.

The error messages is
```
Failure/Error: get :index
     NoMethodError:
       undefined method `[]' for nil:NilClass
```
I tracked it down to https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L30

I found that if I take the example below out of the shared context, everything then works again.
```
    it 'returns authentication error' do
      expect(json["errors"]).to eq(
        ["You need to sign in or sign up before continuing"])
    end
```

**Comment by JonRowe** [comment]
Hi, this is actually the wrong repo to open this issue against, as it's rails specific, but regardless can you gist your specs? As this isn't enough information to figure out what's going wrong here, currently I can at least point out that `send(method, url)` is going to be problematic for you...

**Comment by jiajiawang** [comment]
Thanks @JonRowe
The issue has already been resolved by replacing a line in `spec_helper.rb`
`-config.include RSpec::Rails::RequestExampleGroup, type: :request, parent_example_group: { file_path: /spec\/api/ }`
`+config.include RSpec::Rails::RequestExampleGroup, type: :request`
And add `type: :request` to all api specs under spec/api.

Although I don't what's wrong with that parent_example_group config.

**Comment by JonRowe** [comment]
Pass, but it's not a standard thing to want to do or necessarily even supported...
