### ISSUE TITLE
Include the #cause when formatting exception backtraces

### ISSUE THREAD

**Issue by trejkaz** [rspec/rspec-core#2044]
Since Ruby 2.1, `Exception` has a `#cause` method which shows the underlying cause of the exception. (When running on MRI, if you raise an exception from a rescue block, it sets the cause automatically. When running on JRuby, if the underlying exception came from Java, it exposes `Throwable#getCause()`. The similar naming is not a coincidence - I believe it was JRuby's devs who convinced Ruby to add the feature.)

Often this contains the most useful information about the failure - the actual underlying stack which caused the test to fail, rather than a wrapped exception some higher label provided to format a nice error message.

We're currently using a trick like this to enhance `ExceptionPresenter` to print this extra info:

    RSpec::Core::Formatters::ExceptionPresenter.class_eval do

      # Overridden to print nested causes as well as the top-level exception.
      def formatted_backtrace

        # Caught exception
        exception = @exception
        str = backtrace_formatter.format_backtrace(exception.backtrace, example.metadata)

        # Cause chain
        while exception.respond_to?(:cause)
          exception = exception.cause
          str += "--- Caused by: ---\n"
          str += backtrace_formatter.format_backtrace(exception.backtrace, example.metadata)
        end

        str
      end

    end

Something like this baked into core would probably be better, but I am not sure if it makes sense in general to return it from `formatted_backtrace` itself, because now it formats more than one backtrace. Maybe there should be another method which calls `formatted_backtrace` once for each exception.

**Comment by JonRowe** [comment]
I think this makes more sense as an external formatter, most people don't want the underlying stack frames from an exception when writing tests

**Comment by JonRowe** [comment]
I'd be happy to help you write this in so you could release it as a gem to provide this for others who do want the detail though

**Comment by trejkaz** [comment]
You think that most people don't want to know why their test actually failed? Why show the stack at all then, if the only one you're showing is the wrong one?

**Comment by JonRowe** [comment]
Maybe I'm miss understanding what you mean, what does cause return? From what you're saying I'm expecting the stack which isn't trivially understandable (as it'd show memory locations and the like), where as we currently show the backtrace, which is?

**Comment by JonRowe** [comment]
Can you provide some demo output?

**Comment by trejkaz** [comment]
Given that you have a broken class:

    class BrokenCode
      def self.shallow_method
        begin
          deep_method
        rescue
          raise "Something happened and I'm hiding that from the message 'because usability'."
        end
      end

      def self.deep_method
        raise 'The real cause for the failure is here!'
      end
    end

And you have a spec which triggers the exception:

    RSpec.describe 'some broken code' do
      it 'works' do
        BrokenCode.shallow_method
      end
    end

The current output from RSpec will be:

	  1) some broken code works
	     Failure/Error: raise "Something happened and I'm hiding that from the message 'because usability'."
	     RuntimeError:
	       Something happened and I'm hiding that from the message 'because usability'.
	     # ./my_spec.rb:32:in `rescue in shallow_method'
	     # ./my_spec.rb:29:in `shallow_method'
	     # ./my_spec.rb:43:in `block (2 levels) in <top (required)>'

The code I posted is broken for this particular case (in our real system, it somehow works for the failures I have seen to date, but it isn't very well tested.)

But the ideal output (IMO) is something like this:

      1) some broken code works
         Failure/Error: raise "Something happened and I'm hiding that from the message 'because usability'."
         RuntimeError:
           Something happened and I'm hiding that from the message 'because usability'.
         # ./my_spec.rb:32:in `rescue in shallow_method'
         # ./my_spec.rb:29:in `shallow_method'
         # ./my_spec.rb:43:in `block (2 levels) in <top (required)>'
         --- Caused by: ---
         RuntimeError:
           The real cause for the failure is here!
         # ./my_spec.rb:37:in `deep_method'
         # ./my_spec.rb:30:in `shallow_method'
         # ./my_spec.rb:43:in `block (2 levels) in <top (required)>'

I managed to fix the code I wrote not to fail in this situation, but it formats the wrong result, so I am probably going to change it to override the next method along instead (`format_message_and_backtrace`?)

      def formatted_backtrace

        # Caught exception
        exception = @exception
        str = backtrace_formatter.format_backtrace(exception.backtrace, example.metadata)

        # Cause chain
        while exception.respond_to?(:cause) && exception.cause
          exception = exception.cause
          str << ["--- Caused by: ---\n"]
          str << backtrace_formatter.format_backtrace(exception.backtrace, example.metadata)
        end

        str
      end

**Comment by trejkaz** [comment]
My quick attempt at improving the output in the last 5 minutes of the work week:

    RSpec::Core::Formatters::ExceptionPresenter.class_eval do

      # Overridden to print nested causes as well as the top-level exception.
      # Trying to get something like this into rspec-core: https://github.com/rspec/rspec-core/issues/2044
      def formatted_backtrace(exception = @exception)

        # Caught exception
        lines = backtrace_formatter.format_backtrace(exception.backtrace, example.metadata)

        # Cause chain (recursive)
        cause = exception.respond_to?(:cause) ? exception.cause : nil
        if cause
          lines << ''
          lines << '--- Caused by: ---'

          # Replicating stuff that happens in another method. 
          lines << "#{exception_class_name}:" unless exception_class_name =~ /RSpec/
          encoded_string(cause.message.to_s).split("\n").each do |line|
            lines << "  #{line}"
          end

          lines += formatted_backtrace(cause).map { |line| "  #{line}" }
        end

        lines
      end

    end

This gives:

  1) some broken code works
     Failure/Error: raise "Something happened and I'm hiding that from the message 'because usability'."
     RuntimeError:
       Something happened and I'm hiding that from the message 'because usability'.
     # ./my_spec.rb:46:in `rescue in shallow_method'
     # ./my_spec.rb:43:in `shallow_method'
     # ./my_spec.rb:57:in `block (2 levels) in <top (required)>'
     # 
     # --- Caused by: ---
     # RuntimeError:
     #   The real cause for the failure is here!
     #   ./my_spec.rb:51:in `deep_method'
     #   ./my_spec.rb:44:in `shallow_method'
     #   ./my_spec.rb:57:in `block (2 levels) in <top (required)>'

There might be too many lines prefixed with hashes, but maybe I'm just being too picky. The way the hack is shoehorned in still feels wrong though anyway.

**Comment by stanio** [comment]
Not sure if this could help: https://gist.github.com/stanio/13d74294ca1868fed7fb

**Comment by trejkaz** [comment]
Monkey patching Exception certainly works too, but I thought people decided that monkey patching was evil.

**Comment by myronmarston** [comment]
I disagree with @JonRowe here -- I think that if there is a `cause`, it makes sense to include it in the output.  We wouldn't implement it using monkey patching, of course, but @stanio's gist is useful.  Anyone want to take a stab at a PR?

**Comment by stanio** [comment]
Yes, I haven't meant mine as a complete solution for the given use case, but probably demonstrate some details like omitting duplicate stack for the nested cause(s).

**Comment by samphippen** [comment]
I think we should implement this too, @stanio are you volunteering to make a PR, or is this free for others to take a look at?

**Comment by stanio** [comment]
@samphippen Sorry, I wouldn't be able to help with the RSpec task.  It happens I just came across this issue while searching if there's anything like this already done I could reuse.

**Comment by mrageh** [comment]
@trejkaz My patch for this just got merged into master, maybe we can close this issue now?

**Comment by samphippen** [comment]
Closed by #2074
