### ISSUE TITLE
 is there any way to output data from example to html formatter?

### ISSUE THREAD

**Issue by chandanaGollapudi** [rspec/rspec-core#2056]
Hi,

I am using html formatters to generate rspec test results. I would like print some additional information in html report. is there in method that can be used directly from example to print the additional information into html report ?

**Comment by JonRowe** [comment]
No, you'd have to extend the html formatter to do this.

**Comment by myronmarston** [comment]
Does the HTML formatter not handle the 'reporter.message' notification? (Hard to check on my phone now)

**Comment by JonRowe** [comment]
I had a look, I don't think it does if it does it outputs to console as text not as html
