### ISSUE TITLE
Rspec "let" in random order

### ISSUE THREAD

**Issue by benoittgt** [rspec/rspec-core#2059]
Hello !

I'm having a little random problem that happens sometimes. Test fail randomly. Object are created in a different order.

Here is a quick example of my code : 

```ruby
context 'has two devices' do
  let!(:device1) { create :device, user: user1 }
  let!(:device2) { create :device, user: user2 }

  subject { get :index, store_id: store_id, page: page, format: :json }

  it do
    expect(subject.body).to include_json(
      devices: [
        {
          id: device1.id,
          model: device1.device_model,
          udid: device1.udid,
          adid: device1.adid,
          imei: device1.imei,
          user_id: device1.user_id,
          blacklisted: false
        },
        {
          id: device2.id,
          blacklisted: true
        }
      ]
    )
  end
end
```

Sometimes it will return
```
    Failure/Error: expect(response.body).to include_json(

                 json atom at path "devices/0/id" is not equal to expected value:

                   expected: 19379
                        got: 19380

                 json atom at path "devices/0/udid" is not equal to expected value:

                   expected: "bo350bvpxingx18pxgs6r44wwbff2zgiqovwyq4m"
                        got: "2htpr26rjs9hec5qlxxxbzad9a239ezrgrhjcp1a"

                 json atom at path "devices/0/user_id" is not equal to expected value:

                   expected: 93958
                        got: 93959

                 json atom at path "devices/0/blacklisted" is not equal to expected value:

                   expected: false
                        got: true

                 json atom at path "devices/1/id" is not equal to expected value:

                   expected: 19380
                        got: 19379

                 json atom at path "devices/1/blacklisted" is not equal to expected value:

                   expected: true
                        got: false
```

Sometimes

```
.

Finished in 0.73745 seconds (files took 0.28197 seconds to load)
1 example, 0 failures
```

I'm using [json_expectations](https://github.com/waterlink/rspec-json_expectations) but the problem is the same if I parse the json with `JSON.parse(subject.body)` and match key with `.first` object and `.last` object.

Sometimes `device1` is created after `device2` so my test fail because of info that not match. It's random. 

Maybe my test are not well written or it's an rspec feature. 

I'm using rspec-core `3.2.3` and ruby `ruby 2.2.2p95 (2015-04-13 revision 50295)`

**Comment by cupakromer** [comment]
Your spec isn't necessarily saying that the `let!` statements run in a random order. Under the hood they setup `before` calls in the order defined. What is likely happening is your database is returning the results in a different order. Not all databases return things in default `id` order. Depending on which Rails version you are on, Rails may not be setting a default order on the query either.

I suspect if you added `order(:id)` to your controller query it would resolve this problem. Unless your expectation is to always get results in `id` order, this spec seems to have exposed an order dependent issue with `json_expectations`.

**Comment by cupakromer** [comment]
I would also caution you that this style of spec writing will be very confusing to other. I often re-order my `let` statements alphabetically. If for some reason you had different names than "device1" and "device2" it is likely that my simple re-ordering would break specs. Which would really confuse me.

I suggest instead to use a style like this:

```ruby
let(:device1) { build(:device, user: user1) }
let(:device2) { build(:device, user: user2) }

before do
  device1.save!
  device2.save!
  expect(
    device1.id
  ).to (be < device2.id), "Precondition Failed: device2 id is before device1"
end
```

This makes the order dependent and clear.

**Comment by JonRowe** [comment]
Whats happening here is your results are not being returned in id order, this is actually not guaranteed by your database unless you manually order your query. You can use `match_array` to match regardless of ordering or order your query in your app.

**Comment by benoittgt** [comment]
Thanks a lot both of you for your comments. It's true I didn't specify any order in my request.

I will also be careful to organize my `let` alphabetically. Thanks Aaron for the tips. 

It's sometimes hard to get proper examples. Relishapp is great for that but most of the times the examples you found on relishapp and on internet are very simple and doesn't reflect bigger test. 

I know I'm out of thread but if you have any resources for me to follow, OS project to read and maybe contribute, I'm more than open.

**Comment by JonRowe** [comment]
We've found trivial examples are best to demonstrate features, because bigger tests are dependant on the domain, in this case dependent on both Rails and your own app specific instance, there are worked examples around for testing Rails apps but they usually suffer from being trivial app domains!
