### ISSUE TITLE
rspec single file have a different inheritance relationship than rspec all

### ISSUE THREAD

**Issue by Nxbtch** [rspec/rspec-core#2062]
rspec all:

<img width="316" alt="2015-08-18 6 55 17" src="https://cloud.githubusercontent.com/assets/1689822/9328379/c348766c-45da-11e5-98a2-5eb8d8bb3db3.png">

rspec single file:

<img width="467" alt="2015-08-18 6 55 08" src="https://cloud.githubusercontent.com/assets/1689822/9328386/ceb2c4b2-45da-11e5-942f-739da6ee7062.png">

**Comment by myronmarston** [comment]
I don't understand what you are trying to point out.  None of the classes or modules printed in those screen shots originate from RSpec.

**Comment by Nxbtch** [comment]
@myronmarston 
<img width="647" alt="2015-08-19 10 49 09" src="https://cloud.githubusercontent.com/assets/1689822/9347732/21c54ed8-4660-11e5-908c-603f3e6e0c66.png">

using pry-byebug set a break point in my controller's action,  

show inheritance relationship with following method call
```ruby
  self.class.ancestors
```

the result is diff from *rspec* , without single file as the parameters

<img width="785" alt="2015-08-19 10 53 51" src="https://cloud.githubusercontent.com/assets/1689822/9347767/9edde97a-4660-11e5-9d67-7f72537ca4cc.png">


planners_controller is inhreit from Api::V2::ApplicationController, some method is defined here, but Api::V2 ::ApplicationController didn't show up in the second pic.
hope i'm clear

**Comment by myronmarston** [comment]
RSpec does not modify the inheritance hierarchy of any user-defined classes.  It could be something else (e.g. another gem) that's only loaded in your test environment or due to rails autoloading (unloading and reloading classes has lots of weird edge cases).  Regardless, I'm confident it's not a problem with RSpec, so I'm going to close this.
