### ISSUE TITLE
Custom Formatter accessing ExampleGroupInstance?

### ISSUE THREAD

**Issue by nambrot** [rspec/rspec-core#2066]
Hi,

I would like to write an RSpec Custom Formatter that takes my Controller tests and outputs nicely the requests that have been made include their parameters, implied path, response status code and body.

Ideally, inside the formatters listeners, I would like to have access to the @example_group_instance, but in https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/example.rb#L240 this will get nil-ified.

Is there any way to access the instance and extract the request/response?

**Comment by nambrot** [comment]
What I found works is to keep a reference in `example_started`, and then access it in in `example_passed/example_failed`

**Comment by JonRowe** [comment]
Capturing the specific data you want in `example_started` is actually a pretty sane way to tackle this, we un-set `@example_group_instance` for performance reasons for the majority of users so I think it makes sense for you to have to deal with this yourself in the formatter.

**Comment by nambrot** [comment]
Thanks, sounds good!
