### ISSUE TITLE
How to stop double loading of specs?

### ISSUE THREAD

**Issue by ianks** [rspec/rspec-core#2070]
Say you have a simple script such as this:

```ruby
require 'rspec/core'

Signal.trap 'USR2' do
  RSpec::Core::Runner.run ['spec']
end

puts Process.pid
sleep
```

This script acts as a server, and you can call something like `sudo kill -USR2 23415` to trigger your specs to run.

However, when running this, RSpec keeps reloading my specs, so the amount of specs I run increases every time I trigger the `Runner`. What should I call instead to run my specs?

**Comment by JonRowe** [comment]
You'll need to call `RSpec.reset` before your call to run.
