### ISSUE TITLE
Creating custom macros/DSL with before hooks

### ISSUE THREAD

**Issue by magicalbanana** [rspec/rspec-core#2073]
This isn't really an issue but I was wondering (I think I made it work for a while but stopped working) but how do I make a custom macro with hooks?

```
def some_macro(&block)
  context "some context" do
     before :each do
       do_something
     end

     instance_eval(&block)
  end
end

describe "some test" do
   some_macro do
     # expected hook
     
     it "is expected to have hook" # but this fails
   end
end
```

Any ideas?

**Comment by myronmarston** [comment]
``` ruby
module MyMacros
  def my_macro(&block)
    context "with foo" do
      before { do_something }
      module_exec(&block)
    end
  end
end

RSpec.configure do |config|
  config.extend MyMacros
end
```

**Comment by myronmarston** [comment]
Let me know if that doesn't work, but that's the normal way to do it.

**Comment by magicalbanana** [comment]
It works, but what about if I want to pass an argument to the block? Would instance_exec or class_exec work?

**Comment by myronmarston** [comment]
`class_exec` or `module_exec` will work (they are aliases).  `instance_exec` would work unless you define instance methods in the block, in which case they would be defined as singleton methods instead of instance methods -- which is why I used `module_exec` in my example.

**Comment by magicalbanana** [comment]
Gotcha, reason is I just wanted my macros to be more readable and not have the values tucked away in this class.

Thanks!
