### ISSUE TITLE
Feature request: allow running the same test multiple times with custom data

### ISSUE THREAD

**Issue by bootstraponline** [rspec/rspec-core#2078]
For Selenium testing, it's necessary to run the same test multiple times with different data each time (desired capabilities control the execution environment). Currently to implement this requires [instance eval](https://github.com/bootstraponline/sauce_rspec/blob/232362759c211621a82e3aa79ddc777f46ad6dc0/lib/sauce_rspec/rspec_caps.rb#L19). It'd be nice if rspec-core allowed running example groups multiple times without hacks. The existing dedupe logic means duplicate example groups are ignored.

**Comment by myronmarston** [comment]
The standard way to run a test multiple times with different data is to use dynamically define them in an `each` block:

``` ruby
RSpec.describe "Dynamic tests" do
  [value_1, value_2].each do |val|
    it "runs some test logic with #{val}" do
      run_test_logic_with(val)
    end
  end
end
```

Any reason that doesn't work for your use case?

**Comment by bootstraponline** [comment]
Yes, I have 100s of tests and the values are constantly changing. Wrapping each one in a wait doesn't scale. The config looks like this:

```
SauceRSpec.config do |config|
  config.caps = [
    Platform.windows_8.firefox.v37,
    Platform.mac_10_11.safari.v8_1
  ]
end
```

Each RSpec test is executed in duplicate (once for safari, once for firefox).

In the [Sauce Ruby gem](https://github.com/saucelabs/sauce_ruby/blob/f8603deec98603c52a69f091ef8aec3895ee2fa0/lib/parallel_tests/saucerspec/runner.rb#L16) an environment variable is set and each test is executed using a separate process which is also an unfortunate hack.

**Comment by JonRowe** [comment]
I think you'd be better off with a custom runner that changes the config and reruns the specs personally

**Comment by bootstraponline** [comment]
I'm already using a custom runner for [parallel execution](https://github.com/tmm1/test-queue/blob/855e0f670f43e597ce87c5694fc34abe0792b3d2/lib/test_queue/runner/rspec3.rb#L17). I don't think I can use two RSpec runners. By creating the tests on World register then the change is independent of the runner.

**Comment by JonRowe** [comment]
You can't use two runners but you could further customise your existing one.

**Comment by bootstraponline** [comment]
I'd have to fork the parallel execution gem and modify every RSpec runner which is less than ideal.

**Comment by JonRowe** [comment]
No you'd just have to modify the one runner you use... This is a fairly custom thing you're requesting so I think you're going to have to write some custom code to do it. 

As @myronmarston says the usual way to run tests multiple times is define the tests multiple times using an iterator, while it isn't ideal in your case to do so because you'd have boilerplate in every file you could actually set it up that way fairly easily. If you really wanted to ease this you could create a custom DSL  (`Sauce.describe`?) for yourself that calls `RSpec.describe` once for every environment combination (which a different name ideally) and just use that in your specs.

Either way I'm closing this for now as I don't think it's something that belongs in rspec-core

**Comment by bootstraponline** [comment]
> No you'd just have to modify the one runner you use...

The goal is to offer a solution that works with any of the parallel execution gems which all define their own runner. test-queue alone has at least 3 runners for rspec. Forking these and maintaining custom runners isn't a viable option.

`Sauce.describe` means people would have to modify their existing tests which isn't acceptable.

> No you'd just have to modify the one runner you use... This is a fairly custom thing you're requesting so I think you're going to have to write some custom code to do it.

I think the custom code which patches rspec is the most maintainable fix for now. It's unfortunate that rspec-core doesn't have a more flexible API. A hook into the World `register` method would enable this use case in a more general way without monkey patching.

**Comment by JonRowe** [comment]
If you feel like adding that hook and it does it in such a way that doesn't
impact the performance for the general use case please feel free to open a
PR

**Comment by bootstraponline** [comment]
I think the following code would have minimal performance impact while making it easier for 3rd party code to manipulate example groups before they're registered.

If this approach seems fine then I'm happy to submit a PR with tests. If the use case is too unique though then I understand not wanting it in core.

```ruby
# @api private
#
# Prepare an example group for registration.
# Hook used by 3rd party code.
def before_register(example_group)
  example_group
end

# @api private
#
# Register an example group.
def register(example_group)
  example_group = before_register(example_group)
  example_groups << example_group
  @example_group_counts_by_spec_file[example_group.metadata[:file_path]] += 1
  example_group
end
```

**Comment by myronmarston** [comment]
We're definitely open to adding new APIs to address your needs, as @JonRowe said, but I still don't understand why the normal "define multiple examples in a loop" approach doesn't work.  Can you paste together a more realistic example of what you're trying to do?

**Comment by bootstraponline** [comment]
Sure. I'll work on a better example.

**Comment by JonRowe** [comment]
Almost, it'd be better if the `before_register` hook was a series of blocks that are registered in configuration (on a public api) but the default is empty and thus just a no op. Kind of like how we've done the verifying double callbacks for mocks... 

https://github.com/rspec/rspec-mocks/blob/1826212a66598b171fece2998f68998e4df940e1/lib/rspec/mocks/configuration.rb#L109

**Comment by bootstraponline** [comment]
Thanks for clarifying the correct approach. I agree that's better and I'll update my code.

**Comment by bootstraponline** [comment]
I haven't forgotten about this. I expect to submit a PR within the next few weeks.

**Comment by bootstraponline** [comment]
@myronmarston Here's a full [example](https://github.com/bootstraponline/sauce_connect_ruby) of the setup. It's using the same gems / rspec setup as the test suite I manage for work. In [sauce_helper](https://github.com/bootstraponline/sauce_connect_ruby/blob/f2b5e9cd0c941492ced15912b26cb36987e3439c/helper/sauce_helper.rb) I'm able to run all rspec tests on multiple platforms without having to change anything in the specs or rspec config. This is possible due to the [World.register patch](https://github.com/bootstraponline/sauce_rspec/blob/master/lib/sauce_rspec/rspec.rb#L16) in sauce_rspec. The idea is for Sauce to enable their customers to use this approach so anything that involves modifying specs doesn't work.

It's taken me a bit longer to update the other parts of the sauce gems, for example the [custom formatter](https://github.com/rspec/rspec-core/issues/2091). I still plan on submitting a PR for before_register.

**Comment by bootstraponline** [comment]
I've submitted https://github.com/rspec/rspec-core/issues/2094

**Comment by elrayle** [comment]
I tried to use the original suggestion by @myronmarston but it is not working as I had hoped.  Here is a simplified test following that pattern...

```
RSpec.describe "Dynamic tests" do
  [1, 2].each do |val|
    let(:my_val) { val }

    it "runs some test logic with #{val}" do
      puts "Test: runs some test logic with #{val}"
      puts "  val=#{val}"
      puts "  my_val=#{my_val}"
      expect(my_val).to eq 1
    end
    it "runs some test logic with #{val}" do
      puts "Test: runs some test logic with #{val}"
      puts "  val=#{val}"
      puts "  my_val=#{my_val}"
      expect(my_val).to eq 2
    end
  end
end
```

This prints...
```
Test: runs some test logic with 1
  val=1
  my_val=2
F
Test: runs some test logic with 1
  val=1
  my_val=2
.
Test: runs some test logic with 2
  val=2
  my_val=2
.
Test: runs some test logic with 2
  val=2
  my_val=2
F
```

Note that my_val is NOT set based on the value of val.  It is always 2.

**Comment by JonRowe** [comment]
@elrayle Thats because you can't use let in this fashion, its the equivalent of:
```
let(:my_val) { 1 }
let(:my_val) { 2 }
```
You are overwriting the previous definition. You either need to use `val` directly, or wrap each unit in a `describe` or a `context`.
