### ISSUE TITLE
Enable BaseTextFormatter subclasses to provide custom failure messages

### ISSUE THREAD

**Issue by bootstraponline** [rspec/rspec-core#2091]
When I run on Sauce Labs, it's important that the DocumentationFormatter output the job link which is stored in the example metadata. DocumentationFormatter relies on [notification.fully_formatted_failed_examples](https://github.com/rspec/rspec-core/blob/e37b7b88fb72a2f2f0a0eabf07ffee761370491d/lib/rspec/core/formatters/base_text_formatter.rb#L33) from base_text_formatter which has no customization options.

The old [sauce_ruby gem](https://github.com/saucelabs/sauce_ruby/blob/dddbbcd402791bd673d06da1e1dba737497dfb1c/lib/sauce/rspec/rspec_formatter.rb) monkey patched BaseTextFormatter to achieve custom message support however that broke in RSpec 3. I worked around this by writing a new formatter which [redefines message/to_s on the exception object](https://github.com/bootstraponline/sauce_documentation_formatter/blob/d261fb504ecc5690740c1ef7b609ccc77e787fc0/lib/sauce_documentation/sauce_documentation.rb) with instance eval. It'd be nice if there was a better way.

Would it make sense to update `fully_formatted_failed_examples` to take an optional argument which is then added to the exception message? It'd be eventually passed to the [`fully_formatted` method on `exception_presenter`](https://github.com/rspec/rspec-core/blob/e37b7b88fb72a2f2f0a0eabf07ffee761370491d/lib/rspec/core/formatters/exception_presenter.rb#L72) and [`formatted_message_and_backtrace`](https://github.com/rspec/rspec-core/blob/e37b7b88fb72a2f2f0a0eabf07ffee761370491d/lib/rspec/core/formatters/exception_presenter.rb#L178) would append the extra message to the exception message.

Here's an example of what the output from the [sauce_documentation_formatter](https://github.com/bootstraponline/sauce_documentation_formatter) gem looks like.

```
2) SauceDocumentation fails and outputs sauce link
     Failure/Error: expect(3).to eq(4)

       expected: 4
            got: 3

       (compared using ==)

       https://saucelabs.com/beta/tests/1234

     # ./formatter_spec/sauce_documentation_spec.rb:16:in `block (2 levels) in <top (required)>'
```

**Comment by JonRowe** [comment]
The option you want here is to create your own formatter, thats why we allow you custom formatters. You can subclass our documentation formatter (although I generally prefer you don't) and implement your own features. You should have access to example via the notifications.

**Comment by bootstraponline** [comment]
Ok, thanks for clarifying. I don't actually want to create any formatters, instead I'd like to ensure all existing formatters have extra info in the exception message. It looks like the instance eval approach makes the most sense for my use case.

**Comment by JonRowe** [comment]
Please don't do that, monkey patching is never the answer. If you can provide a PR with an idea for extending the notification cleanly without impacting the performance of the majority of the use cases (e.g. vanilla RSpec) then I'll consider it.

**Comment by JonRowe** [comment]
I'd still prefer you create a custom formatter however, it can even utilise any of RSpec's own formatters internally (using delegation for example) and simply append the data when you need to.

**Comment by myronmarston** [comment]
One idea for an alternate approach: create an exception wrapper class that takes an exception instance and delegates all method calls to it except `message` and `to_s`.  For `message` and `to_s` you can do whatever it is you want.  The stdlib [SimpleDelegator](http://ruby-doc.org/stdlib-2.2.3/libdoc/delegate/rdoc/SimpleDelegator.html) would be perfect for this.

Then in your formatter, you can wrap exceptions with your delegator and pass them on to RSpec and they'll be formatted with the additional text you've injected in `message` or `to_s`.

**Comment by bootstraponline** [comment]
> Please don't do that, monkey patching is never the answer. If you can provide a PR with an idea for extending the notification cleanly without impacting the performance of the majority of the use cases (e.g. vanilla RSpec) then I'll consider it.

The [sauce ruby gem](https://rubygems.org/gems/sauce/versions) has been around since 2010 and [always monkey patched RSpec](https://github.com/saucelabs/sauce_ruby/blob/dddbbcd402791bd673d06da1e1dba737497dfb1c/lib/sauce/rspec/rspec_formatter.rb) because there's no API to add extra lines to the exception message. I agree monkey patching is a terrible approach, it's also the only way to fit this use case (add a line to the exception of every formatter without changing the formatter).

I think something like this would work:

```ruby
class ExceptionPresenter
  def initialize(exception, example, options={})
    @custom_exception_message = example.metadata[:custom_exception_message] || ''
  end

  def failure_lines
    @failure_lines ||=
      begin
        lines = []
        lines << failure_slash_error_line unless (description == failure_slash_error_line)
        lines << "#{exception_class_name}:" unless exception_class_name =~ /RSpec/
        encoded_string(exception.message.to_s).split("\n").each do |line|
          lines << "  #{line}"
        end
        lines << @custom_exception_message if @custom_exception_message
        lines
      end
  end
end
```

> One idea for an alternate approach: create an exception wrapper class that takes an exception instance and delegates all method calls to it except message and to_s. For message and to_s you can do whatever it is you want. The stdlib SimpleDelegator would be perfect for this.
> 
> Then in your formatter, you can wrap exceptions with your delegator and pass them on to RSpec and they'll be formatted with the additional text you've injected in message or to_s.

The issue is I don't control the formatters. Customers of Sauce could be using any formatter and it's not possible to modify the formatters. I tried the idea of just using a delegator, the issue is how do I set the exception to point to the wrapper class instead of the actual exception class?

```ruby
def dump_failures(notification)
    failure_notifications = notification.failure_notifications
    return if failure_notifications.empty?

    failure_notifications.each do |failure|
      failure.exception = MyWrapperClass.new(exception) # this isn't valid
```

Currently I have code that does this:

```ruby
message = "#{exception.message}\n#{sauce_test_link}\n#{nbsp}"
      exception.instance_eval <<-RUBY
        def message
          %q(#{message})
        end
        def to_s
          message
        end
      RUBY
```

This successfully wraps the value of message and inserts the test link. It also works with every formatter. If it was possible to set the exception object to a different object then I'd be able to use a delegator approach instead of eval.

**Comment by JonRowe** [comment]
> The sauce ruby gem has been around since 2010 and always monkey patched RSpec because there's no API to add extra lines to the exception message.

Because no-one has ever asked or proposed a PR... The effort would have been better spent doing that than monkey patching.

>  I agree monkey patching is a terrible approach, it's also the only way to fit this use case (add a line to the exception of every formatter without changing the formatter).

As mentioned it's not, the better way would be to use a sauce formatter or propose a PR to add such an extension.

> I think something like this would work: 

So propose a PR with this.

**Comment by bootstraponline** [comment]
Ok, I'll submit a PR that updates `ExceptionPresenter` to add `example.metadata[:custom_exception_message]` to the `failure_lines`

> Because no-one has ever asked or proposed a PR... The effort would have been better spent doing that than monkey patching.

I agree, I didn't create sauce_ruby or write their RSpec integration. I'm now working on the replacement gem and am hoping to avoid monkey patching.

**Comment by bootstraponline** [comment]
I've submitted https://github.com/rspec/rspec-core/pull/2092 Happy to revise based on feedback.
