### ISSUE TITLE
Fix tests on Travis

### ISSUE THREAD

**Issue by bootstraponline** [rspec/rspec-core#2093]
It looks like all the tests are [failing on Travis Ruby 1.9.2.](https://travis-ci.org/rspec/rspec-core)

**Comment by bootstraponline** [comment]
1.9.2 appears to be seg faulting.

> /home/travis/build/rspec/rspec-mocks/lib/rspec/mocks/any_instance/recorder.rb:232: [BUG] Segmentation fault
ruby 1.9.2p330 (2014-08-07 revision 47094) [x86_64-linux]
>
> https://travis-ci.org/rspec/rspec-core/jobs/86445802
> https://travis-ci.org/rspec/rspec-core/jobs/85355636

**Comment by myronmarston** [comment]
1.9.2 seg faults occasionally.  It's bugs in that version of MRI that we can't do anything about.  I restarted the failing 1.9.2 job and now it passed.

**Comment by bootstraponline** [comment]
Ok, good to know.
