### ISSUE TITLE
Warn about examples which don't assert anything?

### ISSUE THREAD

**Issue by alexdowad** [rspec/rspec-core#2097]
I'm not very sure about this idea, and would like to hear what the maintainers think. What would you think of making RSpec warn about examples which don't contain any assertions, or anything which could make the test *fail*?

Of course, any test can fail if it raises an uncaught exception. But if the tester's intention is to just check for uncaught exceptions, it would be better to use `expect { ... }.not_to raise_error`, to express that intention explicitly.

Where this came from: I am just updating a RSpec 2 suite to RSpec 3, and I discovered some old, forgotten "tests" which don't test anything at all. They look something like this:

```ruby
it "returns the right value" do
  actual.value == expected.value
end
```

I'm sure that the author meant `actual.value.should == expected.value`.

**Comment by myronmarston** [comment]
Yes, this is a worthwhile idea, and in fact it's already on the roadmap (see #759).  Closing this issue so conversation can stay in that one.
