### ISSUE TITLE
Abnormal exits and RSpec traps lead to an abnormal shell.

### ISSUE THREAD

**Issue by envygeeks** [rspec/rspec-core#2103]
```
# Test Test Test
# Oh I'll enter Pry here!
[1] pry(#<RSpec::ExampleGroups::DockerBuilditRepo::Data>)>
# Nah, don't care, keep going, I'm lazy so I'll C-c
RSpec is shutting down and will print the summary report... Interrupt again to force quit.
# RSpec throws, Rspec outputs failures and other data
# RSpec quits

# Press enter just to show it.
jordon ~/development (master *) % jordon ~/development (master *)
```

When this happens we have to reset the shell to get it fixed.

**Comment by envygeeks** [comment]
This could actually be the result of Pry tbh, since it's the one who opens readline.

**Comment by myronmarston** [comment]
This has come up before in #1711.  I'm not sure how RSpec could know that it's in a pry shell in order to make it's SIGINT handler behave differently.  But Pry could temporarily override the SIGINT handler while the user is in its shell, then restore the old handler at the end.  As I explained in #1711:

> If byebug wants `SIGINT` to be handled differently while in the middle of a debugging session, I think it should change the `SIGINT` handler for the duration of the debugging session, and then restore the original `SIGINT` handler afterwords.  Something like this should work:

> ``` ruby
def with_sigint_handler(&handler)
  orig_handler = trap('INT', &handler)
  yield
ensure
  trap('INT', &orig_handler)
end
```

> Otherwise, your solution amounts to _every other ruby project_ changing how they do sigint handling to support byebug (otherwise, if any project handles `SIGINT` then it'll cause the undesirable behavior in byebug).  By replacing the handling while in a debugging session, you can control how it behaves w/o worrying about how the host program normally handles it.

Thoughts?

**Comment by envygeeks** [comment]
@myronmarston 

```ruby
require "pry"

module RSpec
  class << self
    attr_accessor :in_pry
    def in_pry?
      return !!@in_pry
    end
  end
end

Pry.config.hooks.add_hook :before_session, :let_rspec_know do
  RSpec.in_pry =  true
end

Pry.config.hooks.add_hook :after_session, :let_rspec_know do |*args|
  RSpec.in_pry = false
end
```

**Comment by envygeeks** [comment]
Digging through and trying to figure out this problem, I can say that it originates in the `rake_task.rb`

**Comment by myronmarston** [comment]
That's nice to see that Pry has those hooks.  That said, in RSpec we've generally resisted adding logic for specific tools like pry to RSpec itself, and I'm not sure I want to start taking on the maintenance burden.  Each tool of this type (e.g. byebug, ruby-debug, debugger, byebug) has the same needs and it would be a large maintenance burden for RSpec to have specific code for each tool like this.  In addition, if the strategy of each of these tools is that the host application must detect when they are in a shell session and react appropriately, then it's not a very sustainable approach -- it's a lot of work for each tool in the Ruby ecosystem like RSpec that handles SIGINT to have to accomodate each and every pry-like tool.

In contrast, Ruby's `trap` provides a mechanism to replace a signal handler for a time, then restore what was there before.  Such an approach can be used in Pry to make it work properly with RSpec and any other tool that handles SIGINT, and seems like a more sustainable approach.

**Comment by JonRowe** [comment]
For now would this work? 
```Ruby
orig_handler = nil

Pry.config.hooks.add_hook :before_session, :let_rspec_know do
  orig_handler = trap('INT', -> {})  
end

Pry.config.hooks.add_hook :after_session, :let_rspec_know do |*args|
  trap('INT', &orig_handler)
end
```

**Comment by envygeeks** [comment]
@JonRowe @myronmarston I completely understand the need not to want to do that.  I will test out the trap code you provided to see if it works and if it does maybe I could start a RSpec plugin (or I'd be happy to manage one for RSpec) that maintains all these hacks in an isolated repo.

**Comment by myronmarston** [comment]
> @JonRowe @myronmarston I completely understand the need not to want to do that. I will test out the trap code you provided to see if it works and if it does maybe I could start a RSpec plugin (or I'd be happy to manage one for RSpec) that maintains all these hacks in an isolated repo.

That sounds great!  After proving this approach in a plugin, I wonder if the pry maintainers would be amenable to getting it in pry itself.  After all, there's nothing rspec-specific about replacing the `INT` handler before a session and restoring it after a session.  I suspect the same problem exists in other tools that handle SIGINT (such as cucumber and minitest) and if pry did this natively than it would (theoretically) make it more robust and able to work properly in whatever environment it is running.

Regardless, I'm going to close this.
