### ISSUE TITLE
How to override rspec runner?

### ISSUE THREAD

**Issue by AlexCppns** [rspec/rspec-core#2106]
I want to add some runtime logs at beginning and end of tests.

**Comment by JonRowe** [comment]
You should be able to use `before`, `after` and `around` to achieve this, all the hooks take `:example`, and `:context` and `before`/`after` are also triggerable on `:suite` too

**Comment by AlexCppns** [comment]
No I mean at beginning and end of rspec, not individual tests.

**Comment by JonRowe** [comment]
`before(:suite)` and `after(:suite)` meet this ned.
