### ISSUE TITLE
rspec service test always fails

### ISSUE THREAD

**Issue by phiche** [rspec/rspec-core#2110]
I have a bunch of successful serverspec tests executing against a RHEL6 VM on AWS. 

However any "service" test seems to fail with the matchers be_enabled and be_running. It looks like serverspec is mostly just a wrapper around rspec though and I can reproduce the same issue in rspec syntax which is why I'm raising the issue here. Plus it seems that raising issues against serverspec is disabled in their github repo.

I have the following in my spec_helper.rb:

```set :os, :family => 'redhat', :release => '6', :arch => 'x86_64'```

And I'm running ruby 2.0, serverspec 2.24, rspec 3.3

Both serverspec and rspec syntax fail in the same way as they run the same commands:
```
describe service('ntpd') do
    it { should be_enabled }
    it { should be_running }
end

it "is running ntpd" do
    expect(service("ntpd")).to be_enabled
    expect(service("ntpd")).to be_running
end
```
Both sets of tests return the following errors:
```
Failure/Error: it { should be_enabled }
    expected Service "ntpd" to be enabled
    sudo -p 'Password: ' /bin/sh -c chkconfig\ --list\ ntpd\ \|\ grep\ 3:on

Failure/Error: it { should be_running }
    expected Service "ntpd" to be running
    sudo -p 'Password: ' /bin/sh -c service\ ntpd\ status
```
However, running them locally on the server succeeds:
```
$ sudo -p 'Password: ' /bin/sh -c chkconfig\ --list\ ntpd\ \|\ grep\ 3:on
ntpd            0:off   1:off   2:on    3:on    4:on    5:on    6:off
$ echo $?
0

$ sudo -p 'Password: ' /bin/sh -c service\ ntpd\ status
ntpd (pid  1101) is running...
$ echo $?
0
```

Any ideas what might be going wrong?

**Comment by JonRowe** [comment]
Whatever the server spec custom matchers are doing is not detecting the result of the commands, we can't help because this is obviously a server spec problem, RSpec has no knowledge of the service beyond what it exposes.

**Comment by phiche** [comment]
Did you read the issue fully? The following test is calling rspec proper, isn't it?
```
it "is running ntpd" do
    expect(service("ntpd")).to be_enabled
    expect(service("ntpd")).to be_running
end
```

**Comment by JonRowe** [comment]
No, `service("ntpd")` is server spec, as is **probably** `be_enabled` and `be_running`

**Comment by JonRowe** [comment]
If `be_enabled` and `be_running` are RSpec then they are just checking `enabled?` and `running?` on `service("ntpd")`, and that will be returning false hence your tests failing.

**Comment by JonRowe** [comment]
The descriptions on the failure suggest otherwise however.

**Comment by phiche** [comment]
is there some way to write the above test using only rspec syntax?

**Comment by phiche** [comment]
So I just managed to solve my problem. Seems that checking explicitly for a service level fixed it. 
The documentation indicates otherwise, so I guess there could be a bug with rhel6/7 and systemV/systemD changes.

```
describe service('ntpd') do
    it { should be_enabled.with_level(3) }
    it { should be_running }
end
```
