### ISSUE TITLE
Installing gem on OS X El Capitan using System Ruby fails to create binstub

### ISSUE THREAD

**Issue by wspurgin** [rspec/rspec-core#2113]
Hey I :heart: RSpec, and I use it in every ruby project I have.

Recently I updated to El Capitan, and I solved all the myriad of issues around what the upgrade does to the dev env (like SIP, permissions of `/usr/local/bin`, etc.)

The one thing I haven't been able to fix is the mysterious disappearance of the `rspec` executable...
I use the system ruby (i.e. `/usr/bin/ruby`), and while I know it's getting out-dated (since it's 2.0.0), I don't want to deal with adding `rbenv` or something like that for the moment.

Here's what I've tried:
* Reinstalling (uninstall then install) the rspec gem.
* Running `sudo gem pristine rspec --only-executables`

Note on my installation: I have `--bindir /usr/local/bin` in my `~/.gemrc` so it's "shouldn't" be a problem with trying to create an executable where it can't.

The output from installing (with verbose) is below:
```
$ sudo gem install rspec -V
HEAD https://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
HEAD https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
200 OK
GET https://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
200 OK
HEAD https://rubygems.org/specs.4.8.gz
302 Moved Temporarily
HEAD https://rubygems.global.ssl.fastly.net/specs.4.8.gz
200 OK
GET https://rubygems.org/specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/specs.4.8.gz
200 OK
Installing gem rspec-3.3.0
/Library/Ruby/Gems/2.0.0/gems/rspec-3.3.0/License.txt
/Library/Ruby/Gems/2.0.0/gems/rspec-3.3.0/README.md
/Library/Ruby/Gems/2.0.0/gems/rspec-3.3.0/lib/rspec.rb
/Library/Ruby/Gems/2.0.0/gems/rspec-3.3.0/lib/rspec/version.rb
Successfully installed rspec-3.3.0
1 gem installed
```
As you can see, it's installing in the `/Library/Ruby/Gems/2.0.0/gems/rspec-3.3.0`. I've verified that the rspec executable lives in `/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/exe/rspec ` and running that directly works, but there's no executable in `/usr/local/bin`.

Lastly, just to make sure it wasn't a RubyGem issue, I tried installing bundler too: which worked. It even shows (with verbose) that it creates the executables in `/usr/local/bin`
```
$ sudo gem install bundler
...
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/man/index.txt
/usr/local/bin/bundle
/usr/local/bin/bundler
Successfully installed bundler-1.10.6
1 gem installed
```

Am I missing something? I know I could just manually make the link, but I'd really prefer just to solve this issue. If you think it's something unrelated to RSpec, please let me know.

Thanks.

**Comment by JonRowe** [comment]
This isn't related to RSpec, we tell Ruby where the executable is kept via the gemspec and rubygems should be copying it across for you, that it isn't suggests a bug in that

**Comment by JonRowe** [comment]
Have you checked your system rubygems is up to date? `gem update system`

**Comment by wspurgin** [comment]
Well I'm glad it's not something related to RSpec, but yeah I have run `gem update`, I get `Nothing to update`

**Comment by JonRowe** [comment]
Sorry I missed the dashes in my first attempt at the command, perhaps check you're running `2.5.0` (`gem -v`). Additionally try installing `rspec-core` directly as thats what contains the executable.

**Comment by wspurgin** [comment]
Okay there is something different between RSpec version though. I just ran `sudo gem install rspec --version '= 3.2.0' -V` instead of the default of 3.3.0, and now I have the `rspec` executable copied into `/usr/local/bin`

**Comment by JonRowe** [comment]
We haven't changed the executable in between those versions, we did modify the gemspec but nothing related to that.

**Comment by wspurgin** [comment]
Also definitely running an old version of `gem` (like I said, I'm using the system ruby which is 2.0.0). My `gem` is `2.0.14` (quite old)
