### ISSUE TITLE
Error from #format_backtrace blows up rest of suite

### ISSUE THREAD

**Issue by Cohen-Carlisle** [rspec/rspec-core#2117]
I'm getting the following error which crashes the rest of the test suite:

gems/ruby/2.0.0/gems/rspec-core-3.4.0/lib/rspec/core/backtrace_formatter.rb:34:in 'format_backtrace': undefined method 'empty?' for nil:NilClass (NoMethodError)

The `empty?` call was introduced by [this commit](https://github.com/rspec/rspec-core/commit/48db9020b714ac5a37cac52bf7e47bc8de27c5d2).

**Comment by myronmarston** [comment]
Thanks for reporting this!  There's a fix in #2118.

**Comment by Cohen-Carlisle** [comment]
You're welcome! Thanks for the fast turn-around! I changed my message to reflect that the linked commit introduced the `empty?` call but not the issue (which of course it couldn't have... it would just get a NoMethodError for `map` instead it, doh!).

Is there any ETA on when this fix will be included in a release? ☺️

**Comment by myronmarston** [comment]
> Is there any ETA on when this fix will be included in a release? ☺️

How's now? :smile: 

3.4.1 is out with this fix.

**Comment by Cohen-Carlisle** [comment]
❤️
