### ISSUE TITLE
Support for subject containing an expectation.

### ISSUE THREAD

**Issue by envygeeks** [rspec/rspec-core#2121]
It would be neat if we could do something like this:

```ruby
subject do
  expect do
    this.code
  end
end

specify do
  expect_it.to raise_error TheError
end
```

The same way we do `is_expected`, `expect_it` would serve for error testing.

**Comment by envygeeks** [comment]
I know subject can already create that expect but it doesn't allow for the neat alias.

**Comment by myronmarston** [comment]
I find that very confusing -- putting `expect` in `subject` is weird and `expect_it` reads like it might be an alias of `is_expected` but it's subtlety different.  In addition, "more DSL" isn't something RSpec needs.  I don't think it makes sense to add this to rspec-core, but if you wanted to add it to your project (or put into a gem), it's pretty trivial:

``` ruby
module ExpectIt
  def expect_it
    subject
  end
end

RSpec.configure do |c|
  c.include ExpectIt
end
```

**Comment by envygeeks** [comment]
We did, except we went a step further and probably broke RSpec's rules but the result was a much more understandable specification for people to read, we found oneliners in RSpec very hard to read because of the deep nesting so we created top-level automatic deep nesting that results in the same output with top-level descriptions.

**Comment by envygeeks** [comment]
AKA, before it was:

```ruby
describe MyClass do
  describe "#method" do
    let :expect_it do |k, v|
      expect do
        this.code
      end
    end

    specify do
      expect_it.to raise_error TheError
    end
  end
end
```

Now we can do:

```ruby
describe MyClass do
  expect { this.code }.to { raise_error TheError }
  the(:stdout).of(:this_method?).is_expected_to { be_empty }
  expect(:this_method?).to { be_true }
end
```

**Comment by JonRowe** [comment]
>  we found oneliners in RSpec very hard to read

Which is one reason we don't recommend using one liners, for the most part extra test verbosity means extra readability

**Comment by envygeeks** [comment]
The only thing more verbosity guarantees is more reading,  the broad assumption that verbosity somehow automatically means readability is laughable at best, ignorant at worst.  There are many factors in readable code.

**Comment by JonRowe** [comment]
There are, and tests are partly code, but they're also partly documentation, and RSpec is not advanced (nor should it be baring some awesome leap in AI :)) enough to infer the meaning from the code, so if you give it a helping hand (e.g. using `it` with doc strings etc) you can expand the readability of the output and the code. IMHO.

**Comment by envygeeks** [comment]
I'll agree to an extent (which is why we threw out that one line syntax before you even brought it up and mixed the rspec-given idea into a one-line approach that again we later threw away because we felt it was adding no benefit to rspec) but even so in our most recent iterations we include no description in `it` we expect people to infer from the source around it (AKA the subject is what we are testing and we are making sure "it" `is_expected` to behave like we want it to.)  Ultimately most of those can be one liners if people understand that the subject is the context and the context is the scenario.

**Comment by envygeeks** [comment]
The one line approach I tried to take (that I ultimately decided was not worth it) was merging it with subject to create a one-line context that was easier to spot and read, and it did it's job in it's final iteration, but like I said, I felt it added no benefit so I stashed the code and kept my specs as they were.
