### ISSUE TITLE
Runtime logging for shared_examples

### ISSUE THREAD

**Issue by RST-J** [rspec/rspec-core#2125]
Hello, I hope I'm right here with my concern.
We use json runtime logging in our project to have an idea of which tests take how long. For certain recurring expectations we have shared examples for which a log output looks like this:

``` json
{
  "description" : "raises an error",
  "full_description" : "ClassUnderTest raises an error if we expect that",
  "status" : "passed",
  "file_path" : "./spec/models/shared_examples/generic_examples.rb",
  "line_number" : 11,
  "run_time" : 0.135449016,
   "pending_message" : null
}
```

If we aggregate that (actually we use a feature of our CI platform for this) then we have the result that the file `./spec/models/shared_examples/generic_examples.rb` run for 4.2 minutes in total which is not actually useful information.
So my question, it is is possible, or feature request other wise would be: Is it possible to log the file path of the including file or let's better say the top level spec file which uses the shared examples (as it could be the case that shared examples make use of other shared examples)?
Or is there somehow useful conclusion to be drawn from aggregated runtime information about shared examples which I did not see yet?

**Comment by JonRowe** [comment]
You should be able to get access to the example id for the file, which was introduced to solve the problem of identifying tests run from shared examples. You don't mention what you're using to produce the JSON however, is it our formatter?

**Comment by RST-J** [comment]
I use the following command to run the tests and assume this uses the RSpec JsonFormatter:
`SPEC_OPTS="--format progress --format json --out rspec_report.json" bundle exec rspec spec/`
How can I get access to the example id? Can I achieve this by some parameters or do I need a custom logger for that?

**Comment by xaviershay** [comment]
Closing in favour of linked PR!
