### ISSUE TITLE
diffable matchers does not show trailing newline at end of file

### ISSUE THREAD

**Issue by DavidS** [rspec/rspec-core#2134]
Hi,

copying the example from http://www.relishapp.com/rspec/rspec-expectations/v/3-4/docs/custom-matchers/define-diffable-matcher#define-a-diffable-matcher , but modifying it to compare to `"three\nlines\n"` the diff doesn't show that the expected value has an added newline at the end.

```
RSpec::Matchers.define :be_just_like do |expected|
  match do |actual|
    actual == expected
  end

  diffable
end

RSpec.describe "two\nlines" do
  it { is_expected.to be_just_like("three\nlines\n") }
end
```

produces

```
  1) two
lines should be just like "three\nlines\n"
     Failure/Error: it { is_expected.to be_just_like("three\nlines\n") }

       expected "two\nlines" to be just like "three\nlines\n"
       Diff:
       @@ -1,3 +1,3 @@
       -three
       +two
        lines

     # ./test.rb:10:in `block (2 levels) in <top (required)>'
```

**Comment by JonRowe** [comment]
Hi, the TL;DR; is that this is the expected (correct) behaviour.

The longer explanation; A line in posix is terminated with `\n` so `Foo\n` is one line, not two. Similarly `Foo\nBar\n` is two lines but `Foo\nBar` is also two lines just incorrectly terminated. To have a "blank" last line you'd actually have to have `Foo\nBar\n\n`. This is why Github shows those little red icons on some diffs. It shows incorrectly terminated lines as `git` complains about them.

As our differ splits on different lines and the last content is identical, `lines` == `lines` show the differ shows no diff, does that make sense?

**Comment by DavidS** [comment]
The two strings are not byte-for-byte equals, which is the thing I care about. Please consider diff's output in this case:

```
➜  tmp  echo -en 'foo' > foo
➜  tmp  echo -en 'foo\n' > foo2
➜  tmp  diff -u foo*
--- foo	2015-12-17 11:51:41.000000000 +0000
+++ foo2	2015-12-17 11:51:46.000000000 +0000
@@ -1 +1 @@
-foo
\ No newline at end of file
+foo
➜  tmp
```

In the same vein I would not expect 1.1 == 1, because "the last part doesn't matter".

**Comment by JonRowe** [comment]
Consider that if we were to manually correct the diff, (a 3rd party,
diff-lcs, actually implements the output) the output would be confusing...

e.g "foo" vs "foo\n"

>
-foo
+foo

As the incorrectly terminated line ending simply wouldn't show up...

**Comment by JonRowe** [comment]
I did start sketching out a solution in rspec-support (which contains the
differ source code, rspec-core has nothing to do with matchers let alone
diffs) before realising we outsource this display in its entirety so have
no control over it.

**Comment by DavidS** [comment]
I've had a peek at diff-lcs and ruby's split. It seems to me that both are not suitable for detecting/handling the missing-newline case. Adding it to the differ, probably around finalize_output(?) doesn't look too hard. If that doesn't sound too offensive to you, maybe I can whip up a small patch tomorrow?

**Comment by JonRowe** [comment]
Sure but it has to fit into the existing output and not be overly offensive / intensive code wise, remember the default case is correct, theres only a few edge cases like yours which are slightly misleading.
