### ISSUE TITLE
`rspec file:line` syntax running the wrong spec

### ISSUE THREAD

**Issue by benhoskings** [rspec/rspec-core#2136]
Hi all,

I've reduced what looks like an issue in rspec-core where the wrong spec is sometimes run when a particular shared example is in play.

Briefly, when running `spec.rb:line`, if `spec.rb` also includes a reference to a shared example in `shared_spec.rb`, and the shared example defines one of its specs on `shared_spec.rb:line`, then that spec is run instead of the invoked spec.

It depends on the line numbers matching, and seems to also require the shared example to be referenced above the invoked spec, but for a given configuration it seems to be fully reproducible.

I've made a little repo with a reproduction and a longer explanation:

https://github.com/benhoskings/rspec-shared-example-bug

**Comment by myronmarston** [comment]
Thanks for the detailed bug report, (and the repo with a repro case!) @benhoskings!   I haven't yet figured out the root cause but I went ahead and converted it to a failing spec (c681c883fde8bc2567a0a08df40831def040fc80) and I'm hoping it can be useful for someone else.

**Comment by myronmarston** [comment]
I spent a while working on this today and managed to put together a branch that fixes the problem but isn't nearly ready to merge:

https://github.com/rspec/rspec-core/tree/issue-2136-spike

I'm reporting it here because my open source time has been more limited lately, and I don't have the time to get a PR ready tonight.

**Comment by myronmarston** [comment]
@benhoskings I've got a fix in #2170.  Want to try it out and see if it fixes the issue for you?
