### ISSUE TITLE
crash on 3.4.1 using --profile

### ISSUE THREAD

**Issue by backus** [rspec/rspec-core#2142]
Here is a gist reproducing the issue: https://gist.github.com/backus/b7d29b76cd10c75c6726

Basically I have a spec that looks like this:

```ruby
describe '#abort' do
  it 'crashes rspec' do
    expect { abort }.to output('').to_stdout
  end
end
```

Running it without any flags works fine:

```sh
$ bundle exec rspec


Finished in 0.0014 seconds (files took 0.07777 seconds to load)
1 example, 0 failures
```

But with `--profile`:

```sh
$ bundle exec rspec --profile


/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/notifications.rb:418:in `block in slowest_examples': undefined method `-@' for nil:NilClass (NoMethodError)
```

The gist I included has a Gemfile and Gemfile.lock where you can see all of the dependencies.

**Comment by soulcutter** [comment]
Thanks for the steps to reproduce, looking in to this

**Comment by backus** [comment]
Thanks!
