### ISSUE TITLE
Confusing warning when attempting to define `around(:suite)`

### ISSUE THREAD

**Issue by derekprior** [rspec/rspec-core#2150]
I tried to configure RSpec with an `around(:suite)` hook like so:

```ruby
RSpec.configure do |config|
  config.around(:suite) { |example| puts "hi"; example.run }
end
```

but when I ran my suite, I got:

> WARNING: `around(:suite)` hooks are only supported on the RSpec configuration object. This `around(:suite)` hook, registered on an example group, will be ignored.

It seemed to me that I was pretty clearly calling `around` on an RSpec configuration object so this sent me on a bit of a chase. I eventually read through the docs enough to see:

> Note: :example/:each is the only supported scope.

Would it be possible to have `around(:suite)` raise an `ArgumentError` rather than emit this warning?

**Comment by JonRowe** [comment]
Sure, would you like to work up a PR?

**Comment by derekprior** [comment]
Yeah. I ,ay get to it Friday. If not, it won't be until the end of the month.

**Comment by tejasbubane** [comment]
This has been kept for SemVer reasons by @myronmarston and there is a `TODO` to change it to throwing an error in `RSpec4`. https://github.com/rspec/rspec-core/blob/7477810fc65718a69753f04d4a99c3acf2371acb/lib/rspec/core/hooks.rb#L452

**Comment by myronmarston** [comment]
Ha, I had forgotten about that :).  Changing from an ignored hook that generates a warning to one that raises an exception would be a breaking API change so we're going to have to leave it for RSpec 4.
