### ISSUE TITLE
I need a way to conditionally clean up a let(:thing), if it was instantiated

### ISSUE THREAD

**Issue by paddor** [rspec/rspec-core#2162]
I'm developing a binding for a messaging library. In the test suite, I naturally create quite a few sockets. I've been hitting the ulimit for file descriptors recently. Expecting anyone who wants to run the test suite to raise the ulimit is not a nice solution.

I need a way to conditionally cleanup a let(:thing), in case it was instantiated during the test. Is there a way to check if it has been instanciated?

I'm hoping to be able to do something like this:

```ruby
describe Thing do
  let(:foo) { ExpensiveFoo.new }
  after(:each) do
    foo.destroy if let?(:foo) # <-- would be cool
  end

  it "does this" do
    # ...
  end
end
```

Thanks.

**Comment by JonRowe** [comment]
There isn't no, but you can achieve your aims with a bit of structure:

```Ruby
RSpec.describe 'Thing' do
  context 'when using foo' do
    let(:foo) { ExpensiveFoo.new }
    after do
      foo.destroy
    end
    it 'does something with foo'
  end

  it 'does not need foo'
end
```

**Comment by myronmarston** [comment]
You can do this pretty simply without `let`:

``` elixir
describe Thing do
  def foo
    @foo ||= ExpensiveThing.new
  end

  after(:each) do
    @foo.destroy if defined?(@foo)
  end

  it "does this" do
    # ...
  end
end
```

**Comment by paddor** [comment]
Thanks. I take it you don't plan to make this a built-in feature, right?

**Comment by myronmarston** [comment]
> Thanks. I take it you don't plan to make this a built-in feature, right?

Correct.
