### ISSUE TITLE
Feature/API change request: expose failure_slash_error_lines data in ExceptionPresenter

### ISSUE THREAD

**Issue by jzohrab** [rspec/rspec-core#2169]
ServerSpec is currently monkeypatching the class and accessing this internal method (ref https://github.com/mizzy/serverspec/blob/master/lib/serverspec.rb#L46), a change to which has broken ServerSpec.  Ref https://twitter.com/kantrn/status/664913752832126976, it's not good to monkeypatch a private API.  I've submitted a patch to work around the current failure, but it would be more stable if ServerSpec could pull data from a published API.

Class being monkeypatched:
https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/formatters/exception_presenter.rb

If it is better to work with an existing method in the public API, please advise which one is best.  Thanks!

**Comment by JonRowe** [comment]
That entire class is private api because it's just used for our internal formatting, if serverspec needs to format data differently to us they should implement their own formatting, even if this is just vendoring our code as rebadging it as theres.

**Comment by myronmarston** [comment]
I think `failure_slash_error_line` would be a pretty odd public API but perhaps we can provide some other APIs.  What API would help you?

**Comment by jzohrab** [comment]
Thanks @JonRowe.  Too bad Ruby doesn't have private classes.  Vendoring could create other trouble, I've not had good luck with it in the past - maintenance headaches.

@myronmarston - thanks for the offer.  I'm not sure what the design choices were for this that necessitated the monkeypatching.  I'll ask the project maintainer to pitch in here.

**Comment by JonRowe** [comment]
@jzohrab by vendoring in this instance I mean taking the code and making it there own, there would be no other trouble as the serverspec solution would then be independent rather than dependant on us, the only downside is they would have to maintain it themselves...

**Comment by jzohrab** [comment]
Thanks @JonRowe, that downside is the trouble I was referring to.  If they vendor just that one class, I figured there may be other compatibility issues down the line as I think that you were saying that this class is internal only.  Anyway, patched for now, and maybe the maintainer will reach out with more requests.

**Comment by JonRowe** [comment]
@jzohrab Yes they should implement there own formatters if they want to change how things are displayed, not just monkey patch ours, one way uses a public api and the maintenance overhead will be minimal unless they choose otherwise, this way we may continue to break things and we're not going to make APIs public to "support" monkey patches.

**Comment by jzohrab** [comment]
Thanks @JonRowe, appreciated!
