### ISSUE TITLE
Documentation Bug: default value of `--pattern` option

### ISSUE THREAD

**Issue by phs** [rspec/rspec-core#2176]
It looks like [docs][docs] claim two different default values for the `--pattern` option; either `"spec/**/*_spec.rb"` (claimed [here][one]) or `"**/*_spec.rb"` ([here][the-other]).  Which one is accurate?

[docs]: https://www.relishapp.com/rspec/rspec-core/v/3-4/docs/command-line/pattern-option
[one]: https://github.com/rspec/rspec-core/blob/ceecf84/features/command_line/pattern_option.feature#L5
[the-other]: https://github.com/rspec/rspec-core/blob/ceecf84/features/command_line/pattern_option.feature#L28-L42

**Comment by myronmarston** [comment]
Thanks for pointing this out, @phs!  As it turns out, neither is accurate (although one or perhaps both were accurate at some point in the past).  I've pushed an update in #2177 that corrects the docs.  Let me know if things are still unclear.
