### ISSUE TITLE
--profile and --exclude-pattern pattern do not play well together

### ISSUE THREAD

**Issue by JuanitoFatas** [rspec/rspec-core#2178]
When I run this command in a Rails 4.2.5.1 project with Spring:

```
bin/rspec --exclude-pattern "spec/features/*_spec.rb" --profile
```

Or without Spring:

```
bundle exec rspec --exclude-pattern "spec/features/*_spec.rb" --profile
```

The exclude pattern did only execute specs except feature specs. But the profiled result shows me candidates under `spec/features`.

rspec-core 3.3.2 & 3.4.3 both have this issue.

Thanks.

**Comment by JonRowe** [comment]
Profiling will only show you specs that are run, but your exclude will only ignore specs in the root of `spec/features` and not `spec/features/subdir`

**Comment by JuanitoFatas** [comment]
> Profiling will only show you specs that are run, but your exclude will only ignore specs in the root of spec/features and not spec/features/subdir

Oh I got it. Thanks for prompt reply, I am sorry.
