### ISSUE TITLE
Rspec pattern does not find "utils" directory.

### ISSUE THREAD

**Issue by hjkatz** [rspec/rspec-core#2184]
tree spec outputs:
```
spec
├── my_spec.rb
├── scripts/
│   ├── my_customer_data/
│   │   └── sync_spec.rb
│   └── my_customer_data_spec.rb
├── spec_helper.rb
└── utils/
    ├── credentials_spec.rb
    └── google_api_spec.rb
```

When I run: `./bin/rspec --pattern "./spec/**/*_spec.rb"`

```
MyScripts
  has a version number equal to 1

MyScripts::Scripts::MyCustomerData::Sync
  #_get_field_value
    returns a nil
    returns a string
    returns a number
    returns true
    returns false
    returns a date hash
    returns a url
    returns an email
    returns a phone number
  #sync
Must run as root

Finished in 0.02764 seconds (files took 0.70052 seconds to load)
11 examples, 0 failures
```

Expected: All specs to be run.

Actual: All but the utils directory was run.

**Comment by JonRowe** [comment]
Hmm that's odd; We don't filter anything like that, have you checked your `~/.rspec` and `.rspec` files for `--exclude-pattern` that might be removing them? Can you check what files RSpec has loaded for me by adding this to your `spec_helper.rb`:

```
RSpec.configuration.after(:suite) do
  puts RSpec.configuration.files_to_run.inspect
end
```

**Comment by hjkatz** [comment]
project .rspec:
```
--format documentation
--color
```

No home .rspec, I'm using the defaults that come with `bundle gem`

Files to run
```
["/home/harrison/Projects/neadwerx_scripts/spec/neadwerx_scripts_spec.rb", "/home/harrison/Projects/neadwerx_scripts/spec/scripts/xerp_customer_data/sync_spec.rb", "/home/harrison/Projects/neadwerx_scripts/spec/scripts/xerp_customer_data_spec.rb", "/home/harrison/Projects/neadwerx_scripts/spec/utils/credentials_spec.rb", "/home/harrison/Projects/neadwerx_scripts/spec/utils/google_api_spec.rb"]
```

So it appears to be picking it up, but it's not getting run? Strange indeed. Additionally there are no instances of the pattern `exclude-pattern` in my codebase, except for the ones in rspec-core-3.4.3.

**Comment by hjkatz** [comment]
Ok I think I know the problem, which leads me to a question.

I have a spec for a Thor script I wrote which tests that it should abort with a certain message:
```
  describe "#sync" do
    it "must be run as root" do
      expect( @sync.invoke( :sync ) ).to output( /must be run as root/i ).to_stdout
    end   
  end
```

If I comment this example, then the specs continue to run. Here's the code for sync:
```
    def sync
      abort "Must run as root" unless Process.euid == 0
      ...
    end
```

So what I think is happening is that the `abort` is exiting everything, even rspec. I do not expect this behaviour. How can I test this with a spec? Is there a way to capture, or run the thor task in a separate thread (what I thought rspec was already doing) to test this code?

**Comment by hjkatz** [comment]
I'm going to close this out and open a separate issue. For anyone following along here's my solution:
```
  describe "#sync" do
    it "must be run as root" do
      expect { @sync.invoke( :sync ) }.to raise_error SystemExit

      #expect {
      #  begin @sync.invoke( :sync )
      #  rescue SystemExit
      #  end
      #}.to output( /must run as root/i ).to_stderr_from_any_process
    end   
  end
```

The commented expect does not currently work, I do not know why.

**Comment by hunner** [comment]
@hjkatz I'm having the same issue; specifying `to_stdout` blocks further parsing of specs to be run. Where did this end up? On 3.7.1

**Comment by JonRowe** [comment]
@hunner @hjkatz's issue was he was aborting his spec run using `abort` which raises a `SystemExit` using a `to_stdout` block won't block your spec unless you have something in that block that well blocks, the `to_stdout` matcher just replaces `$stdout` with a wrapper that allows us to introspects its content
