### ISSUE TITLE
Consider providing register_listener as a public API on Configuration

### ISSUE THREAD

**Issue by fireyone29** [rspec/rspec-core#2190]
I'm trying to write a helper for some rspec tests that listens to all the pass/fail/pending messages and inspects example metadata as you might in a formatter, however I have no intention of ever outputting any sort of progress indication from this helper (because it's aggregating data in such a way that there is no meaningful intermediate state).  This makes it exceedingly difficult to make the operation of this helper transparent to the user because that there's no way I can see to distinguish a formatter which doesn't want to be involved in the output from one that does.  In other words, I'd like the behavior of a formatter but with the ability to not override the default formatter. If the CLI or the configuration defines another formatter, then there's no problem (because mine would simply be added to them).

Currently I can achieve the behavior I want by using the (private) [reporter](https://github.com/rspec/rspec-core/blob/19761e35a0fa8e7d61eaf4af52226fa0c2a39817/lib/rspec/core/configuration.rb#L825-L837) from a configuration and then its (public) [register_listener](https://github.com/rspec/rspec-core/blob/19761e35a0fa8e7d61eaf4af52226fa0c2a39817/lib/rspec/core/reporter.rb#L40-L52) api (I don't appear to need any other part of the reporter interface).  But I can't see any way to achieve the same result using only public interfaces.

I've searched previous issues (although not exhaustively) and didn't see anything particularly helpful.  However, I've seen people advise using the reporter interface on Configuration in a [few](https://github.com/rspec/rspec-rails/issues/1352#issuecomment-91933880) [places](https://github.com/rspec/rspec-core/issues/1851#issuecomment-70557704) despite the fact that it's marked private, perhaps the easier way is just for it to be made public (or for me to treat it as such)?

**Comment by myronmarston** [comment]
Thanks for asking about our public APIs :).

This makes sense to me.  And perhaps `RSpec.configuration.reporter` should be public. I'm surprised it's not.

@JonRowe what do you think?  You've done the most work here.

**Comment by JonRowe** [comment]
I'm kind of surprised `Configuration#reporter` is private, my intent has been for it to be public, PR incoming...

**Comment by fireyone29** [comment]
Very cool. Thanks guys!
