### ISSUE TITLE
config.warning does not produce warnings

### ISSUE THREAD

**Issue by JordiPolo** [rspec/rspec-core#2195]
If in my `spec_helper.rb` I add  `config.warnings = true` I do not in fact get Ruby warnings.
If instead I have a .rspec file with `--warnings` I do get the warnings as expected.

I've checked the code and both do the same, modify `$VERBOSE`. I wonder if the problem is that in the case of the spec_helper.rb file, `$VERBOSE` is modified after having required my code while in the .rspec file I'm not sure if that's true.

**Comment by JonRowe** [comment]
> I've checked the code and both do the same, modify $VERBOSE. I wonder if the problem is that in the case of the spec_helper.rb file, $VERBOSE is modified after having required my code while in the .rspec file I'm not sure if that's true.

That's exactly the issue, your spec_helper must be loaded before anything else, we recommend adding `--require spec_helper.rb` to your `.rspec` file.

**Comment by JordiPolo** [comment]
I see, so then to have warnings one way or the other I do need the .rspec file.

**Comment by JonRowe** [comment]
Or delay the loading of your code until your specs run, this means you can't require anything until the spec_helper is required by your specs and the configuration block has run, you can also use `--warnings` with the executable of course
