### ISSUE TITLE
Warnings-flag should default to true. 

### ISSUE THREAD

**Issue by yxhuvud** [rspec/rspec-core#2201]
Too many projects start without warnings enabled and then when they figure that hey, it would be nice to have, then they get drowned by too many warnings and doesn't follow through. 

Having low tolerance of warnings is healthy and therefore I propose to change the default value to check for them. It should of course be simple to turn it off for existing projects that can't realistically enable it.

**Comment by myronmarston** [comment]
We tried something like this in RSpec 3.0.  In 3.0, the `.rspec` file generated by `rspec --init` had `--warnings` in it.  We got lots of questions/comments on twitter and elsewhere asking, "why do I get spammed with so much warning output on RSpec 3?"  The unfortunate truth is that most of the ruby ecosystem does not have warning-free code, and that means that if you enable warnings on a project that uses gems, you're likely to get lots of warning output you can't do anything about.  In addition, the warning output won't give you any indication about how to turn it off: when a gem has code that triggers ruby warnings, Ruby isn't going to tell you "configure RSpec to disable warnings like so".  It makes for a very bad experience for RSpec users if they are stuck getting tons of noisy warning output from code they did not write and there's no indication how to disable it.

The solution we came up with for RSpec 3.1 was to move the warnings flag into the commented-out part of the `spec_helper.rb` file generated by `rspec --init`.  This encourages users to set it but forces them to take action (e.g. uncommenting it) to enable it so they are aware of how it got turned on and will therefore know how to turn it off if they need to.

If you want it to default to true for you, you can just add `--warnings` to `~/.rspec` and it'll enable it for all projects using rspec on your machine.

For more background, see #1571 and #1572.

**Comment by MicMicMon** [comment]
Do you think there would be a way to enable warnings on the tested code but **not** on the dependency code?

True I don't want to be spammed by dependencies having warnings in their code, but it would be interesting to have warnings for my own code. Unless all output warnings are already covered by Rubocop / Reek?

**Comment by JonRowe** [comment]
There isn't a way to do that properly, you can see how we deal with this internally in our spec suite, (we turn on warnings and check we don't generate any as a spec).
