### ISSUE TITLE
Add context to deprecation warning

### ISSUE THREAD

**Issue by jasnow** [rspec/rspec-core#2207]
Missing context (filename, line number, etc) with this warning:
**[DEPRECATION] last_comment is deprecated. Please use last_description instead.**

**Comment by myronmarston** [comment]
This comes from [rake](https://github.com/ruby/rake/blob/461cfcb0795dff750508871669621412375b6986/lib/rake/task_manager.rb#L10), not from RSpec.  Nothing we can do about this.  Please report it there if you'd like to see it changed.

**Comment by jasnow** [comment]
sorry
