### ISSUE TITLE
rake_task using deprecated "last_comment" method

### ISSUE THREAD

**Issue by jasnow** [rspec/rspec-core#2210]
Warning message from rake: 
 * **[DEPRECATION] `last_comment` is deprecated. Please use `last_description` instead.**

Triggered by "last_comment" on line 91 of rspec-core-3.5.0.beta1/lib/rspec/core/rake_task.rb file.

Also triggered by "last_comment" on line 118 of **unsupported** rspec-core-2.14.8/lib/rspec/core/rake_task.rb file.

**Comment by myronmarston** [comment]
This has been fixed in rspec-core 3.4.4 and 3.5.0.beta2.

We don't plan to backport to rspec 2.14.
