### ISSUE TITLE
anyway to reset files required by RSpec::Core::Runner

### ISSUE THREAD

**Issue by tansaku** [rspec/rspec-core#2211]
I've just been playing with RSpec::Core::Runner.run which is fun, but I notice that if I pass in file requires like so:

```ruby
RSpec::Core::Runner.run(['-r', 'myfile.rb', 'myspec.rb`
```

then those required files seem to hang around ...

I've tried various resets in between runs:

```ruby
RSpec.clear_examples
RSpec.reset
RSpec.world.reset
```

but while these reset other things, none of them appears to reset the files that were required by an earlier run of the runner with a -r flag.

Is there any simple way to reset the required files?  Grab a new instance of the runner or something?

Many thanks in advance

**Comment by myronmarston** [comment]
> Is there any simple way to reset the required files?

No, because Ruby causes `require 'foo'` to be a no-op if `require 'foo'` has been called previously in the process.  RSpec can't (and shouldn't, even if it could) change how Ruby's `require` works to allow you to re-require a file that's already been required in the process.

If you really want to mess with Ruby's require behavior, you can remove previously required files from `$LOADED_FEATURES` but I'm not sure if that's something ruby officially supports or not.

**Comment by tansaku** [comment]
Thanks @myronmarston - much appreciated. 

So alternatively is there some way to reload files, or simply just have the RSpec instance reset completely?

**Comment by JonRowe** [comment]
@tansaku depending on what you want to do, you could fork the process before invoking RSpec's runner, or you could use `load`

**Comment by tansaku** [comment]
thanks @JonRowe - forking seems to be doing what I want.  Does RSpec have it's own `load` operation or is that just Ruby

**Comment by JonRowe** [comment]
`load` is a ruby command, it evaluates the file in question (but allows re-evaluation)

**Comment by tansaku** [comment]
right, but re-loading a file can leave stray methods hanging around - seems like forking is the way to go ... 

many thanks again

**Comment by AirWick219** [comment]
> depending on what you want to do, you could fork the process before invoking RSpec's runner, or you could use load

@JonRowe Do you have any example for forking the process before invoking Rspec's runner? 

We have a gem that pulls common configuration and gems together to share for a couple of our apps. The gem loads up a config yml file from the consuming app in the gem's railtie and we want to test the effect from the different configurations. We set up a dummy app in our gem we did this in the `rails_helper.rb` 

```
require File.expand_path('dummy/config/environment', __dir__)
```

I have the `require 'rails_help.rb'` on top of the 2 tests with different config yml file. The test passed if I just run the individual test but they wouldn't not together. Then I realized the 'require 'rails_help.rb'` only run once which means the dummy app was only loaded once then it is cache. I believe that "forking the process" that you mentioned would solve my problem.

**Comment by JonRowe** [comment]
`load` takes a filename see: https://ruby-doc.org/core-3.0.0/Kernel.html#method-i-load where as `require` will take slightly looser feature names, https://ruby-doc.org/core-3.0.0/Kernel.html#method-i-require

Forking is covered by: https://ruby-doc.org/core-3.0.0/Kernel.html#method-i-fork it's essentially `fork { # do things in fork }`

**Comment by AirWick219** [comment]
O ic. But where do I fork the process? would it be somewhere within the `spec` folder in my gem like  `spec_helper.rb` or in the test file? or is that somewhere inside `bin/rspec`?

**Comment by JonRowe** [comment]
If you wish to fork the runner, you must fork in your own code, and invoke RSpec yourself.

**Comment by AirWick219** [comment]
> If you wish to fork the runner, you must fork in your own code, and invoke RSpec yourself.

mhmm ..... does that means I will have to 

1. Tell the original process to continue or stop when it hits one of those 2 tests 
2. fork the process and kick off the Rspec runner again
3. So it requires 'rails_helper.rb' and load up the dummy app as if it's the first time ??

**Comment by AirWick219** [comment]
Tried something like this in one of those tests. It did load up a different process for the configuration but it doesn't seem like it kick off the test. Am I missing something here?

```
# fruit_store_controller_spec.rb

fork do 
  require 'rails_helper'

  RSpec.describe FruitStoreController do
    ...
    ...
    it { expect(response.body).to eq('apple') }
  end
end

**Comment by pirj** [comment]
What if you also `require 'rspec/autorun'`, @AirWick219?

**Comment by JonRowe** [comment]
Read the source of the `ForkRunner` / `RunDispatcher` within the bisector for an example of how to control flow within a fork: e.g. https://github.com/rspec/rspec-core/blob/main/lib/rspec/core/bisect/fork_runner.rb#L93-112

Its not something that works out of the box.
