### ISSUE TITLE
HTML report is missing :extra_failure_lines

### ISSUE THREAD

**Issue by Nakilon** [rspec/rspec-core#2220]
I don't see `example.metadata[:extra_failure_lines]` lines in failures in HTML report generated with `-fh -o report.htm`. Is it only me?

**Comment by JonRowe** [comment]
It's quite possible the HTML formatter hasn't been expanded to include this information, feel free to open a PR implementing it! :)

**Comment by mrageh** [comment]
@JonRowe I can create a PR for this issue, it seems like the html formatter does not use the newly created `ExceptionPresenter` to get any of the failure messages.

This [method](https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/notifications.rb#L171) returns a correctly formatted error message that includes the `extra_failure_lines` from the [`exception_presenter`]( https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/formatters/html_formatter.rb#L74)

**Comment by mrageh** [comment]
I believe we can close this issue

**Comment by Nakilon** [comment]
@mrageh is it implemented or what?

**Comment by mrageh** [comment]
My message was'nt very clear @Nakilon, this [PR](https://github.com/rspec/rspec-core/pull/2222) may have fixed the above problem

**Comment by JonRowe** [comment]
@Nakilon do you want to try using the master version of rspec to see if this is fixed?

**Comment by xaviershay** [comment]
Please reopen if not fixed!
