### ISSUE TITLE
Adding report listener with documentation formatter results in duplicate summary

### ISSUE THREAD

**Issue by andypike** [rspec/rspec-core#2224]
I've added a custom listener using:

```
RSpec.configure do |config|
  config.reporter.register_listener(Reporter.new, :start, :example_started, :start_dump)
end
```

It works great and when I leave the output formatter as default I see a dot per passing example and summary as expected.

However, if I change my `.rspec` config file to include `--format documentation` then I see a dot and the spec description per example and also I see duplicate summaries when the suite is complete.

My limited understanding is that when you register a listener object, it is notified of the events that you subscribe to but it isn't classed as a formatter per se. Is this expected behaviour and if so, is there a way to use the documentation formatter and a custom listener and only get one set of output?

I looked around the rspec-core codebase but didn't spot any obvious reason for this but I'm not very familiar with it. The version of rspec-core that I'm using is: 3.4.4. If it helps, here is the project and commit that contains what I'm up to: https://github.com/andypike/rectify/pull/8/commits/e61b6b10d05686782b03c8625fbb2404bc1db06a (it collects database stats as spec run).

Thanks in advance for any help and also thank you for all the work you folks do on RSpec, it's greatly appreciated ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by JonRowe** [comment]
This is likely a bug caused by load ordering issues, are you configuring the reporter (also I'm assuming here that `Reporter.new` **is not** `RSpec::Core::Reporter.new`) from your `spec_helper.rb`? If so try adding `-r spec_helper` to your `.rspec`...

**Comment by andypike** [comment]
Thanks for the feedback @JonRowe. Firstly yes, `Reporter.new` is my own reporter class in this case, sorry for the confusion. Yes I'm configuring the reporter in my `spec_helper.rb` file and also I'm already including the `--require spec_helper` option in my `.rspec` file.

I've had a play around with the order of things and I found a combination that works. If I remove `--format documentation` from my `.rspec` file and instead configure it in `spec_helper.rb` with `config.formatter = :documentation` then if I move my usage of `#register_listener` to be after the formatter configuration then it works fine. So yes, it looks like an ordering bug of when things are loaded/configured. 

For clarity, this order example works for me:

```
# .rspec

--color
--require spec_helper
```

```
# spec_helper.rb

RSpec.configure do |config|
  # snip
  config.formatter = :documentation
  config.reporter.register_listener(Reporter.new, :start, :example_started, :start_dump)
end
```

but this order produces double output:

```
# spec_helper.rb

RSpec.configure do |config|
  # snip
  config.reporter.register_listener(Reporter.new, :start, :example_started, :start_dump)  
  config.formatter = :documentation
end
```
