### ISSUE TITLE
rspec is not listed in gem list

### ISSUE THREAD

**Issue by knaseem** [rspec/rspec-core#2228]
I installed rspec => sudo gem install rspec --version 2.8.0.  It installed successfully but when I do a gem list it does not show up in the list:

Khalids-MBP:~ KNaseem$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.2.0)
io-console (default: 0.4.2)
json (default: 1.7.7)
minitest (default: 4.3.2)
psych (default: 2.0.0)
rake (default: 0.9.6)
rdoc (default: 4.0.0)
test-unit (default: 2.0.0.0)

**Comment by myronmarston** [comment]
What does `sudo gem list` show?  `sudo gem install` may install to a different location than `gem install`.

**Comment by knaseem** [comment]
sudo gem list shows:

*** LOCAL GEMS ***

bigdecimal (default: 1.2.0)
io-console (default: 0.4.2)
json (default: 1.7.7)
minitest (default: 4.3.2)
psych (default: 2.0.0)
rake (default: 0.9.6)
rdoc (default: 4.0.0)
test-unit (default: 2.0.0.0)

**Comment by knaseem** [comment]
the gem env shows:

Khalids-MBP:~ KNaseem$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.3
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [universal.x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194
  - USER INSTALLATION DIRECTORY: /Users/KNaseem/.gem/ruby/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194/bin
  - SPEC CACHE DIRECTORY: /Users/KNaseem/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-15
  - GEM PATHS:
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194/bin
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194@global/bin
     - /Users/khalidnaseem/.rvm/rubies/ruby-1.9.3-p194/bin
     - /Users/khalidnaseem/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/KNaseem/.rvm/bin

**Comment by knaseem** [comment]
when I do rspec -v:

Khalids-MBP:~ KNaseem$ rspec -v
/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'rspec-core' (>= 0) among 8 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194:/Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194@global', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:320:in `to_spec'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/rspec:22:in `<main>'

**Comment by knaseem** [comment]
when I try to install rspec-core this is what I get:

Khalids-MBP:~ KNaseem$ sudo gem install rspec-core
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/rspec

**Comment by knaseem** [comment]
Any help would be appreciated.  I am studying for ruby/ROR.  Thanks.

**Comment by myronmarston** [comment]
There's something messed up in your environment.  I'm not sure what it is.  Regardless, it's an issue with how `rubygems` is working on your system, not an issue with how `rspec` is working.  (We just package `rspec` as a gem, and it's up to `rubygems` to install it correctly).

I'd encourage you to report this to [the rubygems maintainers](https://github.com/rubygems/rubygems) and see if they can help.
