### ISSUE TITLE
Using `--bisect` in `SPEC_OPTS` results in infinite loop

### ISSUE THREAD

**Issue by urbanautomaton** [rspec/rspec-core#2231]
### Expected behaviour

Using `SPEC_OPTS="--bisect"` should work the same as using `--bisect` on the command line.

### Actual behaviour

RSpec prints its bisection startup message, then continuously spawns new processes and does not terminate.

### Steps to reproduce

```
cat > blah_spec.rb <<EOS
RSpec.describe 'blah' do
  it 'is true' do
    expect(true).to be_truthy
  end
end
EOS

rspec blah_spec.rb --bisect # Works as normal

SPEC_OPTS="--bisect" rspec blah_spec.rb # loops infinitely spawning new rspec instances
```

### Discussion

I'm not sure if this is necessarily a case you'll want to handle, but it was a problem we ran into recently while trying to bisect order-dependent failures from CI. We use a separate test runner, [knapsack](https://github.com/ArturT/knapsack), to manage parallelisation of our build. Since this controls RSpec invocation, it's frequently necessary to use `SPEC_OPTS` to add extra options such as `--fail-fast` and `--bisect`.

When `--bisect` is specified at the command line, RSpec spawns child processes each time it runs a bisect round, [removing `--bisect` from the original CLI arguments](https://github.com/rspec/rspec-core/blob/cf8dfdc76586a9bb09da0bd03f0da3f2cf8fc580/lib/rspec/core/bisect/runner.rb#L15) so the child processes don't try to start a new bisection.

When `--bisect` is specified in `SPEC_OPTS`, however, it's passed through to the child processes, which then start a new bisection, launch more child processes, and so on and so on.

I'd be happy to submit a PR to address this problem, but first wanted to check whether you think it's worth the extra complexity that would be required to support `--bisect` via `SPEC_OPTS`, or whether this is an option you only want to support as a CLI argument.

**Comment by JonRowe** [comment]
This isn't an unreasonable assumption, although it's easy to see why the behaviour results, I've tried to trivially isolate this but without success so far, I'm out of time to work on this tonight, but feel free to have a go!

**Comment by myronmarston** [comment]
We'd happily merge a fix for this :).  I honestly never considered `SPEC_OPTS` when adding `--bisect` so I'm not too surprised to see it caused this problem.

**Comment by JonRowe** [comment]
I've tried manipulating the env we pass to Open3 but without any joy, similarly tried to unset the env on the command without any luck, didn't try directly manipulating ENV however.

**Comment by urbanautomaton** [comment]
Thanks for looking into it - I'm having a go too. So far I've managed to fork-bomb my own laptop by writing a correctly-failing test that didn't quite clean up after itself. Tricky one, this. :)

I've also tried to pass a modified env to `Open3` (using a copy of the original, but with just `--bisect` removed from SPEC_OPTS). When I do this, though, the child processes seem to lose any notion of which examples they should be running, and act as if called with no arguments. They get this info from the DRb server, though, so I'm a bit at a loss as to why modifying the env should interfere with this.

**Comment by bf4** [comment]
I'm going to guess that the reason is that `--bisect` should only be passed into the top-level RSpec process, but when it's in the ENV, it gets passed into every child which then spawns more children, each trying to bisect.

Just got this memory-usage artifact on our circleci failure

> Your build has exceeded the memory limit of 4G on 1 container

```
 17038 161640 3.5 ruby /home/ubuntu/rails_server/vendor/bundle/ruby/2.2.0/bin/rake knapsack:rspec
```

and then 43 of these

```
 17444 27524  0.8 /home/ubuntu/.rvm/rubies/ruby-2.2.4/bin/ruby -I/home/ubuntu/rails_server/vendor/bundle/ruby/2.2.0/gems/webmock- (etc)
```

**Comment by bf4** [comment]
yeah, the runner has `@original_cli_args = original_cli_args.reject { |arg| arg.start_with?("--bisect") }` which only looks at cli args.  I'm not sure if the spawned runners should have a different ENV['SPEC_OPTS'] passed to them or if RSpec should modify before the runners start and restore it when they end

**Comment by bf4** [comment]
(and if anyone is paying attention, apparently I did not read @urbanautomaton 's description carefully enough because these details are laid out in it.).

any particular reason to use open3 vs. spawn?

**Comment by myronmarston** [comment]
> any particular reason to use open3 vs. spawn?

Not that I know of.  I've used `open3` a few times and reached for it because I was familiar with it.  I don't think I've ever used `Process.spawn` before and didn't consider it.

If switching helps you fix this issue and satisfies the tests, go for it.

**Comment by bf4** [comment]
hmm, 

> Open3.popen3(*cmd, **opts, &block)
> The parameters env, cmd, and opts are passed to Process.spawn.
> ```ruby
require 'open3'
require 'pp'

> ENV.keys.collect { |k| ENV.delete(k) }
result = Open3.popen3({'A' => 'B', 'C' => 'D'}, '/usr/bin/env') do |i, out, err, thr|
  output = Thread.new { out.read }
  error  = Thread.new { err.read }

>  [ output.value, error.value, thr.value ]
end

> pp result #=> ["A=B\nC=D\n", "", #<Process::Status: pid 46225 exit 0>]
```
