### ISSUE TITLE
Tests pass with exit code 1?

### ISSUE THREAD

**Issue by NullVoxPopuli** [rspec/rspec-core#2235]
Not sure why I'm getting exit code 1 (with `echo $?` after I run rspec), but here is the project and branch that the problem exists on:

https://github.com/NullVoxPopuli/meshchat/pull/13

How do I debug this to try to find the source of the problem? or, could something possibly be misconfigured?

**Comment by JonRowe** [comment]
Can you gist your run output or point to a travis log? We do have a configurable failure code but normally a successful run of the `rspec` command (as opposed to running rspec via rake) would exit 0.

**Comment by NullVoxPopuli** [comment]
Here iss
 the Travis build/log https://travis-ci.org/NullVoxPopuli/meshchat/jobs/127304636

Maybe I'm missing something simple? I've never had this happen before.

**Comment by NullVoxPopuli** [comment]
here is a gist of the rspec output and exit code: https://gist.github.com/NullVoxPopuli/ab15a8323ba40a41abfa6eebdf399ee4

**Comment by myronmarston** [comment]
I noticed in your output that you're using simplecov.  SimpleCov can be configured to exit with non-zero status when your coverage percent is below a certain threshold.  Can you check if that's going on here?

**Comment by NullVoxPopuli** [comment]
oh! good idea. thanks, I'll report back when I figure out what that's configured to

**Comment by NullVoxPopuli** [comment]
@myronmarston ok, so, I found on the simplecov readme, that if I set 
```ruby
SimpleCov.minimum_coverage 80
```
then it won't change the exit code if its below 80.
Luckily, I'm slightly above 80%.

However,
```
Finished in 2.59 seconds (files took 0.82088 seconds to load)
103 examples, 0 failures

Randomized with seed 30190

Coverage = 80.93%. Sending report to https://codeclimate.com for branch refactor... done.
webdev@ubuntu 192.168.163.129  ~/Development/meshchat
⬡ v5.10.1 💎  2.3.0@meshchat (refactor) $ echo $?
1
```

But I'll keep poking around, cause I'm also using code climate

**Comment by NullVoxPopuli** [comment]
I don't think its code climate, cause I commented out the require, and commented it out from my gemspec (and re-ran bundle)... and then did the same for simplecov.

Still, exit 1.

```
bundle exec rspec
....
echo $?
1
```

here is my bundle currently:

bundle exec gem list:

```

*** LOCAL GEMS ***

action_cable_client (1.2.4)
activemodel (5.0.0.beta4)
activerecord (5.0.0.beta4)
activesupport (5.0.0.beta4)
addressable (2.4.0)
arel (7.0.0)
ast (2.2.0)
awesome_print (1.6.1)
bundler (1.11.2)
byebug (8.2.5)
coderay (1.1.1)
colorize (0.7.7)
concurrent-ruby (1.0.2)
cookiejar (0.3.0)
diff-lcs (1.2.5)
em-http-request (1.1.3)
em-rspec (0.1.1)
em-socksify (0.3.1)
em-websocket (0.5.1)
em-websocket-client (0.1.2)
eventmachine (1.2.0.1)
eventmachine_httpserver (0.2.1)
http_parser.rb (0.6.0)
i18n (0.7.0)
meshchat (0.9.0)
method_source (0.8.2)
minitest (5.8.4)
parser (2.3.1.0)
powerpack (0.1.1)
pry (0.10.3)
pry-byebug (3.3.0)
rainbow (2.1.0)
rspec (3.4.0)
rspec-core (3.4.4)
rspec-expectations (3.4.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
rubocop (0.39.0)
ruby-progressbar (1.8.0)
slop (3.6.0)
sqlite3 (1.3.11)
thread_safe (0.3.5)
tzinfo (1.2.2)
unicode-display_width (1.0.5)
websocket (1.2.3)
yard (0.8.7.6)

```

**Comment by myronmarston** [comment]
Here's my suggestion to track this down:

* Add a stand-alone spec file containing a simple passing spec:

``` ruby
RSpec.describe "Hello World" do
  it "passes" do
    expect("hello world").to start_with("hello")
  end
end
```

* Be sure not to require anything from this file.
* Remove any `-r` or `--require` flags from `.rspec` so that you can run just this spec with nothing else from your project loaded.
* Run `bundle exec path/to/spec; echo $?` see what it exited with (I expect it'll be 0).
* Selectively require bits of your application and gems you use in this file, re-running `bundle exec path/to/spec; echo $?` to see how it affects the exit status.
* Keep doing this until you've identified which file or gem triggers the exit code of 1.  That should pinpoint the culprit.

**Comment by NullVoxPopuli** [comment]
ah ha! it's something in my `spec_helper.rb`

**Comment by NullVoxPopuli** [comment]
now, I've commented out my spec_helper.rb, and am uncommenting one line at a time to see what's causing the exit status of 1

**Comment by NullVoxPopuli** [comment]
looks like it's the `em-rspec` gem :-(

it was really nice for running all my tests in an EventMachine run loop

**Comment by NullVoxPopuli** [comment]
here are the files for em-rspec: https://github.com/stevegraham/em-rspec/tree/master/lib I'm looking to see what's causing the failure, atm

**Comment by NullVoxPopuli** [comment]
does `Rspec::Core::Example#run` have to return a specific value? I just copied this in to my spec_file (without em-rspec), and it my single simple test failed:

```ruby
RSpec::Core::Example.class_eval do
  alias ignorant_run run

  def run(example_group_instance, reporter)
    Fiber.new do
      EM.run do
        df = EM::DefaultDeferrable.new
        df.callback { |x| EM.stop }
        ignorant_run example_group_instance, reporter
        df.succeed
      end
    end.resume
  end
end
```

**Comment by NullVoxPopuli** [comment]
ok, so, The EM.run loop returns nil, so that's probably what's going on.

**Comment by myronmarston** [comment]
> does Rspec::Core::Example#run have to return a specific value?

Yes, it does.  It needs to return `true` to indicate it passed, and `false` to indicate it failed.  `nil` is falsey so RSpec is interpretting that as failing.

**Comment by NullVoxPopuli** [comment]
@myronmarston do you have any recommendations for testing with EventMachine? 
I'm trying to have a separate run loop per test.

**Comment by myronmarston** [comment]
I've never used EventMachine, sorry.

**Comment by NullVoxPopuli** [comment]
We'll I'll keep doing research, and post back when I have a solution. Maybe this could get added to the rspec docs :-)

**Comment by NullVoxPopuli** [comment]
@myronmarston this is what I have so far:

```ruby
RSpec::Core::Example.class_eval do
  alias ignorant_run run

  def run(example_group_instance, reporter)
    result = false

    Fiber.new do
      EM.run do
        df = EM::DefaultDeferrable.new
        df.callback do |test_result|
          result = test_result
          # stop if we are still running.
          # We won't be running if something inside the test
          # stops the run loop.
          EM.stop if EM.reactor_running?
        end
        test_result = ignorant_run example_group_instance, reporter
        df.set_deferred_status :succeeded, test_result
      end
    end.resume

    result
  end
end
```

I ran `rspec` 15 times in a row to try to catch any race conditions possibly brought up by the randomization of the tests. 

I have a passing build: https://travis-ci.org/NullVoxPopuli/meshchat/builds/127627569

And I was sure to test that if I change my tests to deliberately fail, rspec also fails with a failing exit code. 

Woo!

**Comment by myronmarston** [comment]
Sounds like you've got a working solution then.  Gonna close this.

**Comment by NullVoxPopuli** [comment]
@myronmarston yeah! do you think there is a place this could be documented somewhere? does it make sense to document with rspec? or... should it go elsewhere?

**Comment by myronmarston** [comment]
What specifically are you looking to document?

**Comment by NullVoxPopuli** [comment]
that if you have an app that uses event machine, and if you have evented code, you must have the little monkey patch is required in order for the tests to pass.

**Comment by myronmarston** [comment]
RSpec is used in so many contexts (as its a generic ruby testing tool) that I don't think it makes sense for us to host documentation targeting integration with specific niche ruby libraries.  You can publish a blog post spreading the word about how you got it to work, though.

**Comment by NullVoxPopuli** [comment]
ok! :-) thanks!
