### ISSUE TITLE
bug: order of files given at command line is not preserved (when ordered)

### ISSUE THREAD

**Issue by e2** [rspec/rspec-core#2247]
### My problem

Specs execute in the wrong order, e.g. given two failing specs

`rspec --order defined --fail-fast spec/foo_spec.rb spec/bar_spec.rb`

It runs `spec/bar_spec.rb` before `spec/foo_spec.rb`.

### I'll cut to the chase: 

The `sort` here breaks the order: https://github.com/rspec/rspec-core/blob/7a23830/lib/rspec/core/configuration.rb#L1762

### Code history

I traced that `sort` to this commit: https://github.com/rspec/rspec-core/commit/d91410f4d753c2ed2c75ae68137170aef4ab1f96#diff-347a1d9242143ec7d337efe37081249aR905

### Conclusion / my expectation

Yes, sorting is import if `seed` is being used. But ... if order is defined, I want the files to run in the order I passed them on the command line.

**Comment by JonRowe** [comment]
Order defined is not the same as order "passed in", as the commit mentions we need to sort files (not specs) to ensure consistency.

**Comment by e2** [comment]
@JonRowe - yes, but there's no way to run files NOT in an alphabetical order.

If "alphabetical" is important, then the `order` option should be explicitly called "alphabetical".

**Comment by e2** [comment]
Trivial example:

`rspec spec/unit_spec.rb spec/acceptance_spec.rb`

This runs `acceptance_spec` before `unit_spec` simply because "a" < "u". There is no way to run `unit_spec` before `acceptance_spec`. And there's no sane reason to prevent that.

I understand that the file system doesn't return files in alphabetical order. 
I also understand that some people name their specs `1_test_spec.rb`, `2_test_spec.rb` and expect them to be ordered when passing a directory as an argument.

However, individual files passed on the command line actually guarantee consistency.

If I run `rspec specs/foo_spec.rb specs` it's obvious I want `foo_spec.rb` to be run first, even if it's already in `specs`.

**Comment by e2** [comment]
### Impact:

The only test that fails (once `sort` is removed) is this one:

https://github.com/rspec/rspec-core/blob/8483181/spec/rspec/core/configuration_spec.rb#L596

I'd submit a PR, but I have no clue how to make this configurable.

**Comment by JonRowe** [comment]
You're missing the point, `order` has no bearing on spec file loading. To achieve what you want I suggest you order your specs properly. E.g. if you tag your acceptances specs with `type: :acceptance` you could make them always run last with:

```Ruby
RSpec.configure do |config|
  config.register_ordering :global do |examples|
    acceptance, rest = examples.partition { |ex| ex.metadata[:type] == :acceptance }
    [rest, acceptance]
  end
end
```

**Comment by e2** [comment]
Wow! *That* should be in the docs/examples. With that example, everything makes sense. I didn't get the "global" part.

(The existing examples just didn't make any practical sense to me. Like, why would you want to reverse tests or reuse an instance variable between specs?)

Thanks!

**Comment by JonRowe** [comment]
I'll update the docs a bit to make it clearer

**Comment by e2** [comment]
A bit off-topic, but I have the impression that one major reason people use both RSpec and Cucumber in Rails apps is because ... they don't know how to isolate acceptance/functional tests from unit tests.

The "solution" was always to run slower RSpec tests (functional, integration or acceptance) in a separate RSpec process/config after unit tests succeeded. (Which is what I always ended up doing).

I also think too many people "give up" when they find that the tests seem to run in a consistent albeit "random" order (because "alphabetical" is pretty much the same as "random" if files are named after classes and modules after directories). 

Most command-line tools are "file based". Here, RSpec is "example/group" based - but the metadata never seemed convenient enough to use and rely on. (Except maybe for before/after filters).

As a paradigm, it makes more sense to think of RSpec as a "database" of "grouped examples" instead of a "list of files with tests". And databases have queries. Metadata alone is useless if you can't easily construct the "query" you need. (e.g. a pseudo-query: `run tests where type not in [:pending, :wip] prioritize by: unit => [last_failed, most_failing, remaining], functional => [quick, remaining, slow], acceptance => [last_failed, most_failing, remaining]`).

I believe emphasizing this would be useful, because it would naturally lead people to the "right" solutions faster. E.g. to stop trying to control RSpec from the command line and use metadata-based configurations and helper classes.

**Comment by JonRowe** [comment]
> The "solution" was always to run slower RSpec tests (functional, integration or acceptance) in a separate RSpec process/config after unit tests succeeded. (Which is what I always ended up doing).

Yes. Processes are cheap, loading rails isn't mind, but if you're separating them properly you only load rails in the latter.

> I also think too many people "give up" when they find that the tests seem to run in a consistent albeit "random" order (because "alphabetical" is pretty much the same as "random" if files are named after classes and modules after directories).

Most people use the properly `:random` ordering as it's what we recommend as a default, the default "defined" is a leftover for compatibility reasons, it should only really be used for legacy specs that are dependant on each other. 

I actually combine the snippet I show above with the randomising strategy to randomise both sets of specs.

> Most command-line tools are "file based". Here, RSpec is "example/group" based - but the metadata never seemed convenient enough to use and rely on. (Except maybe for before/after filters).

This is a bit of an unfair comparison, rspec isn't some unix tool that can process files as it's given, it's a Ruby environment and subject to the laws therein, the ordering is done to ensure consistency, something that isn't otherwise guaranteed.

> As a paradigm, it makes more sense to think of RSpec as a "database" of "grouped examples" instead of a "list of files with tests". And databases have queries. Metadata alone is useless if you can't easily construct the "query" you need. (e.g. a pseudo-query: run tests where type not in [:pending, :wip] prioritize by: unit => [last_failed, most_failing, remaining], functional => [quick, remaining, slow], acceptance => [last_failed, most_failing, remaining]).

It's a heirarchy of grouped examples, rather than files yes, and you can filter on the metadata, see https://relishapp.com/rspec/rspec-core/v/3-4/docs/filtering

> I believe emphasizing this would be useful, because it would naturally lead people to the "right" solutions faster. E.g. to stop trying to control RSpec from the command line and use metadata-based configurations and helper classes.

Most of this is available from the command line though and RSpec is a very command line orientated tool. One off runs should be configured via the command line, whilst general project settings are configured via files.

**Comment by e2** [comment]
> This is a bit of an unfair comparison, rspec isn't some unix tool that can process files as it's given, it's a Ruby environment and subject to the laws therein, the ordering is done to ensure consistency, something that isn't otherwise guaranteed.

I mean that as a good thing - as opposed to Minitest/Test::Unit, where it's just "files with classes with methods". RSpec is a DSL, so you have an API where e.g. Minitest would needs hacks and plugins.

Users with more of a "minitest mindset" will shudder at the mere thought of "order dependency".

Consistency is irrelevant if we go back to the database analogy: a database can return record "unsorted" in the order they happen to be on the database. Users want them sorted in some meaningful way. Or, at least, to show the same order when the page/view/table is refreshed.

It's up to the user (or developer) to decide what to sort by. And this is usually convenient.

Here, in RSpec, sorting alphabetically just solved the "inconsistency" issue. A filename is basically a unique key (it's guaranteed to be unique), like a primary key in the database. So it's like sorting a database by primary key. Consistent, but not too practical.

What if I wanted to sort by file size? There is a `file_path` method, but it isn't clearly documented, except mentioned here: https://relishapp.com/rspec/rspec-core/v/3-4/docs/formatters/json-formatter.

My point here is: if RSpec is like a database, then the API/documentation should easily map to "queries" and "tables" and "columns". E.g. if RSpec was a database, then there would be a "schema" somewhere mentioning `file_path`. And other "fields" that could be used during filtering/ordering.

`fail_fast` is pretty much like `limit(1)` in SQL. So it's part of a "query" too. `profile` is pretty much like an `analyze` statement.

> and you can filter on the metadata

My favorite being: `c.filter_run_including :focus => ENV['CI'] != 'true'` (don't filter on Travis, etc.).

> One off runs should be configured via the command line, whilst general project settings are configured via files.

And that's exactly what should be "suggested" to users: to use the command line only for one-off changes (e.g. filtering based on things like `:focus`, `:wip`, a given file/line, reproducing a build error with a given seed, etc.).

Given what you said, I think it's a "design flaw" to map the configuration to match the command line arguments - instead of making both the configuration and command line arguments map to "building a query of examples to run".

Because the RSpec configuration is not really for "configuring RSpec" or "selecting files" but for "building a query".

Overall, I'm suggesting there is a clearer and more powerful way of structuring the documentation and a better "mindset" for using RSpec effectively. One that isn't at all apparent.

RSpec simply has a lot more in common with a tool like PostgreSQL `psql` tool (in how it queries and formats output) than Unix tools like `find` or `tar` or `rsync` (which have exclusion/inclusion patterns, matching, filtering, etc. based on files). E.g. "backtrace filtering" is pretty much just formatting output. Just like `psql` has an ascii vs html mode.

Which explains my initial confusion and I didn't "get" how ordering works and why it's designed this way. 

The whole "query building" is in bits and pieces (ordering, pattern matching, filtering, limiting, metadata) because it's designed to map to command-line options. (Meanwhile `psql` just allows you to enter a "query" on the command-line directly - kind of like what RSpec configuration is actually for).

I'm not suggesting allowing Ruby code directly in command line options for RSpec - but I am suggesting not letting the configuring be rigidly limited by what's available on the command-line.

Anyway, time to stop ranting and get back to work...

**Comment by e2** [comment]
For the sake of the solution, this is how to postpone acceptance tests:

```ruby
config.register_ordering :global do |examples|
  examples.partition { |ex| ex.metadata[:type] != :acceptance }.flatten
end
```

Without `flatten` I get:  `undefined method `descendants' for #<Array:0x00000003d967c0>` in `flat_map`.

**Comment by JonRowe** [comment]
Yes, that's what the `acceptance, rest` `[rest, acceptance]` was doing, the reason why I broke it up is normally I randomise each set of examples too
