### ISSUE TITLE
"Custom formatters" docs mention subclassing/overriding in text but use notifications in the example

### ISSUE THREAD

**Issue by henrik** [rspec/rspec-core#2269]
https://relishapp.com/rspec/rspec-core/v/3-4/docs/formatters/custom-formatters

It's unclear what you're actually expected to do.

**Comment by JonRowe** [comment]
You have to do the later regardless of wether you subclass or not.

**Comment by henrik** [comment]
@JonRowe Thank you. I was actually not asking for me but rather suggesting that those docs could be clarified to help others.

If I ever work on custom formatters enough to know how to clarify the docs myself, I might, but I don't think I will work on that today.

**Comment by JonRowe** [comment]
We always welcome PR improvements to the documentation if you have suggestions.
