### ISSUE TITLE
is it semantically versioned?

### ISSUE THREAD

**Issue by matkoniecz** [rspec/rspec-core#2270]
During building my gem I encountered

```
WARNING:  pessimistic dependency on rspec (~> 3.4.0, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.4', '>= 3.4.0'
```

In readme and in repository search I failed to find answer for this question.

**Comment by myronmarston** [comment]
Yes, RSpec follows SemVer:

https://relishapp.com/rspec/docs/versioningpolicy

**Comment by soulcutter** [comment]
This comes from RubyGems. https://github.com/rubygems/rubygems/blob/04d4d8546789f8741032be4c5ea92ebbf38ffa05/lib/rubygems/specification.rb#L2882-L2892
