### ISSUE TITLE
.subject  executes without being called if there is a .subject! in upper context

### ISSUE THREAD

**Issue by NIHERASE** [rspec/rspec-core#2273]
As you can see the `subject(:a)` is not executed at all while the `subject(:b)` is executed. `before(:each)` does not affect the result but it shows that `subject(b)` is executed first anyway.

```
# rspec -v
# 3.4.4
# rspec --init

# spec/test_spec.rb
require 'spec_helper'

RSpec.describe do
  subject!(:a) do
    puts 'subject!'
  end

  context 'context 2' do
    before(:each) do
      puts 'before'
    end

    subject(:b) do
      puts 'usual subject'
    end

    it '' do
    end
  end
end

# usual subject
# before
# .
#
# Finished in 0.00048 seconds (files took 0.06446 seconds to load)
# 1 example, 0 failures
```

I got rspec 3.4.4 from rubygems which seems to be the latest one there. What version should I use instead?

**Comment by myronmarston** [comment]
This is not a bug.  This is `subject!` working as it is designed to work.  Specifically it:

* Declares a `subject`
* Tells RSpec to call `subject` in a `before` hook.

Then you redefine `subject` in the nested context -- but it does not change the fact that you told RSpec to call `subject` in a before hook.

In general, I recommend avoiding `subject!`.  It exists for API consistency/parity with `let`/`let!` but I don't think I've ever seen a good use case, to be honest.  (And I personally avoid `let!`, too).
