### ISSUE TITLE
`shared_context` of type feature executes even when `include_context` is never called

### ISSUE THREAD

**Issue by Pistos** [rspec/rspec-core#2276]
To me, this is unexpected behaviour.  It is causing test pollution in my case.  Consider a `shared_context` which creates a record in the DB, and some specs expecting no record to exist.  It will always exist due to this "bug".

I am not certain this is an issue with `rspec-core`, as opposed to some other `rspec-*` library.

Reproducible proof at https://github.com/Pistos/rspec-shared-context-executed .

--------

```
% bundle exec rspec
requiring "./spec/support/shared-context-with-type-feature.rb"
requiring "./spec/support/shared-context-without-type-feature.rb"
executing with feature

rspec
  does not execute the shared_context without feature
  does not execute the shared_context with feature (FAILED - 1)

Failures:

  1) rspec does not execute the shared_context with feature
     Failure/Error: expect($shared_context_with_feature_executed).to be_falsy
     
       expected: falsey value
            got: true
     # ./spec/rspec-shared-context-spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.01397 seconds (files took 0.45565 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/rspec-shared-context-spec.rb:6 # rspec does not execute the shared_context with feature
```

**Comment by Pistos** [comment]
I'm realizing now that I don't need (or shouldn't) put `type: :feature` on a `shared_context`, but rather on the thing that has `include_context`.

**Comment by myronmarston** [comment]
You've hit upon a bit of RSpec that is working as designed but that can be confusing.  If you add metadata to a `shared_context` declaration, RSpec will auto-include that context in matching groups.

We agree this is confusing, so we have some changes coming in 3.5 that correct this (see #2256 and #1790 for the background discussion).  A summary of the changes is in our [3.5 release blog post draft](https://github.com/rspec/rspec.github.io/pull/95/files#diff-53a04b55b9871439ae50bf55f2674382R104).
