### ISSUE TITLE
Unable to retrieve status and or finished_at in example_finished listener.

### ISSUE THREAD

**Issue by Rodney-QAGeek** [rspec/rspec-core#2290]
**Problem:** `notification.example.execution_result.finished_at` and `notification.example.execution_result.status` return `nil` in the `example_finished` method of my custom listener.

**Failing Spec:**
A reproducible example can be found here: https://github.com/Rodney-QAGeek/rspec_example
I hope you don't mind this format, but this issue was difficult for me to reproduce with the Unit tests in `rspec-core`. I'd love feedback on how I could have gotten this to reproduce with the rspec unit tests in the project.

@myronmarston FYI, this is the bug I brought up in https://github.com/rspec/rspec-core/issues/2289

**Comment by myronmarston** [comment]
> I hope you don't mind this format, but this issue was difficult for me to reproduce with the Unit tests in rspec-core

What you've done is fantastic :).

**Comment by myronmarston** [comment]
I've got a fix in #2291.

> I'd love feedback on how I could have gotten this to reproduce with the rspec unit tests in the project.

You can check out how I did it, if that helps.

**Comment by myronmarston** [comment]
The fix is in master and 3-5-maintenance and will be included in the next release.
