### ISSUE TITLE
Fail execution when there are tests focused

### ISSUE THREAD

**Issue by fornellas** [rspec/rspec-core#2292]
Hello,

When using RSpec with:

``` ruby
  config.filter_run :focus
  config.run_all_when_everything_filtered = true
```

sometimes mistakes are made and a focused test is committed. When a release is made, only focused examples are executed and all other examples are not executed.

I usually execute rspec from Rake, and it would be very handy to have a command line option to be used in such case: "--disable-filters". This would force all examples to be executed in this situation, making sure we get both a useful default configuration and full coverage during builds.

Does this option make sense to exist? Or is there a way to fail when there are focused tests?

Thank you.

**Comment by samphippen** [comment]
I typically wrap those two lines in 

```
unless ENV["CI"]
...
end
```

which neatly cleans up that problem. Would that work for you?

**Comment by myronmarston** [comment]
Taking @samphippen's suggestion a step further, you can have focused examples fail on CI:

``` ruby
RSpec.configure do |c|
  if ENV['CI']
    c.before(:example, :focus) do
      raise ":focus should not be committed"
    end
  else
    c.filter_run_when_matching :focus
  end
end
```

(Note also that `filter_run_when_matching` is the new config we recommend for that setup.  See http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/#core-configfilterrunwhenmatching for more info).

**Comment by fornellas** [comment]
That works, of course, my question is if an option like --disable-filters makes sense. If so, I can dig into the code and make a PR. What do you guys think?

**Comment by JonRowe** [comment]
Given the ease of customising this with regular ruby I don't think it needs a flag personally

**Comment by xaviershay** [comment]
I'm generally negative on adding new config flags, we already have a heap.
