### ISSUE TITLE
RSpec::ExampleGroups constants accumulate on repeated runs from within the same process

### ISSUE THREAD

**Issue by kjhenner** [rspec/rspec-core#2312]
I've noticed that when running repeated tests within the same process, references to examples accumulate as RSpec::ExampleGroups constants. This only comes up as an issue for me because of my very 'off-label' use of RSpec to run tests periodically as a service. In this case, however, it leads to a memory leak with duplicate constant references to examples accumulating as my_first_example, my_first_example_1, my_first_example_2, etc. each time the spec is run.

I found that it's possible to remove those constants after each run with something like the following, and that this resolves the memory leak.

    RSpec::ExampleGroups.constants.each{ | c | RSpec::ExampleGroups.send(:remove_const, c) }

It may be that considering the fact that what I'm doing is outside the ordinary use-case, this kind of hackiness will be inevitable, but I'm curious if there's some more elegant way to keep these constants from accumulating.

**Comment by myronmarston** [comment]
I think it would make sense for `RSpec::Core::World.reset` ([see here](https://github.com/rspec/rspec-core/blob/b54e2a161b7de5e6cfdcfde9abce2ea3cec10b82/lib/rspec/core/world.rb#L34-L37)) to clear these constants and also for `RSpec.reset` ([see here](https://github.com/rspec/rspec-core/blob/b54e2a161b7de5e6cfdcfde9abce2ea3cec10b82/lib/rspec/core.rb#L58-L61)) to do so.  It might seem funny to have two ways to reset it, but `RSpec.world.reset` is just meant to reset the non-config data (all the stuff world tracks) and `RSpec.reset` is meant to reset config and non-config data.  `RSpec.world` is responsible for tracking the example groups and this is an extension of that tracking, IMO.

So maybe a method could be added like `RSpec::ExampleGroups.remove_all_constants` and called from both `reset` methods.  Want to take a stab at that?

**Comment by kjhenner** [comment]
Sure, that makes sense. I'll see if I can set up a PR when I have a chance.

**Comment by JonRowe** [comment]
Closed by #2328
