### ISSUE TITLE
How to set default environment var for RSpec?

### ISSUE THREAD

**Issue by 1c7** [rspec/rspec-core#2315]
### I dont't wanna prefix a `RAILS_ENV=development` every single time
```Ruby
# work
RAILS_ENV=development rspec spec/routing/username_schoolname_spec.rb

# not working
# because in test environment
rspec spec/routing/username_schoolname_spec.rb
```

<br/>
### I tried put  `ENV["RAILS_ENV"] ||= 'development' `  in top of `spec_helper.rb` but not working

```Ruby
ENV["RAILS_ENV"] ||= 'development' 
require 'factory_girl_rails'
require 'support/factory_girl'
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
```

### I tried to use dovenv gem but still not working.

<br/>
what should I do to set default environment to `development`?

Thanks :dancer: 
:smile: 

Thanks for your time~
RSpec is awesome!

**Comment by mrageh** [comment]
I'm not sure if you can set the `RAILS_ENV` to anything as it's set in [rspec-rails as test](https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L23)

**Comment by samphippen** [comment]
If you want to override RAILS_ENV for a specific test, or for all tests, you can simply do `ENV["RAILS_ENV"] = "development"` in that test, or at the top of your spec helper. The `||=` will only override it if it's not set.

**Comment by 1c7** [comment]
@samphippen Thank you !
By the way I saw your talk on Youtube, very funny.
:D

**Comment by wedgemartin** [comment]
This does not work with Rails 5.1.4 and rspec 3.7.  It gladly ignores your ENV setting in the spec helper and will seemingly happily destroy your development database every time, leaving you feeling betrayed and disappointed. Some developers have been known to seek therapy.

**Comment by myronmarston** [comment]
@wedgemartin if you'd like to report a problem, please open an issue in the rspec-rails repo, provide code that is not working how you expect, how you expect it to work, and what it is doing instead.

**Comment by shiralwz** [comment]
Have you try
`      before(:each) do
          stub_const('ENV', 'RACK_ATTACK_BLOCK_IP_LIST' => '')
      end
`

**Comment by cmdr-pushpendra-singh** [comment]
@shiralwz Thanks it works for me

**Comment by Startouf** [comment]
Adding this at the top of my rails_helper (above `require`s)

```
ENV['SOME_ENV'] ||= 'some_value'
```

works
