### ISSUE TITLE
Consider running entire suite when --next-failure run completes

### ISSUE THREAD

**Issue by soulcutter** [rspec/rspec-core#2322]
To ensure fixes didn't break previous tests RSpec could rerun the specs that it skipped over from only failures.

I often do this manually, except when I do it, it runs the specs already-covered by --next-failure . Not sure how this interacts with only failures (maybe useful there too?), or it could be an additional config. I lean towards making it the behavior only for --next-failure - but I can see arguments against also. Just throwing it out there.

**Comment by myronmarston** [comment]
IMO, it would be quite confusing for `--next-failure` to run everything.  Running everything is practically the opposite of `--next-failure`.  You can always do this:

``` bash
$ rspec --next-failure && rspec
```

If anything failed during the `--next-failure` run, it'll stop there, but if everything passed, it'll continue on to run the entire suite.  You can type that once and then just keep hitting your up arrow to keep re-running that command.

**Comment by soulcutter** [comment]
Yeah, but what I was getting at was avoiding re-running the tests that had passed under --next-failure . Still that is a trivial one-step way to accomplish verification. Usually this is for finicky legacy test suites that are slow. Honestly I wish I never wanted this at all (hah)
