### ISSUE TITLE
Before :all vs before :suite - scope clarification?

### ISSUE THREAD

**Issue by Portalboy** [rspec/rspec-core#2325]
In my program I am using Watir to spool up web browsers and test various pages for a website. The easiest way to do this (which I have been using) is to go with watir-rspec's default behavior of opening a new browser instance for every test package, then close it afterwards.

I really want to make my program more efficient, so that instead of opening and closing windows for every unit test, it will 'borrow' a browser that was already open from the previous test, redirect it to the page it tests on, and test. 
The problem with this is that although when I instantiate my browser object in before :all it works just fine, in before :suite it can't be accessed. If I puts the object name from before :all it comes back nil, and likewise within each spec file it comes back nil.

Basically, I'm instantiating the object in before :suite and destroying it in after :suite so that it can persist through all specs, then only close at the end. Is there anything I am missing about scope here? Is there a better way to do this altogether?
Furthermore, is there a way to do this while still maintaining the command shortening functionality 

(I.E. button(id: "foo") or send_keys :return)?

My spec_helper.rb

```ruby
require_relative '../login'
require_relative '../logInObject'

require 'watir'




# Configuration for watir-rspec
require "watir/rspec"

RSpec.configure do |config|
  # Use Watir::RSpec::HtmlFormatter to get links to the screenshots, html and
  # all other files created during the failing examples.
  config.add_formatter(:progress) if config.formatters.empty?
  config.add_formatter(Watir::RSpec::HtmlFormatter)

  # Open up the browser for each example.
#=begin
  config.before :all do
  
#  puts "----------before all!"
#    @browser = LoginDrone.new :internet_explorer if !@browser
#	@browser.doLogin
#	puts "Before all browser: #{@browser}"
#	sleep(3)
  end
  
  config.before :suite do
#  puts "----------before suite!"
#  puts "Before suite browser: #{@browser}"
	$user = Credentials.new #if !$user
	@browser = LoginDrone.new :internet_explorer if !@browser
	@browser.doLogin
	puts @browser
  end
  
#  config.before :all do
#	goto "office.rcsdev.com/dasqa"
#  end
#=end
=begin
  #This bit is of my own making, it chooses not to open a new browser if one exists.
  config.before :all do
    if @browser.nil?
		@browser = LoginDrone.new :internet_explorer
		doLogin
	end
  end
=end
#=begin
  # Close that browser after each example.
  config.after :suite do
  puts "----------after suite!" if @browser
  puts "after suite browser: #{@browser}"
    @browser.close if @browser
  end
#=end





  # Include RSpec::Helper into each of your example group for making it possible to
  # write in your examples instead of:
  #   @browser.goto "localhost"
  #   @browser.text_field(name: "first_name").set "Bob"
  #
  # like this:
  #   goto "localhost"
  #   text_field(name: "first_name").set "Bob"
  #
  # This needs that you've used @browser as an instance variable name in
  # before :all block.
  config.include Watir::RSpec::Helper

  # Include RSpec::Matchers into each of your example group for making it possible to
  # use #within with some of RSpec matchers for easier asynchronous testing:
  #   expect(@browser.text_field(name: "first_name")).to exist.within(2)
  #   expect(@browser.text_field(name: "first_name")).to be_present.within(2)
  #   expect(@browser.text_field(name: "first_name")).to be_visible.within(2)
  #
  # You can also use #during to test if something stays the same during the specified period:
  #   expect(@browser.text_field(name: "first_name")).to exist.during(2)
  config.include Watir::RSpec::Matchers
end

```

LoginDrone is an object that inherits from Watir::Browser with some added goodies, like the doLogin method which goes to my test site and gets a credential input.

P.S. I -DON'T- want to use global variables if at all possible, because A: they are inefficient and B: I want to eventually add multi-threading support.

**Comment by Portalboy** [comment]
Apologies, I intended to post this on the Watir-rspec github first to see if they knew what was going on.

I'll leave it here though,

**Comment by myronmarston** [comment]
In RSpec 3, we renamed `:each` to `:example` and `:all` to `:context` to hopefully make the difference more clear (however, we kept `:each` and `:all` as aliases for backwards compatibility).  A `before(:all)` hook in `config` does _not_ run before all specs in the suite; it adds a `before(:all)` hook to every top-level example group.  I think `before(:context)` makes this much more clear.  Instance variables assigned in `:all`/`:context` hooks get copied to the example group class the examples execute against but no effort has ever been made to do that for `before(:suite)` (in fact, I don't even know if it's come up before).

If you really want something to happen before the suite starts , `before(:suite)` is what you want.  Instead of using an instance variable, I'd recommend managing the state yourself, doing something like:

``` ruby
module Browser
  def self.instance
    @browser ||= LoginDrone.new :internet_explorer
  end
end

RSpec.configure do |c|
  c.before(:suite) { Browser.instance }
  c.after(:suite) { Browser.instance.close }
end
```

If you need to access the browser from any examples you can just use `Browser.instance`.

**Comment by Portalboy** [comment]
Thank you, with a bit of tweaking this worked perfectly for my needs! I really appreciate your quick and accurate response!

For others who may end up googling this, to make this work with Watir-RSpec's command shortening system (I.E. "title" instead of "@browser.title"), I put the following in the body of my spec_helper:
```
  module Browser
	def self.instance
	  @browser ||= LoginDrone.new :internet_explorer
	end
  end
```
The following under my RSpec.configure:
```
RSpec.configure do |c|
  c.before(:suite) { Browser.instance }
  c.after(:suite) { Browser.instance.close }
end
```
and the following under my before :all
```
@browser = Browser.instance
```
This is because Watir-RSpec requires that you reference @browser in your before :all in order to shorten commands.

As for the new usages of before/after, I will do my best to get comfortable with them. Thanks again!
