### ISSUE TITLE
errors in before/after(:suite) are not rescued and treated as failures

### ISSUE THREAD

**Issue by ghostsquad** [rspec/rspec-core#2329]
this is related to https://github.com/rspec/rspec-core/issues/21 but I didn't want to resurrect that thread.

I get a proper exit code, but if I wasn't paying attention, or looking at the exit code, I would have seen the `3 examples, 0 failures` and assumed all my tests pass.

```
$ rspec --version
3.5.3

$ rspec -cfd; echo "exitcode: $?"

Library
  marks books as unavailable after they are checked out

Student
  checks out the book from library if it is available
  does not check out the book from library if not available

An error occurred in an `after(:suite)` hook.
Failure/Error: raise Bogus::ContractNotFulfilled.new(fake_name, missed: missed, actual: actual)

Bogus::ContractNotFulfilled:
  Contract not fullfilled for library!

  Missed interactions:
    - #has_book?("Moby Dick") => true

  Actual interactions:
    - #return("Moby Dick") => []
    - #checkout("Moby Dick") => "Moby Dick"
    - #has_book?("Moby Dick") => false
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/bogus-0.1.6/lib/bogus/contracts/verifies_contracts.rb:14:in `verify'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/bogus-0.1.6/lib/bogus/contracts/adds_contract_verification.rb:18:in `block in add'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/bogus-0.1.6/lib/bogus/contracts/adds_contract_verification.rb:44:in `block in after_suite'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/example.rb:443:in `instance_exec'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/example.rb:443:in `instance_exec'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/hooks.rb:357:in `run'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1882:in `block in run_suite_hooks'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1880:in `each'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1880:in `run_suite_hooks'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1837:in `with_suite_hooks'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:112:in `block in run_specs'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:77:in `report'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:111:in `run_specs'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:87:in `run'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/wes/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/exe/rspec:4:in `<top (required)>'
# /Users/wes/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
# /Users/wes/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
# /Users/wes/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
# /Users/wes/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
#
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 0.01941 seconds (files took 0.11226 seconds to load)
3 examples, 0 failures

exitcode: 1
```

I filed an issue with Bogus in case they aren't hooking into `after(:suite)` properly. 
https://github.com/psyho/bogus/issues/74

**Comment by myronmarston** [comment]
A recent change was made to greatly improve how RSpec handles errors in `before(:suite)` and `after(:suite)` hooks in #2316.  Before that, errors in `:suite` hooks were not handled at all -- they would just crash the process and spit out the normal exception output that ruby provides.  Besides resulting in excessive output (e.g. Ruby does not backtrace filtering like we do), recent changes in how `bundle exec` works caused `bundle exec rspec` to spit out `bundler: failed to load command: rspec` in this situation -- which was quite confusing.

In #2316, we decided to rescue errors in `:suite` hooks and print out similar failure output to any normal example failure.  We exit with non-zero status as well, as you noted.

With that background out of the way, it's not clear to me what you want to be different.  The output you are getting is the output we designed for this case and it's not clear to me how it could be made better.

> if I wasn't paying attention, or looking at the exit code, I would have seen the 3 examples, 0 failures and assumed all my tests pass.

The thing is, all your tests _did_ pass.  A `:suite` hook is an out-of-bad hook that lets you run some start-of-suite setup logic or end-of-suite cleanup logic.  A `:suite` hook is not tied to any particular example and thus a failure in a `:suite` hook has nothing to do with whether or no any examples failed, but should cause the suite as a whole to fail (which we indicate via a non-zero exit code).

How can we improve things?

**Comment by ghostsquad** [comment]
@myronmarston great questions, I probably should have included some solutions that would make this clearer.

I think maybe it could be as simple as `3 Example, 0 Failures, 1 Hook Error` or something similar. Just to make it abundantly clear that you exited with code `1` for a reason.

In a related note, do you have any documentation on how to dynamically add test cases? I could probably work with `bogus` to convert their usage of `after(:suite)` to a dynamic set of tests cases so that you would actually see explicit failures.

**Comment by myronmarston** [comment]
> I think maybe it could be as simple as `3 Example, 0 Failures, 1 Hook Error` or something similar. Just to make it abundantly clear that you exited with code `1` for a reason.

**Comment by myronmarston** [comment]
Woops, hit the wrong button.  Will respond later.

**Comment by JonRowe** [comment]
@myronmarston I'd be ok with us adding a "but n Errors occurred" or similar to that line if something does happen... (Not sure I like "Hook Error" it's a bit specific).

**Comment by myronmarston** [comment]
> @myronmarston I'd be ok with us adding a "but n Errors occurred" or similar to that line if something does happen... (Not sure I like "Hook Error" it's a bit specific).

:+1:

**Comment by xaviershay** [comment]
In hindsight, this might be more justification for the API proposed in https://github.com/rspec/rspec-core/issues/740#issuecomment-15700039 ?

**Comment by xaviershay** [comment]
Closing because it's fixed on master!
