### ISSUE TITLE
Access runtime info within specs?

### ISSUE THREAD

**Issue by Portalboy** [rspec/rspec-core#2330]
It would be massively helpful for me to be able to access the runtimes for a given test from within the code (rather than having to look at a report generated by a special output format) because I want to do optimization tests. I want to have a test run multiple times, then average the time it took for all runs and store that average. That way, when running my suite after a code change, I can see if it negatively impacted performance at all.

Currently I can't find a way to call how long a test took from within code. The formatters are nice, and particularly I'm using the HTML format which shows runtimes, but I need some way to make code decisions based on those runtimes.

Is there any way to do this now? Are there plans to include this in the future? Where are the bees going?? Why does sub-par mean bad?!?!
But mostly those first two.

**Comment by myronmarston** [comment]
[`RSpec::Core::Example::ExecutionResult#run_time`](http://rspec.info/documentation/3.5/rspec-core/RSpec/Core/Example/ExecutionResult.html#run_time-instance_method) returns how long an example took to run.  You can access an example's execution result via [`RSpec::Core::Example#execution_result`](http://rspec.info/documentation/3.5/rspec-core/RSpec/Core/Example.html#execution_result-instance_method).  For example:

``` ruby
RSpec.describe SomeClass do
  it "does something" do
    # ...
  end

  after do |example|
    example.execution_result # => returns the execution result
  end
end
```

Note, however, that the `run_time` is not set until the example is finished, and RSpec considers an example's hooks to be part of the example (kinda like how a prologue and epilogue are part of a book), so `run_time` won't be set in any of the normal places where you can easily access an example (e.g. the example block itself or any of the hooks).  `run_time` will be set by the time a listener or formatter is notified of an example, though, so if that meets your purposes it should work.

If you need to access the run time in an `after` hook or similar, you can calculate the "run time so far" by subtracting [`started_at`](http://rspec.info/documentation/3.5/rspec-core/RSpec/Core/Example/ExecutionResult.html#started_at-instance_method) from the current time.

Let us know if that does not meet your needs!

**Comment by Portalboy** [comment]
Perhaps I don't understand what I'm talking about, but what about if I wanted to access an example's runtime from a higher example?
Something like this perhaps:

`
describe "timing test" do
  context "during the time-taking period" do
    it "does something that takes time" do
      #Stuff here
    end
end
  
  context "during the calculation period" do
    it "prints the runtime" do
      puts example.execution_result.run_time
    end
end
`
Would this work?

**Comment by JonRowe** [comment]
Tests deliberately don't have access to one another, but you could capture this data into your own structure and access it anywhere else, any other ordering other than `:defined` for your outer shared examples would be broken however. 

Might I suggest an alternative? There is part of the standard library that does this, (Benmark::IPS) you could wrap all your examples in benchmarking code rather than attempting to jury rig something out of our internals, you could then capture metrics from that rather than re-running tests.

```Ruby
require 'benchmark/ips'

module MeasureExamples
  around(:example) do |ex|
    Benchmark.ips { |x| x.report { ex.run } }
  end
end

RSpec.configuration.include MeasureExamples
```
What it sounds like you're trying to do
