### ISSUE TITLE
`method_missing': undefined local variable or method `"\u2028"

### ISSUE THREAD

**Issue by mattlindsey** [rspec/rspec-core#2348]
Following skeleton spec causes error in ruby-2.3.1 and rspec 3.5.4:
```
require 'rails_helper'
require 'spec_helper'

RSpec.describe "Redeemify API", type: :request do
  describe "GET /users/:user_id/redeemify_codes/:id" do
    it "returns the specified code" do
    end
   end
end
```

Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:732:in `method_missing': undefined local variable or method `"\u2028"' for #<Class:0x007f9bcad8f4b0> (NameError)
	from /Users/mattlindsey/Documents/github/redeemify/spec/requests/api_spec.rb:19:in `block (2 levels) in <top (required)>'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `subclass'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
	from /Users/mattlindsey/Documents/github/redeemify/spec/requests/api_spec.rb:5:in `block in <top (required)>'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `subclass'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
	from /Users/mattlindsey/Documents/github/redeemify/spec/requests/api_spec.rb:4:in `<top (required)>'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mattlindsey/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mrageh** [comment]
@mattlindsey can you please provide us with a skeleton Rails app where you can reproduce the issue, it will make it easier for us to fix this problem.

**Comment by mattlindsey** [comment]
@mrageh The spec works in a newly created rails app.  So must be something changed in my environment.
I'll continue to investigate.  You can close this issue if you want.  Thanks.

**Comment by mattlindsey** [comment]
@mrageh This issue can be closed.  I think it was an issue with my Mac installing xcode in the background.   Sorry for the false issue.
