### ISSUE TITLE
Shared Examples should raise error when included recursively

### ISSUE THREAD

**Issue by marko-avlijas** [rspec/rspec-core#2355]
I just spent a few minutes wondering why this doesn't work

    shared_examples_for 'test' do
      # tons of code

      include_examples_for 'test'
    end

This does nothing. It should raise an error with message something like `can't include shared examples recursively (hint: move include_examples 'test' out of block shared_examples_for 'test')`

**Comment by myronmarston** [comment]
Want to take a stab at it?
