### ISSUE TITLE
when_first_matching_example_defined runs multiple times

### ISSUE THREAD

**Issue by soulcutter** [rspec/rspec-core#2366]
```ruby
  config.when_first_matching_example_defined(type: :feature) do
    Rails.application.load_tasks
    Rake::Task["assets:precompile"].invoke
    @count = defined?(@count) ? @count + 1 : 1
    puts @count
  end
```

I tried throwing that into a `spec_helper.rb` in a rails project, and it ends up running that block 1053 times.

The cucumber example in RSpec documentation uses `require` and so you would never see if the block executed multiple times. FWIW when I changed the cuke to try to get it to run the block a few times, it doesn't. So it DOES work to only-run-once sometimes. 

I have yet to isolate a good test case for this (working on it). Some ideas:

* interaction with RSpec-defined metadata (this project had `config.infer_spec_type_from_file_location!`)
* interaction with some other library (`"rspec-its"`, `"rspec-collection_matchers"`,
`"rspec-instrumentation-matcher"`, `"rspec-activemodel-mocks"`) all used in this project.. really need to boil this down to the bare minimum
* having multiple hooks attached to a metadata key

**Comment by myronmarston** [comment]
The part of the implementation responsible for ensuring that the hook only fires once is here:

https://github.com/rspec/rspec-core/blob/98429a80a7187de797a9dcdc0ec84d38d0815af4/lib/rspec/core/configuration.rb#L1763-L1764

I don't have any good ideas for what's causing this.  Keep us posted, @soulcutter.

**Comment by soulcutter** [comment]
It's a product of `config.infer_spec_type_from_file_location!`

**Comment by myronmarston** [comment]
Interesting.  It's not clear to me how that could trigger the bug.  Can you come up with an isolated example (w/o rspec-rails) that re-implements `config.infer_spec_type_from_file_location!` (or something like it) that repros the bug?

**Comment by yujinakayama** [comment]
Fixed by https://github.com/rspec/rspec-core/pull/2400.
