### ISSUE TITLE
Make possible to suppress displaying pending (skipped) specs in RSpec

### ISSUE THREAD

**Issue by matkoniecz** [rspec/rspec-core#2384]
Displaying tests that are pending is cluttering output, without way to hide them.

According to my googling (leading among other to http://stackoverflow.com/questions/29906229/how-to-suppress-displaying-pending-skipped-specs-in-rspec) it seems currently impossible.

**Comment by JonRowe** [comment]
You can do this by implementing a formatter that doesn't display output for pending specs, see the documentation for custom formatters and #2377 for some background on this.

**Comment by krb-trustwave** [comment]
I agree that this would be extremely useful and it would be great if this were available out of the box. Other things I'd love to see are display of file and line for each test as it runs, and a timing of how long each test takes. I don't mean to be greedy, I realize that this is open source and rspec is already a great tool. I wish I had time to do this myself.
