### ISSUE TITLE
Recommended way to autoload classes required by specs?

### ISSUE THREAD

**Issue by timraasveld** [rspec/rspec-core#2391]
I'm writing a gem that allows Ruby developers to write a new type of test helper class. They should be able to write the test helper classes under the path:
```
spec/docker/my_helper_class.rb
```
To load these classes efficiently and not slow down testsuites, I believe it makes sense to autoload these classes.

Right now, I made a [Rails-dependent implementation](https://github.com/timraasveld/sidedock/blob/03bb55311c49770f1a5b3c9fd6c04d3331dc32ba/lib/sidedock/railtie.rb), but would prefer if the gem is usable for all Rspec users, also those who don't use Rails.

Is there a Rails way to achieve this? I couldn't find any reference to "autoload paths" or similar in the rspec-core source. Argumentation for eager loading everything is also welcome :)

**Comment by myronmarston** [comment]
> To load these classes efficiently and not slow down testsuites, I believe it makes sense to autoload these classes.

Why does it make sense for your gem to be responsible to load the user's code at all?  In standard Ruby, the norm is for users to `require` their code as needed.  That puts them in complete control, and the user can decide to eagerly load it up front (by requiring a bunch of `support/blah` files from `spec_helper.rb`) or by requiring files at the top of specs that use them (which is how I would generally do it).  RSpec puts the `spec` directory on the load path to make it easy to load files via `require 'support/my_helper.rb'`.

**Comment by timraasveld** [comment]
> Why does it make sense for your gem to be responsible to load the user's code at all? In standard Ruby, the norm is for users to require their code as needed. That puts them in complete control, and the user can decide to eagerly load it up front (by requiring a bunch of support/blah files from spec_helper.rb) or by requiring files at the top of specs that use them (which is how I would generally do it). RSpec puts the spec directory on the load path to make it easy to load files via require 'support/my_helper.rb'.

Thanks for your input. Yes, maybe the convention is different in the plain Ruby vs Rails world. I believe most Rails devs prefer if a gem defines the convention (like how rspec-rails loads your whole Rails environment by default), but this may be different because in plain Ruby if more control is desired.

More ideas are still welcome!

**Comment by JonRowe** [comment]
Closing as this is a request for advise.

My 2¢ would be to either use Rails autoloading, or get your users to define how they're code is loaded, don't forget Ruby offers an autoload implementation, with the caveat you have to define constants to paths to load, your gem could do this for your uses under a certain convention if desired, but I wouldn't recommend that due to the sorts of confusing issues that happen.
