### ISSUE TITLE
EOFError on calling ExampleGroup

### ISSUE THREAD

**Issue by felyppers** [rspec/rspec-core#2394]
I'm stucked with this issue almost a week, I am mobile tests on real devices locally without trouble. When I commit my changes to my repository and try to run the tests into another machine, I get the EOFError (end of file reached) on calling RSpec::Core::ExampleGroup. I double checked the Gemfile contents and executed bundle install.

I'm using rspec 3.5.0 and ruby 2.3.3. Please let me know if any further details are needed to aid me with this, I'm new in the community and do not know yet how to give proper details.

**Comment by myronmarston** [comment]
What do you mean by "calling `RSpec::Core::ExampleGroup`?    It's a class, not a method, and it's not clear what you mean.  Can you provide your spec file and and the stack trace?

**Comment by JonRowe** [comment]
@felyppers you'll need to provide the code thats causing you trouble. An EOFError normally means you have invalid code, e.g. you're missing an `end` or closing bracket somewhere.

**Comment by felyppers** [comment]
Hey guys, sorry for the lack of info. I dug a bit deeper into the problem and found out that the problem was with the path size of the solution. In my local machine the path was quite short, but remotely it was huge because of jenkins. OSX path length limit seems to be 104 chars and ruby reports this problem as an EOFError. Nothing to do with rspec, I'm sorry.

**Comment by myronmarston** [comment]
Glad you figured it out!
