### ISSUE TITLE
Feature Idea: option to display Example/Example Group IDs in output

### ISSUE THREAD

**Issue by gltarsa** [rspec/rspec-core#2395]
`rspec` has a useful feature that allows me to specify an example group or example by number using the `[#:#]` notation on the command line.  For a complicated or unknown spec file it can be challenging to determine what the proper example ID is.

This is a request for a `--format with-ids` or something similar that causes the Example Group and Example IDs to be part of the output.  This feature would make it possible to identify which tests had which ordinal IDs and would make the ability to run examples by ID more helpful.

The method that I believe is popularly used instead of this is manually tagging tests and using the `--tag` option to control what gets executed.  But the ID method holds the promise of being able to execute specific tests without having to modify code.

**Comment by myronmarston** [comment]
> The method that I believe is popularly used instead of this is manually tagging tests and using the --tag option to control what gets executed.

Personally, I tend to use a few different ways:

* By line number: `rspec spec/foo_spec.rb:16`.  I use a text editor plugin that, in a single keystroke, shells out and runs the spec under the cursor by appending the line number.
* By example description: `rspec spec/foo_spec.rb -e "some text"`
* By focusing: with `config.filter_run_when_matching :focus` set, I can prefix `it`, `describe`, `context`, etc. with an `f` (e.g. `fit`, `fdescribe`, `fcontext`) to easily focus on a particular example or group, or multiple examples or groups.
* By tag: as you mentioned, using `--tag` is possible but I rarely use it. I tend to only use it for permanent tags, to run a particular cross section of the specs.  E.g. `--tag db` to run all the spec that use the DB.

Have you tried all these options?  What do you find lacking about them that you want to use example ids instead?  FWIW, example ids were introduced in rspec 3.3 to support a few feature but weren't really intended for end users to type them at the command line.  Instead, they are used internally by `--bisect`, `--only-failures` and `--next-failure`.

As for your general suggestion: the id is available to any formatter that wants to include it in the output.  If you want to use example ids in your personal workflow, using a custom formatter is the way to go.  I don't believe the demand is sufficient to warrant us adding them a `--with-ids` option.  Believe me when I say that if we implemented every formatter option request we receive, the CLI would be huge and bloated.  If you write a custom formatter to include the ids and it sees lots of use from the community, we can consider including the feature in a future release.

**Comment by gltarsa** [comment]
Thanks for the information.  I will pursue a custom formatter.  There is no need to keep this open as far as I am concerned.
