### ISSUE TITLE
Custom rspec command on failure

### ISSUE THREAD

**Issue by jclif** [rspec/rspec-core#2397]
It'd be great to be able to customize the command that is displayed when a spec fails. For example, since I run rails within docker, I would use something like `docker-compose run --rm server rspec ./lib/my_spec.rb`, instead of `rspec ./lib/my_spec.rb`. It sounds like a small thing, but I spend a lot of time cycling through copy+paste+prepend.

**Comment by mikegee** [comment]
Not what you're asking for, but I use [guard](https://github.com/guard/guard) to streamline that workflow.

**Comment by xaviershay** [comment]
This is a pretty niche use case. I reckon it should be pretty straightforward with a custom formatter, so I'd start there: http://www.rubydoc.info/gems/rspec-core/RSpec/Core/Formatters
