### ISSUE TITLE
Feature idea: visible for testing

### ISSUE THREAD

**Issue by danielribeiro** [rspec/rspec-core#2403]
It would be great to have a helper that would, in a scoped and thread safe manner, make instance and class methods on a given subject visible for testing.

This allows easy clean up for series of `send` or `__send__`  calls being done.

**Comment by myronmarston** [comment]
It's not clear to me what you mean.  Can you provide an example?

**Comment by JonRowe** [comment]
@myronmarston I believe they are asking for introspection into private methods and instance variables, both of which would be test smells IMO. If you are testing those things @danielribeiro you are either constructing your tests in a way we'd advise against or have classes that are too large and should be broken down into smaller units :)

**Comment by myronmarston** [comment]
I agree with @JonRowe.  Tests that target public APIs are more effective.  If you have something private that you think warrants direct testing, it's a sign that it should probably be extracted into a new collaborator as its public API and directly tested there.

If you want to go against this advice, that's fine; programming is about tradeoffs and it's not always worth following such guidelines.  But I don't think RSpec should encourage it by including the feature you're asking for.

You should be able to build it as a separate gem, though.  It doesn't seem like something that needs to be integrated into RSpec, anyway--it can just be a stand-alone thing called from RSpec examples (or minitest tests or whatever) as needed.

Closing.
