### ISSUE TITLE
before(:each) is never executed sometimes

### ISSUE THREAD

**Issue by marko-avlijas** [rspec/rspec-core#2404]
I have this simple code

    require 'json'
    
    module Html
      class JsonHelper
        attr_accessor :path
    
        def initialize(path)
          @path = path
        end
    
        def add(data)
          old = JSON.parse(File.read(path))
          merged = old.merge(data)
          File.write(path, merged.to_json)
        end
      end
    end

and this spec (reduced as much as I could while still working)

    require 'html/helpers/json_helper'
    
    describe Html::JsonHelper do
      let(:path) { "/test/data.json" }
      subject { described_class.new(path) }
    
      describe "#add(data)" do
        before(:each) do
          allow(File).to receive(:write).with(path, anything) do |path, data|
            @saved_string = data
            @saved_json = JSON.parse(data)
          end
    
          subject.add(new_data)
        end
    
        let(:new_data) { { oldestIndex: 100 } }
        let(:old_data) { {"test" => 'testing', "old" => 50} }
    
        def stub_old_json
          allow(File).to receive(:read).with(path).and_return(@data_before.to_json)
        end
    
        context "when given data is not present" do
          before(:each) do
            puts "HERE"
            binding.pry
            @data_before = old_data
            stub_old_json
          end
    
          it "adds data" do
            expect(@saved_json).to include("oldestIndex" => 100)
          end
    
          it "doesn't change old data" do
            expect(@saved_json).to include(old_data)
          end
        end
      end
    end

`HERE` never gets printed and `binding.pry` doesn't stop execution and tests fail with message  
 `No such file or directory @ rb_sysopen - /test/data.json`

This all means that `before(:each)` never gets executed. 

I suspect it's got something to do with mixing let variables & instance variables.

**Comment by myronmarston** [comment]
`before` hooks get executed from the outside in--meaning that the one that stubs `File.write` gets run first, then the one with `puts "HERE"`.  It's failing while running the outer hook, so the example aborts before the inner hook gets a chance to run.  Specifically, the `subject.add(new_data)` line in the outer hook gets to the `old = JSON.parse(File.read(path))` line in `#add` and fails when trying to `File.read(path)` because no file at that path exists and you haven't stubbed `File.read` yet.

Does that make sense?

**Comment by marko-avlijas** [comment]
Thank you. Yes everything makes sense. I should have just left this on stackoverflow longer, but I got no responses, even comments so I thought it's a bug. And I kinda forgot I put `subject.add` in before block, that was experiment attempting to reduce size of specs which worked for first several specs.

Definitively not an rspec issue.
