### ISSUE TITLE
Feature Request: Intermittent Progress Update Event

### ISSUE THREAD

**Issue by jfelchner** [rspec/rspec-core#2410]
I've thought about this off and on for at least a few years and every time I do I just blow it off because it's not _that_ big of a deal, but I finally got to the point where I decided to ask. :)

You might know that I maintain fuubar.  There aren't really any more features that it needs, but one of the things that constantly bothers me is when you're in the middle of a spec that takes multiple seconds to run (say it has to hit the internet for something), the elapsed timer obviously doesn't update that entire time.  Even more importantly, the ETA timer doesn't either.

I would really like some sort of an event that the formatters could subscribe to that gets polled every second or few that I could use to do a simple refresh of the bar.  This would then update the timers and give the formatter much more of a "realtime" feel.

Thoughts?

**Comment by myronmarston** [comment]
As far as RSpec is concerned, individual specs are a black box, and while they are running it has no new information to report. Besides that, introducing extra logic to "tick" every second while a spec is running would have a perf effect on the spec (although, probably not easily noticeable) since MRI has the GIL--so if we introduce a thread to notify every second, the GIL's going to have to pause the thread the spec is running in while we notify formatters.  I don't think I want to introduce that extra overhead into RSpec for what is a niche use case.

However, I think you can implement this yourself in your formatter pretty easily.  Something like:

``` ruby
class Fuubar
  Formatters.register self, :example_started, :example_finished

  def example_started(notification)
    # ....your current logic...
    @current_example_thread = start_tick_thread
  end

  def example_finished(notification)
    @current_example_thread.kill
  end

  def example_ticked(notification)
    # this will be called once per second for any example
    # that takes longer than a second, so you can use it to
    # update whatever you want
  end

private

  def start_tick_thread(notification)
    Thread.new do
      loop do
        sleep(1)
        example_ticked(notification)
      end
    end
  end
end
```

(I just wrote that up and haven't tried running it or anything, but hopefully you get the point).

Will that work for you?

**Comment by jfelchner** [comment]
Dang @myronmarston you are _on it._ :)

Let me test this out. I'll close this for now and get back to you later. 

Thank you!

**Comment by myronmarston** [comment]
I'm curious to hear how this turns out!  Let us know, please.

BTW, I didn't include any sort of synchronization, but I believe you'll need that as once you introduce a 2nd thread operating on the formatter's internal state you're likely to have race conditions if you're not careful.

**Comment by jfelchner** [comment]
@myronmarston it's been a while but I finally got around to this. :)

Here's [the commit](https://github.com/thekompanee/fuubar/commit/cfae2e17fd025fe6780e8d0caa76245686f63493) with the code based on what you suggested.

It works great!  I'd love it if you (and maybe @JonRowe since he worked on the formatter stuff quite a bit?) could take a gander and make sure I didn't do anything dumb before I release it out into the wild.

Also I think I found a bug with the profile formatter but I'll submit that as a separate issue.

**Comment by jfelchner** [comment]
Additionally, it's released as `fuubar` version `2.3.0.beta1` if you want to try it live.

**Comment by myronmarston** [comment]
It looks reasonable.  I don't have any suggestions.

**Comment by myronmarston** [comment]
Actually, I do have one thought: spawning a thread per example seems kinda expensive.   Can it be refactored to spawn only one thread for the entire formatter?  Maybe you can find a way to re-use the same thread for each example.

**Comment by jfelchner** [comment]
I was thinking the same thing. If I did one one `start` and `finish` instead, that might work. Maybe?

**Comment by myronmarston** [comment]
I think that would work.

**Comment by jfelchner** [comment]
@myronmarston [it did!](https://github.com/thekompanee/fuubar/commit/66c774f71057b8b568acfc15af36bdc66134313c)  Seems to be working and about to release it.  Thanks again for the help!

**Comment by jfelchner** [comment]
Also, for what it's worth, there was zero noticeable performance impact. :) 👍

**Comment by JonRowe** [comment]
Looks fine to me!
