### ISSUE TITLE
Options file should append formatters when using cli formatters too

### ISSUE THREAD

**Issue by bobbytables** [rspec/rspec-core#2422]
Hi! I'm realizing that when using the CLI to do something like so:

```
$ rspec -f progress -O custom.rspec spec/
```

And `custom.rspec` has:

```
--format RSpecJunitFormatter --out 'tmp/rspec-results/<%= SecureRandom.hex(10) %>'
```

It actually will not append multiple formatters to the RSpec configuration. I find this odd because it's very possible to add multiple from the CLI doing `-f progress -f documentation --out docformat.txt` 

I found a spec that asserts that this behavior I'm describing is true, however it looks very old (several years):
https://github.com/rspec/rspec-core/blob/master/spec/rspec/core/configuration_options_spec.rb#L474-L478

Is there a reason to maintain this behavior? Why always prefer CLI instead of merging both options like the others?

The main reason why I could see to _not_ do this is if someone declares a `--formatter` in a global rspec config that does not exist in another project when they go to run the rspec CLI. While I can see this concern as a valid one, a person could just as easily hurt themselves since the Option parses will run the script through ERB first.

**Comment by JonRowe** [comment]
Closing in favour of discussion on #2423
