### ISSUE TITLE
Setting --example ignores any --tag parameters, which results in unexpected behavior

### ISSUE THREAD

**Issue by TikiTDO** [rspec/rspec-core#2426]
I want to use both --example and --tag to select a set of tests to run, such as in the following example:

Given the following spec:

```ruby
describe "example group" do
  it "tagged test", tagged: true do
    #...
  end

  it "untagged test" do
    #...
  end
end
```
Running: `rspec --example "example group" --tag tagged`

I would expect only `example group tagged test` to run, but for the above set of command line options `example group untagged test` also runs. In fact, the `--tag` parameter seems to be completely ignored if `--example` is provided, with no mention of it anywhere in the RSpec.configuration object.

This behavior is not mentioned in any documentation I could find.

**Comment by myronmarston** [comment]
As discussed in #2407, RSpec currently ORs multiple filters.  In this case, that means it runs any specs that have `"example group"` in their description OR are have `tagged: true` metadata.

We are discussing changing that in #2408.  However, there are concerns about it potentially being a breaking change.  Please join the discussion in #2408 if you have some thoughts on a way forward.
