### ISSUE TITLE
Code in `before(:all)` blocks execute in skipped tests

### ISSUE THREAD

**Issue by devonestes** [rspec/rspec-core#2436]
When I try and make an entire test pending using `xdescribe`, code that
is put in any `before(:all)` blocks are still executed. This seems to
me like it should not happen since I'm saying that I want to skip that
whole set of tests. In my eyes as a user, I wouldn't expect anything in
that block to execute if it's being skipped.

I think this is a bug, but I'm not 100% sure. At the very least, it
seems like surprising behavior as a user.

I have an example of this behavior here if you want to pull that branch down and check it out (or just tell me how I'm most likely using this feature wrong 😉 ): https://github.com/devonestes/rspec-core/blob/before-all-example/spec/rspec/core/pending_spec.rb

In that example, because everything is wrapped in an `xdescribe`
block, I would assume everything in that block wouldn't be executed.

**Comment by myronmarston** [comment]
Skipping `:all`/`:context` hooks when all the examples in a context are skipped would be good.  Want to take a stab at implementing that?

**Comment by devonestes** [comment]
Yeah, I'd be happy to give it a go. If I don't get this finished in the next week or two I might not get to it for like 2-3 months, though (👶 🔜), so I totally wouldn't mind if someone else tackles this!
