### ISSUE TITLE
Rubocop comment goes into docs

### ISSUE THREAD

**Issue by mvasin** [rspec/rspec-core#2440]
I've noticed [on rubydoc.info](http://www.rubydoc.info/gems/rspec-core/RSpec/Core/ExampleGroup) that comment aimed for Rubocop makes its way to documentation:

> rubocop:disable Metrics/ClassLength ExampleGroup and Example are the main structural elements of rspec-core. Consider this example:

Here's the comment itself:

https://github.com/rspec/rspec-core/blob/f27f6a107af7e9011c7801cb124eacc06e47b67a/lib/rspec/core/example_group.rb#L5

There should be a way to bypass parsing some comments, but google couldn't suggest me how.

**Comment by xaviershay** [comment]
Fixed with linked PR. Thanks!
