### ISSUE TITLE
Make aggregate_failures optional default behaviour

### ISSUE THREAD

**Issue by markburns** [rspec/rspec-core#2456]
I did a quick search of the docs and issues and don't think I saw anything supporting/asking for this, so apologies if this is a duplicate.

I love the aggregate_failures feature. I wonder if there have been any thoughts on making this a configurable default in the framework?

E.g.

```ruby
RSpec.configure do |c|
  c.always_use_aggregate_failures = true
end
```

Obviously I can implement on individual projects but doesn't it seem like a desirable thing to have in general?

**Comment by xaviershay** [comment]
Thanks for the suggestion, but there is already a way to do it! Per https://relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures

> RSpec::Core provides metadata integration for this feature. Each example that is tagged with :aggregate_failures will be wrapped in an aggregate_failures block. You can also use config.define_derived_metadata to apply this to every example automatically.

Example in this blog post: http://rspec.info/blog/2015/06/rspec-3-3-has-been-released/

**Comment by markburns** [comment]
Ah great thanks. Yeah I kind of misread that as a way to enable it it per example via metadata rather than setting the metadata globally
