### ISSUE TITLE
Configurable rerun command?

### ISSUE THREAD

**Issue by asterite** [rspec/rspec-core#2462]
Right now when there are spec failures you get a really nice and convenient section that you can copy and paste to rerun failed examples. For example:

```
Failed examples:

rspec ./spec/foo_spec.rb:4 # foo bar
```

In my case I'm running `rspec` inside a docker container and so I have a `scripts/test` wrapper to do that, which also forwards arguments to rspec. So, the above output is not that useful anymore because I have to copy it and replace "rspec" with "scripts/test".

Do you think it would be a nice thing to have an RSpec configuration to change that "rspec" string in that output? That way when there are failures I would get:

```
Failed examples:

scripts/test ./spec/foo_spec.rb:4 # foo bar
```

Maybe something like:

```ruby
RSpec.configure do |config|
  config.rerun_command = "scripts/test"
end
```

**Comment by myronmarston** [comment]
What you're asking for makes sense.  As it happens, we're already discussing supporting a config option for the format of the rerun command in #2119 (see [this comment](https://github.com/rspec/rspec-core/issues/2119#issuecomment-278573420) for an example...we'd want to expand that to allow users to override the `rspec` bit to `scripts/test` or whatever as well).  I'm going to close this so we can keep the conversation all in one place on that existing issue.  Feel free to comment there with any feedback you have.
