### ISSUE TITLE
expect(receiver).to receive(:method) prevents :method calling on the receiver

### ISSUE THREAD

**Issue by chumakoff** [rspec/rspec-core#2465]
rspec (3.2.0)
rspec-rails (3.2.3)
rails (~> 4.2.3)

I am testing a Rails application model custom validation method. In my test I want to make sure that the method has been called and has added validation errors.

```
    expect(user).to receive(:custom_validation_method)
    user.valid?               # should call :custom_validation_method
    expect(user.errors[:some_field]).to include("some_error")
```

The first expectation is successful. But in fact, it causes the `:custom_validation_method` not to be actually called. (I also checked this with `binding.pry`)

The second expectation fails, since `:custom_validation_method` is never really executed.

If I remove the first line (`expect(user).to receive(:custom_validation_method)`), the test is successful and `:custom_validation_method` is executed.

I understand that this problem can be easily solved by splitting this test to two:

```
it "executes the method" do
    expect(user).to receive(:custom_validation_method)
    user.valid?               # should call :custom_validation_method
end

it "adds error messages" do
    user.valid?
    expect(user.errors[:some_field]).to include("some_error")
end
```

But I think this issue should be fixed.

**Comment by mikegee** [comment]
Try:
```ruby
expect(user).to receive(:custom_validation_method).and_call_original
```

https://relishapp.com/rspec/rspec-mocks/v/3-6/docs/configuring-responses/calling-the-original-implementation

**Comment by chumakoff** [comment]
@mikegee Thanks. This makes things clear.
