### ISSUE TITLE
Accessing the let of a let inside of a let causes a segfault.

### ISSUE THREAD

**Issue by envygeeks** [rspec/rspec-core#2468]
I accidentally discovered this segfault by writing a spec wrong:

```
let :asset do
  asset.manifest.find("plugins/bootstrap").first.to_s
end
```

and then doing `asset` will cause a segfault.  I know this is not intended behavior but a segfault is a major bug.  I don't know if this is caused by Ruby indirectly but I know it was caused by the let syntax at the end of the day.

```
From: jekyll/jekyll-assets/spec/tests/lib/jekyll/assets/plugins/bootstrap_spec.rb :

     6: describe "Plugins/Bootstrap" do
     7:   let(:asset) { asset.manifest.find("plugins/bootstrap.css").first }
     8:   it "should require bootstrap" do
     9:     require"pry"
    10:     Pry.output = STDOUT
 => 11:     binding.pry
    12:     # expect(asset.to_s).not_to(be_empty)
    13:   end
    14: end

[1] pry(#<RSpec::ExampleGroups::PluginsBootstrap>)> asset
Segmentation fault (core dumped)
```

**Comment by myronmarston** [comment]
Given RSpec is pure ruby with no C extensions, this is a bug in Ruby, as pure ruby code should not be allowed by the interpreter to cause a segfault.  There's unfortunately nothing we can do about it, AFAIK.

You can speak up on the open ruby issue about this:

https://bugs.ruby-lang.org/issues/9505

**Comment by JonRowe** [comment]
The correct error Ruby should issue is `StackLevelTooDeep` fyi

**Comment by envygeeks** [comment]
I had assumed that. I just didn't know if RSpec had triggered something
that needed investigation, but it seems it's been known and unfixed for
quite a while.
