### ISSUE TITLE
Rspec::Core::Example::ExecutionResult has no status

### ISSUE THREAD

**Issue by EarlofLemongrab** [rspec/rspec-core#2473]
Hi I am trying to find a way to let Rspec fail fast on some given examples(test will abort when one of those tests fail, and won't execute the rest tests)

Now, I used this way 
after(:each) do |example|
if example.fail == true && example.is_the_target_example
exit(1)
end

However, I cannot find a way to check the result for a given example, I checked this official document http://www.rubydoc.info/gems/rspec-core/RSpec/Core/Example/ExecutionResult#status-instance_method But when I do example.execution_result.status, it returns nothing.
Here is the yaml format result for example.execution_result.to_yaml
```
--- "#<RSpec::Core::Example::ExecutionResult:0x00555a8887e550 @started_at=2017-11-01
  10:48:30 -0700>"
```

**Comment by myronmarston** [comment]
While `after` hooks are separate code blocks from the "main" example code block (e.g. an `it` block), they are still considered to be part of the example, and a failure in an `after` hook makes the example fail just like if there was a failure in an `it` block.  Therefore, the example is not yet complete when an `after` hook runs, so we haven't yet set the status.

If you need access to the result of each example, you're better off writing a custom formatter.  They get access the completely filled in example execution result.
