### ISSUE TITLE
Different behavior for Hash for single run versus suite run

### ISSUE THREAD

**Issue by phoenixfangor** [rspec/rspec-core#2483]
I am using tags to run a filter on my suite, attempting to set-up environment URLs, logins, etc. based on the tag selected.

Rspec is not running a called def inside of the describe statement when I run the suite/do not specify an *.rb file to run. The definition is inside of a describe statement in my spec_helper.rb file. 
I've included an expect statement, and said statement fails in this scenario.
i.e. `rspec -t env_q`

However, when I specify a file to run, it does run the definition and populate the Hash. Allowing the describe to pass.
i.e. `rspec -t env_q .\spec\test_spec.rb`

I would expect these two scenarios to have the same behavior.

```
describe 'Setting up environment from a tag' do
    it 'Is prod', env_prod: true do
        MyEnv = setupEnvironment('prod')
        expect(MyEnv).to have_key(:navPointURL)
      end
    it 'Is local', env_local: true do
        MyEnv = setupEnvironment('local')
        expect(MyEnv).to have_key(:navPointURL)
    end
    it 'Is Q', env_q: true do
      MyEnv = setupEnvironment('q')
      expect(MyEnv).to have_key(:navPointURL)
      PP.pp(MyEnv)
      # puts "setupEnviroment = " STDERR.puts
    end
    it 'Is Stage', env_stage: true do
      MyEnv = setupEnvironment('stage')
      expect(MyEnv).to have_key(:navPointURL)
    end
end

def setupEnvironment(envName)
    puts "def setupEnvironment() was called with #{envName}"
    if (envName == "local")
        tmpEnv = {
        navPointURL: "http://navpointq.conductix.net/"
        }
    elsif (envName == 'prod')
        tmpEnv= {
          navPointURL: "https://navpoint.conductix.net/"
          }
    elsif(envName == "stage")
          tmpEnv = {
           navPointURL: "http://navpoints.conductix.net/"
          }
    elsif (envName == "q")
          tmpEnv = {
          navPointURL: "http://navpointq.conductix.net/"
          }
    end
    return tmpEnv
end

**Comment by JonRowe** [comment]
I'm not quite sure what your question is, did you figure this out?

**Comment by phoenixfangor** [comment]
Thanks for your reply. I did figure this out; my suite had two functions with the same name. The second function overrode the other when all files/the whole suite was called.
