### ISSUE TITLE
Question: DEPRECATION WARNING: The behavior of `changed?`

### ISSUE THREAD

**Issue by wbotelhos** [rspec/rspec-core#2496]
First, thanks for this great gem @myronmarston . (:

I don't know where to ask, so hope this issue is not a noise. I couldn't find any thing about RSpec method, different of the `*changed?` code for my own.

I have this code:

```
expect { delete :destroy }.to change { User.count }

# or

expect { delete :destroy }.to change(User, :count)
```

It raises the following WARN:

```
DEPRECATION WARNING: The behavior of `changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes?` instead.
```

In other specs:

```
DEPRECATION WARNING: The behavior of `changed_attributes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.transform_values(&:first)` instead.
```

How can I solve this warn? Is there any other method instead of `change` for this? Should I just ignore and it will still works fine?

Thanks.

**Comment by myronmarston** [comment]
Those deprecation warnings are being issued by Rails (notice the "in the next version of Rails" bit), and they have no connection to RSpec's `change` matcher.  As this is a Rails issue, we're not able to provide support.  You can seek help from the Rails maintainers.

**Comment by chrise86** [comment]
@wbotelhos did you work out why you were getting this?

**Comment by wbotelhos** [comment]
No, I don't @chrise86 . I'm sorry.

**Comment by EtiNoked** [comment]
@wbotelhos, @chrise86 any luck getting rid of these warnings?
