### ISSUE TITLE
Do we need to fix errors with Ruby head?

### ISSUE THREAD

**Issue by benoittgt** [rspec/rspec-core#2499]
Hello

I just read https://github.com/rspec/rspec-core/pull/2497 and the related discussion on ruby's redmine https://bugs.ruby-lang.org/issues/14045.

Their is one comment from Martin Dürst : 
> For a core library such as RSpec, please test the betas and release candidates (yes we know they were late this time). Things will be easier for you if you find problems earlier.

So I went to #2497 build with ruby-head and saw many errors : 
https://travis-ci.org/rspec/rspec-core/jobs/323909016

Do we want to start fixing them or are we waiting for Ruby release candidate first?

**Comment by benoittgt** [comment]
I'm answering to my own issue. I think it's a bad idea. I will check RSpec against beta and release candidate when they will be released.

**Comment by JonRowe** [comment]
FYI we do normally check against release candidates as they become available, but the team was all busy at the time this year.

**Comment by benoittgt** [comment]
👍 
Will try to do it this year if team is busy.
