### ISSUE TITLE
Add a configuration option to continue on failure

### ISSUE THREAD

**Issue by Dbz** [rspec/rspec-core#2510]
Hello,

Would it be possible to add an option to continue on spec failure:

```
describe "nonblocking failures", continue_on_failure: true do
end
```

The specs with this flag will exit 0 even if they fail.

This allows for more flexibility to use rspec for writing tests that are used in production systems before doing certain actions.

It would also be interesting to allow something a little bit more complex:

```
describe "nonblocking failures", continue_on_failure: true if production? do
end
```

However, I don't think the above syntax currently works with the DSL.

I just found `pending` which does pretty much the same thing (except it fails on passing tests), so this could potentially be very easy to implement.

How do you feel about this feature request?

**Comment by myronmarston** [comment]
As you noted, we already have `pending`.  What is the use case for another similar feature like this?

**Comment by Dbz** [comment]
I have a bunch of tests that I would like to run as a prerequisite to other actions (e.g. on startup run these tests before saying you are healthy). On certain specs, I do not want failures to stop the entire  process.

I could say `at_exit { exit(0) }`, but then all specs exit with `0`, and important ones that fail do not stop the process. The way I'm currently getting around this is by moving specs that are nonblocking when failing to a new file and adding the `at_exit { exit(0) }`, but now I have very relevant specs split up between two files.

**Comment by myronmarston** [comment]
The normal way to prevent certain specs from affecting the exit status is to filter them (e.g. `rspec --tag '~excluded_tag'`) or to skip them with `skip` metadata.  For example, you could implement `continue_on_failure` metadata so that it automatically sets `skip` in certain environments:

``` ruby
RSpec.configure do |c|
  c.defined_derived_metadata(:continue_on_failure) do |meta|
    meta[:skip] = 'Not intended to be checked in prod'
  end if production?
end
```

Do those options meet your needs?

**Comment by Dbz** [comment]
Unfortunately, I tried this, but we actually need to run the specs.

1) The specs don't always fail because there could be systems that are booting up and just a bit slower
2) It is useful to run the specs, see the failures, and metric/report on them

**Comment by myronmarston** [comment]
My suggestion is to run `rspec` twice:

- On one run, exclude all the `continue_on_failure` specs
- On another run, run just the `continue_on_failure` specs (and ignore the exit status)

Example in bash:

``` shell
$ rspec --tag continue_on_failure; rspec --tag '~continue_on_failure'
```

**Comment by Dbz** [comment]
Thank you @myronmarston, that is a better solution than splitting the specs into multiple files, and I will implement it.

Do you see the use-case for this feature? (We want to use RSpec as a different type of live integration test / gateway than normal development testing).

Would you consider implementing it? I'd be happy to help plan out a more elegant way for users to implement this in their code. There is lots of language that could work from `dry_run` to `continue_on_failure`.

**Comment by myronmarston** [comment]
I think your use case is pretty non-standard; in all my years of using and maintaining RSpec, I've never wanted a way to run a spec and ignore whether or not it passes or fails, and I can't remember a user ever requesting it before.

Given that, I don't think it's something we'll be accepting into core at this point.  Every new feature included in RSpec adds to the effort it takes for us to maintain RSpec in the future, so our bar is pretty high at this point for new features.  You can implement it in an extension gem, though.  Let us know if RSpec doesn't easily support that and we can advise further.

**Comment by Dbz** [comment]
We don't want to ignore failures, we just want the specs to continue and exit 0 for specific specs. We will pay attention and log the results, so the failures are definitely not ignored.

However, I agree this is definitely non-standard.

Thank you for your time considering this feature, and keep up the great work!

**Comment by JonRowe** [comment]
You could achieve what you want with the tags and failure code status e.g:
```shell
$ rspec --tag '~continue_on_failure' && rspec --tag 'continue_on_failure' --failure-exit-code 0
```

**Comment by Dbz** [comment]
Thank you @JonRowe that'll also work
