### ISSUE TITLE
A question: why does RSpec core code use the EncodedString class?

### ISSUE THREAD

**Issue by vittorius** [rspec/rspec-core#2517]
When deals with exception backtraces. Was digging through the `RSpec::Core::Formatters::ExceptionPresenter` as became curious about that. Thanks. Also, I'm working on a custom errors formatted and wondering if I should use this class. I don't want to depend on `rspec-support` if I don't need to.

**Comment by xaviershay** [comment]
We still support a large variety of Rubies, back to 1.8.7 and some old JRuby versions. This class is needed to ensure consistent behaviour across them.

The specs give you a taste of the types of issues we've run into: https://github.com/rspec/rspec-support/blob/master/spec/rspec/support/encoded_string_spec.rb

If you want to release your custom formatters to the wild, then using `EncodedString` is probably the "right" thing to do, though many of the issues we've faced are pretty niche - we have so many users though that niche issues become common!

If you're just doing a formatter for yourself, then I probably wouldn't bother unless you're seeing encoding issues.

Hope that helps!

**Comment by vittorius** [comment]
Thanks for the detailed reply.
