### ISSUE TITLE
LoadError in configuration.rb

### ISSUE THREAD

**Issue by rosalinekarr** [rspec/rspec-core#2528]
I'm getting a LoadError on RSpec version 3.7.1 using Ruby 2.4.3

```
$ rspec spec/features
WARN: Unresolved specs during Gem::Specification.reset:
      tzinfo (~> 1.1)
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:986:in `require': cannot load such file -- rspec/core/example_status_persister (LoadError)
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:986:in `block in last_run_statuses'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:983:in `tap'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:983:in `last_run_statuses'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:209:in `initialize'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:164:in `new'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:164:in `notify_non_example_exception'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1957:in `rescue in load_spec_file_handling_errors'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1953:in `load_spec_file_handling_errors'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1496:in `block in load_spec_files'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1494:in `each'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1494:in `load_spec_files'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:100:in `setup'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/bin/rspec:23:in `load'
        from /Users/rosalinekarr/.rbenv/versions/2.4.3/bin/rspec:23:in `<main>'
```

My specific ruby version is...
```
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
```

RSpec version 3.7.0 works fine for me, so I'm guessing the issue is a recent change, and it looks like that file was just modified with this commit: https://github.com/rspec/rspec-core/commit/a26887b0783391e24ad5f9fe763319d307d0e153

Maybe the `block.__id__` trick creates unintended bugs on Ruby 2.4.3?

**Comment by myronmarston** [comment]
For some reason, `rspec/core/example_status_persister` isn't available to load in your environment.  I think either `/Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/` isn't being put on your `$LOAD_PATH` or the file is missing from `/Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_status_persister.rb` where it should exist.  Can you check to see if the file is there?  If it's not there, there's something screwed up with your gem installation and youu should uninstall and reinstall RSpec.  If the file is there, is suggests the rspec-core lib directory isn't on your `$LOAD_PATH`.  To see if that's happening, edit `/Users/rosalinekarr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb` and add `puts $LOAD_PATH.join("\n")` to the `last_run_statuses` method before the existing part of the method (e.g. `@last_run_statuses ||= ...`).  That should show you if RSpec is being put on the load path correctly.

**Comment by cdaz5** [comment]
@rosalinekarr did you figure this out?  Im having the same issue and i checked @myronmarston suggestions (file exists and is on load path) so not sure what is going on.

**Comment by benningm** [comment]
I have the same problem in a rails project. It works when using invoking the 'rake spec' task instead of 'rspec'. The ExampleStatusPersister is autoloaded. Maybe there is some ordering problem or some conflict with rails autoloading.

**Comment by JonRowe** [comment]
You can try a direct require to see if that fixes it, that would bypass the autoloading, or just check for the files presence.

**Comment by pirj** [comment]
Closing as there's no clear reproduction example.
Please feel free to reopen if it happens to you. Happy to address that.
