### ISSUE TITLE
Make output files / lines as links

### ISSUE THREAD

**Issue by alextakitani** [rspec/rspec-core#2536]
I repeatedly need to open a failed example on my editor, to fix it. 

So, I want to change the output on console to have link to a file and line on the editor. 

Better Errors gem has this option here:

https://github.com/charliesome/better_errors/wiki/Link-to-your-editor

This is an example of a failure:

7) Sign in user can sign in with valid credentials
     Failure/Error: visit new_user_session_path
     
     NameError:
       undefined local variable or method `new_user_session_path' for #<RSpec::ExampleGroups::SignIn:0x000000000b8fe8b8>
       Did you mean?  new_admin_user_session_path
                      admin_user_session_path
     # ./spec/support/helpers/session_helpers.rb:12:in `signin'
     # ./spec/features/users/sign_in_spec.rb:23:in `block (2 levels) in <top (required)>'

Can someone please point me to what I should customize to have this functionality ?

**Comment by xaviershay** [comment]
Take a look at [Custom Formatters](https://relishapp.com/rspec/rspec-core/docs/formatters/custom-formatters)

> The simplest way is to subclass RSpec's BaseTextFormatter, and then override just the methods that you want to modify.

From a quick scan, https://ieftimov.com/how-to-write-rspec-formatters-from-scratch looks like a pretty decent tutorial.

Good luck!
