### ISSUE TITLE
Feature idea: Add option to order "Failed Exemples" (SummaryNotification) by failed line number

### ISSUE THREAD

**Issue by Marinlemaignan** [rspec/rspec-core#2541]
Basically here's my thoughts, i've been working like a robot for the past few months fixing thousands of specs, one after another.. But i knew were i was going and wanted to work as fast as possible.
But i pretty quickly got annoyed by the fact that this summary would always display the failed exemples in the randomized order. I would have loved to just stupidly fix my file from top to bottom. Copying and pasting line numbers.

Therefore, i was thinking that this summary should display the failed exemples ordered by line number. So what do you think about adding an option allowing this behavior. And even better (imho) this should be the default behavior)

Here's what i mean:

```
Failed examples:

rspec ./spec/models/my_model_spec.rb:489 # ....
rspec ./spec/models/my_model_spec.rb:484 # ....
rspec ./spec/models/my_model_spec.rb:502 # ....
rspec ./spec/models/my_model_spec.rb:800 # ....
rspec ./spec/models/my_model_spec.rb:701 # ....
rspec ./spec/models/my_model_spec.rb:751 # ....
rspec ./spec/models/my_model_spec.rb:517 # ....
rspec ./spec/models/my_model_spec.rb:513 # ....
rspec ./spec/models/my_model_spec.rb:508 # ....
```

could become:

```
Failed examples:

rspec ./spec/models/my_model_spec.rb:484 # ....
rspec ./spec/models/my_model_spec.rb:489 # ....
rspec ./spec/models/my_model_spec.rb:502 # ....
rspec ./spec/models/my_model_spec.rb:508 # ....
rspec ./spec/models/my_model_spec.rb:513 # ....
rspec ./spec/models/my_model_spec.rb:517 # ....
rspec ./spec/models/my_model_spec.rb:701 # ....
rspec ./spec/models/my_model_spec.rb:751 # ....
rspec ./spec/models/my_model_spec.rb:800 # ....
```

ps: i couldn't find any issues on this topic so far, and i do apologize if this had already been discussed

**Comment by Marinlemaignan** [comment]
Thank you for this very quick reply, i will investigate this option and see if it fit my needs, and will come back to you asap! But anyways , couldn't that just be an option at least (this is just for the summary at the end).
And maybe while using this option it would say 
```
Failed examples (ordered by line number):
```

**Comment by myronmarston** [comment]
There is an option for this: `--formatter`.  A formatter picks how to display it's output, and can re-order the failure summary at the end as desired.  Anyone who wants this behavior can write a custom formatter to get this behavior.  An option directly in `RSpec.configure` doesn't really make sense with how RSpec's output was designed to work.  An option in `RSpec.configure` would only affect formatters which are written to support it, and would be ignored by other formatters.  In addition, if we added options for every feature request like this RSpec would have a ton of additional options, adding to the maintenance burden for the RSpec core team and adding to the number of options users have to wade through to find the options they care about.

If someone creates a custom formatter that implements this feature request, please post here so those who are interested are made aware of it.

**Comment by JonRowe** [comment]
`--order defined` would also do what you want

**Comment by Marinlemaignan** [comment]
Thank you very much !
