### ISSUE TITLE
NoMethodError 'fully_formatted'

### ISSUE THREAD

**Issue by mikeyduece** [rspec/rspec-core#2546]
### Subject of the issue
I am attempting to set up rspec to run only failures with `rspec --only-failures`. When I do this I get this error

```
 block in fully_formatted_failed_examples': undefined method 'fully_formatted' for #
 <RSpec::Core::Notifications::ExampleNotification:0x00007fce3766b108> (NoMethodError)
```

When I run `be rspec --only-failures` I get this error:

`bundler: failed to load command: rspec (/Users/mikeheft/.rbenv/versions/2.5.0/bin/rspec)`

I have `config.example_status_persistence_file_path = './spec/examples.txt'` set up in `spec_helper.rb`
The stacktrace says it's erroring on `/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:114:in 'block in fully_formatted_failed_examples'` with an undefinedmethod for `fully_formatted`

### Your environment
* Ruby version: 2.5.0
* rspec-core version: 3.7.1

### Steps to reproduce
Not sure of the steps to reproduce. I simply enter `rspec --only-failures` or  `bundle exec rspec --only-failures`

### Expected behavior
"0 examples, 0 failures"

### Actual behavior
One of two errors depending on what I enter into terminal.
With `bundle exec rspec --only-failures` I get :
`bundler: failed to load command: rspec (/Users/mikeheft/.rbenv/versions/2.5.0/bin/rspec)`
Along with 

```
 block in fully_formatted_failed_examples': undefined method 'fully_formatted' for #
 <RSpec::Core::Notifications::ExampleNotification:0x00007fce3766b108> (NoMethodError)
```

And when I just enter `rspec --only-failures` The error is: 
```
 block in fully_formatted_failed_examples': undefined method 'fully_formatted' for #
 <RSpec::Core::Notifications::ExampleNotification:0x00007fce3766b108> (NoMethodError)
```

**Comment by myronmarston** [comment]
Can you provide a full stacktrace?  It provides important context.

**Comment by mikeyduece** [comment]
```
Run options: include {:last_run_status=>"failed"}

All examples were filtered out

Randomized with seed 36778
must have 0 Critical Security Issues (FAILED - 1)

Coverage report generated for RSpec to /Users/mikeheft/turing/bread_shop/coverage. 174 / 249 LOC (69.88%) covered.
Traceback (most recent call last):
	18: from /Users/mikeheft/.rbenv/versions/2.5.0/bin/rspec:23:in `<main>'
	17: from /Users/mikeheft/.rbenv/versions/2.5.0/bin/rspec:23:in `load'
	16: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
	15: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	14: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	13: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
	12: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
	11: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
	10: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
	 9: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
	 8: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:175:in `block in finish'
	 7: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
	 6: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `each'
	 5: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:in `block in notify'
	 4: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
	 3: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
	 2: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each_with_index'
	 1: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each'
/Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples': undefined method `fully_formatted' for #<RSpec::Core::Notifications::ExampleNotification:0x00007f890cc37cc8> (NoMethodError)
```

**Comment by mikeyduece** [comment]
I have not edited the local installation of RSpec. I'm not sure how to put together an example for you to clone unless you clone the project that I'm working in. It seems to only error out when there are no errors. I was under the impression that if that were the case, that the response would be '0 examples, 0 failures'

**Comment by myronmarston** [comment]
>  I'm not sure how to put together an example for you to clone unless you clone the project that I'm working in.

For problems like this, I usually create an isolated, runnable example by doing something like:

1. Make a new branch.
2. Delete an arbitrary half the specs
3. Run the `rspec` command again and see if the same problem happens.  If the same problem happens, go back to step 2 and delete half the specs again.  If the problem goes away, it indicates that something in the half you deleted is causing the problem.  Switch which half you are keeping and which you are deleting, then run again the `rspec` command again to see if the problem happens again.
4. In this fashion, continue narrowing things down to the smallest set of specs you can that reproduce the example.
5. Do the same with your dependencies in your `Gemfile` (paring them down) and you `lib`/`app` code so that you get them down to a minimal set of dependencies and implementation code.
6. Create a new git repo with the minimal project you've created, and report here with instructions to clone and run the project.  (Or just paste a code snippet here if it can be repro'd with a single file of code).

Note that many times when I've gone through this exercise, the act of doing it has itself identified the source of the problem before I got things pared all the way down.  For example, if removing a particular gem makes the problem go away, it indicates that the gem was causing the problem, and you can either report that here or continue to look into it yourself.

**Comment by mikeyduece** [comment]
hey @myronmarston thanks for the insight! Sorry for the delayed response, been having a hectic month. It turns out it was my brakeman gem. I deleted all tests except one and the error still persisted. Then I started on the Gemfile and removed `gem brakeman`. Now I need to figure out how that was cause the `--only-failures` flag to cause the `fully_formatted` to give a no method error.

**Comment by JonRowe** [comment]
Thanks for the confirmation, closing for now as I don't think theres anything further RSpec can do to help here.
