### ISSUE TITLE
[feature request] Stricter shared_examples_for "previously defined" behavior

### ISSUE THREAD

**Issue by mallyvai** [rspec/rspec-core#2549]
### Subject of the issue

Currently, if you accidentally redefine a `shared_examples_for` example, you get something like this:

```
WARNING: Shared example group 'syncs to ZP with the EmployeeBenefitSyncer' has been previously defined at:
  /var/www/spec/services/benefits/hsa/hsa_employee_benefit_service_spec.rb:33
...and you are now defining it at:
/var/www/spec/services/subscription/processor_spec.rb:3
```

### Feature request

We have a pretty expansive codebase with hundreds of thousands of tests, and to reduce the possibility of errors, something that would be helpful for us (and I'm sure many other codebases) would be to enforce that these redefinitions are failures or errors, not warnings. Is there some existing setting for this? If not, I'm happy to take a swing at a patch that enables failure with an additional configuration option.

**Comment by benoittgt** [comment]
Hello @mallyvai 

It seems a big change to me to turn from a warning to failures/errors. Why warnings are not enough for you?

👋

**Comment by mallyvai** [comment]
Hi @benoittgt !

For clarification, I'm feature-requesting a _setting_ that allows `shared_examples_for` to fail in event of a conflict, instead of just a warning.

The reason for this is gradual pollution we've noticed over the course of iterating on a very large codebase (hundreds of thousands of lines) over the years.

When we run tests locally, we generally run individual tests in a small part of the code. This introduces no conflict. Our CI runs them all (many tens of thousands of tests) together, with multiple instances of identically-named `shared_examples_for`, but the warnings have been ignored since there's so much log output and the builds are all green.

As you know, the challenge with the failures is we could be accidentally introducing pollution without being aware of it. We think this sort of optional setting would help us make a more resilient RSpec test suite.

Best,
Vaibhav

**Comment by myronmarston** [comment]
I think this makes sense.  Feel free to open a PR, @mallyvai!

**Comment by JonRowe** [comment]
Yes this already exists, see https://www.rubydoc.info/github/rspec/rspec-core/RSpec/Core/Configuration#raise_on_warning=-instance_method
