### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by themaddoctor** [rspec/rspec-core#2556]
If I download the tarball, I should not have to do a git. I should have everything that I need to install the package. But no. Never for ruby gems. What a f**king hassle every ruby package is.

How do I install this thing from the tarball that I downloaded?

# git init
Initialized empty Git repository in /mnt/quadrupole/sources/misc/rspec-core-3.8.0/.git/
rspec-core-3.8.0 # rake build
rake aborted!
Bundler::GitError: The git source https://github.com/rspec/rspec.git is not yet checked out. Please run `bundle install` before trying to start your application
/mnt/quadrupole/sources/misc/rspec-core-3.8.0/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
rspec-core-3.8.0 # bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will
break this application for all non-root users on this machine.
Fetching https://github.com/rspec/rspec.git

Retrying `git clone 'https://github.com/rspec/rspec.git' "/usr/lib64/ruby/gems/2.1.0/cache/bundler/git/rspec-938802b745ce218e139a5579996be082ce5a66c3" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/rspec/rspec.git' "/usr/lib64/ruby/gems/2.1.0/cache/bundler/git/rspec-938802b745ce218e139a5579996be082ce5a66c3" --bare --no-hardlinks --quiet` in directory /mnt/quadrupole/sources/misc/rspec-core-3.8.0 has failed.
Retrying `git clone 'https://github.com/rspec/rspec.git' "/usr/lib64/ruby/gems/2.1.0/cache/bundler/git/rspec-938802b745ce218e139a5579996be082ce5a66c3" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/rspec/rspec.git' "/usr/lib64/ruby/gems/2.1.0/cache/bundler/git/rspec-938802b745ce218e139a5579996be082ce5a66c3" --bare --no-hardlinks --quiet` in directory /mnt/quadrupole/sources/misc/rspec-core-3.8.0 has failed.
Retrying `git clone 'https://github.com/rspec/rspec.git' "/usr/lib64/ruby/gems/2.1.0/cache/bundler/git/rspec-938802b745ce218e139a5579996be082ce5a66c3" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/rspec/rspec.git' "/usr/lib64/ruby/gems/2.1.0/cache/bundler/git/rspec-938802b745ce218e139a5579996be082ce5a66c3" --bare --no-hardlinks --quiet` in directory /mnt/quadrupole/sources/misc/rspec-core-3.8.0 has failed.
Git error: command `git clone 'https://github.com/rspec/rspec.git'
"/usr/lib64/ruby/gems/2.1.0/cache/bundler/git/rspec-938802b745ce218e139a5579996be082ce5a66c3" --bare
--no-hardlinks --quiet` in directory /mnt/quadrupole/sources/misc/rspec-core-3.8.0 has failed.

**Comment by myronmarston** [comment]
> If I download the tarball, I should not have to do a git.

What tarball are you referring to?  AFAIK, we don't distribute RSpec releases as a downloadable tarball.

The standard way to install rspec is _not_ to download a tarball.  As our [readme says](https://github.com/rspec/rspec-core#install), you can install RSpec using the `gem` command:

``` bash
$ gem install rspec
```

If you are trying to install it for a particular ruby project, the project is probably using [bundler](https://bundler.io/) and the recommended approach is to add `gem 'rspec', '~> 3.8'` to the `Gemfile`, and then run `bundle install`.

In both cases, you don't have to download a tarball or mess with `git` at all.

**Comment by themaddoctor** [comment]
What is the purpose of this file?:
https://github.com/rspec/rspec-core/archive/v3.8.0.tar.gz

**Comment by myronmarston** [comment]
Thanks for providing the link.  TBH, we've not quite sure what's responsible for generating those releases; we don't ever do anything when we cut a release to build the tarball or upload it to that page or anything.  I suspect that github generates that automatically when we tag a commit with a release version number.  Sorry if that's confusing, but I don't know how to disable it--and I'm not sure that we should.  While we don't recommend downloading the tarballs from that page as your way of installing RSpec, there are other use cases for those tarballs (such as folks who maintain the `rspec` package for linux distros).

**Comment by JonRowe** [comment]
FYI the way to "install" the tarball is to place it in a location of your choice and add `/your/path/of/choice/rspec-core/lib` to your Ruby path.
