### ISSUE TITLE
Rspec respond_to not functional with required keyword in call to new

### ISSUE THREAD

**Issue by liamelliott** [rspec/rspec-core#2561]
** Originially posted in rspec/rspec-expectations but a glance at the code looks like the issue is in rspec core instead **

I have some code using rspec version 3.8 that doesn't produce the result expected [at this link](https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/respond-to-matcher#specify-required-keywords). If I create another class method with the same keywords and behaviour, it works without any issues.

```
class Visit

  Facility = Struct.new(:code, :name) do
    def to_facility
      self
    end
  end

  attr_reader :facility, :start_date, :number_of_nights

  def initialize(facility:, start_date: nil, number_of_nights: 1)
    @facility = facility
    @start_date = start_date
    @number_of_nights = number_of_nights
  end

  def self.other(facility:, start_date: nil, number_of_nights: 1)
    @facility = facility
    @start_date = start_date
    @number_of_nights = number_of_nights
  end

end
```

```
describe Visit do

  describe ".initialize" do
    it "correctly responds to :new" do
      expect(described_class).to respond_to(:other).with_keywords(:facility) # Works!
      expect(described_class).to respond_to(:new).with_keywords(:facility) # Doesn't work!
    end
  end
end
```
This test fails with "expected Visit to respond to :new with keyword :facility," but I don't see how my usage is any different from the relishapp example docs (1 required and 2 other keyword arguments). Only in their case they're using plant(seed:, fertilizer: nil, water: 'daily).

**Comment by myronmarston** [comment]
Closing since this is in fact an rspec-expectations issue.

**Comment by myronmarston** [comment]
(I'll respond there).
