### ISSUE TITLE
Odd --pattern Behavior

### ISSUE THREAD

**Issue by jonmchan** [rspec/rspec-core#2562]
### - Odd --pattern Behavior

Rubymine by default appends the following pattern to the "all specs in spec folder" test run: ```--pattern **/*_spec.rb```. Lately, I've noticed the filtering is not working as expecting in running all tests, but only runs the specs in the parent folder. It no longer traverses to the subfolders to run all the specs. I change the pattern to ```'**{,/*/**}/*_spec.rb'``` and it works.

### Your environment
* Ruby version: 2.4.2
* rspec-core version:  3.8.0

### Steps to reproduce
``` bundle exec rspec spec  --pattern **/*_spec.rb```

### Expected behavior
It runs all specs in the spec folder and subfolders.

### Actual behavior
It only runs the specs directly in the spec folder.

If this is a rubymine issue and ```--pattern **/*_spec.rb``` is not valid, I'll be happy to report a bug there. The odd thing about it is that I have another project using the exact same pattern, yet it still works there.

**Comment by JonRowe** [comment]
Our default pattern is `'spec/**{,/*/**}/*_spec.rb'`, I believe to avoid this exact issue, I suggest you get them to use that.

**Comment by myronmarston** [comment]
Alternately, why does rubymine pass a `--pattern` at all?  The option is really only intended for use in non-standard setups where the project isn't following the normal naming pattern.

**Comment by jonmchan** [comment]
Bug created on rubymine bug tracker: https://youtrack.jetbrains.com/issue/RUBY-22484
