### ISSUE TITLE
Stubbing a base method, will erroneously stub a child method that overrides it when that child method is in a nested block

### ISSUE THREAD

**Issue by jcavalieri** [rspec/rspec-core#2563]
### Subject of the issue

Stubbing a base method, will erroneously stub a child method that overrides it when that child method is in a nested call in a block.

### Your environment
* Ruby version: ruby 2.4.4
* rspec-core version: 3.8.0

### Steps to reproduce

Working demo here:
https://github.com/jcavalieri/rspec_issue

Running `rspec ./program_spec.rb` shows the failing test that should succeed

### Expected behavior

Only the base implementation of the method `foo` should be stubbed.

### Actual behavior

The base implementation of `foo` is stubbed, however, the child implementation of `foo` when in a nested block is also being stubbed.

**Comment by JonRowe** [comment]
Closing as this isn't an rspec-core issue. Will reopen on rspec-mocks.
