### ISSUE TITLE
New failures after updating RSpec 2.4.1 to 3.8.0 via transpec 3.4.0

### ISSUE THREAD

**Issue by BanzaiMan** [rspec/rspec-core#2569]
### Subject of the issue

I'm trying to upgrade RSpec for https://github.com/travis-ci/travis-tasks.

I followed steps outlined in https://relishapp.com/rspec/docs/upgrade, but at step 11, I see new failures.

Before: [Pass with RSpec 2.14.1](https://travis-ci.org/travis-ci/travis-tasks/builds/430568659)
After: [Failure with RSpec 3.8.0](https://travis-ci.org/travis-ci/travis-tasks/builds/433834121)

I did not run the intermediate step after `transpec` on Travis CI, but locally it was green.

### Your environment
* Ruby version: 2.4.2
* rspec-core version: 3.8.0
* transpec 3.4.0 (See https://github.com/travis-ci/travis-tasks/commit/3615eaab21ed499f2ba65aafe82478a8c8cf7a4f)

### Steps to reproduce

```sh-session
$ git clone https://github.com/travis-ci/travis-tasks.git
$ cd travis-tasks
$ git checkout ha-rspec3
$ bundle install
$ bundle exec rspec  # the command run on Travis is slightly different, but is within the realm of log display differences
```

### Expected behavior

All specs converted by `transpec` should still pass with RSpec 3.8.0.

The diff: https://github.com/travis-ci/travis-tasks/compare/8306c53086ee85e944d34e58d1243c9ce9cd01d5...6ea89a5

### Actual behavior

Some new failures are observed. See https://travis-ci.org/travis-ci/travis-tasks/builds/433834121

**Comment by JonRowe** [comment]
:wave: Hiro! 

If you check your spec output you'll see it's because you have matchers incorrectly defined in your `spec_helper.rb`, I wonder if transpec has missed these, try running it directly against the `spec_helper.rb` file?

**Comment by BanzaiMan** [comment]
Hey, @JonRowe! Looks like I did miss a couple of those when I went through warnings after running `rspec` the second time. I've run `transpec` on `spec_helper.rb`, which fixed those, but the rest remains. See https://travis-ci.org/travis-ci/travis-tasks/builds/434071389.

**Comment by benoittgt** [comment]
Hello Hiro 😀

I hope everything is going well.

My surprise is more how the previous tests were passing. 😄 

For example in [task_spec](https://github.com/travis-ci/travis-tasks/blob/b1cfc42e2b28226d1a3e1a293e0447c179866eef/spec/addons/webhook/task_spec.rb#L118)

```ruby
# with master branch
p payload_from(env).keys.sort
# => ["author_email", "author_name", "base_commit", "branch", "build_url", "commit", "commit_id", "committed_at", "committer_email", "committer_name", "compare_url", "config", "duration", "finished_at", "head_commit", "id", "matrix", "message", "number", "pull_request", "pull_request_number", "pull_request_title", "repository", "result", "result_message", "started_at", "state", "status", "status_message", "tag", "type"]

p payload.keys.map(&:to_s).sort
# => ["build", "commit", "jobs", "owner", "pull_request", "repository", "request", "tag"]
payload_from(env).keys.sort.should == payload.keys.map(&:to_s).sort
```

It will even work with
```ruby
payload_from(env).keys.sort.should == 'RSPEC'
```

The problem with the previous tests on 2.14 is the tests don't return failure but stop at first failure. For example
```diff
--- a/spec/addons/webhook/task_spec.rb
+++ b/spec/addons/webhook/task_spec.rb
@@ -98,8 +98,11 @@ describe Travis::Addons::Webhook::Task do
     targets.each do |url|
       uri = URI.parse(url)
       http.post uri.path do |env|
+        puts "/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:101"
         env[:url].host.should == uri.host
+        puts "/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:103"
         env[:request_headers]['Authorization'].should == authorization_for(repo_slug, '123456')
+        puts 'never printed'
         payload_from(env).keys.sort.should == payload.keys.map(&:to_s).sort
         200
       end
```

Will output:
```
$ bundle exec rspec spec/addons/webhook/task_spec.rb:95
Run options: include {:locations=>{"./spec/addons/webhook/task_spec.rb"=>[95]}}
/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:101
/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:103
E task=webhook status=failed url=http://one.webhook.com/path
/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:101
/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:103
E task=webhook status=failed url=http://second.webhook.com/path
/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:101
/Users/bti/code/travis-tasks/spec/addons/webhook/task_spec.rb:103
E task=webhook status=failed url=http://user:password@three.webhook.com/path
E task=webhook failures=3 build=1 errors={"http://one.webhook.com/path"=>"expected: \"1dbf0e06b0b880c9143ef1823687eb3ab4a6b4a90f3a17b0a7cd840992405ea5\"\n     got: nil (using ==)", "http://second.webhook.com/path"=>"expected: \"1dbf0e06b0b880c9143ef1823687eb3ab4a6b4a90f3a17b0a7cd840992405ea5\"\n     got: nil (using ==)", "http://user:password@three.webhook.com/path"=>"expected: \"1dbf0e06b0b880c9143ef1823687eb3ab4a6b4a90f3a17b0a7cd840992405ea5\"\n     got: \"Basic dXNlcjpwYXNzd29yZA==\" (using ==)"}
```

As you can see `puts "never printed"` is never visible.

I don't think I need to dig into RSpec 2.x related behavior or issue. But in that case, the errors you have are relevant. 

I tried to look at it but it requires more knowledge of your app and is outside of the scope of this issue.

So I will close the issue for now, because it doesn't seem related to RSpec. But feel free Hiro to reopen it if you think we need to look at it.

**Comment by JonRowe** [comment]
Yes very weird, I've done a double check and the specs definitely should have failed on 2.14, 2.99 etc but don't as the error is bubbled up somewhere else. Theres some multi threaded stuff happening which makes me suspicious too. The 3.x. version of RSpec does do some exception stuff differently under the hood to aggregate failures, so maybe thats why is showing the failures that should actually happen?

**Comment by BanzaiMan** [comment]
Very curious, indeed. Thank you very much for taking the time to look into this. @benoittgt @JonRowe
