### ISSUE TITLE
--only-failures Runs More Than Failing Specs

### ISSUE THREAD

**Issue by jfelchner** [rspec/rspec-core#2599]
It seems as though when running with --only-failures, I'm getting more than just the failures to run.  This seems to be a regression as I've never had this issue before.  I wanted to see if anyone knew what the issue might be before I take the time to repo it.

The data in the file I'm saving the example run info to is correct.  There are like 4 failures and tons of `unknown` status.

### Your environment
* Ruby version: 2.5.1
* rspec-core version: 3.8.0

### Expected behavior
`--only-failures` runs only the failed examples.

### Actual behavior
`--only-failures` runs more than the failed examples.

**Comment by JonRowe** [comment]
The `--only-failures` flag has the affect of setting up an inclusion filter based on an example status of 'failed'. This can potentially interact with the other filters, so if you are manually including other types it will combine with them, this might be what is happening here and is "by design" if so.

**Comment by jfelchner** [comment]
@JonRowe thanks for the reply. As far as I know I am not, but how would I verify that?

**Comment by JonRowe** [comment]
You can see what RSpec prints out when running, it'll list the filters.

**Comment by JonRowe** [comment]
If you believe this is a genuine bug, we'll need a smallest possible reproducible repo (or a spec that will run in our suite), we don't have the resources to debug large open source projects or private repos, and we can't debug without further information in this case (We have tests for all of this behaviour naturally :)).

**Comment by jfelchner** [comment]
@JonRowe totally understandable :)

**Comment by jfelchner** [comment]
@JonRowe figured it out.  It wasn't an extra filter but it was my fault.  Sorry for wasting your time.

**Comment by JonRowe** [comment]
No worries! Sorry I couldn't be of much help!
