### ISSUE TITLE
Strict predicate matchers

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec-core#2605]
### Subject of the issue

It would be great to have a configuration for predicate matchers to be "strict" in the sense that they require the return result to be a boolean and not something that is truthy or falsey. It's easy for these methods to have values that creep their way to the client side in tricky to debug ways, so we try as much as possible in our codebase to enforce that they always return `true` or `false`. Right now we avoid the predicate matchers and instead use `expect(thing.there?).to be true`.

### Your environment
* Ruby version: 2.5
* rspec-core version: 3.8

### Steps to reproduce

```rb
class MyClass
  def there?
    'yep'
  end
end

it 'returns true' do
  expect(MyClass.new).to be_there
end
```

### Expected behavior
The above test fails because the method returns `'yep'` instead of `true`.

### Actual behavior
The above test passes.

**Comment by JonRowe** [comment]
Hi, `rspec-core` contains no matchers, so this was the wrong repo to suggest this, however its well documented that `rspec-expectations` predicate matchers obey Ruby's truthiness rules, and I'm not sure I want to change that. We have the option to be more precise as you've mentioned, so making our matchers ambiguous seems less than ideal.

Have you considered implementing your own custom matcher that does what you want?
