### ISSUE TITLE
adding a alias to examples for pry

### ISSUE THREAD

**Issue by rjrobinson** [rspec/rspec-core#2608]
### Subject of the issue

I'm looking to add some alias to easier invoke the binding.pry call to my tests. following along in the book "Effective Testing in RSpec 3" it states to add the following to my rspec config.

### Your environment
* Ruby version: 2.4.1
* rspec-core version: 3.x

### Steps to reproduce
added the following code to my `/rails_helper.rb`

```ruby
RSpec.configure do |config|
  config.alias_example_group_to :pdescribe, pry: true

  config.alias_example_to :pit, pry: true

  config.after(:example, pry: true) do |ex|
    require 'pry'
    binding.pry
  end
end
```

### Expected behavior
when calling alias `pit` i am hoping that a pry session opens up at the start of my example

### Actual behavior
binding.pry opens up in the config block. 

following along with 

[This book](https://books.google.com/books?id=8g5QDwAAQBAJ&pg=PT187&lpg=PT187&dq=config.alias_example_to+:pit,+pry:+true&source=bl&ots=R4Xh_4egmW&sig=ACfU3U1yQvbLyCgTu8dbDnIehXouW5neJA&hl=en&sa=X&ved=2ahUKEwjF8_yu8PDgAhWnzlkKHTdbDcsQ6AEwAXoECAkQAQ#v=onepage&q=config.alias_example_to%20%3Apit%2C%20pry%3A%20true&f=false)

**Comment by JonRowe** [comment]
Hi @rjrobinson, if you switch the `after` for a `before` it'll execute `binding.pry` before the example runs. Myron alludes to this in the book (by saying when the block will run). Don't be mislead by "seeing" the config file, you are in the context of the example.

Additionally Github issues are not the place to ask for support, our time is limited and we'd much appreciate it if you use our mailing list, or communities such as StackOverflow and other forums, and save Github for bug reports / feature requests etc.

**Comment by rjrobinson** [comment]
Ok. thanks.
