### ISSUE TITLE
Running examples by id does not work when examples are defined in a required file

### ISSUE THREAD

**Issue by p-mongo** [rspec/rspec-core#2613]
### Subject of the issue

In the MongoDB Ruby driver we have some tests which use a common runner on different data sets. Up to now the test definitions were copy pasted for each data set, which was not ideal. I decided to DRY up these definitions by creating a method which defined the tests. Unfortunately rspec seems to deal with this situation quite poorly.

I created a small project to demonstrate the issue: https://github.com/p-mongo/tests/tree/master/rspec-id. It has a file `spec/foo_spec.rb` which invokes `define_example` which itself is in `spec/bar.rb`. The `define_example` function calls `describe/it` to create the tests.

The first issue is it appears to be impossible to execute any of tests defined in this way by their id. If I run `rspec` (and thus the entire suite) I get:

<pre>
speed% rspec
FFF

Failures:

  1) foo bars
     Failure/Error: expect(1).to eq(2)
     
       expected: 2
            got: 1
     
       (compared using ==)
     # ./spec/bar.rb:4:in `block (2 levels) in define_example'

  2) foo bazzes 0
     Failure/Error: expect(1).to eq(3)
     
       expected: 3
            got: 1
     
       (compared using ==)
     # ./spec/bar.rb:9:in `block (3 levels) in define_example'

  3) foo bazzes 1
     Failure/Error: expect(1).to eq(3)
     
       expected: 3
            got: 1
     
       (compared using ==)
     # ./spec/bar.rb:9:in `block (3 levels) in define_example'

Finished in 0.00778 seconds (files took 0.05593 seconds to load)
3 examples, 3 failures

Failed examples:

rspec './spec/bar.rb[1:1]' # foo bars
rspec './spec/bar.rb[1:2]' # foo bazzes 0
rspec './spec/bar.rb[1:3]' # foo bazzes 1
</pre>

`rspec --help` says:

<pre>
    You can also pass example ids enclosed in square brackets:

      rspec path/to/a_spec.rb[1:5,1:6] # run the 5th and 6th examples/groups defined in the 1st group
</pre>

This does not work given the ids reported by rspec above:

<pre>
speed% rspec './spec/bar.rb[1:1]'
Run options: include {:ids=>{"./spec/bar.rb"=>["1:1"]}}

All examples were filtered out

Finished in 0.00012 seconds (files took 0.03192 seconds to load)
0 examples, 0 failures
</pre>

The second issue is the stack trace does not include `foo_spec.rb` at all. Running `rspec -b` I only get:

<pre>
...
     # /home/w/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /home/w/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/bar.rb:9:in `block (3 levels) in define_example'
     # /home/w/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # /home/w/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
     # /home/w/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
...
</pre>

Since the `define_example` method can be called from multiple files, thus defining different examples, only having `bar.rb` in the stack trace is insufficient to determine which file caused the failure.

### Your environment
* Ruby version: 2.6.1
* rspec-core version: 3.8.0

### Steps to reproduce

https://github.com/p-mongo/tests/tree/master/rspec-id

### Expected behavior
There should be a way to:

1. Run a test by its id, even if the test is defined in a file required from a spec file and not in a spec file itself.
2. See both the spec file and the file where the test is defined in the backtrace.

### Actual behavior

Neither of the above appears to be possible.

**Comment by JonRowe** [comment]
:wave: First off, have you checked out `https://relishapp.com/rspec/rspec-core/v/3-8/docs/example-groups/shared-examples` theres a whole bunch of things we do to allow that to programmatically define examples in a user friendly way. It may be a better interface for what you're doing that inventing your own from scratch.

Secondly, your example is fixed simply by wrapping `define_example` in a proper describe:

```
# spec/foo_spec.rb
require 'rspec'
require_relative './bar'

RSpec.describe do
  define_example
end
# =>
# rspec ./spec/foo_spec.rb[1:1:1] #  foo bars
# rspec ./spec/foo_spec.rb[1:1:2] #  foo bazzes 0
# rspec ./spec/foo_spec.rb[1:1:3] #  foo bazzes 1
```

Why? The RSpec DSL uses the file it was called from to define its top level name, and then the lower contexts are chained off that, so you need at minimum a proper describe in each spec file.

**Comment by JonRowe** [comment]
Also in future by minimum reproduction repo we mean a repo with just the issue at hand, not a massive repo full of tests, to avoid downloading large amounts of unnecessary files I had to manually download your two files, if it had been larger I wouldn't have bothered.

**Comment by p-mongo** [comment]
Thanks, putting a describe block around the method call works. I could not figure out where in the documentation this was stated.

**Comment by JonRowe** [comment]
It's not stated, but you're not doing something we support, I think there's
a public api for creating example groups with name, if not I'd accept a pr
making a way to create them programmatically rather than abusing the core
dsl

**Comment by p-mongo** [comment]
I'm afraid I don't exactly know what "creating example groups with name" means but here is an example of programmatically building the specs from external test definitions that we use:

https://github.com/mongodb/mongo-ruby-driver/blob/80eb6f0185172dbc5866c1318ddf2667a2b11b53/spec/support/crud.rb

**Comment by JonRowe** [comment]
Yes that is using our DSL outside of its intended use. As a forewarning it will break in RSpec 4 as we will remove the monkey patch versions at that time. You should at least use `RSpec.<method>` for top level methods.

**Comment by p-mongo** [comment]
If there is something else that we should be using to achieve equivalent results I am happy to investigate that, otherwise can you clarify if there is an action item that you are suggesting?

**Comment by JonRowe** [comment]
I'm saying at least use `RSpec.<method>` over `<method>` as the monkey patched main methods are definietly not designed fo this. You could also experiment with `RSpec::Core::ExampleGroup.new` rather than the DSL and register them yourself, but some of that will be private api. I'm open to adding something to support that if appropriate.

**Comment by p-mongo** [comment]
That change is easy enough to make, but can you clarify whether you are saying there is a difference between

<pre>
RSpec.describe do
# ...
end
</pre>

and

<pre>
describe do
# ...
end
</pre>

?

Another issue I ran into is I extracted a helper method to deal with requirements here: https://github.com/p-mongo/mongo-ruby-driver/blob/1792/spec/support/crud.rb#L187

This method defines a context, and this context is not showing up in my formatter output. I tried RSpec.context but got an error about that only being allowed at top level. Can I define contexts in separate methods and have them be included in RSpec output?

**Comment by JonRowe** [comment]
@p-mongo the difference is the first is using an rspec method on an rspec module, and is the preferred way to create specs. The second is a legacy mixin of RSpec into Ruby's main object which is only available when rspec mixes it in during a defined setup process. It is going away in RSpec 4.

Secondly you need to ensure that `context` is invoked within an existing `RSpec.describe` block.

All of this is ruby class semantics, the DSL you are mis-using is creating classes to invoke. Consider that in your usage.

Honestly I would prefer you instantiate `ExampleGroup` and `Examples` directly. If you find problems with those I'll happily fix issues to make those public APIs.

**Comment by p-mongo** [comment]
I did this: https://github.com/p-mongo/tests/blob/master/rspec-id/spec/context_fn_spec.rb

The output is on the bottom. The "nested fn with yield" describe produces the same output as "nested fn" describe, but there is an additional context "my yielding context" defined for the "nested fn with yield" case.

I looked at https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/dsl.rb to figure out what the DSL does and how to do it via ExampleGroup/Example but, sorry, I don't understand how to figure this out short of becoming an RSpec internals expert first.

**Comment by JonRowe** [comment]
> I did this: https://github.com/p-mongo/tests/blob/master/rspec-id/spec/context_fn_spec.rb

> The output is on the bottom. The "nested fn with yield" describe produces the same output as "nested fn" describe, but there is an additional context "my yielding context" defined for the "nested fn with yield" case.

If you look at the scoping during your blocks you'll see that the nested yield is resolving to the describe block, so the extra context is empty and skipped. Easily testable by adding an `it` directly between lines 26-27. (I checked the scope by using a simple `puts self`).

> What classes do describe and context map to?
`ExampleGroup`

May I suggest if you don't want to look at RSpec internals you use `shared_examples` to declare your examples rather than programmatically creating things?

**Comment by p-mongo** [comment]
Thanks, using instance_exec instead of yield produces the desired results.

Is there any sort of documentation or discussion available for the motivation behind the changes mentioned here for rspec 4? So far my impression is rspec 4 is going to remove functionality that exists in rspec 3 but I haven't seen the motivation for the change, or a suggested path forward for users relying on the functionality that is potentially getting removed.

**Comment by JonRowe** [comment]
> Is there any sort of documentation or discussion available for the motivation behind the changes mentioned here for rspec 4?

Sort of, this has been the plan since we re-wrote the API to be non monkey patching. The aim was always to eliminate monkey patching.

> So far my impression is rspec 4 is going to remove functionality that exists in rspec 3 

No functionality is being removed, a legacy API is being removed. This is the point of major version changes. 

> but I haven't seen the motivation for the change.

The motivation for the change is to completely eliminate monkey patching.

> or a suggested path forward for users relying on the functionality that is potentially getting removed.

Add `RSpec.` in front of monkey patched methods.
