### ISSUE TITLE
How to override the capybara's "find_available_port(host) into my spec_helper.rb

### ISSUE THREAD

**Issue by Tejareddy1** [rspec/rspec-core#2618]
Can you help me on the below query:

I want to override the capybara's "find_available_port(host)" in my spec_helper.rb, Is it possible?. If it is possible, how can I add it in my spec_helper.rb.
Actually, my requirement is that I want to provide different ports for different browsers where I am running the tests parallelly. I want to do as like below and the method has to pick automatically.

if ENV['TEST_ENV_NUMBER']
  class Capybara::Server
    def find_available_port
      @port = 9887 + ENV['TEST_ENV_NUMBER'].to_i
      @port += 1 while is_port_open?(@port) and not is_running_on_port?(@port)
    end
  end
end

The issue link is described well in the given below link:
https://github.com/grosser/parallel_tests/issues/691
 
Please guide me on this.

**Comment by benoittgt** [comment]
Hello @Tejareddy1 

I am sorry but this related to capybara https://github.com/teamcapybara/capybara/blob/f6b2f3adf061727ad72f71cabae1bd769015ae5c/lib/capybara/server.rb#L103 not RSpec.

Maybe you could open an issue on Github's Capybara?
