### ISSUE TITLE
Let! shadowing

### ISSUE THREAD

**Issue by danielwaterworth** [rspec/rspec-core#2620]
Here's the behaviour in question, this test fails.

```ruby
describe do
  let!(:foo) { 1 }

  context do
    let(:foo) { raise "boom" }

    it {}
  end
end
```

The inner `foo` overrides the outer `foo`'s behaviour, but it doesn't turn `foo` into a `let` from a `let!`. This isn't what I would expect although I understand why it happens.

**Comment by benoittgt** [comment]
What is your question?

**Comment by danielwaterworth** [comment]
@benoittgt, do you consider this a bug?

**Comment by benoittgt** [comment]
I don't see this as a bug. 😊

So I am closing the issue. We can re-open it if needed.

**Comment by mikegee** [comment]
I'd say the example code's behavior is somewhat surprising. One might expect `let`s and `let!`s to be completely independent and not interact with each other. Perhaps a documentation adjustment is warranted?

**Comment by benoittgt** [comment]
What do you think about it @JonRowe ?

**Comment by JonRowe** [comment]
From:  https://relishapp.com/rspec/rspec-core/v/3-8/docs/helper-methods/let-and-let

> Use let to define a memoized helper method. The value will be cached across
multiple calls in the same example but not across examples.
>
> Note that let is lazy-evaluated: it is not evaluated until the first time
the method it defines is invoked. You can use let! to force the method's
invocation before each example.

It should therefore be clear this is expected Ruby semantics for methods that have been defined.

If we add to this I think it should be in the form of adding a note to the second paragraph that `"This can not be undone and will apply to any future conflicting method definition"`. Or some such.

**Comment by JonRowe** [comment]
I'd also support highlighting the fact that methods are defined, maybe we just add `helper *method*`
