### ISSUE TITLE
Feature Request: print status messages within examples (documentation formatter)

### ISSUE THREAD

**Issue by joequincy** [rspec/rspec-core#2621]
#### Request Description
Add a method to print status messages nested below an Example's description, like:
```
Navigation Bar (describe)
  As an Admin (context)
    should show Admin navigation links (it)
      => in this place (step / status message)
      => in that place (step / status message)
```

#### Background
During a class project, my group found ourselves either 1) repeating complicated setup multiple times for different examples, or 2) including many expectations within a single example and accepting that the documentation formatter wouldn't provide detailed status output. We realized we'd like a way to include status (or "step") messages inline with the documentation formatter, so that the setup and interaction pattern could be completed once as we went through several expectations. I was able to monkey patch this in via a helper in `spec/support`.

#### The Monkey Patch
 - added a `step` method to `RSpec::Core::ExampleGroup`
 - added a `print_steps` method to `RSpec::Core::Formatters::DocumentationFormatter`, which was then added to the end of the `example_passed` and `example_failed` methods. (the `example_pending` method only appears to run when an example is skipped entirely, so no steps would ever be added to the metadata)
``` ruby
class RSpec::Core::ExampleGroup
  def step(message)
    metadata = current_example.metadata
    metadata[:steps] ||= []
    metadata[:steps] << message
    yield
  end

  private

  def current_example
    # Examples are added to each ExampleGroup at the time they are executed
    # so the "current" example will be the last one in the ExampleGroup.
    # Need to access from the current SubClass of the particular ExampleGroup
    # because that's where the Example inserts itself when it is initialized.
    self.class.examples.last
  end
end

class RSpec::Core::Formatters::DocumentationFormatter
  def example_passed(passed)
    output.puts passed_output(passed.example)
    print_steps(passed.example, :success)
  end

  def example_failed(failure)
    output.puts failure_output(failure.example)
    print_steps(failure.example, :failure)
  end

  private

  def print_steps(example, state)
    # The monkey patch doesn't have the ConsoleCodes constant initialized like
    # the core file, so for readability I assigned it to a variable on a
    # separate line.
    wrapper = RSpec::Core::Formatters::ConsoleCodes
    steps = example.metadata[:steps] || []
    last_step = steps.size - 1
    steps.each_with_index do |message, step|
      # Since execution of the Example block ends immediately at a failure,
      # print every step message as a :success (they must necessarily have
      # succeeded for us to have moved past them) until the last one, then print
      # the last one with the :success/:failed state of its parent Example.
      output.puts wrapper.wrap("  #{current_indentation}=> #{message}",
                               step < last_step ? :success : state)
    end
  end
end
```
(note: I intentionally formatted the output of step messages to be prefixed with '`=> `' due to personal preference. I am a student, and I hit a wall trying to understand how I could give it a default prefix of '` `' and accept an override at the `ExampleGroup`- and/or `step`-level with arguments passed to those methods in _spec files. Because of this, I hardcoded my preferred format. I would not expect a native implementation to match my formatting, if this feature is approved.)

#### Usage
Within an example, you can now call the `step` method, and pass it a block containing the code for that step.
``` ruby
describe 'Navigation Bar' do
  before(:each) do
    # some substantial setup
  end

  context 'As an Admin' do
    it 'should show Admin navigation links' do
      step 'in this place' do
        # expectations relevant to 'this place'
      end

      step 'in that place' do
        # expectations relevant to 'that place'
      end
    end
  end
end
```
When running RSpec with the documentation formatter, it will now print these messages as shown in the feature request above.
<details>
  <summary>Screenshot of console output</summary>
I threw in an intentional failure to demonstrate how this appears when a test fails. Since I got sidetracked by this very early in our project and it wasn't something we could include in the final submission, it's on an early branch where we have very little going on yet to test.
<img width="657" alt="Screen Shot 2019-04-29 at 11 41 29 PM" src="https://user-images.githubusercontent.com/3322920/56942519-6a468f00-6ad8-11e9-9980-ec1f55df9a35.png">
</details>

**Comment by benoittgt** [comment]
Hello @joequincy and thanks for your detailed feature request.

I understand what your are trying to do, but I am not completely convinced about how the tests will be written at the end. It looks like a breaking change on RSpec DSL. 🙂

I am wondering if your initial issues could be addressed differently.

> 1) repeating complicated setup multiple times for different examples
> 2) including many expectations within a single example and accepting that the documentation formatter wouldn't provide detailed status output.

For *1)* see below with a very classic example turned into shared examples.

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "~> 3"
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

RSpec.configure do |config|
  config.formatter = :documentation
end

RSpec.describe 'Navigation Bar' do
  context 'as an admin' do
    context 'in  place A' do
      it 'shows status bar' do
        expect(true).to eq(true)
      end
    end

    context 'in  place B' do
      it 'shows status bar' do
        expect(true).to eq(true)
      end
    end
  end
end

# with shared examples
RSpec.shared_examples "in place" do |place|
  context "in place #{place}" do
    it "shows status bar" do
      expect(true).to eq(true)
    end
  end
end

RSpec.describe 'Navigation Bar' do
  context 'as an admin' do
    include_examples "in place", "A"
    include_examples "in place", "B"
  end
end
```

<img width="477" alt="Capture d’écran 2019-04-30 à 09 54 46" src="https://user-images.githubusercontent.com/8417720/56947648-19fa1c00-6b2e-11e9-8859-736a5cc4e60e.png">

Did you thought about using [shared context](https://relishapp.com/rspec/rspec-core/v/3-8/docs/example-groups/shared-context) for repeated complicated setups?

For **2)** I don't think this is something we want to encourage but I prefer to see what @JonRowe think about it. 😊

**Comment by JonRowe** [comment]
Hi, this can be best addressed by building a custom formatter, if you take the existing format you like as a base (preferably by vendoring it within your code, extending from our classes is an unsupported API although it would work) and then adding an extra notification. You can then configure your code to send this new notification to any reporter that is registered to receive it and get the output you desire.

As this is fairly specific I'm going to close this for now, but I'm happy to help provide advice on how to build this for yourself, you could then choose to release it as a gem and if enough community support was for it we might consider it for inclusion into the core.

**Comment by joequincy** [comment]
Thank you both very much for the feedback.
@benoittgt I was not aware that functionality existed. If I understand correctly, I could then (within the `context 'as an admin'`) have a `before(:all)` block which would run the complicated setup a single time and maintain that state through each example just within the `context 'as an admin'`? That would make sense.

@JonRowe I do want to explore this path, as it wouldn't require a change to the core, but it solves the problem of how to easily include it in future projects (also, building a gem is something I already wanted to explore). Thank you for your offer of help! I'll see how far I get on my own first, but would it be all right to tag you in an issue on that project to seek (help if I completely hit a wall)?

**Comment by JonRowe** [comment]
You could also use custom matchers and aggregate failures to have messages for different step failures. Happy to be tagged in issues but beware there may be delays in replies!

**Comment by benoittgt** [comment]
@joequincy We tend to say to avoid using `before(:all)` because it creates sort of global state. On big test suite it can cause painful problems, hard to debug. You should make your test independent also don't try to make your test too DRY. :)

**Comment by mrgenixus** [comment]
I know this is from long ago (and far away) but I would really love to see this, if not as part of core rspec, as a gem plugin for it.  Bouncing this around the office, it could have a couple of variations (including subclassing the example group to provide a `context with: :multiple_steps` or having `it ... then_it` sets where `then_it` would run like an `after` hook. The whole thing is a little beyond my ken, or I think I would do it myself, given how long we have talked about this, particularly for feature, system, and request setups that for various reasons require large datasets/fixtures/setups that take a long time to run, or for bigger flows that document and capture bad emergent behavior in more complex use flows.

**Comment by pirj** [comment]
Given the open design of the formatter, I suggest anyone interested to write an RSpec extension as a grm that would introduce a custom formatter and the ‘step’ method.
