### ISSUE TITLE
How to get the example status in after (:suite)

### ISSUE THREAD

**Issue by Tejareddy1** [rspec/rspec-core#2626]
How to get the example status(faled/passed/skipped) in after (:suite).
I tried with custom formatters. but could not able to do it.  I want to use the example status in after (:suite). Please let me know how can I configure it

**Comment by pirj** [comment]
This should be available in a [custom formatter](https://relishapp.com/rspec/rspec-core/docs/formatters/custom-formatters) by defining `example_failed`/`example_passed`/`example_pending` methods. Can you please provide some example of your custom formatter?

**Comment by Tejareddy1** [comment]
This is my custom formatter, I am able to print the value in custom formatter as shown beow:
class StatusFormatter
        RSpec::Core::Formatters.register self, :example_passed, :example_pending, :example_failed
          def initialize(out)
            @out = out
          end
          def failedcount
            @out.length
          end
          def example_finished(notification)
            example = notification.example
            result = example.execution_result
            stat = result.status
            if stat === 'failed'
            p "status is #{stat}"
              @out<< stat
            end
          end
          alias example_passed example_finished
          alias example_pending example_finished
          alias example_failed example_finished
     end

RSpec.configure do |config|
  config.add_formatter StatusFormatter
.
.
.
.
etc
config.after(:suite) do
out=Array.new
  count= StatusFormatter.new(out).failedcount
    p "execution_result:#{count}"
end
end

Here I want the status and number of failures inside after(:suite) method. Please help me and let me know if still needed any details.

**Comment by pirj** [comment]
[Fromatter protocol docs](http://rspec.info/documentation/3.8/rspec-core/RSpec/Core/Formatters/Protocol.html) are pretty good, you may want to check them out.

Think of a formatter as something that accumulates data. Its methods are called when events happen, e.g. an example fails.
But since you only need counts, this is already provided by [SummaryNotification](http://rspec.info/documentation/3.8/rspec-core/RSpec/Core/Notifications/SummaryNotification.html) passed to formatter's [`dump_summary`](http://rspec.info/documentation/3.8/rspec-core/RSpec/Core/Formatters/Protocol.html#dump_summary-instance_method).

So, your formatter should look like:
```
class StatusFormatter
  RSpec::Core::Formatters.register self, :dump_summary

  def initialize(output)
    @output = output
  end

  def dump_summary(summary)
    @out << "failed: #{summary.failed_count}"
    @out << "pending: #{summary.pending_count}"
    @out << "total: #{summary.example_count}"
  end
end
```

You don't need a `config.after(:suite)` to output the results, but still need to add it:
```
config.add_formatter StatusFormatter
```

Hope that helps.

**Comment by Tejareddy1** [comment]
I am doing some activity in after(:suite) based on the failed count.so I
need it in after(:suite).please let me know how can I get formatter's
methods/ variables in my after(:suite)

**Comment by pirj** [comment]
Can you provide more details on what you are doing exactly in `after`?

**Comment by Tejareddy1** [comment]
Hi, I am trying to use headless gem where I am recording a video and saving
the video in after(:suite) if the failure happens otherwise do not save and
just discard the recorded video. So I required failed count in
after(:suite).

Headless gem: https://github.com/leonid-shevtsov/headless

$headless_server_video.stop_and_save("#{tests_to_run}.mp4")
where stop_and_save is a method in headless gem to save the video.

Let me know if you need any further information

**Comment by JonRowe** [comment]
You can do your `stop_and_save` in the formatters hook instead...

**Comment by benoittgt** [comment]
I don't think this is a rspec-core issue but some help to properly use a formatter. I think we can close the issue but keep having a discussion if need more help @Tejareddy1
