### ISSUE TITLE
non existing tag runs all tests

### ISSUE THREAD

**Issue by MarioRuiz** [rspec/rspec-core#2628]
### Subject of the issue
When running tests supplying a wrong tag, run all the tests:
`rspec . --tag nonexisting`

### Your environment
* Ruby version: 2.5.1
* rspec-core version: 3.8.0

**Comment by JonRowe** [comment]
Can you post your output and/or `.rspec` and `spec_helper.rb` files, as this is usually by design as there are options to control this behaviour

**Comment by MarioRuiz** [comment]
I found the problem, there was on rspec this config: config.run_all_when_everything_filtered = true
Thanks!
