### ISSUE TITLE
allow(object).to receive(:method) overwriting previous definitions on block syntax

### ISSUE THREAD

**Issue by Drowze** [rspec/rspec-core#2640]
### Subject of the issue
`allow(object).to receive(:method)` return value is overwriting previous definitions on block syntax, whilst working as intended on `expect(object).to receive(:method)` with its block syntax.

### Your environment
* Ruby version: 2.5.1
* rspec-core version: 3.8.0

### Steps to reproduce
allow an object to receive the same method two times using block syntax. The return value should be wrong

### Expected behavior
with expect instead of allow this does not happen. I understand that this is the expected behaviour (being able to assert for two calls to the said method)

### Actual behavior
The method's return value is always the one from the last allow call.

Script reproducing:
https://gist.github.com/Drowze/8b61a58bdb4e773af26319630357f713

**Comment by JonRowe** [comment]
:wave: I'm afraid the blocks being given to expect is to allow complex return values, so you are essentially doing:

```
expect(TestClass).to receive(:test_method).and_return('jonas')
expect(TestClass).to receive(:test_method).and_return('julio')
```

Which I hope explains why this is behaving as it is, and is to be expected.

The reason allow works is that `with` is designed to select different values. You need to use `with` in your expects to get the behaviour you want. Remember you can use complex argument matchers in with to help with this.
