### ISSUE TITLE
Can we send tags with regex to rspec --dry-run?

### ISSUE THREAD

**Issue by uppak** [rspec/rspec-core#2641]
Hi,

I have a requirement for my rspec tests. I have a bunch of tests in a folder tagged with different tags, but all these tags start with "FR_". Similarly I have some other tests in same which do not have this tag at all.

Is there way which I can find the tests which doesn't have these "FR_" tag with --dry-run or any command.

Regards,
Kalyan Uppalapati

**Comment by benoittgt** [comment]
Hello

I am [not sure](https://github.com/rspec/rspec-core/blob/b4af5c7ef75ee2194059e5dd6a7383718914e91a/lib/rspec/core/option_parser.rb#L240-L244) you can using `--tag` argument. You can negate tags usings `~` but in your case you need to regex tags.

If you want to run only the test without `FR_`tags you can do:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec"
end

require 'rspec/autorun'

RSpec.configure do |c|
  c.default_formatter = 'doc'
  c.filter_run_excluding lang: Proc.new { |value| value.match?(/FR/) }
end

RSpec.describe 'FR tagged', lang: 'FR_foo' do
  it 'fails but is filtered out' do
    expect(1).to eq(2)
  end
end

RSpec.describe 'RU tagged', lang: 'RU_foo' do
  it 'succeed' do
    expect(1).to eq(1)
  end
end

=begin
Run options: exclude {:lang=>#<Proc:rspec_tag_filtering.rb:17>}

RU tagged
  succeed

Finished in 0.00138 seconds (files took 0.14858 seconds to load)
1 example, 0 failures
=end

**Comment by uppak** [comment]
Thanks, will try this.
