### ISSUE TITLE
Ruby proposal for default bloc parameter with "it"

### ISSUE THREAD

**Issue by benoittgt** [rspec/rspec-core#2645]
Hello

A recent discussion was open on Ruby tracker for a proposal about a default block parameter. Even if the idea is good, the proposal is to have a default block parameter named `it`.

https://bugs.ruby-lang.org/issues/15897

As mentioned in  the discussion RSpec should not technically not be impacted.

jeremyevans0 (Jeremy Evans) wrote:
> mikegee (Michael Gee) wrote:
> > > RSpec won't break because their "it" requires an argument
> > 
> > Unfortunately this is not accurate. RSpec has a shorthand style like this:
> > 
> > `subject { fortytwo }
> > it { is_expected.to eq 42 }`
> 
> That's a block argument :).  In any case, the parser treats it differently as NODE_ITER/NODE_FCALL, not as NODE_VCALL:

I will try today (I am at CookPad Ruby Hack Challenge with you core Ruby members).

I don't think this is a good idea because it could lead to a lot of confusions.

**Comment by benoittgt** [comment]
I open the issue only to have a discussion.

**Comment by benoittgt** [comment]
I wrote a test in RSpec core test suite and run using ruby master with [an updated patch](https://bugs.ruby-lang.org/issues/15897#note-22).

`~/code/ruby_source_code/install/bin/bundle exec rspec spec/rspec/core_spec.rb`

```diff
--- a/spec/rspec/core/example_group_spec.rb
+++ b/spec/rspec/core/example_group_spec.rb
@@ -33,6 +33,10 @@ module RSpec::Core
       end
     end

+    it "does not blow with 'it' patch" do
+      expect([1, 2].map { it.to_s }).to eq(["1", "2"])
+    end
+
```

```
~/code/ruby_source_code/install/bin/bundle exec rspec spec/rspec/core/example_group_spec.rb --example patch       [15:57:56]
Run options: include {:full_description=>/patch/}

Randomized with seed 61921

RSpec::Core::ExampleGroup
  does not blow with 'it' patch

Finished in 0.00315 seconds (files took 0.28764 seconds to load)
1 example, 0 failures

Randomized with seed 61921
=end
```

It works. Same with all of the rspec-core test suite.

Curious about what do you think about this Ruby proposal @JonRowe.

**Comment by JonRowe** [comment]
Thanks for the heads up, I've left some feedback
