### ISSUE TITLE
Exclude examples specified by several values of the same tag

### ISSUE THREAD

**Issue by Onumis** [rspec/rspec-core#2653]
### Exclude examples specified by several values of the same tag

There should be the ability to do `rspec --tag ~type:model --tag ~type:controller` and have rspec understand it should `exclude {:type =>['model', 'controller']}`

### Your environment
* Ruby version: 2.5
* rspec-core version: 3.8

### Expected behavior
RSpec outputs `Run options: exclude {:type=>['model', 'controller']}`

### Actual behavior
RSpec outputs `Run options: exclude {:type=>"controller"}`

(The last flag overrides the previous ones)

**Comment by JonRowe** [comment]
This is a duplicate of #1622 the current behaviour has always been `AND` not `OR`, see discussion there and possible feature extensions.
