### ISSUE TITLE
Show line number of failing expectation

### ISSUE THREAD

**Issue by nakulpathak3** [rspec/rspec-core#2654]
```ruby
it 'should not do anything' do
  expect(did.length).to eq(1)
  do_something
  expect(did.length).to eq(1)
end
```

When this fails, I get 
```ruby
Failure/Error: expect(did.length).to eq(1)

       expected: 1
            got: 0

       (compared using ==)
```

Is there a way to know which `expect` failed? Maybe `do_something` did something it wasn't supposed to or my initial assumption is wrong. 

I'm curious if there's some `expect` failure line number option to save me the headache of trying to comment out expects and figuring out which failed. 

rspec-core 3.8.2
ruby 2.3.8p459

**Comment by JonRowe** [comment]
`--backtrace` will list the stack of the failure, but not prettily, as an aside I'd probably write your particular case as:

```
expect { do_something }.to_not change { did.length }
```

Which would tell you what went wrong

**Comment by nakulpathak3** [comment]
Thanks for the tip, I still think navigation would be easier if we provided the `expect` line number in the output somewhere (without backtrace). What do you think?

**Comment by JonRowe** [comment]
I'd take a look at any PR adding this for sure, don't have the time to look at it myself :)

**Comment by pirj** [comment]
I'd happily get rid of `--backtrace` if proper line numbers were shown (somehow I can't since it's there by default for me with no evidence in `.rspec` configs).

Would you like to take a stab at this @nakulpathak3 ?

**Comment by nakulpathak3** [comment]
Sure, happy to take a look and try and make a PR within the next couple
weeks. Let me know if that’s too long a wait though.

**Comment by pirj** [comment]
It's never too late! Thanks for taking care of this 👍

**Comment by alauddinu** [comment]
is this done ?

**Comment by pirj** [comment]
Apparently not.

**Comment by jesrodri** [comment]
can I work on this one?

**Comment by pirj** [comment]
Go for it, @jesrodri

**Comment by EduardoSCosta** [comment]
I was looking at this issue and it already show in the output the line where the expect failed, did I miss something? :monocle_face: 

```sh
Failures:

  1) Example when something does something
     Failure/Error: expect(my_number).to eq(1)
     
       expected: 1
            got: 2
     
       (compared using ==)
     # ./spec/lib/example_spec.rb:34:in `block (3 levels) in <top (required)>'
```

**Comment by pirj** [comment]
Fair enough. Thanks for bringing this up.
