### ISSUE TITLE
Pendings is not shown

### ISSUE THREAD

**Issue by BrazhnykYuriy** [rspec/rspec-core#2656]
### Subject of the issue
When hash `pending: true` is used all pendings are ignored, and 0 examples is shown
I'm not sure if my understanding of current pending logic is right but showing 0 examples is not right for sure.
Also 2.99 is showing 2 examples, 0 failures, 2 pending

### Your environment
* Ruby version: 2.3.6
* rspec-core version: 3.8.2

### Steps to reproduce
```
RSpec.describe "Should show 1 failed and 1 pending", pending: true do
  it "passes" do
    expect(1).to eq(1)
  end

  it "fails" do
    expect(1).to eq(0)
  end
end
```
or
```
RSpec.describe "Should show 1 failed and 1 pending" do
  it "passes", pending: true do
    expect(1).to eq(1)
  end

  it "fails", pending: true do
    expect(1).to eq(0)
  end
end
```
### Expected behavior
2 examples, 1 failures, 1 pending

### Actual behavior
0 examples, 0 failures

**Comment by JonRowe** [comment]
Pending changed its behaviour in RSpec 3. It expects examples to fail, and if they don't they "fail" as unexpected. You are looking for skip.

**Comment by JonRowe** [comment]
Sorry I misread this at first, I'll take a look, but I'm not entirely sure pending is supported as a metadata anymore, but then you'd have examples running.

**Comment by JonRowe** [comment]
Running either or both of your snippets on Ruby 2.6 work fine, I'm installing 2.3.6 to see if thats the issue, are you sure your files are being loaded?

**Comment by BrazhnykYuriy** [comment]
@JonRowe that may be an issue with my project, and i apologies for that.
Did you get any chance to see if that is reproduced on 2.3.6?

**Comment by benoittgt** [comment]
I have the behavior you expect on Ruby 2.3.6 and 2.6.3

```ruby
$ ruby pending_not_shown.rb                                                                           [16:47:30]
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 1.17.3
Using rspec-support 3.8.2 (was 3.6.0)
Using rspec-core 3.8.2 (was 3.6.0)
Using diff-lcs 1.3
Using rspec-expectations 3.8.4 (was 3.6.0)
Using rspec-mocks 3.8.1 (was 3.6.0)
Using rspec 3.8.0 (was 3.6.0)
Ruby version: 2.3.6
F*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Pending fails
     # No reason given
     Failure/Error: expect(1).to eq(0)

       expected: 0
            got: 1

       (compared using ==)
     # pending_not_shown.rb:23:in `block (2 levels) in <main>'

Failures:

  1) Pending passes FIXED
     Expected pending 'No reason given' to fail. No error was raised.
     # pending_not_shown.rb:18

Finished in 0.0144 seconds (files took 0.11705 seconds to load)
2 examples, 1 failure, 1 pending

Failed examples:

rspec pending_not_shown.rb:18 # Pending passes
```

I used this code

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec"
end

require 'rspec/autorun'

puts "Ruby version: #{RUBY_VERSION}"

RSpec.describe "Pending", pending: true do
  it "passes" do
    expect(1).to eq(1)
  end

  it "fails" do
    expect(1).to eq(0)
  end
end
```

**Comment by BrazhnykYuriy** [comment]
@benoittgt thank you for looking into this. Then this is something to do with my configuration or gems.

**Comment by BrazhnykYuriy** [comment]
Found the issue, someone added this seven years ago
```
RSpec.configure do |c|
  # declare an exclusion filter
  c.filter_run_excluding pending: true
end
```

But somehow this was not affecting the RSpec 2.99, but RSpec 3.8 took it seriously :)

**Comment by JonRowe** [comment]
I believe that was previously named differently in 2.99
