### ISSUE TITLE
How to run the same tests multiple times with different values?

### ISSUE THREAD

**Issue by elrayle** [rspec/rspec-core#2663]
### Subject of the issue
Suggestion for running multiple tests expressed in Issue #2078 does not work as I expected.  Should the method shown under Steps to reproduce work to run a test multiple times with different values? 

In my real tests, I am passing val to a class initializer that is setup in a let statement to test various conditions for the initializer parameters that should produce the same results.

### Your environment
* Ruby version: 2.5.5
* rspec-core version: 3.8.2

### Steps to reproduce

I tried to use the original suggestion by @myronmarston in Issue #2078 but it is not working as I had hoped.  Here is a simplified test following that pattern...

```
RSpec.describe "Dynamic tests" do
  [1, 2].each do |val|
    let(:my_val) { val }

    it "runs some test logic with #{val} expecting 1" do
      puts "Test: runs some test logic with #{val} expecting 1"
      puts "  val=#{val}"
      puts "  my_val=#{my_val}"
      expect(my_val).to eq 1
    end
    it "runs some test logic with #{val} expecting 2" do
      puts "Test: runs some test logic with #{val} expecting 2"
      puts "  val=#{val}"
      puts "  my_val=#{my_val}"
      expect(my_val).to eq 2
    end
  end
end
```

### Expected behavior
```
Test: runs some test logic with 2 expecting 1
  val=2
  my_val=2
F
Test: runs some test logic with 1 expecting 1
  val=1
  my_val=1
.
Test: runs some test logic with 2 expecting 2
  val=2
  my_val=2
.
Test: runs some test logic with 1 expecting 2
  val=1
  my_val=1
F
```

Note that my_val and val should always have the same value.

### Actual behavior
```
Test: runs some test logic with 2 expecting 1
  val=2
  my_val=2
F
Test: runs some test logic with 1 expecting 1
  val=1
  my_val=2
F
Test: runs some test logic with 2 expecting 2
  val=2
  my_val=2
.
Test: runs some test logic with 1 expecting 2
  val=1
  my_val=2
.
```

Note that my_val is NOT set based on the value of val.  It is always 2.

**Comment by elrayle** [comment]
I solved my own question.  In case someone else also runs into this, the solution is to wrap the let statement and all tests inside a context block...

```
RSpec.describe "Dynamic tests" do
  [1, 2].each do |val|
    context 'with multiple values' do
      let(:my_val) { val }

      it "runs some test logic with #{val} expecting 1" do
        puts "Test: runs some test logic with #{val} expecting 1"
        puts "  val=#{val}"
        puts "  my_val=#{my_val}"
        expect(my_val).to eq 1
      end
      it "runs some test logic with #{val} expecting 2" do
        puts "Test: runs some test logic with #{val} expecting 2"
        puts "  val=#{val}"
        puts "  my_val=#{my_val}"
        expect(my_val).to eq 2
      end
    end
  end
end
```

Now produces...
```
Test: runs some test logic with 1 expecting 2
  val=1
  my_val=1
F
Test: runs some test logic with 1 expecting 1
  val=1
  my_val=1
.
Test: runs some test logic with 2 expecting 1
  val=2
  my_val=2
F
Test: runs some test logic with 2 expecting 2
  val=2
  my_val=2
.
```

As you can see, val and my_val have the same value for all tests, which is what would be expected.

**Comment by jamesst20** [comment]
> I solved my own question. In case someone else also runs into this, the solution is to wrap the let statement and all tests inside a context block...
> 
> ```
> RSpec.describe "Dynamic tests" do
>   [1, 2].each do |val|
>     context 'with multiple values' do
>       let(:my_val) { val }
> 
>       it "runs some test logic with #{val} expecting 1" do
>         puts "Test: runs some test logic with #{val} expecting 1"
>         puts "  val=#{val}"
>         puts "  my_val=#{my_val}"
>         expect(my_val).to eq 1
>       end
>       it "runs some test logic with #{val} expecting 2" do
>         puts "Test: runs some test logic with #{val} expecting 2"
>         puts "  val=#{val}"
>         puts "  my_val=#{my_val}"
>         expect(my_val).to eq 2
>       end
>     end
>   end
> end
> ```
> 
> Now produces...
> 
> ```
> Test: runs some test logic with 1 expecting 2
>   val=1
>   my_val=1
> F
> Test: runs some test logic with 1 expecting 1
>   val=1
>   my_val=1
> .
> Test: runs some test logic with 2 expecting 1
>   val=2
>   my_val=2
> F
> Test: runs some test logic with 2 expecting 2
>   val=2
>   my_val=2
> .
> ```
> 
> As you can see, val and my_val have the same value for all tests, which is what would be expected.

Thanks! I had the same issue and the workaround fixed it

**Comment by pirj** [comment]
Just to clarify - it's not a workaround, it's just Ruby.

```ruby
  [1, 2].each do |val|
    let(:my_val) { val }
```
expands to:
```ruby
  let(:my_val) { 1 }
  let(:my_val) { 2 }
```
and the last one wins.

[Shared examples](https://relishapp.com/rspec/rspec-core/v/3-10/docs/example-groups/shared-examples) are usually a better solution.

**Comment by bellmyer** [comment]
> Just to clarify - it's not a workaround, it's just Ruby.
> 
> ```ruby
>   [1, 2].each do |val|
>     let(:my_val) { val }
> ```
> 
> expands to:
> 
> ```ruby
>   let(:my_val) { 1 }
>   let(:my_val) { 2 }
> ```
> 
> and the last one wins.
> 
> [Shared examples](https://relishapp.com/rspec/rspec-core/v/3-10/docs/example-groups/shared-examples) are usually a better solution.

This isn't exactly true. `[1, 2].each` is creating two separate context blocks, which unfortunately will have the same description when run. In the first context block, `my_val` will equal 1, and in the second, it will equal 2. That's why the tests are intermittently passing/failing.

**Comment by pirj** [comment]
> is creating two separate context 

Just `[1, 2].each { |i| let(:val) { i } }` doesn't.
But
```ruby
[1, 2].each do |i|
  context "when i is #{i}" do
    let(:val) { i }
    it { … }
```

does.
I personally prefer shared examples. And there’s a cop that will raise an offence if you define examples inside iterators (can’t recall if example groups, too).
