### ISSUE TITLE
Missing sourced VERSION constant causes rspec load failure

### ISSUE THREAD

**Issue by pointo1d** [rspec/rspec-core#2686]
Whilst 'playing' with a new Gem, I inadvertently commented out the declarations of both ```<Gem>::<VERSION>``` and also ```require <Gem>/version``` - which, when rspec was subsequently run against a gemspec file containing ```spec.version = <Gem>::VERSION```, the following output resulted ...
```$ rspec
Resolving dependencies...
Traceback (most recent call last):
	5: from /home/davep/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	4: from /home/davep/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	3: from /home/davep/.rvm/gems/ruby-2.5.1/bin/rspec:23:in `<main>'
	2: from /home/davep/.rvm/gems/ruby-2.5.1/bin/rspec:23:in `load'
	1: from /home/davep/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.9.1/exe/rspec:3:in `<top (required)>'
/home/davep/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.9.1/exe/rspec:3:in `require': cannot load such file -- rspec/core (LoadError)
```

Having discovered the cause, my expectation would be that the error would be handled more gracefully in as much as a ```<Gem>::VERSION not found```  error would be generated instead of the far less helpful error (see above) that did result

**Comment by JonRowe** [comment]
Hi, can you provide more detail, e.g. the command you used, the spec file(s) that caused this and the files loaded? Its rather non standard to direct rspec towards a gemspec so I'm also curious as to your goal here...

Transferred to `rspec-core` as this appears to be about `rspec-core`...

**Comment by pirj** [comment]
Please provide a reproduction example, or at least point at the gem you are playing with, and feel free to reopen.

**Comment by pointo1d** [comment]
Oops, my bad - I failed to notice that the screen capture wasn't as comprehensive as it should have been !!

I was merely trying to run the command ```$ rspec```, although it s/b noted that ```$ bundle exec rspec``` also failed in the exact same way until either the ```require``` or the constant definition in my source file under test was uncommented. Even more interestingly though, specifying the version as a string constant in the gemspec also caused the problem - irrespective of whether ```VERSION``` was defined in the source file.

The above was omitted from the original post and has now been included for completeness. I'm guessing it (the problem as reported) was down to the Gem I was developing as I can no longer reproduce the problem - which is, of itself, both a good and a bad thing :-((
