### ISSUE TITLE
avoid having rspec --only-failures affect coverage results

### ISSUE THREAD

**Issue by tansaku** [rspec/rspec-core#2694]
### Your environment
* Ruby version: 2.6.5
* rspec-core version: 3.9

### Steps to reproduce

Use simplecov with rspec and run rspec with --only-failures

### Expected behavior

Ideally coverage information would not be updated

### Actual behavior

Coverage information is updated, but I've worked around it with the following in spec_helper.rb

```rb
require 'simplecov' unless ARGV.include?('--only-failures')
```

but I wonder if there isn't a better solution - maybe on the part of the coverage gem? maybe a better way of detecting when we are running only failures?

**Comment by pirj** [comment]
The same applies when you run a limited number of specs, or when you focus on a specific example/example group.

Typical examples I've seen in the wild require `simplecov` conditionally:
```ruby
require 'simplecov' if ENV['COVERAGE']
```
and coverage runs reports are run and are later available on CI.

I suggest to somehow compare the total number of examples and the number of examples to run, and require `simplecov` when those two are equal.
I'm not sure how would you get a total number of examples in your project if you run it focused to say one file.

**Comment by JonRowe** [comment]
Coverage isn't a feature of rspec so its up to the coverage libraries to deal with this.
