### ISSUE TITLE
`when_first_matching_example_defined` runs when all matching examples are filtered out 

### ISSUE THREAD

**Issue by ojab** [rspec/rspec-core#2697]
### Your environment
* Ruby version: 2.5.7
* rspec-core version: 3.8.2

### Steps to reproduce
1.
```ruby
config.when_first_matching_example_defined(type: :feature) do
  require 'support/db'
end
```
2. Have an example with `type: :feature`
3. `bundle exec rspec -t ~type:feature`

### Expected behavior
`require 'support/db'` is not run

### Actual behavior
`require 'support/db'` is run

**Comment by JonRowe** [comment]
:wave: It's when the example is defined, not when its run. You've loaded the example and filtered it out, which is defined, but skipped.

**Comment by JonRowe** [comment]
Without knowing the contents of your `support/db` I can't help with much advice, but you can then add something else to be run when the first example runs to setup the db etc.

**Comment by pirj** [comment]
Hey Slava 👋 

I can suggest using a regular `before` hook with some trigger-once check:
```ruby
before(:example, type: :feature) do
  only_once { require 'support/db' }
end
```

**Comment by JonRowe** [comment]
Fun fact, `require 'support/db'` will only run once provided its the same path.

**Comment by pirj** [comment]
Agree, it's a bad example. A slightly better one:

```ruby
before(:example, type: :feature) do
  only_once { expensive_setup }
end
```

**Comment by ojab** [comment]
I knew had a clue that answer would be that, thanks anyway :)
