### ISSUE TITLE
ability to detect "focus" at the level of spec_helper

### ISSUE THREAD

**Issue by tansaku** [rspec/rspec-core#2698]
### Subject of the issue

I'd like to be able to adjust some high level behaviour (like the use of a particular coverage formatter) depending on whether a focus is being applied

### Your environment
* Ruby version: 2.6.5
* rspec-core version: 3.9

### Steps to reproduce

I want to be able to do something like this in spec_helper.rb

```rb
SimpleCov.formatter = SimpleCov::Formatter::Console unless RSpec.has_focus?
```

### Expected behavior

Description of what I'm trying to achieve here: https://github.com/chetan/simplecov-console/issues/14#issuecomment-586188300, but basically I'd like to be able to set a high level behaviour based on whether RSpec is running with a focus

### Actual behavior

I think the focus is not detected until we are actually inside a particular test run, so at the point the spec_helper.rb is being parsed we don't know that there will be a focus applied?  So the way to achieve what I want is to add something like the following to every individual test?

```rb
RSpec.after(:suite) do
  SimpleCov.formatter = SimpleCov::Formatter::Console unless has_focus?
end
```

even then I'm not sure how to programmatically detect whether RSpec has a focus, but I'd rather not have to alter every test file to achieve this effect, and wonder if there isn't some way to specify this sort of thing globally ...

Many thanks in advance for taking a look at this.

**Comment by JonRowe** [comment]
It is impossible to discover if focus has been applied until the entire spec suite is loaded. The closest you'd be able to get is:

```
RSpec.before(:suite) do
  SimpleCov.formatter = SimpleCov::Formatter::Console unless has_focus?
end
```

Although focus is nothing special other than metadata so theres no easy way to see if it has been set.

Something like this might achieve your goals however:

```
SimpleCov.formatter = SimpleCov::Formatter::Console
RSpec.configuration.when_first_matching_example_defined(focus: true) do
  # turn off coverage
  SimpleCov.formatter = nil # ?
end
```

Closing because I'm not sure theres anything we can do here, happy to continue conversation.

**Comment by tansaku** [comment]
excellent - just the input I needed - the following does exactly what I need:

```rb
SimpleCov.formatter = SimpleCov::Formatter::Console
RSpec.configuration.when_first_matching_example_defined(focus: true) do
  SimpleCov.formatter = SimpleCov::Formatter::SimpleFormatter
end
```

Thanks so much!
