### ISSUE TITLE
Using refinement is not possible inside of spec

### ISSUE THREAD

**Issue by manueljacob** [rspec/rspec-core#2699]
### Your environment
* Ruby version: 2.7.0p0
* rspec-core version: 3.9.1

### Steps to reproduce

```ruby
module Test
  refine String do
    def boom
      raise 'boom'
    end
  end
end

RSpec.describe 'foo' do
  it 'bar' do
    using Test
    expect{''.boom}.to raise_error 'boom'
  end
end
```

### Expected behavior

The spec passes.

### Actual behavior

```
  1) foo bar
     Failure/Error: using Test
     
     NoMethodError:
       undefined method `using' for #<RSpec::ExampleGroups::Foo "bar" (./refinement_spec.rb:10)>
     # ./refinement_spec.rb:11:in `block (2 levels) in <top (required)>'
```

**Comment by twalpole** [comment]
This is just the way refinements work in Ruby.  You can only specify `using` at file or module scope, not at method scope.  To use refintements in a test you'd need to do either

```
module Test
	refine String do
		def boom
			raise 'boom'
		end
	end
end

using Test  # file scope

RSpec.describe 'foo' do
	it 'bar' do
		expect{''.boom}.to raise_error 'boom'
	end
end
```

or

```
module Test
	refine String do
		def boom
			raise 'boom'
		end
	end
end

RSpec.describe 'foo' do
       using Test # module scope
	
        it 'bar' do
		expect{''.boom}.to raise_error 'boom'
	end
end
```

**Comment by JonRowe** [comment]
Closing because @twalpole has provided the answer, an `RSpec.describe` block generates a test class, whilst an example is an instance of that class, so you can only use refinements outside of the test.

**Comment by ecoologic** [comment]
Thank you ❤️ 

I took your example and re-wrote it following [Better Specs conventions](https://www.betterspecs.org/).

```ruby
module Test
  refine String do
    def boom
      raise 'boom'
    end
  end
end

RSpec.describe String do
  context "when Test refinements are used" do
    using Test

    describe '#boom' do
      it "raises an error" do
        expect { ''.boom }.to raise_error 'boom'
      end
    end
  end
end
```

**Comment by paddor** [comment]
`instance_double` and `instance_spy` don't seem to work with refined classes. My refinement adds a method to class `Xyz`, but when I `expect(xyz).to receive(:my_refinement_method)`, I get 

```
Failure/Error:
||                    expect(xyz).to receive(:my_refinement_method)
the Xyz class does not implement the instance method: my_refinement_method
```

I tried with `using MyRefinement` in the file scope, in the `describe`  block, as well as inside a `context` block. I guess it doesn't work because RSpec's code is in different files, where my refinement doesn't apply.

My current workaround is to use a `double`/`spy`.

**Comment by JonRowe** [comment]
Honestly thats probably the correct behaviour, when you use a refinement you don't create a permanent method, and the double doesn't know that method exists (else it would "just work" tm)
