### ISSUE TITLE
Ability to override argument of `shared_examples` with `let` inside block

### ISSUE THREAD

**Issue by AlexWayfer** [rspec/rspec-core#2702]
### Subject of the issue

It'd be nice to have an ability to override `shared_examples` variable via `let` inside a block.

It'd be useful when at most of cases you can provide literals like Integer, Boolean, etc., without explicit block and `let`, but for some cases you depends on `let` variables.

### Your environment
* Ruby version: 2.7
* rspec-core version: 3.9.1

### Steps to reproduce

```ruby
shared_examples 'it parses nil' do |expected_result = nil|
  let(:value) { nil }

  it do
    expect(subject).to eql(expected_result)
  end
end

let(:some_class) { Class.new }

it_behaves_like 'it parses nil', 42

it_behaves_like 'it parses nil' do
  let(:expected_result) { some_class.new }
end
```

### Expected behavior

`expected_result` is `42` for the first include and an instance of `some_class` for the second.

### Actual behavior

`expected_result` is `nil` for the second case.

#### Use `let` everywhere

Extra code.

```ruby
shared_examples 'it parses nil' do
  let(:value) { nil }

  it do
    expect(subject).to eql(expected_result)
  end
end

let(:some_class) { Class.new }

it_behaves_like 'it parses nil' do
  let(:expected_result) { 42 }
end

it_behaves_like 'it parses nil' do
  let(:expected_result) { some_class.new }
end
```

#### Use `Proc`

Unacceptable when `expected_result` can be instance of `Proc`

```ruby
shared_examples 'it parses nil' do |expected_result = nil|
  let(:value) { nil }

  it do
    if expected_result.is_a?(Proc)
      expected_result = instance_exec(&expected_result)
    end

    expect(subject).to eql(expected_result)
  end
end

let(:some_class) { Class.new }

it_behaves_like 'it parses nil', 42

it_behaves_like 'it parses nil', -> { some_class.new }
```

**Comment by pirj** [comment]
You should use `it_behaves_like` instead of `include_examples` in this case. There's [a slight difference](https://relishapp.com/rspec/rspec-core/v/3-9/docs/example-groups/shared-examples) in how they work.
Please feel free to reopen if it still doesn't work as you expect it it.

**Comment by AlexWayfer** [comment]
Thank you! My bad: I like `include_examples`, but in the problem code I'm already using `it_behaves_like`. So… issue is not resolved.

**Comment by pirj** [comment]
I see what you mean now. There's a way around it (it's mentioned in the same doc):

```ruby
RSpec.describe do
  shared_examples 'it is parameterizable in two different ways' do |param = 0|
    let(:param2) { param } # <= this is the key, notice param names are *different*

    it do
      STDOUT.puts "value: #{param.to_s} #{param2.to_s}"
    end
  end

  it_behaves_like 'it is parameterizable in two different ways', 42

  it_behaves_like 'it is parameterizable in two different ways' do
    let(:param2) { 24 }
  end
end
```

Its output:
```
value: 42 42
value: 0 24
```

Is this what you expect?

Again, please feel free to re-open and provide a runnable example of something that does not work as expected.

**Comment by JonRowe** [comment]
For reference, the problem with this:

```
shared_examples 'it parses nil' do |expected_result = nil|
  let(:value) { nil }

  it do
    expect(subject).to eql(expected_result)
  end
end

let(:some_class) { Class.new }

it_behaves_like 'it parses nil', 42

it_behaves_like 'it parses nil' do
  let(:expected_result) { some_class.new }
end
```

Is not your `let`, it's normal ruby precedence, no matter what we do the local variable in your block will take precedence in the parser.  (Although `value` is also never used...). The best way to achieve what you want based on your code is this:

```
shared_examples 'it parses nil' do |passed_in_expected_result = :__not_set|
  let(:expected_result) do
    passed_in_expected_result == :__not_set ? :default : passed_in_expected_result
  end

  it do
    expect(subject).to eql(expected_result)
  end
end

let(:some_class) { Class.new }

it_behaves_like 'it parses nil', 42

it_behaves_like 'it parses nil' do
  let(:expected_result) { some_class.new }
end
```

**Comment by AlexWayfer** [comment]
> Is this what you expect?

I don't lile `params2` (`paramsN`) syntax.

> Again, please feel free to re-open

I can't.

> and provide a runnable example of something that does not work as expected.

I've provided above. If you want a real-life one, here it's: https://github.com/AlexWayfer/formalism/blob/master/spec/formalism/form/coercion_spec.rb#L58

**Comment by AlexWayfer** [comment]
OK, it can be like `block_expected_result = nil` and `let(:expected_result) { block_expected_result }`. But I was talking about syntax-sugar and expected behavior, but as you wish.

**Comment by JonRowe** [comment]
> But I was talking about syntax-sugar and expected behavior, but as you wish.

This is Ruby precedence. A local block variable will always take precedence over a method. We can't fix it even if we wanted to.

**Comment by AlexWayfer** [comment]
> This is Ruby precedence. A local block variable will always take precedence over a method. We can't fix it even if we wanted to.

That's true, OK, thanks.
