### ISSUE TITLE
context with no block

### ISSUE THREAD

**Issue by taki** [rspec/rspec-core#2705]
### Subject of the issue

There is context with no block code. Test is passed when I execute RSpec.

Is it expected behaviour?

### Your environment
* Ruby version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
* rspec-core version: 3.9.1

### Steps to reproduce

Below is test code(array_spec.rb).

```ruby
RSpec.describe Array do
  describe '#empty?' do
    it { expect([].empty?).to eq true }

    context
  end
end
```

And, You execute `rspec array_spec.rb`.

### Expected behavior

I have not idea on it.

### Actual behavior

Test is passed.

**Comment by pirj** [comment]
You can do that. I believe it can even be a one with dynamically added examples with metadata processing.

**Comment by taki** [comment]
Thank you for reply.

**Comment by JonRowe** [comment]
A context with no block has no effect, we could issue a warning about this but in general it doesn't seem to have bothered anyone, and creating an example group without a block is useful if your an extension gem so my opinion is to leave it be.
