### ISSUE TITLE
Relish does not document before/after without scope

### ISSUE THREAD

**Issue by penelopezone** [rspec/rspec-core#2707]
The relish page for before and after documents how each of the scopes work, but not that `before { ... }` is `before(:each)`. We should document that

https://relishapp.com/rspec/rspec-core/v/3-9/docs/hooks/before-and-after-hooks#%60before%60/%60after%60-blocks-are-run-in-order

**Comment by JonRowe** [comment]
Thanks for reporting @penelopezone :)
