### ISSUE TITLE
How to override project configuration options without parameters?

### ISSUE THREAD

**Issue by lackovic** [rspec/rspec-core#2710]
`.rspec-local` allow individual developers to set options that override the common project options in `.rspec` (see [_Read command line configuration options from files_](https://relishapp.com/rspec/rspec-core/v/3-8/docs/configuration/read-command-line-configuration-options-from-files)).

It is clear how to add options and change options which accept arguments, but how do you disable/suppress common project options that don't accept any argument?

For example, given the following `.rspec`:
```
--backtrace
```

What should developers write in their `.rspec-local` to disable backtracing?

* Ruby version: 2.5.3
* rspec-core version: 3.8

Related issue: #599

**Comment by pirj** [comment]
Do you suggest a `--no-backtrace` option to override a project-level `--backtrace` just like `--no-color`/`--no-profile` do?
You may start [here](https://github.com/rspec/rspec-core/blob/dd3b2abe63b0dbd4c5c4131275a858d63cddab0e/lib/rspec/core/option_parser.rb#L133) and draw some inspiration [here](https://github.com/rspec/rspec-core/blob/dd3b2abe63b0dbd4c5c4131275a858d63cddab0e/lib/rspec/core/option_parser.rb#L150) for the start if you would like to tackle adding this option @lackovic. Some changes to docs and tests will come along, but worry not, we'll help you along the way.

**Comment by lackovic** [comment]
That seems like it will do! Thanks for the hints, I will gladly work on this as soon as I find the time.
