### ISSUE TITLE
Unable to access group metadata in before(:context) hook

### ISSUE THREAD

**Issue by legalosLOTR** [rspec/rspec-core#2728]
### Subject of the issue
I have a `before(:context)` hook and I want to get file_path of the group here but it throws
```
RSpec::Core::ExampleGroup::WrongScopeError metadata is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).
```

This doesn't make sense to me. Is there no way to get the file path in a `before(:context)` hook?

### Your environment
* Ruby version: 2.6
* rspec-core version: 3.9

### Steps to reproduce
```
before(:context) do |group|
  puts group.metadata[:file_path]
end
```

### Expected behavior
Should print the file path

### Actual behavior
Throws RSpec::Core::ExampleGroup::WrongScopeError

**Comment by pirj** [comment]
Why do you need the file path there?

```ruby
RSpec.context "some context" do
  path = metadata[:file_path]
  before do
    STDOUT.puts path
  end
  it {}
end
```
Would you agree to use such a workaround?

**Comment by legalosLOTR** [comment]
Thanks for the prompt response!

I'm basically building a gem that does some analysis on the groups and examples being executed (imagine recording their runtimes). So I don't have access to a user's spec files. I can only add my hooks in the `RSpec.configure` block.

**Comment by JonRowe** [comment]
This is a generic error raised when you call an API method that doesn't exist in your scope, RSpec `describe` / `context` methods define example group classes, with examples being instances of those classes, so you are attempting to call a class method than an instance method, and this is us catching that attempt and warning about the confusion.

You have several ways to progress from here, firstly, `file_path` should be directly accessible as a method, secondly `example_group` returns the class so you could use `example_group.metadata` although be aware that won't include the examples metadata, thirdly, you don't have to use hooks, you can also include / extend the class from config with `config.include Module` `config.extend Module` etc, which can in fact execute class level methods on eval (same as any include or extend).

**Comment by Alainx277** [comment]
Metadata can be accessed in a global hook like this:
```ruby
RSpec.configure do |config|
  config.before(:context) do
    value = self.class.metadata[:your_key]
  end
end
```
