### ISSUE TITLE
Contrary to documentation,`around` hooks runs before `before`

### ISSUE THREAD

**Issue by rahul342** [rspec/rspec-core#2729]
### Subject of the issue
Contrary to documentation,`around` hooks runs before `before`

Describe your issue here.
The docs here https://www.rubydoc.info/gems/rspec-core/RSpec%2FCore%2FHooks%3Aaround says -

> All around hooks execute immediately surrounding an example, this means that all before hooks will have run and no after hooks will have run yet.

### Your environment
* Ruby version: 2.7.1p83
* rspec-core version:  3.9.2

### Steps to reproduce
Here's the example I used
```
RSpec.configure do |config|
  config.before(:each) do
    puts 'before in configure'
  end
end

RSpec.describe "Order" do
  before(:each) do
    puts 'before in describe'
  end

  around do |t|
    puts 'around started'
    t.run
    puts 'around exiting'
  end

  it 'some example' do
  end
end
```

### Expected behavior
I would expect the prints in `before` to show before the prints in `around` since 
>  all before hooks will have run 

### Actual behavior
This is the output I get
```
around started
before in configure
before in describe
around exiting
```

**Comment by pirj** [comment]
Yep, it's quite the opposite of what https://relishapp.com/rspec/rspec-core/v/3-9/docs/hooks/around-hooks#per-example-hooks-are-wrapped-by-the-%60around%60-hook says.

Would you like to send a pull request with a fix?

**Comment by rahul342** [comment]
@pirj the example in your link is showing what happens. Do you mean we should fix the doc or correct the behavior? Intuitively I would expect `before` to run before `around`. Worry is it might be a breaking change if users have been relying on the current behavior. 
Not familiar with the codebase, but can take a stab if you think we should change it.

**Comment by JonRowe** [comment]
Fix the ruby doc (its just a comment), the cucumber scenario shows the correct order.

**Comment by ikesyo** [comment]
Looks like the behavior was discussed in #2544 and the document was updated in #2661, but the description adeed is wrong (contrary).
