### ISSUE TITLE
Proc-based if: metadata filters are reversed

### ISSUE THREAD

**Issue by CodingAnarchy** [rspec/rspec-core#2734]
### Subject of the issue

When applying an `if:` metadata filter that involves a `lambda` or `proc` executing, the expected result is reversed.

### Your environment
* Ruby version: 2.6.4
* rspec-core version: 3.8.2

### Steps to reproduce

```ruby
describe Foo do
    describe "#bar" do
      [0..4].each do |x|
        it "runs this example when x is even", if: x % 2 == 0 do
          # runs as expected when x is even
        end

       it "runs this example when x is even", if: -> { x % 2 == 0 } do
         # UNEXPECTED: THIS RUNS WHEN X IS ODD
       end
     end
   end
end
```

### Expected behavior

Using a proc as a metadata filter for `if:` should run when it evaluates as true.

### Actual behavior

Metadata filters for `if:` run when the proc evaluates as `false`.

**Comment by JonRowe** [comment]
This is to be expected. `if:` and `unless:` take booleans. A proc is a truthy value so it is `true` as far as `if:` or `unless:` is concerned.

Modifying your example slightly so it runs:
```
RSpec.describe "Foo" do
  describe "#bar" do
    (0..4).each do |x|
      it "runs this example when #{x} is even", if: x % 2 == 0 do
        # runs as expected when x is even
      end

      it "runs this example when #{x} is even", if: -> { x % 2 == 0 } do
        # UNEXPECTED: THIS RUNS WHEN X IS ODD
      end
    end
  end
end
```

With the command `rspec --format doc file` so you can see whats going on:
```
Foo
  #bar
    runs this example when 0 is even
    runs this example when 0 is even
    runs this example when 1 is even
    runs this example when 2 is even
    runs this example when 2 is even
    runs this example when 3 is even
    runs this example when 4 is even
    runs this example when 4 is even
```

**Comment by CodingAnarchy** [comment]
@JonRowe I understand that it is to be expected as currently designed, but I don't see why I should not expect the metadata filter to have a more dynamic capability here.

Would it be that complicated to allow it to evaluate a `proc` or accept a boolean? Why shouldn't that be a reasonable expectation?

**Comment by JonRowe** [comment]
My apologies your issue was worded as bug report and not a feature request :)

If you'd like to take a go at implementing this feature I'd happily take a look to what the implications are, but this isn't something we have on our roadmap.

**Comment by JonRowe** [comment]
Particularly "Proc-based if: metadata filters are reversed" is not correct, they are considered truthy, thats not reversed.

**Comment by CodingAnarchy** [comment]
Yeah, sorry about the wording. I will look into what needs to be done to enable this support.
