### ISSUE TITLE
Add a `summary` formatter alias to `base_text_formatter`

### ISSUE THREAD

**Issue by eloyesp** [rspec/rspec-core#2738]
I run specs using foreman, and the progress meter blocks the output, I found a way to fix it using the BaseTextFormatter (that is the progress format without progress). The only issue I found is that using it requires me to add `--format RSpec::Core::Formatters::BaseTextFormatter` on the procfile.

I think that the `base_text_formatter` is actually quite good on its own and can be aliased to `summary` in [`built_in_formatter`](https://github.com/rspec/rspec-core/blob/ceecf78ccc338c5e1248871c4956ac8717b2b5fb/lib/rspec/core/formatters.rb#L205 ).

**Comment by pirj** [comment]
Hey!

I'm having a hard time understanding why would you run specs from Foreman. As far as I remember it shuts down when one of the processes exits.

What is the problem with adding `--format RSpec::Core::Formatters::BaseTextFormatter` to the `Procfile` (or `.rspec`, or `.rspec-local`)?

Even if we add an alias for it, how would it solve your issue? The default formatter won't change, and you will still have to specify `--format summary` in `Procfile`/`.rspec`.

Side note and self-ad: If you happen to use tmux, you may consider using [`overmind`](https://github.com/DarthSim/overmind) or [`toreman`](https://github.com/pirj/toreman) instead and stop worrying about interleaved output.

**Comment by JonRowe** [comment]
:wave: Thanks for taking the time to suggest this, however the `BaseTextFormatter` is not designed for direct usage, and having a formatter that doesn't output anything during spec runs means there is no way of detecting if your spec run is running or not, so its not something we wish to encourage, you are welcome to use it with its current name as its part of the public api, but I don't wish to add an alias.
