### ISSUE TITLE
install with --user is not providing rspec command

### ISSUE THREAD

**Issue by matkoniecz** [rspec/rspec-core#2751]
### Subject of the issue
I tried to install rspec but I had trouble to get `rspec` command.

### Your environment
* Ruby version: `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`
* rspec-core version: `3.9.2`

### Steps to reproduce

```
gem install --user rspec
```

resulted in 

```
Successfully installed rspec-3.9.0
1 gem installed
```

without any complaints, but

`rspec` resulted in `bash: /usr/local/bin/rspec: No such file or directory`

### Expected behavior
`rspec` command works or I get warning during install that my PATH is broken or at least hint what kind of thing went wrong (maybe `--user` install is unsupported?)

### Actual behavior
`rspec` command was not working

`sudo gem install rspec` worked.

**Comment by JonRowe** [comment]
:wave: This sounds like an issue for Rubygems to work out why your `--user` gems are not accessible. Especially if root install works.

**Comment by matkoniecz** [comment]
So it should be handled by https://github.com/rubygems/rubygems ? I have seen some messages "your path is not including XYZ, commands will not run" but I have no idea whatever it was emitted by rubygems, ruby or by gem itself.

**Comment by JonRowe** [comment]
Gem's are not responsible for their installation, they provide a manifest of files to rubygems (or some other package manager) which puts them in appropriate places.

The path error sounds like it's coming from rubygems because your system is misconfigured but I don't know that for certain.
