### ISSUE TITLE
Is overall suite status available within the suite?

### ISSUE THREAD

**Issue by TJNII** [rspec/rspec-core#2754]
I'd like to write the test status to an API for general reporting when the suite completes.  It would be more convenient to do this in a `config.after(:suite)` block rather than wrapping rspec and reading the exit code.  Is there an rspec API that can be used to read the suite status from within the suite?

Looking at https://github.com/rspec/rspec-core/blob/main/lib/rspec/core/runner.rb#L113-L126 it doesn't look like there is an overall pass/fail variable that can be read.  Instead it looks like to send notifications about the suite run from within the suite I'd need to use the `config.reporter.register_listener` hook and track overall pass/fail myself.  Is that accurate?

**Comment by pirj** [comment]
That's correct. Listen to `:example_failed`, `:example_passed` and `:stop`, should provide you with all the information you need. `RSpec.world.non_example_failure` might be of some interest to you as well.

If you get stuck with something, please let us know on the mailing list, or use StackOverflow. http://rspec.info/help/
We strive to limit Github issues to bugs and enhancement requests.

**Comment by JonRowe** [comment]
Not quite but you can listen to `dump_summary` which is called at the end of the suite, it gives you duration, examples, failed_examples, pending_examples, load_time and errors_outside_of_examples_count.

A suite will fail if it has any failed_examples or any errors out of examples.
