### ISSUE TITLE
Suppressing entire backtrace for failed specs

### ISSUE THREAD

**Issue by dskim** [rspec/rspec-core#2755]
### Subject of the issue

I wonder if it makes sense to have an option to suppress entire backtrace for failed specs.
I see that we can use `backtrace_exclusion_patterns` or `filter_gems_from_backtrace` to filter specific lines, but I feel I'd like to see very minimalistic backtrace where you have just the last entry of the stacktrace. 

I'm thinking of adding something like `--no-backtrace` option.

I'm willing to work on it myself if this sounds reasonable. I might be missing an obvious alternative or someone could prove that I'm insane for wanting to such thing 😅 
My motivation for this is to receive more digestible failure outputs from CI.

### Your environment
* Ruby version: 2.6.6
* rspec-core version: 3.9

### Steps to reproduce
It's a feature request.

### Expected behavior
I want to be able to filter out backtrace entirely and only have the top most backtrace to indicate where the failing spec is.

### Actual behavior
I have to specify each path or gems to suppress all backtrace and it may need to be updated even after that if new gem or path gets introduced.

**Comment by pirj** [comment]
I guess you're looking to implement a custom formatter. Please check https://relishapp.com/rspec/rspec-core/docs/formatters/custom-formatters
You may start with overriding the default `lib/rspec/core/backtrace_formatter.rb`.

If you're unable to achieve the desired results, let's discuss how you imagine it to work. I would be most interested in how shared examples' traces are shown, are you going to both show the example group that includes shared examples and shared examples, or just the latter?

**Comment by JonRowe** [comment]
You can configure the backtrace filtering, it takes either a gem name or a regular expression.

https://relishapp.com/rspec/rspec-core/v/3-9/docs/configuration/excluding-lines-from-the-backtrace

If thats no sufficient I'd be happy to review a PR that limited the backtrace size by line number, with a `--no-backtrace` setting the limit to 0 or maybe 1.

**Comment by dskim** [comment]
@pirj @JonRowe Thanks for your replies.

Yes, I knew about those options but didn't try them out yet because seemed a little tedious.
However, I'll play with those for a bit and report back how it went.

**Comment by JonRowe** [comment]
For example, if you find the backtrace tedious it likely has thing like rack-test or capybara or rails in it, all of those can be filtered out as gem names to leave just your code / specs, you could further filter out your own dsl or library code by regular expression for path, I would humbly suggest that a few filtered lines will generally be better for diagnostics than a single line

**Comment by dskim** [comment]
Sure, I'll close this issue for now and reopen if I have more a concrete example. Thanks a lot for your comments @JonRowe 🙏
