### ISSUE TITLE
Pluggable config template

### ISSUE THREAD

**Issue by pirj** [rspec/rspec-core#2757]
### Subject of the issue

Other RSpec components, e.g. Expectations and Mocks have configuration options, most of which have documentation, e.g.:
```
      # Configures the maximum character length that RSpec will print while
      # formatting an object. You can set length to nil to prevent RSpec from
      # doing truncation.
      # @example
      # @param [Fixnum] length the number of characters to limit the formatted output to.
      #     rspec.expect_with :rspec do |c|
      #       c.max_formatted_output_length = 200
      #     end
```

Add a possibility for components/extensions to declare their desired additions to the default generated `spec/spec_helper.rb` so that those options make their way to the generated spec helper.

An `RSpec::Core::ProjectInitializer.add(<String>)` method would allow extensions to add those options. The project initializer then replaces the `<== extension config goes here ==>` placeholder in `lib/rspec/core/project_initializer/spec/spec_helper.rb` with those strings.

I can work on that if it makes sense.

A side benefit of that is that e.g. `expect_with :rspec` is not added unless `rspec-expectations` are part of the `Gemfile.
This has a downside, though, that it's not there if `rspec-expectations` are added at a later point in time.

**Comment by JonRowe** [comment]
Do many people add gems they want to use before they run the initialiser? This seems like it would have a limited use case of the first run only, and I really don't want to get into the business of having/being a generator... IF we were to add something like this, it would be better if it could be run at anytime, e.g. `rspec --init <gem_name>` but then merging and diffing etc becomes difficult...

**Comment by pirj** [comment]
> merging and diffing etc becomes difficult...

We could be adding the second `RSpec.configure do` block for each gem.

Expectations and mocks could warn if they are included and required, but not configured in the spec helper. On the other hand, I can imagine multiple different spec helpers where they are only used in some of them, but not all. Users will be forced to introduce the complexity into Gemfile groups to only load extensions when they are used.

I'm giving up on that until I have a better approach in mind.
