### ISSUE TITLE
Provide a way to programmatically remove formatters

### ISSUE THREAD

**Issue by agis** [rspec/rspec-core#2763]
Currently there's `#add_formatter` for registering a new formatter. But there's no counterpart to remove one. This would be useful in skroutz/rspecq#6 or other custom runners maybe. The rationale is that we want to run a dry-run with a JSON formatter to grab the example IDs, and right after (in the same process) issue the regular run.

I'd like to do something like this:

```ruby
def files_to_example_ids(files)
  formatter = RSpec::Core::Formatters::JsonFormatter.new(StringIO.new)
  RSpec.configuration.add_formatter(formatter)
  RSpec.configuration.dry_run = true

  opts = RSpec::Core::ConfigurationOptions.new(files)
  RSpec::Core::Runner.new(opts).run($stderr, $stdout)
ensure
  RSpec.configuration.dry_run = false

  # NOTE: this doesn't exist
  RSpec.configuration.remove_formatter(formatter)
end

```

Does that sound reasonable? Or perhaps there's already a way to do this that slipped my eyes? Thanks in advance!

**Comment by agis** [comment]
Ah, a bit too hasty. It seems that `#clear_examples` does the trick.

**Comment by pirj** [comment]
What do you collect from this dry run exactly? Just the example ids?
`RSpec.world` has a `all_examples` method. It's marked as private, but I guess for such a closely integrated tool as `rspecq`, it's quite ok to rely in the internals that deeply.

**Comment by agis** [comment]
@pirj Yep, I want to obtain the example ids of a _subset_ of the files. https://github.com/skroutz/rspecq/pull/36 is what I came up with. Do you think it's better to do this via `Rspec.world.all_examples`?

**Comment by JonRowe** [comment]
The RSpec globals are intended for use by RSpec itself in a single pass, but you can create your own versions of configuration, world etc and use those when you need something more complex. In theory you should be able to duplicate a config and add the formatter / dry run for this purpose.

**Comment by pirj** [comment]
@agis If `all_examples` is providing the information you need, that you can feed to RSpec later on, sure.

Just a word of precaution specifically about splitting by examples. Examples may have stateful setup. The simplest example is:
```ruby
before(:all) { @admin = create(:admin) }
before(:each) { sign_in @admin }
```
Sometimes, this setup is so heavy that it takes the majority of the spec run time.
If you split the examples that need this setup across workers, those workers will each have to run this setup.
[`let_it_be`](https://github.com/test-prof/test-prof/blob/master/docs/recipes/let_it_be.md)/`let_once` are used in the wild, I've seen several major projects using them, primarily to speed tests up.

The same applies to splitting by example groups, as they similarly can have shared setup.

So in a generic case, I'd stick to splitting by spec files.

**Comment by agis** [comment]
Thanks for the heads up @pirj. In the generic case, we do schedule whole spec files. We only split very slow files to individual examples (see [documentation](https://github.com/skroutz/rspecq#spec-file-splitting)).
