### ISSUE TITLE
irb: warn: can't alias context from irb_context.

### ISSUE THREAD

**Issue by rlue** [rspec/rspec-core#2776]
### Subject of the issue

I see that this bug was described in [rspec-rails #1693](https://github.com/rspec/rspec-rails/issues/1693) over four years ago, but I'm still seeing it in the most recent minor versions of Ruby and RSpec (2.7 / 3.9).

When executing `irb -r <module>`, if the given module is either a) RSpec or b) a script that requires RSpec in turn, then the following warning will be printed to the console:

> irb: warn: can't alias context from irb_context.

Note that calling `require 'rspec'` from within `irb` does **not** produce the warning:

```
irb(main):001:0> require 'rspec'
=> true
```

### Your environment

* Ruby version: 2.7.0
* rspec-core version: 3.9.0

### Steps to reproduce

```sh
$ mkdir bug
$ cd bug
$ bundle init
$ echo "gem 'rspec'" >> Gemfile
$ bundle install
$ bundle exec irb -r rspec
```

### Expected behavior

IRB console should be invoked without warning; _i.e.:_

```sh
$ bundle exec irb -r rspec
irb(main):001:0>
```

### Actual behavior

```sh
$ bundle exec irb -r rspec
irb: warn: can't alias context from irb_context.
irb(main):001:0>
```

**Comment by JonRowe** [comment]
@rlue did you read the follow up to that issue? It's possible that this issue only appears to be coming

**Comment by JonRowe** [comment]
This because by default RSpec monkey patches `context` into the top level, disable monkey patching to silence it.

**Comment by fedgut** [comment]
PR in here https://github.com/1DocWay/th-connect/pull/1
