### ISSUE TITLE
Bisect runs indefinitely on tiny groups of tests - cleanup command?

### ISSUE THREAD

**Issue by locofocos** [rspec/rspec-core#2777]
### Subject of the issue

I've had a lot of good results using `rspec bisect` (thank you!!). Now I'm often running into flaky specs that can be reproduced with a specific seed, but they cause bisect to run seemingly indefinitely on tiny groups of tests. It will output
> Checking that failure(s) are order-dependent... failure appears to be order-dependent

then keep halving the number of examples (like it should), but then once it reaches a group of 2 examples, it moves on to other rounds trying 1 or 2 other examples. It keeps trying rounds with these small example groups, and never finds the culprit (within a reasonable period of time).

One factor that probably affects this: I have to reset my database in order for the failure to appear. To demonstrate:
```
rails db:drop && rails db:create && rails db:migrate && rails db:migrate RAILS_ENV=test
bundle exec rspec --seed 1234 <long list of spec files> # one of the test cases fails
bundle exec rspec --seed 1234 <long list of spec files> # tests all pass

rails db:drop && rails db:create && rails db:migrate && rails db:migrate RAILS_ENV=test
bundle exec rspec --seed 1234 <long list of spec files> # one of the test cases fails
bundle exec rspec --seed 1234 <long list of spec files> # tests all pass
```

My theory is that I need to reset my database between each round of bisect. But, I haven't found any mechanism for doing that fully. Running `DatabaseCleaner.clean_with(:truncation)` doesn't help, so we probably have some issue caused by sequences. The closest I've found is adding this to my spec/support/database_cleaner.rb
```ruby
RSpec.configure do |config|
  config.before(:suite) do
    `rails db:drop && rails db:create && rails db:migrate && rails db:migrate RAILS_ENV=test`
  end
end
```
but this fails:
> Caused by:
> PG::ObjectInUse: ERROR:  database "asdf_test" is being accessed by other users
> DETAIL:  There is 1 other session using the database.

Is there some mechanism for running an arbitrary cleanup command between each round of bisect?

### Your environment
* Ruby version: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
* rspec-core version: rspec-core (3.9.3)

### Steps to reproduce
* Find a specific rspec command that fails when starting with a fresh db state, but passes when running a second time. 
* Make sure the rspec command has a seed.
* Add "--bisect" to the rspec command. Run it.

I wish I could share our actual codebase, but it's my work closed-source project. I'd be glad to test out fixes or provide additional diagnostic info on our codebase.

### Expected behavior
It should output something like
```
Round 1: bisecting over non-failing examples 1-2014 .. multiple culprits detected - splitting candidates (44.33 seconds)
Round 2: bisecting over non-failing examples 1-1007 .. multiple culprits detected - splitting candidates (45.57 seconds)
....
Round 10: bisecting over non-failing examples 25-26 ...

Dolla dolla bill yall, we found a minimal reproduction set! Here's the command:

bundle exec rspec --seed 123 test_file1.rb[1:1:1] test_file2.rb[1:3:2]
```

### Actual behavior
It outputs this
```
Running suite to find failures... (2 minutes 14.3 seconds)
Starting bisect with 1 failing example and 2014 non-failing examples.
Checking that failure(s) are order-dependent... failure appears to be order-dependent

Round 1: bisecting over non-failing examples 1-2014 .. multiple culprits detected - splitting candidates (44.33 seconds)
Round 2: bisecting over non-failing examples 1-1007 .. multiple culprits detected - splitting candidates (45.57 seconds)
Round 3: bisecting over non-failing examples 1-504 .. multiple culprits detected - splitting candidates (48.71 seconds)
Round 4: bisecting over non-failing examples 1-252 .. multiple culprits detected - splitting candidates (1 minute 10.09 seconds)
Round 5: bisecting over non-failing examples 1-126 .. multiple culprits detected - splitting candidates (1 minute 15.6 seconds)
Round 6: bisecting over non-failing examples 1-63 .. multiple culprits detected - splitting candidates (1 minute 20.9 seconds)
Round 7: bisecting over non-failing examples 1-32 .. multiple culprits detected - splitting candidates (1 minute 23.26 seconds)
Round 8: bisecting over non-failing examples 1-16 .. multiple culprits detected - splitting candidates (1 minute 23.36 seconds)
Round 9: bisecting over non-failing examples 1-8 .. multiple culprits detected - splitting candidates (1 minute 25.94 seconds)
Round 10: bisecting over non-failing examples 1-4 .. multiple culprits detected - splitting candidates (1 minute 28.78 seconds)
Round 11: bisecting over non-failing examples 1-2 .. multiple culprits detected - splitting candidates (1 minute 25.72 seconds)
Round 12: bisecting over non-failing examples 3-4 .. multiple culprits detected - splitting candidates (1 minute 23.51 seconds)
Round 13: bisecting over non-failing examples 5-8
<halted with ctrl-c> 

Bisect aborted!

The most minimal reproduction command discovered so far is:

rspec  './spec/asdf/qwer/asdf/qwer_spec.rb[1:1:1,1:2:1,1:3:1,1:3:2,1:4:1,1:5:1:1,1:5:2:1,1:6:1:1,1:6:1:2,1:6:1:3,1:6:1:4,1:6:1:5,1:6:1:6:1,1:6:1:6:2,1:6:1:6:3,1:6:1:6:4,1:6:1:6:5,1:6:2:1,1:6:2:2,1:7:1,1:7:2,1:7:3,1:7:4,1:7:5,1:7:6,1:7:7,1:7:8,1:7:9,1:7:10,1:7:11:1,1:7:11:2,1:7:11:3,1:7:11:4,1:7:12:1,1:7:12:2,1:7:12:3,1:7:13:1:1,1:7:13:1:2,1:7:13:2:1,1:7:13:2:2,1:7:14:1,1:7:14:2,1:7:14:3,1:7:15:1,1:7:15:2,1:7:15:3,1:7:16:1,1:7:16:2,1:7:16:3,1:7:16:4,1:7:17:1,1:7:17:2,1:7:18:1,1:7:18:2,1:7:18:3,1:7:19:1,1:7:19:2,1:7:19:3,1:7:20:1,1:7:20:2,1:7:21:1,1:7:21:2,1:7:22:1]' <many other similar paths>
```

**Comment by benoittgt** [comment]
Hello @locofocos 

Thanks for the detailed issue. I think you already find the issue. Did you tried to reset your sequences? I saw that `database-cleaner` probably use it. https://github.com/DatabaseCleaner/database_cleaner-active_record/blob/72acb8e1f39bd1765305e2bdfb2f67b77428bba6/lib/database_cleaner/active_record/truncation.rb#L218-L227

But you could use `reset_pk_sequence!(<table_name>)`. _[source for PostgreSQL](https://github.com/rails/rails/blob/a50333b51e60719739033f5a4b0b25e808583b0b/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L275-L300)

Maybe something like
```ruby
ActiveRecord::Base.connection.tables.each do |table|
  ActiveRecord::Base.connection.reset_pk_sequence!(table)
end
```

**Comment by JonRowe** [comment]
You've found our hooks, (`before(:hooks)` and `after(:suite)`) which are intended for this kind of cleanup, your problem seems to be that you are shelling out to cleanup, but as the test suite processes are still running, I assume Rails isn't shutdown, in particular I assume ActiveRecord is holding a connection in its pool, it is possible to disconnect it however at which point your command should work.

**Comment by pirj** [comment]
To me, this is not something the bisect itself is able to work around or something we can fix in RSpec Rails.

Bisect won't help you in the case when tests to fail on the first run and pass on the subsequent one.
You have to find what is causing this problem first if you plan to use bisect on this project.
The workaround with resetting sequences might work for you.

Let's switch to our [mailing list](http://rspec.info/help/). Appreciate if you could provide failure details and the related code (spec, models, factories). People on the mailing list might be able to spot something.

**Comment by locofocos** [comment]
Thanks for all the tips! Yeah, I realize it's not quite reproducible, at least in the way that rspec needs it to be. 

Here's what I tried with the advice above, in case this helps anyone else coming across this issue:
```ruby
# Attempt 1. Reset the sequences.
config.before(:suite) do
  ActiveRecord::Base.connection.tables.each do |table|
    ActiveRecord::Base.connection.reset_pk_sequence!(table)
    puts 'Reset sequence for ' + table
  end
  ...

# Attempt 2. Disconnect the connection pool, then run the cleanup command.
config.before(:suite) do
  ActiveRecord::Base.connection_pool.disconnect!
  puts `rails db:drop && rails db:create && rails db:migrate && rails db:migrate RAILS_ENV=test`
  ...

# Attempt 3. Run the reset command by hand in another terminal.
config.before(:suite) do
  ActiveRecord::Base.connection_pool.disconnect!
  puts 'Open another terminal and run your db reset command, then press enter here.'
  gets
  ...
```
To my surprise, none of those attempts above worked. There must be some difference between running my reset command in a `before(:suite)` and running it before rspec is invoked.

One more thing I want to try: Edit the gem locally to provide some mechanism for running an arbitrary cleanup command between each round of bisect. It looks like I could edit `shell_command.command_for` https://github.com/rspec/rspec-core/blob/b9915aedd07eb61e0d85ddb6b40f06bdb98ee884/lib/rspec/core/bisect/shell_command.rb#L17 or maybe `shell_runner.rb` where that's called, and there add my shell snippet to reset the database.

If I can find some reasonably small subset of related code I could share, I'll be glad to follow up on the mailing list. Thanks for the offer. Until then, I'll have to hope I can resolve the failure, in which case I'll be glad to report back here and let everyone know what the issue was. 

I appreciate the help, and all the work you folks have done on rspec over the years!

**Comment by locofocos** [comment]
Hey, good news! I was able to make the edits locally in example_minimizer.rb to reset the database: https://github.com/locofocos/rspec-core/commit/24589002fbeaaa23e1dbb7ae3fcc6cbcac0061d1

After this, bisect worked like a charm for me (36 rounds! 😮 ), and I have a pretty small minimal reproduction command. I'll post back here with a description/example of the root cause once I can resolve it.

I don't know if it would be worth the development+reviewing+testing+maintenance, but for my use case, it could be helpful to provide a cleanup command parameter, so I could run
```
bundle exec rspec --order random --seed 21081 --bisect --bisect-cleanup-cmd='rails db:drop && rails db:create && rails db:migrate && rails db:migrate RAILS_ENV=test'
```
and get the same effect.

**Comment by JonRowe** [comment]
If you're using the fork runner (which is typically faster) I think you'd run into the same issue with that command, so figuring out how to do it in Ruby may still be necessary

**Comment by locofocos** [comment]
I might not be able to give this the full root-cause analysis I think it deserves, but I was able to get very close to the root cause, so here's what I can provide:

In short, we were defining some singleton methods that returned a specific record. At the time we initialize those singleton methods, we saved a reference to that specific record. Through some sequence of operations, including both seeds and migrations that updated these records, that cached record would be different.

After discovering this, I tried running `bin/spring stop` between rspec runs to see if that would clear out the cached reference, but it had no effect surprisingly. I don't know what gets cleared out by resetting the database, which wouldn't get cleared by `bin/spring stop`, but there's some difference 🤷.

So, my poor man's takeaway for any folks finding this on Google - try resetting your database fully and see if that's necessary to reproduce it.

Here are some relevant snippets to demonstrate what we were doing in more detail. I don't think there's a lot of value in sharing the full reproduction set, unless you folks are eager to get a copy for understanding + improving rspec.

Thanks again for the tips!

```ruby
# app/models/market.rb

class Market < ApplicationRecord
  validates :name, :human_readable_name, presence: true

  # After a market changes, we need to redefine our finders so they return the latest data
  after_commit :refresh_market_finder, on: %i[create update]
  after_destroy_commit :destroy_market_finder

  # Temporary method used for conversion of Market_AAA to Market_BBB
  def self.market_aaa
    Market.market_bbb
  end

  send def self.define_market_finders
    all.find_each do |market|
      define_singleton_method(market.name) { market }
    end
  end

  def refresh_market_finder
    record = self
    self.class.define_singleton_method(record.name) { record }
  end

  def destroy_market_finder
    record = self
    self.class.define_singleton_method(record.name) { raise NoMethodError, "undefined method #{record.name}" }
  end
end

# db/migrate/whatever.rb
class AddMarket < ActiveRecord::Migration[5.2]
  def up
    safety_assured do
      execute "insert into markets (name, created_at, updated_at, human_readable_name) values ('market_aaa', NOW(), NOW(), 'Market_AAA')" if Market.find_by(name: 'market_aaa').nil?
    end
  end

  def down
    Market.find_by(name: 'market_aaa')&.destroy
  end
end

# spec/support/database_cleaner.rb
require_relative Rails.root.join('db', 'seeds', '003_markets.rb')
RSpec.configure do |config|
  config.use_transactional_fixtures = false

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
    Seeds::Markets.seed
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction
  end
...
end

# db/seeds/003_markets.rb
module Seeds
  module Markets
    def self.seed
    ...
      market_bbb = Market.find_or_initialize_by(id: 8)
      market_bbb.update!(name: 'market_bbb', human_readable_name: 'Market_BBB')

      # Because we are hardcoding id creation, we need to reset the pk sequence to allow further market creation
      ActiveRecord::Base.connection.reset_pk_sequence!('markets')
    end
  end
end

# app/models/organization.rb
class Organization < ApplicationRecord

  has_many :market_aaa_accounts, -> { joins(:market).where(markets: { id: Market.market_aaa.id }) },
           class_name: :MarketAccount, as: :owner, dependent: :destroy
end

# spec/models/organization_spec.rb
require 'rails_helper'
RSpec.describe Organization, type: :model do
  let!(:org) { create(:organization) }

  describe '#connected_market' do
    let!(:owner_org) { create(:organization) }
    let!(:market_account) { create(:market_account, market: Market.market_bbb, owner: owner_org) }

    it 'case 1' do
      # This was our failure point
      owner_org.market_aaa_accounts.first.onboarded?
    end

    it 'case 2' do
      # This is close to demonstrating the root cause of the failure point
      # See the market_aaa method in market.rb
      expect(Market.market_bbb.name).to eq(Market.market_aaa.name) # fails
      expect(Market.market_bbb.id).to eq(Market.market_aaa.id)
    end
  end
end
```

**Comment by JonRowe** [comment]
> After discovering this, I tried running bin/spring stop between rspec runs to see if that would clear out the cached reference, but it had no effect surprisingly. I don't know what gets cleared out by resetting the database, which wouldn't get cleared by bin/spring stop, but there's some difference 🤷.

I think it comes down to how Rails keeps around references. Spring is designed to improve code reloading speed, but not to cache database connections etc, where as probably the issue with your app is that the ActiveRecord connection pool is not being reset?
