### ISSUE TITLE
How do I run test collection only?

### ISSUE THREAD

**Issue by draganrakas** [rspec/rspec-core#2781]
I'm trying to run test collection only, and then run all of the collected test case metadata (e.g. tags, filepath, etc.) through a validation function (e.g. a tag of a certain naming convention must exist). Is there a way to do this with rspec? Googled everywhere but can't seem to find a solution.

If anyone is familiar with pytest, the pytest equivalent is a `--collect-only` flag, and then you can implement a hook that iterates over each collected item (test). Thank you in advance!

**Comment by JonRowe** [comment]
I'm not sure what a collection is here, our metadata exists on example groups and examples after they've run, but we don't collect them into anything. We do have hooks which run around things using metadata, and filters etc plus we have a formatter / event listener api that could be used to do this with your own state capturing... 

Hooks are documented here:
https://relishapp.com/rspec/rspec-core/v/3-9/docs/hooks/before-and-after-hooks

The formatters are documented here:
http://rspec.info/documentation/3.9/rspec-core/RSpec/Core/Formatters/Protocol.html

Typically we ask that queries are directed to the mailing list or other discussion tools and our issues kept clear for bug reports and feature requests so I'm closing this, but I'm happy to help here if you have more questions.
