### ISSUE TITLE
Filepath handling in MetaData#populate_location_attributes

### ISSUE THREAD

**Issue by Aqualon** [rspec/rspec-core#2814]
### Subject of the issue
I was profiling the test suite of a closed source app I'm working on and saw using stackprof in `:cpu` mode, that over 10% of CPU time was used in the computation of `absolute_file_path` in

https://github.com/rspec/rspec-core/blob/addcfb47cb0582b8e976c938ff18728144a7dcee/lib/rspec/core/metadata.rb#L155

Digging deeper on our test suite with 7497 examples, I logged each `absolute_file_path` and it was computed 15085 times with only 183 unique paths (we heavily use shared_examples). In another apps test suite with 7817, we had 15195 calls with 511 unique paths. I also saw that the computed `absolute_file_path` was always equal to `file_path` determined in https://github.com/rspec/rspec-core/blob/addcfb47cb0582b8e976c938ff18728144a7dcee/lib/rspec/core/metadata.rb#L146-L152.

So two questions:
- Is `file_path` ever different from `absolute_file_path`? If not, we could save all the calls to `File.expand_path`.
- If `absolute_file_path` has to be computed, could some caching be useful to remember a mapping from `file_path` to `absolute_file_path`? Same question could be asked about calls to `Metadata.relative_path(file_path)`.

On the big scale, this probably won't make a real difference for IO-bound test suites, that talk to databases, but it could make sense for CPU-bound test suites with many shared examples. The biggest difference in profiling I found was in a file with 4357 examples, that heavily relies on nested shared examples, where we hit `absolute_file_path` 9513 times with only 3 different paths.

rspec-core 3.10.0:
```
==================================
  Mode: wall(1000)
  Samples: 1607 (3.48% miss rate)
  GC: 207 (12.88%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       378  (23.5%)         296  (18.4%)     RSpec::Core::Metadata::HashPopulator#populate_location_attributes
```

rspec-core 3.10.0 just reusing `file_path` instead of computing `absolute_file_path`:
```
==================================
  Mode: wall(1000)
  Samples: 1254 (4.86% miss rate)
  GC: 190 (15.15%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
[...] 16 other lines
        89   (7.1%)          20   (1.6%)     RSpec::Core::Metadata::HashPopulator#populate_location_attributes
```
But on overall runtime for the execution of this file, there was still no measurable difference.

### My personal conclusion
> - Is `file_path` ever different from `absolute_file_path`? If not, we could save all the calls to `File.expand_path`.

If computed `absolute_file_path` is never different from `file_path`, this could be still worth doing it, but otherwise it's probably not worth making the code more complex for potentially some edge case gains. But would be interesting to get feedback from someone with experience on the rspec-core internals.

### Your environment
* Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19] (macOS catalina)
* rspec-core version: 3.10.0

**Comment by pirj** [comment]
Interesting find, thanks for reporting.

If you set a conditional breakpoint
```ruby
binding.pry unless file_path == absolute_file_path
```
does it stop during your suite run?

What is the performance impact if you
```diff
- absolute_file_path            = File.expand_path(relative_file_path)
+ absolute_file_path            = file_path
```

**Comment by Aqualon** [comment]
I did a `puts "#{file_path} | #{absolute_file_path}" if file_path != absolute_file_path` and it never printed it on both test suites (I verified it prints without the condition).

> ```diff
> - absolute_file_path            = File.expand_path(relative_file_path)
> + absolute_file_path            = file_path
> ```
That's what I tried, but besides the changes in stackprof output I mentioned in my initial comment, it didn't result in any real runtime improvement, even in the case of the one large test file, where stackprof showed the biggest change. So could be another example of micro benchmark improvement, that is not visible in the real world.

Maybe interesting, I used stackprof by wrapping all the code in the generated rspec file
```diff
#!/usr/bin/env ruby_executable_hooks
#
# This file was generated by RubyGems.
#
# The application 'rspec-core' is installed as part of a gem, and
# this file is here to facilitate running it.
#

+ require 'stackprof'
+ StackProf.run(mode: :wall, out: "tmp/stackprof.dump") do
    require 'rubygems'

    version = ">= 0.a"

    str = ARGV.first
    if str
      str = str.b[/\A_(.*)_\z/, 1]
      if str and Gem::Version.correct?(str)
        version = str
        ARGV.shift
      end
    end

    if Gem.respond_to?(:activate_bin_path)
    load Gem.activate_bin_path('rspec-core', 'rspec', version)
    else
    gem "rspec-core", version
    load Gem.bin_path("rspec-core", "rspec", version)
    end
+ end
```

**Comment by pirj** [comment]
Interesting.

Have you tried building a flamegraph from your dump? https://github.com/test-prof/test-prof/blob/master/docs/profilers/stack_prof.md#report-formats

I'll close this issue since there's no obvious performance impact even though the code might be sub-optimal.

Let's continue our discussion in our mailing list http://rspec.info/help/. Please share your findings!

**Comment by Aqualon** [comment]
@pirj thanks, I will look into test-prof after Christmas and write to the mailing list, once I found out more. Happy holidays! 🎄

**Comment by JonRowe** [comment]
If you can find a benchmarkable improvement through caching, we would be open to PRs
