### ISSUE TITLE
Different behavior between Ruby 2.7 and Ruby 3.0

### ISSUE THREAD

**Issue by taichi-ishitani** [rspec/rspec-core#2820]
### Subject of the issue

I found different behavior between Ruby 2.7 and Ruby 3.0.
I think it's caused by changes of Ruby 3.0 and I'd like to any idea why this difference occurs.

### Your environment
* Ruby version:
    * ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
    * ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
* rspec-core version:
    * 3.10.0

### Steps to reproduce

Run the following spec code with Ruby 2.7 and 3.0.

```ruby
RSpec.describe NameError do
  example 'test 1' do
    expect { foo }.to raise_error(include(inspect))
  end

  context do
    example 'test 2' do
      expect { foo }.to raise_error(include(inspect))
    end
  end
end
```

For Ruby 2.7, `test 1` will be passed but `test 2` will be failed.

```console
$ RBENV_VERSION=2.7.2 rspec test_spec.rb
.F

Failures:

  1) NameError  test 2
     Failure/Error: expect { foo }.to raise_error(include(inspect))

       expected Exception with include "#<RSpec::ExampleGroups::NameError::Anonymous \"test 2\" (./test_spec.rb:7)>", got #<NameError: undefined local variable or method `foo' for #<RSpec::ExampleGroups::NameError::Anonymous:0x000055fe31909040>> with backtrace:
         # ./test_spec.rb:8:in `block (4 levels) in <top (required)>'
         # ./test_spec.rb:8:in `block (3 levels) in <top (required)>'
     # ./test_spec.rb:8:in `block (3 levels) in <top (required)>'

Finished in 0.01508 seconds (files took 0.07416 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./test_spec.rb:7 # NameError  test 2
```

For Ruby 3.0, both of `test 1` and `test 2` will be passed.

```console
$ RBENV_VERSION=3.0.0 rspec test_spec.rb
..

Finished in 0.00615 seconds (files took 0.08018 seconds to load)
2 examples, 0 failures
```

### Expected behavior

I think `test 2` should also be passed even in the case of Ruby 2.7 but I'm not sure.

### Actual behavior

In case of Ruby 2.7, `test 1` will be passed but `test 2` will be failed.
In case of Ruby 3.0, `test 1` and `test 2` will be passed.

**Comment by pirj** [comment]
This is due to this difference:
3.0:
```
NameError: undefined local variable or method `foo' for #<RSpec::ExampleGroups::NameError::Anonymous "test 2" (./spec/a_spec.rb:3)>
```

2.7:
```
NameError: undefined local variable or method `foo' for #<RSpec::ExampleGroups::NameError::Anonymous:0x00007fa49654f398>
```

where `inspect` in both cases is
```
"#<RSpec::ExampleGroups::NameError::Anonymous \"test 2\" (./spec/a_spec.rb:3)>"
```

I can't think of an approach to work around this.

Apart from this synthetic example, do you experience any problems with real specs?

**Comment by taichi-ishitani** [comment]
> do you experience any problems with real specs?

Yes. My some unit tests are broken due to this problem when I try to update Ruby 2.7 to 3.0.

**Comment by pirj** [comment]
Please provide a failing spec.

**Comment by taichi-ishitani** [comment]
These are a failing spec and its log.
https://github.com/rggen/rggen-core/blob/5222c3646ff600068f38af7b789dc97948f2d778/spec/rggen/core/utility/error_utility_spec.rb#L48
https://github.com/rggen/rggen-core/runs/1613456971?check_suite_focus=true#step:6:15

**Comment by JonRowe** [comment]
Your examples appear to be monkey patching exceptions, exception output can and does change across Ruby versions and is not within RSpecs domain.

In your original examples, you use `inspect` output for an instance of a class (which is what a test is here), and can also change across Ruby versions, this is not something we provide, its the standard Ruby inspect, you're doing the equivalent of this:
```
begin
  foo
rescue NameError => error
  fail unless error.message.include(inspect)
end
```

Closing because changes in Ruby versions can cause changes in standard Ruby output.
