### ISSUE TITLE
Defining helpers that use let, before, etc.

### ISSUE THREAD

**Issue by askreet** [rspec/rspec-core#2860]
Hello!

I am trying to define helper methods to de-duplicate some cases where we intercept creation of objects as well as some method calls. I had an idea to make a method which calls `let` and `before` to do this. This seems to work right until I want to call another late-binding construct, e.g. another `let`.

This works:

```ruby
  def spying_on(klass, as:)
    let(as) { instance_spy(klass) }

    before { allow(klass).to receive(:new).and_return(send(as)) }
  end
```

However, this does not:

```ruby
  def stub_instances(klass, as: nil, **stubs)
    as ||= klass.name.underscore

    let(as) { instance_double(klass) }

    before :each do
      allow(klass).to receive(:new).and_return(send(as))

      stubs.each do |method, value_or_proc|
        if value_or_proc.is_a?(Proc)
          allow(send(as)).to receive(method, &value_or_proc)
        else
          allow(send(as)).to receive(method).and_return(value_or_proc)
        end
      end
    end
  end
```

The use case of the latter would be something like:
```
describe Foo do
  let(:value_by_default) { 1 }
  stubbing TheClass, method: -> { value_by_default }

  describe "edge case" do
    let(:value_by_default) { 2 }
    # example
  end
end
```

The first helper works, it defines a let to create the spy and a before to intercept construction. However, the second gives me this error:

```
RSpec::Core::ExampleGroup::WrongScopeError: `deployment_result` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc).
```

Is there a supported way to write a helper which uses a `let` defined in the example group in this way?

**Comment by pirj** [comment]
Sure, it should be possible in some way.

The example you've provided it hard to reproduce. `deployment_result` mentioned in the error message is not anywhere in the code you've provided. Also `stubbing` method is not defined.

I believe there is nothing actionable here, so I'll close the issue.

Let's continue our discussion on our mailing list, see https://rspec.info/help/

**Comment by askreet** [comment]
Thanks @pirj classic case of trying to sanitize my code as an example. I'll put together a working example outside my codebase and send a message to the mailing list. :+1:
