### ISSUE TITLE
Cannot access RSpec results in  config.after(:suite) do  - Require Documentation

### ISSUE THREAD

**Issue by stevenm111** [rspec/rspec-core#2879]
### Subject of the issue
In attempting to build a webhook for RSpec results I cannot find clear documentation on the obj that stores the results of the tests I can call the formatters and dump etc but they are empty. 

Is there a handy object to pull the notifications from that builds the results to post to a webhook ? 
I was trying to collect them to send to a formatter, however,  but cannot find the instance or object name 
is there the VAR that is used to put the formated results available ?

### Your environment
* Ruby version: 2.3.8
* rspec-core version: 4.0

### Steps to reproduce
In the spec_helper.rb of RSpec_rails

      config.after(:suite) do 
    
        puts user_email + "::" + project_key
        puts RSpec::Core::Notifications::SummaryNotification[]
    
      end

I also tried dump_summary(SummaryNotifications) but was unable to make it provide the results of the existing RUNNER

### Expected behavior

Command Line outputs the Variables held from the current runner 

### Actual behavior

All values are NIL

**Comment by JonRowe** [comment]
If you wish to receive the life cycle notifications you need to build a "formatter" that receives them, and register it to receive them. You can find the protocol for that documented here:
https://rspec.info/documentation/3.9/rspec-core/RSpec/Core/Formatters/Protocol.html

The reporter will call registered formatters at the right point with the information required.

**Comment by pirj** [comment]
@stevenm111 In addition to what @JonRowe said, you can check the discussion in https://github.com/rspec/rspec-core/issues/2801

**Comment by stevenm111** [comment]
Thanks Jim / Pirj,

Pirji this has really helped , the dump_summary hook is exactly what I'm looking for , however it appears to be overcomplicating an issue, Its not that I'm wanting to change the console output or the format of it, Im just wishing to grab it and use it. However as I'm learning they are in different "Events"

I do not wish to have a different command line or pass to a text file or to create a custom format.

When rspec runs with the after(:suite) option I can put to the console as below
the 

    ubuntu:~/environment/wb (master) $ rspec
    [WB] You are posting to - patient_forest_94_147_5512
    ..........
    [WB] [WBS]: Githook was successfully created.


    Finished in 0.59525 seconds (files took 5.44 seconds to load)
    10 examples, 0 failures
    
Appologies if my terminology is incorrect I'm just trying to get my head around the objects, classes and structure of RSpec, however 
The initiated  EVENT produces a dump in the above example    "10 examples, 0 failures" 
Thats all I wish to collect inside the after(:suite) call , if this requires I rebuild a custom formatter that duplicates this AND also passes the notifications into a usable string variable then so be it, just seems difficult when clearly that EVENTS notifications and formatted dump already exist?

Thank you for your answers and support to date, I'm a recent convert to RSpec from minitests 

Appologies to re-prase the question, I have found several people looking for this answer as well as myself but through my lack of understanding of the code base I know I'm not asking correctly.

**Comment by stevenm111** [comment]
PS I'm working on a custom formatter just to see how goes

**Comment by pirj** [comment]
@stevenm111 `after(:suite)` is not designed to receive the results of the test suite run.
Take a look at [this formatter](https://github.com/rspec/rspec-core/blob/fe3084758857f0714f05ada44a18f1dfe9bf7a7e/lib/rspec/core/formatters/json_formatter.rb#L9) and adjust it to your needs. [`dump_summary`](https://github.com/rspec/rspec-core/blob/fe3084758857f0714f05ada44a18f1dfe9bf7a7e/lib/rspec/core/formatters/json_formatter.rb#L24) specifically looks useful for your case.

The JSON formatter won't affect the console output. You'll understand it better when you'll realize that several formatters can be in action for the same run time and output to different streams. From `rspec --help`:
```
    -f, --format FORMATTER             Choose a formatter.
                                         [p]rogress (default - dots)
                                         [d]ocumentation (group and example names)
                                         [h]tml
                                         [j]son
                                         [f]ailures ("file:line:reason", suitable for editors integration)
                                         custom formatter class name

    -o, --out FILE                     Write output to a file instead of $stdout. This option applies
                                         to the previously specified --format, or the default format
                                         if no format is specified.
```

If the only thing that your code is supposed to do is to send a webhook with specs execution results - a formatted is a perfect place to do so.

Also, it's not necessary to specify formatters in the command line, you can do so in the [configuration file](https://relishapp.com/rspec/rspec-core/v/3-9/docs/configuration/read-command-line-configuration-options-from-files).

If you have any further questions, feel free to search for it or ask in our [Google Group](https://rspec.info/help/).

I encourage you to send a PR to update the documentation if this is a question multiple people are struggling with.

**Comment by stevenm111** [comment]
@pirj 

THANK YOU

I now have this working a TREAT, I so appreciate your patience and advice on this, especially taking ownership of the issue and working through it even though I was slow.

For anyone else working through this here's what I did

in rspec.rb   config file

    --require spec_helper
    --require custom_formatter.rb --format CustomFormatter --format progress

This calls the custom formatted file to be included as well as the output then also runs the standard formatted along side it so you get all the progress bar and error notifications on the screen

custom_formatter.rb in /spec

```
    class CustomFormatter
  # This registers the notifications this formatter supports, and tells
  # us that this was written against the RSpec 3.x formatter API.
  RSpec::Core::Formatters.register self, :dump_summary , :example_started ,:close

  def initialize(output)
    @output = output
    @output_hash = {
            :version => RSpec::Core::Version::STRING
          }
  end
  
# this is my rough work out of the progress bar put anything in here you want to show for each test set to the screen
  def example_started(notification)
    @output << "." 
  end
 
  
  def dump_summary(summary)
          @output_hash[:summary] = {
            :duration => summary.duration,
            :example_count => summary.example_count,
            :failure_count => summary.failure_count,
            :pending_count => summary.pending_count,
            :errors_outside_of_examples_count => summary.errors_outside_of_examples_count
          }
          @output_hash[:summary_line] = summary.totals_line
  end
 
# this is the part that triggers AFTER  tests are run and summary built put your thing in here whatever you need
  def close(notification)
   description =  "Duration : " << @output_hash[:summary][:duration] << " seconds."     
    uri = URI('http://mydomain/landingpage')
    res = Net::HTTP.post_form(uri, 'duration' => "#{description}")
    # this returns the server response
    puts "\n[WB] " + res.body
  
  end
  

  
end
```

**Comment by JonRowe** [comment]
Formatters are called formatters because they historically were only used to provide output to the CLI and were quite rigid, we gradually expanded that to allow custom formatters and in RSpec 3 completely rewrote them to be a pub sub model.

The key thing I think you may still be missing here is you can have multiple, so you can add a normal output formatter and a custom formatter to subscribe to events from RSpec.

You can also do this programatically via:
https://rspec.info/documentation/3.9/rspec-core/RSpec/Core/Configuration.html#add_formatter-instance_method

So you could have a gem which installed itself with a formatter without requiring any cli input from the user, as long as you had a require in the spec_helper to configure the right parts.

**Comment by stevenm111** [comment]
Morning Jon

Thanks for that, yes much cleaner and tidier, that's a cleaner method as well, so will continue to test usability and content for a while and then add to possible refactoring stuff. But a gem is the end goal with no user input other than a token load.

Thank you both so much for help to date :)

**Comment by JonRowe** [comment]
You should be able to do:
```
# users spec_helper.rb
require 'my_gem/rspec'

# lib/my_gem/rspec.rb
require 'my_gem/awesomeness'
RSpec.configuration do |config|
  config.add_formatter MyGem::Awesomeness
end
```
Etc, you might want to add some logic in your file about seeing if theres only the default configured and if so configured those as well, but essentially it should be entirely doable that you only need the end user to require your one file.
