### ISSUE TITLE
Feature request: Cover multiple scenarios with concise syntax

### ISSUE THREAD

**Issue by markburns** [rspec/rspec-core#2896]
### Subject of the issue
Testing multiple edge cases with concise syntax.

### Your environment
* Ruby version: Any
* rspec-core version : Future

### Steps to reproduce
N/A

### Expected behavior
I think a little code snippet gets the points across. 
Something I have found useful is doing this kind of thing:

```ruby

with_lets(
  self, [
    { foo: false, bar: false, baz: false },
    { foo: false, bar: nil,   baz: false },
    { foo: nil,   bar: nil,   baz: false },
    #...
    { foo: true,  bar: true,  baz: true }
  ]
) do
  it 'works' do
    expect(foo && bar).to eq baz
  end
end

```

I end up re-implementing similar versions of this from time to time.
Here's a simple implementation from a Rails project:

```ruby
module SpecSupport
  module WithLets
    extend ActiveSupport::Concern

    class_methods do
      def with_lets(base, scenarios, &block)
        scenarios.each do |spec_attrs|
          description = spec_attrs.map { |n, v| "with #{n}: #{v}" }.join(', ')

          _with_lets_define_context(base, spec_attrs, description, &block)
        end
      end

      private

      def _with_lets_define_context(base, spec_attrs, description, &block)
        base.instance_eval do
          context description do
            spec_attrs.each do |name, value|
              let(name) { value }
            end

            instance_eval(&block)
          end
        end
      end
    end
  end
end

RSpec.configure do |c|
  c.include SpecSupport::WithLets
end
```

Then you get output with a new context for each scenario, and the `let` keys and values in the context description.

### Actual behavior
As far as I'm aware this or similar functionality doesn't exist. Please correct me if I'm wrong. Do you think this is something you'd be interested in having a pull request for?
I find it really convenient for covering lots of cases in a relatively easy-to-read intuitive form.
I prefer it to heavily nested contexts that cover (or may miss some coverage) the same set of (or a subset of) edge cases.

It would probably be nicer if the syntax could avoid needing passing in `self`, but I haven't investigated to see how doable that is.

I'd be happy to have a stab at it, if you think it belongs in RSpec.

I've not really contributed (much?) to RSpec, so I'm not sure whether this would live in rspec-core or somewhere else. Apologies if it's not here.

**Comment by JonRowe** [comment]
I would implement this using shared examples, which is intended for this sort of repetition:

```
shared_examples_for "my example" do |**kwargs|
  kwargs.each { |name, value| let(name) { value }
  it "works" do
     expect(foo && bar).to eq baz
  end
end

it_behaves_like "my example", foo: false, bar: false, baz: false
it_behaves_like "my example", foo: false, bar: nil,   baz: false
it_behaves_like "my example", foo: nil,   bar: nil,   baz: false
#...
it_behaves_like "my example", foo: true,  bar: true,  baz: true
```

**Comment by pirj** [comment]
It would make an interesting RSpec extension. But with an existing alternative notation, I would suggest keeping it as an extension, and keeping the core less TIMTOWTDI.

**Comment by markburns** [comment]
Fair points.

I've found shared example failures to be pretty opaque in the past, but it could have been how they were used.

I'll take another look at that approach. Named keywords looks like a good simplification. It sounds like addressing any issues with shared_examples would be a better focus if I can remind myself what the troubles were.

**Comment by markburns** [comment]
Hey so I'm re-opening this, just to say I have tried out the shared_examples approach.

I do still find it to be quite opaque for understanding failures.

What would your thoughts be on automatically adding in a context similar to the above that uses passed in arguments to describe the context?

Is that something worth pursuing?

**Comment by markburns** [comment]
To clarify, to add this to the `shared_examples` functionality rather than this proposed `with_lets` method

**Comment by pirj** [comment]
You can do that, too:
```ruby
shared_examples "my example" do |foo:, bar:, baz:|
  context "with foo: #{foo}, bar: #{bar}, baz: #{baz}" do
    it "works" do
       expect(foo && bar).to eq baz
    end
  end
end
```
Even simpler when you use `**kwargs`. To define `let`s, you can use this one-liner:
```ruby
context "with #{kwargs}" do 
  kwargs.each { |name, value| let(name) { value } }
```

**Comment by markburns** [comment]
Yes, that's possible, but from what I've seen, I don't think generally people actually _do_. So you get identical opaque failure messages. Which probably leads to less people using them. And then people like me still wanting something briefer.

Would there be disadvantages to adding in these contexts by default? Each time you use a new combination of arguments for a shared example, it seems to me that it's conceptually a new context.

**Comment by JonRowe** [comment]
Shared examples uses a new context each time already

**Comment by markburns** [comment]
Ok so I'm just on mobile now but will look at the code later.

Maybe I need to rephrase it as "would there be any issues with automatically naming these contexts by default in a way which makes the failure output more useful"

**Comment by JonRowe** [comment]
> would there be any issues with automatically naming these contexts

The name is generated from the method used to invoke the group, and the name of the shared examples, inspecting meta data is potentially possible but would create potentially rather large names which are also class names, (basically we can't guarantee that they are primitives)

**Comment by markburns** [comment]
Ah I see. 

Ok well perhaps I'll gemify it at some point.

Thanks for your time.

**Comment by pirj** [comment]
> uses a new context each time already

Unless used with `include_examples`.

@markburns What do you propose exactly, how would it look in specs?
Something like that?
```ruby
shared_examples_with_description_including_parameters "my examples" do |foo: bar:, baz:|
  # ...
end
```

To keep in mind, `it_behaves_like` accepts a block that you can also use to define `let`s:
```ruby
it_behaves_like "my examples", foo: 1, bar: 2 do
  let(:baz) { 'baz' }
end
```
but in this case it won't be possible for a shared example group to have a description that includes `baz`.

**Comment by markburns** [comment]
@pirj in an ideal world it would just be

```ruby
shared_examples 'my examples' do |foo:, bar:, baz:|
  # ...
end
```

But I'm not sure it's all that viable with the caveats you and Jon have presented.
I suppose if I were to address your `it_behaves_like` scenario, I'd say that the generated context containing only the `foo: 1, bar: 2` would be the least surprising thing.

Given that `with_lets` does what I want and is a small amount of code though I think it does make sense to just create a gem.
