### ISSUE TITLE
.rspec configuration works only when calling rspec form the containing folder

### ISSUE THREAD

**Issue by BroiSatse** [rspec/rspec-core#2919]
### .rspec file ignored when executing test while in a subfolder
`.rspec` file works as expected, but only when running tests from the directory containing .rspec file. 

### Your environment
* Ruby version: 2.7.2p137
* rspec-core version: 3.10.1

### Steps to reproduce
Having any test suite with `.rspec` file, enter `spec` folder and run `rspec .` - tests will be executed without `.rspec` configuration

### Expected behavior
When searching for configuration, rspec should recursively check parent folders for `.rspec` files and merge their configuration

### Actual behavior
When running tests while inside one of the subfolders, rspec behaves as no .rspec file exists - which is problematic when configuration includes `--require` options.

**Comment by JonRowe** [comment]
Sorry, this is by design, we don't want to recursively check folders for `.rspec` files, that gets problematic in mono repos or vendored projects and for example would mean we require home folder `.rspec` files twice, the expectation is you run rspec from the project root.
