### ISSUE TITLE
User-defined metadata is not passed to examples without descriptions

### ISSUE THREAD

**Issue by malclocke** [rspec/rspec-core#2921]
### User-defined metadata is not passed to examples without descriptions
May or may not be considered a bug, but it doesn't seem to be possible to pass user-defined metadata to an example (I think `describe` and `context` too) without a description.  It's probably not considered best practice but writing examples without a description is something I do in the wild fairly often:
```ruby
RSpec.describe 'all the description I need right here' do
  example do
    ...
  end
end
```
Whilst examples work with no arguments like this, if custom metadata is defined it doesn't get passed to the example
### Your environment
* Ruby version: 2.7.3
* rspec-core version: 3.10.0

### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.10.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

RSpec.describe 'metadata without description' do
  example 'has a description', foo: 42 do |example|
    expect(example.metadata[:foo]).to eq(42)
  end

  # Doesn't have a description
  example foo: 42 do |example|
    expect(example.metadata[:foo]).to eq(42)
  end

  # Parenthesis don't help
  example(foo: 42) do |example|
    expect(example.metadata[:foo]).to eq(42)
  end
end
```
### Expected behavior

The above test should pass.

### Actual behavior

```
$ ruby metadata.rb 
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Using bundler 2.1.4
Using diff-lcs 1.4.4
Using rspec-support 3.10.3
Using rspec-core 3.10.1
Using rspec-expectations 3.10.1
Using rspec-mocks 3.10.2
Using rspec 3.10.0
Ruby version is: 2.7.3
.FF

Failures:

  1) metadata without description {:foo=>42}
     Failure/Error: expect(example.metadata[:foo]).to eq(42)
     
       expected: 42
            got: nil
     
       (compared using ==)
     # metadata.rb:26:in `block (2 levels) in <main>'

  2) metadata without description {:foo=>42}
     Failure/Error: expect(example.metadata[:foo]).to eq(42)
     
       expected: 42
            got: nil
     
       (compared using ==)
     # metadata.rb:31:in `block (2 levels) in <main>'

Finished in 0.00883 seconds (files took 0.04549 seconds to load)
3 examples, 2 failures

Failed examples:

rspec metadata.rb:25 # metadata without description {:foo=>42}
rspec metadata.rb:30 # metadata without description {:foo=>42}
```
I'm happy to attempt a fix if the team consider it a bug.  Thanks folks, love your work :heart: :raised_hands:

**Comment by pirj** [comment]
Thanks for bringing this up.
This is as designed:
```
      #   @overload $1(&example_implementation)
      #     @param example_implementation [Block] The implementation of the example.
      #   @overload $1(doc_string, *metadata)
      #     @param doc_string [String] The example's doc string.
      #     @param metadata [Array<Symbol>, Hash] Metadata for the example.
      #       Symbols will be transformed into hash entries with `true` values.
      #   @overload $1(doc_string, *metadata, &example_implementation)
      #     @param doc_string [String] The example's doc string.
      #     @param metadata [Array<Symbol>, Hash] Metadata for the example.
      #       Symbols will be transformed into hash entries with `true` values.
      #     @param example_implementation [Block] The implementation of the example.
```
Methods defining examples consider the first argument as a docstring, even if it's an option hash.
This is also the case for `specify` that doesn't usually come with a docstring.

This issue comes up sporadically, I have had the same question myself a while ago. It's probably something worth documenting. I'd suggest adding a new file, `features/metadata/usage.feature` that would contain examples corresponding to the above doc and this specific case when there's no docstring.

**Comment by JonRowe** [comment]
I'd add we encourage docstrings, as one of the points of using RSpec is to provide descriptive tests, its one of the reasons we've extracted (essentially soft deprecating) things like the `its` one line syntax extension.

We could add a warning if there isn't a string passed as the first argument, maybe in RSpec 4?

**Comment by pirj** [comment]
> We could add a warning if there isn't a string passed as the first argument, maybe in RSpec 4?

Indeed!
There are more legitimate cases when it's not a string, though.
Class - even if we don't really recommend it since it triggers eager loading. Can be both for top-level example groups and nested, too, e.g.
```ruby
RSpce.describe Calculations do
  describe Calculations::Sum do
```

Symbols.
```ruby
context :celsius do
# even though
context 'when the temperature is presented in Celsius' do
# would be better
```
 I'm on the fence with this, since users may think it's used as metadata. Need to gather usages from real-world apps usage.
```ruby
context #focus do
```
