### ISSUE TITLE
Inherit and extend let definitions in inner describe blocks.

### ISSUE THREAD

**Issue by Peeja** [rspec/rspec-core#294]
I've taken to an idiom like the following:

```
describe Post do
  subject { Post.new(post_attributes) }
  let(:post_attributes) { { } }

  its(:description) { should be_empty }

  describe "with a title" do
    let(:post_attributes) { { title: "10 things about yak shaving you're doing wrong" } }

    its(:description) { should == "10 things about yak shaving you're doing wrong" }

    describe "with an author" do
      let(:post_attributes) { { title: "10 things about yak shaving you're doing wrong", author: "Ernest Holbrecht" } }

      its(:description) { should == "10 things about yak shaving you're doing wrong by Ernest Holbrecht" }
    end
  end
end
```

The `Post.new` call is DRYed up into the top of the spec, and each nested describe block defined what's different from its parent block.  Except: here, the innermost describe block's definition of `post_attributes` repeats the title from the one above it.

I'd prefer to say something like this:

```
context "with an author" do
  let(:post_attributes) { super.merge( author: "Ernest Holbrecht" ) }

  its(:description) { should == "10 things about yak shaving you're doing wrong by Ernest Holbrecht" }
end
```

Unfortunately, I don't think we can use `super`, it would have to be `super()` (which is uglier) or else we'd get the error "Implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly."

So this issue is here to decide two things:
1. Is this a good thing to add to RSpec?
2. If so, what's the right word to use to refer to the inherited value of a let?

I'm happy to write the implementation.

**Comment by dmitry** [comment]
Nice. I found this topic in 2019. :+1: Still working for RSspec 3.8.

**Comment by aesyondu** [comment]
[TLDR;](https://github.com/rspec/rspec-core/pull/757/files#diff-112a3ec80f232a6de7289060604874f6R39)

```ruby
context 'when overriding let in a nested context' do
  let(:a_value) { super() + " (modified)" }

  it 'can use `super` to reference the parent context value' do
    expect(a_value).to eq("a string (modified)")
  end
end
```

**Comment by robinboening** [comment]
Only found this neat feature so many years later ❤️ 

I stumbled into an error when using `super` instead of `super()`, but It is nicely explained here: https://rspec.info/blog/2013/02/rspec-2-13-is-released/#let-and-subject-declarations-can-use-super
