### ISSUE TITLE
Arguments of shared example evaluated before any `before` block

### ISSUE THREAD

**Issue by YarikST** [rspec/rspec-core#2947]
### Subject of the issue
Arguments of shared example evaluated before any `before` block. We should mention this in [docs](https://relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples)

### Your environment
* Ruby version: 2.6.8
* rspec-core version: 3.8.2

### Steps to reproduce

```
describe 'ArgumentsOfSharedExamples' do
  before do
    puts "This line appears once arguments are evaluated"
    puts Time.current
    travel_to Time.current.middle_of_day.utc
  end

  after { travel_back }

  shared_examples 'rspec-examples' do |run_date|
    it 'should be the middle of day' do
      expect(run_date).to eq Time.current.middle_of_day
    end
  end

  puts "Evaluated arguments"
  puts Time.current
  include_examples 'rspec-examples', Time.current.middle_of_day
end
```

**Comment by JonRowe** [comment]
This is just normal Ruby precendence. Things outside of specs are evaluated before specs are run.
