### ISSUE TITLE
Force incremental output when $stdout isn't a tty

### ISSUE THREAD

**Issue by tammersaleh** [rspec/rspec-core#2962]
I'd like a flag that tells the progress formatter to flush stdout after each `.` so that it's immediately printed to the terminal, even if `rspec` detects that it's not running under a TTY.  (I expect this would be useful regardless of formatter, but this is the formatter I'm currently using)

### Your environment
* Ruby version: 2.7.6p219
* rspec-core version: 3.10.1

### Steps to reproduce

Run `rspec -f p | cat` 
### Expected behavior

Each dot would show as soon as the respective test is run.

### Actual behavior

The dots aren't shown until all of the tests finish running.

**Comment by pirj** [comment]
Are you certain that there is something in RSpec that can fix this? Isn’t it related to the pipe buffer?

**Comment by tammersaleh** [comment]
You are correct!

**Comment by tammersaleh** [comment]
(well, mostly! for those who stumble on this because of Google:  I was using a non-standard `cat`.  GNU `cat` is unbuffered by default, so if you try to reproduce this using standard `cat`, you'll see each `.` printed separately.)
