### ISSUE TITLE
warning: Passing safe_level with the 2nd argument of ERB.new is deprecated.

### ISSUE THREAD

**Issue by CoderJayUK** [rspec/rspec-core#2976]
Running `bundle exec rspec` produces the following error. Infact even running `bin/rspec --version` produces the error:

```
/home/coderjay/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:171: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/home/coderjay/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:171: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```

### Environment
* Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
* rspec-core version: 3.5.4

**Comment by JonRowe** [comment]
Please upgrade to a later version

**Comment by JonRowe** [comment]
:wave: Please use the latest version of RSpec, anything below `3.12.0` is unsupported, and there is a fix related to this already.

**Comment by CoderJayUK** [comment]
Thanks folks, upgraded to 3.12 and errors have gone.
