### ISSUE TITLE
Force-run of skipped examples

### ISSUE THREAD

**Issue by svyatov** [rspec/rspec-core#3004]
### Summary
I want to be able to force-run skipped examples.

### Reasoning
A long time ago, I had to "disable" a lot of specs in a project (via `xit` and `xdescribe`), along with lots of code commented out. I needed to turn off many features and notifications in the codebase.

Now it's time to bring the specs back. Some of the code has already been uncommented, so the ideal solution would be to run "disabled" (read `skipped`) specs only and quickly check which ones I can "enable" by `xit` -> `it`.

It seems there is no way to do it at the moment. I figured I could isolate skipped specs by using the `--tag` parameter like so `rspec --tag skip`. This correctly selects all the skipped specs, but there is no way to force them to run :(

It might be a rare edge case, or maybe I'm looking at the problem from the wrong angle.

I'm happy to contribute and implement this feature if more people find it useful.

**Comment by pirj** [comment]
What I can suggest is to mass-replace `xit`/`xdescribe` with using metadata directly:
```diff
- xit 'does this' do
+ it 'does this', feature: :one do
```

This way you can still skip them by default:
```ruby
RSpec.configure do |config|
  config.define_derived_metadata(:feature) do |meta|
    meta[:skip] = meta[:feature].to_s # skip for features
    meta[:skip] = meta[:feature].to_s if meta[:feature] == :one # skip for select features
  end
end
```

or adding the following to your `.rspec` file:
```
    -t, --tag TAG[:VALUE]              Run examples with the specified tag, or exclude examples
                                       by adding ~ before the tag.
                                         - e.g. ~slow
                                         - TAG is always converted to a symbol
```

If you run `rspec --tag feature` to run only those tagged examples. By default it would run without them.

http://rspec.info/help/ is a good starting point for general questions
[Related doc](https://relishapp.com/rspec/rspec-core/v/3-9/docs/command-line/tag-option)
