### ISSUE TITLE
Rspec tests loading the wrong 'uri' in rspec after upgrading Bundler

### ISSUE THREAD

**Issue by SpyMachine** [rspec/rspec-core#3007]
### Your environment
* Ruby version: 2.7.6
* rspec-core version: 3.12.1
* Bundler version: 2.4.6

### Steps to reproduce
Create a project with the following structure:

- lib
    - uri.rb
- spec
    - uri_spec.rb
- Gemfile

In both uri.rb and uri_spec.rb you can put the following:

```
test = require 'uri'
puts test # returns `true`
::URI::Parser.new
```

and in Gemfile
```
source 'https://rubygems.org'

gem 'rspec', '~> 3.12.0'
```

Then `bundle install` and run `bundle exec rspec`. You will get the following error:

### Expected behavior
I would expect it to load the 'uri' gem from the Ruby standard library and run the code successfully.

### Actual behavior
```
An error occurred while loading ./spec/uri_spec.rb.
Failure/Error: ::URI::Parser.new

NameError:
  uninitialized constant URI
# ./spec/uri_spec.rb:3:in `<top (required)>'
No examples found.
```

However, if you run `ruby ./lib/uri.rb` this will run just fine.

It seems to me that the issue is from this method [here](https://github.com/rspec/rspec-core/blob/main/lib/rspec/core/ruby_project.rb#L12-L14). This causes the lib folder to get added to the $LOAD_PATH first and will check here before it checks the std library. Thus, it sees "uri.rb' from lib and it seems impossible to load the one from the standard library without changing the name of my local file. This is an option, but it seems like confusing behavior to me and I feel like rspec is making assumptions that perhaps it should not.

I can workaround this problem by adding the `-ruri` flag but it also doesn't seem to be possible to add ruby options when running rspec directly.

By the way, this problem started for us when upgrading from Bundler 1.17 to Bundler 2.4 and I think is likely due to [this](https://bugs.ruby-lang.org/issues/18147) because "uri" was required in Rubygems.

**Comment by pirj** [comment]
What your suggestion would be for RSpec?

**Comment by JonRowe** [comment]
You should not shadow library names off the standard library or any other gem, if you has this as `lib/my_lib/uri.rb` you'd be fine, its common practise to load `lib/<library_name>.rb` within gemspecs for example. I'd suggest renaming your file.
