### ISSUE TITLE
Documentation on https://relishapp.com/rspec/ is down

### ISSUE THREAD

**Issue by schnittchen** [rspec/rspec-core#3010]
It's been for a couple of days now.

**Comment by benoittgt** [comment]
Hello

Yes it is well known issue that is on all relish website and we have no way to change it at the moment.

Closing because it is not related to rspec-core itself.

See: https://github.com/rspec/doc-site/issues/5#issuecomment-1446152910

**Comment by JonRowe** [comment]
The relish documentation has been replaced by a self hosted version, you can find it via https://rspec.info/documentation/
