### ISSUE TITLE
Relish is down!

### ISSUE THREAD

**Issue by TravisSpangle** [rspec/rspec-core#3011]
### Documentation is offline

Cannot review documentation on relish. Are there plans to move the documentation?

**Comment by dmke** [comment]
In the meantime, the Wayback Machine has [some snapshots](https://web.archive.org/web/*/https://relishapp.com/rspec). The latest [one from 2023/02/07](https://web.archive.org/web/20230207010221/https://relishapp.com/rspec).

Of course, the search doesn't work there.

**Comment by JonRowe** [comment]
The relish documentation has been replaced by a self hosted version, you can find it via https://rspec.info/documentation/

**Comment by mayanks-github** [comment]
Than you @dmke for snapshot reference

**Comment by JonRowe** [comment]
You shouldn't need a snapshot the exact same documentation is hosted on our website, unless you're looing for 2.x documentation.
