### ISSUE TITLE
relish app down

### ISSUE THREAD

**Issue by phoet** [rspec/rspec-core#3012]
dont know where to put this, but the rspec docs are not accessible cause the [relish app](https://relishapp.com/) on heroku is down 🤷 

<img width="510" alt="Bildschirmfoto 2023-03-02 um 14 39 44" src="https://user-images.githubusercontent.com/48745/222444705-fb0ee260-e8e0-4b21-89c9-bb776e9702a1.png">

**Comment by JonRowe** [comment]
Duplicate of #3011 #3010 #3009, please read those issues.

**Comment by phoet** [comment]
well, maybe keep one of them open? that would have prevented this issue.

**Comment by JonRowe** [comment]
Its not something we can solve

**Comment by JonRowe** [comment]
The relish documentation has been replaced by a self hosted version, you can find it via https://rspec.info/documentation/

**Comment by rpelorosso-sv** [comment]
Ah yes, thank you! I was hoping better documentation was provided. These
feel like a robotic translation of the code structure, sadly :(

**Comment by eric-norcross** [comment]
@JonRowe given it's been down for a few months now, are there plans to fix the issue/relaunch? Or should the site be considered dead?

**Comment by phoet** [comment]
https://rspec.info/documentation/

**Comment by JonRowe** [comment]
@eric-norcross we replaced our usage of it with our own self hosted documentation (which is linked to above) e.g. https://rspec.info/features/3-12/rspec-core/ its is the same content as Relish had.
