### ISSUE TITLE
How can I add a custom command option for rspec --order like `rspec --order prioritized`

### ISSUE THREAD

**Issue by Aiderlei** [rspec/rspec-core#3024]
Hey,

I am working on a gem to prioritize specs in a specific order and just realized that calling `rspec path_1 path_2 path_3` applies the preset ordering to path_1, path_2, path_3 instead of running it in passed order. 

So I was wondering how can I achieve this the easiest way.

As far as I know by now I would have to use `register_ordering` and looked at some example for that. So far so good, but how would I add an option to use my newly defined order from command line? 

Thanks!

**Comment by JonRowe** [comment]
In short, you can't. Currently you can configure the ordering globally, or define a strategy to tag examples with.

However I was surprised that this didn't just work, so I fixed it, #3025 will allow custom ordering via the CLI in a future version. Closing in favour of #3025, please see if that will suit your use case.

**Comment by Aiderlei** [comment]
@JonRowe Ok thank you!!
