### ISSUE TITLE
Raise errors if `it` executed in a `before` block

### ISSUE THREAD

**Issue by fmichaut-diff** [rspec/rspec-core#3038]
### Subject of the issue
Currently, if a `it` block (example block) is defined inside a `before` block, the `it` block will never run.

### Your environment
* Ruby version: 3.2.0
* rspec-core version: 3.12.2

### Steps to reproduce
```ruby
[...]
      context 'some deeply nested context' do
        let(:deleted_list) { [] }

        before do
          expect(TestClass).to receive(:delete).exactly(60).times do |arg|
            deleted_list << arg.to_i
          end

          it 'only uses what was deleted' do
            expect do
              described_class.new(object).call
            end.to change(deleted_list, :size).by(+60)

            expect(deleted_list).to eq(ids_list)
          end
        end
      end
[...]
```

This will never run, because the `end` of the before is after the `it` block. (this is a mistake, and currently no errors are raised so the user believes it is working)

### Expected behavior
This should raise an error, as much as using `let` in an `it` block is an error.

### Actual behavior
The current behavior silently skips the `it` blocks, and the user might never realise the specs are never run.

**Comment by JonRowe** [comment]
:wave: You do get an error if the block is executed:

```
`it` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).
```

But if you have no other specs the block is never executed, which is what happened in your case.
