### ISSUE TITLE
No way to filter tags with and logic

### ISSUE THREAD

**Issue by LukeIGS** [rspec/rspec-core#3061]
### Subject of the issue
When running tests, it's sometimes useful to be able to run a subset of tests constrained by a pair of tags, currently doing so will run all examples matching either tag.

### Your environment
* Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
RSpec 3.12
  - rspec-core 3.12.2
  - rspec-expectations 3.12.3
  - rspec-mocks 3.12.6
  - rspec-support 3.12.1

### Steps to reproduce
1. create a spec file with the following content
```ruby
RSpec.describe 'foo', type: 'integration' do
  it 'bar', target: 'cart' do
    expect(true).to be
  end

  it 'baz' do
    expect(true).to be
  end

end

RSpec.describe 'qux', type: 'feature' do
  it 'bar', target: 'cart' do
    expect(true).to be
  end

  it 'baz' do
    expect(true).to be
  end

end
```
1.  run `rspec -t type:integration -t target:cart`

### Expected behavior
Should only run foo -> bar and qux -> bar

### Actual behavior
runs foo -> bar, foo-> baz and foo -> bar

### Workaround
Define the following and require it somewhere before rspec filters examples (like the spec_helper.rb)
```ruby
module RSpecAndFilter
  def include_example?(example)
    @rules.empty? || RSpec::Core::MetadataFilter.apply?(:all?, @rules, example.metadata)
  end

  RSpec::Core::InclusionRules.include(RSpecAndFilter)
end
```

**Comment by pirj** [comment]
Why should it run qux:bar, it’s not of an integration type?

**Comment by pirj** [comment]
There’s an extensive discussion in #1622 , so I’ll close this as a duplicate.

**Comment by LukeIGS** [comment]
I mispoke, it should only have run one test.  Sorry for opening a dupe, i couldn't find that issue.
