### ISSUE TITLE
Adding ProfileFormatter report to output stream?

### ISSUE THREAD

**Issue by Leee-xx** [rspec/rspec-core#3082]
### Subject of the issue
Is there a way to include the profile report (i.e. the one listing the slowest-running tests) into the specified output stream? I poked around and it seems to only ever print to STDOUT, even if I've specified an `--out`. (Our goal is to include the report in our CI build artifacts.)

### Your environment
* Ruby version: 3.1.2
* rspec-core version: 3.13.0

### Steps to reproduce
```bash
bundle exec rspec --profile --out blah.out
```

### Expected behavior
Report is printed in the specified output stream.

### Actual behavior
Report only printed to STDOUT.

**Comment by pirj** [comment]
If I’m not mistaken, output is only for ‘—formatter’, see https://github.com/rspec/rspec-core/blob/1e661db5c5b431c0ee88a383e8e3767f02dccbfe/features/command_line/format_option.feature#L76

I think it makes sense to allow —profile to output to any stream, too. Would you like to contribute this?

**Comment by JonRowe** [comment]
The profile formatter does take a configurable output stream, but it is the "main" configuration stream which comes from the config. `--out` is intended to configure formatters passed on the comand line, or progress by default, the docs even state this:

```
  You can also specify an output target (`$stdout` by default) with an `--out`
  option immediately following the `--format` option:

  ```bash
  $ rspec spec --format documentation --out rspec.txt
  ```
```

If you configure RSpec using config you should get the effect you want:

```
RSpec.configure do |config|
  if ENV['CI']
    config.output_stream = File.open('ci_out.txt', 'w')
  end
 end
```
