### ISSUE TITLE
Failed to clone rspec repo on the branch `4-0-dev`

### ISSUE THREAD

**Issue by eisukeyeongjo** [rspec/rspec-core#3088]
### Failed to clone rspec repo during CI

On the branch `4-0-dev` , every job on CI failed to clone rspec repository and are down.
https://github.com/rspec/rspec-core/actions/runs/8874478323/job/25365014656?pr=3081

```
Run script/clone_all_rspec_repos
  script/clone_all_rspec_repos
  shell: /usr/bin/bash -e {0}
  env:
    RSPEC_CI: true
    RSPEC_VERSION: = 4.0.0.pre
    __UNUSED_VARIABLE: Prevents build error when {matrix.env} is used.
~/work/rspec-core ~/work/rspec-core/rspec-core
Cloning into 'rspec'...
fatal: could not read Username for 'https://github.com/': No such device or address
Error: Process completed with exit code 128.
```

This is because rspec repo was renamed to rspec-metagem on  Oct 27, 2021(I found [this commit](https://github.com/rspec/rspec-metagem/commit/a6fb2b4bb7b7aa50625d8f66b553d3fc6bcc1a0d)) and we have to update [script/clone_all_rspec_repo](https://github.com/rspec/rspec-core/blob/4-0-dev/script/clone_all_rspec_repos)

**Comment by JonRowe** [comment]
`4-0-dev` will be back in active development after we switch to the monorepo
