### ISSUE TITLE
Feature Request: Allow CLI tags option to specify a hash

### ISSUE THREAD

**Issue by olbrich** [rspec/rspec-core#3092]
### Subject of the issue

Assuming I have a spec like...

```ruby
it "does something useful", tag1: { tag2: true } do
  ...
end
```

It is currently not possible to include or exclude this style of tag from the CLI.

### Your environment

* Ruby version: 3.3.2
* rspec-core version: 3.13.0

### Expected behavior
I'd like to be able to do something like..

```sh
rspec --tag tag1:tag2:true
# or
rspec --tag tag1:{tag2:true}
```

### Actual behavior

RSpec attempts to run specs tagged with `tag2:true` or `{tag2:true}` as strings

**Comment by pirj** [comment]
Can you give some examples of nested tags in other tools?
This looks interesting. Can you provide some examples from your daily usage, unless it’s super secret?

Somewhat related https://github.com/rspec/rspec-core/issues/1821

**Comment by JonRowe** [comment]
:wave: Although we allow complicated metadata for examples (which is what you've set when thinking of it as tag1) as you've noted the cli isn't capable of filtering on those complicated values, however this isn't something I want to expand here, instead put your tags into the top level.

If this is about being able to pass in the metadata from outside, consider splatting the hash instead e.g.
```
# instead of
it "does the thing", tag1: my_hash
# do
it "also does the thing, **my_hash
```
