### ISSUE TITLE
Exclude an array of tag values

### ISSUE THREAD

**Issue by runephilosof-abtion** [rspec/rspec-core#3120]
### Subject of the issue
Exclude an array of tag values.

### Your environment
* Ruby version: 3.1.6
* rspec-core version: 3.13.1

### Steps to reproduce
```
rspec --tag ~type:model --tag ~type:system
```

### Expected behavior
```
Run options: exclude {:type=>["model","system"]}
```

### Actual behavior
```
Run options: exclude {:type=>"system"}
```

**Comment by runephilosof-abtion** [comment]
I agree that it is the expected behavior according to the docs, it is a feature proposal.
However, it is not a duplicate of #1622, because I was still aiming for a `OR` between the two values (which I did not make clear).

**Comment by JonRowe** [comment]
#1622 covers both AND and OR and the need to disambiguate behavior
