### ISSUE TITLE
Forced color output

### ISSUE THREAD

**Issue by Shamaoke** [rspec/rspec-core#326]
Hi.

In versions of RSpec before 2.0 it was possible to pipe the color output to pagers or redirect it to a file. There's the RSPEC_COLOR environment variable for that purpose. However, now the usage of that variable is unsupported, the color tags is stripped in the mentioned conditions and the output in the Less or More pagers becomes monochrome. Also, there are no color tags in the output file. 

I would like to have an ability to color the piped or redirected output. It can be realised by adding the `--force-color` option for example or may be better to not allow the present `--color` option to strip the color tags.

Thanks.

**Comment by franklinyu** [comment]
Option `--tty` will do it. Put it in `~/.rspec` if you want it globally.
