### ISSUE TITLE
Feature Idea: Fail examples when no expectation was set

### ISSUE THREAD

**Issue by sens3** [rspec/rspec-core#404]
I'm wondering if it would make sense to fail an example if no expectations were set during it's execution.

Basically I'd want to be notified (one way or the other) if I do something like this

```
it "shoud calculate a tuples sum" do
  tuple =  Tuple.new(1,2)
  tuple.sum == nil
end

it "should process the payment" do
end
```

Both examples will "pass". All green. Programmer is happy (at least for a while).

Another useful addition might be to fail examples if a message expectation is the last expression in the example, and thus cannot be met:

```
it "saves the record" do
  post :create
  @user.should_receive(:save)
end

after do
  # nothing here
end
```

(I hope I haven't forgotten any corner cases where the expectation could still be met)

One can argue that programmers should be smart enough not to write tests like this. On the other hand, having a passing example should guarantee that something was in fact passed.

Any thoughts?

Simon

**Comment by christophweegen** [comment]
Any progress on this feature? Code below doesn't work anymore. ( RSpec 3.8 ). Thanks!

> FWIW, here's a way to get this:
> 
> ```ruby
> RSpec.configure do |config|
>   config.after(:each) do
>     result = self.example.metadata[:execution_result]
>     has_mock_expectations = RSpec::Mocks.space.instance_eval{receivers}.empty?
>     if !result[:exception] && !result[:pending_message] && !RSpec::Matchers.last_should && hasnt_mock_expectations
>       $stderr.puts "[WARN] No expectations found in example at #{self.example.location}: Maybe you forgot to write `should` in the example?"
>     end
>   end
> end
> ```
> 
> (taken from [this blog post](http://blog.sorah.jp/2012/12/17/rspec-warn-for-no-expectations)).

**Comment by JonRowe** [comment]
There is no feature planned here. I'd imagine the code snippet needs modifying for the new expect syntax.
