### ISSUE TITLE
Print failure/error messages on STDERR

### ISSUE THREAD

**Issue by mrtazz** [rspec/rspec-core#668]
The default rspec run doesn't output failure messages on STDERR but STDOUT. This kind of makes sense, since a failure in the suite is not an error in rspec itself. However for integrating it into other tools (which was how I discovered it) and given the fact that a failure in the spec suite can be regarded as an error, I think outputting failure messages on STDERR would make sense.

Any thoughts on this?

**Comment by pboling** [comment]
@mrtazz (or anyone) what custom formatter are you using to split the output?  I find myself in the same situation now.

**Comment by mrtazz** [comment]
> what custom formatter are you using to split the output?

@pboling it's been over 10 years since I worked on this so I honestly don't have any details in my head anymore (and no access to the codebase either) 😬 . But if I remember correctly I wrote our own formatter which implemented `Formatter#dump_failures` to write to `STDERR`.
