### ISSUE TITLE
Logging output should not use tty configurations, i.e. color

### ISSUE THREAD

**Issue by chendrix** [rspec/rspec-core#675]
Currently, when outputting to a file using

`--format documentation --out log/spec.log`

while having your configurations use colorized output (for tty, presumably), the output file it creates contains a bunch of escaped color codes, e.g. `:ESC:[32m`

```
Buildtool
[32m  is truthy[0m
  validations
[32m    should require name to be set[0m
[32m    should require case sensitive unique value for name[0m
  when basic buildtool
[32m    should be valid[0m
[32m    should eq "Bamboo"[0m
  when invalid
[32m    should be invalid[0m

Finished in 0.25029 seconds
[32m6 examples, 0 failures[0m
```

I assume this is because it's simply taking what would be outputted to `STDOUT` and redirecting it to a log file.

**Comment by jonworek** [comment]
I'm seeing this issue in RSpec 3.9.1. Is there a chance that a regression might have been introduced since this was fixed?

**Comment by JonRowe** [comment]
You can force it off with configuration.
