### ISSUE TITLE
Support multiple mocking frameworks

### ISSUE THREAD

**Issue by dchelimsky** [rspec/rspec-core#683]
Switching mocking frameworks in a suite is currently an "all at once" deal because there is no support for using more than one mocking framework at a time.

@jimweirich is working on a workaround for this in flexmock, but it depends on paths that are internal to rspec: https://gist.github.com/3738752

Let's consider making the adapters shipped w/ RSpec composable, so that we can support more than one, e.g.

``` ruby
RSpec.configure do |c|
  c.mock_with :rspec, :flexmock, :mocha, :rr
end
```

**Comment by mrageh** [comment]
@myronmarston what's the status of this issue?

**Comment by JonRowe** [comment]
Very stale...

**Comment by myronmarston** [comment]
Yep, quite stale.  It's one of those things that it'd be nice if RSpec had but that I doubt I'll ever get to.  Maybe someone will contribute it at some point, though.

**Comment by brunomeira** [comment]
+1?

**Comment by yivo** [comment]
There is a nice gem for it: https://github.com/endeepak/rspec-multi-mock

**Comment by myronmarston** [comment]
Thanks for pointing that out @yivo!  Given the rarity of the need for this feature, I think it makes sense for it to exist as an extension gem rather than as part of rspec itself.  Closing.
