### ISSUE TITLE
Command-line flag to run specs multiple times

### ISSUE THREAD

**Issue by afeld** [rspec/rspec-core#795]
I have some integration tests that are failing inconsistently, and as I'm fixing them I'd love to be able to run specific specs multiple times to see which still fail intermittently.  Something like the following:

```
$ rspec -n 3 spec
...
  should pass consistently

Finished in 43 seconds
1 example, 1/3 failures
```

Thoughts?

**Comment by avit** [comment]
Running the test suite repeatedly (in the same process) would also be helpful for tracing memory leaks.

**Comment by lionelperrin** [comment]
Hello,

I discover this request right now, looking for the same option. 

This ability to repeat a test suite exists in several test framework. For instance https://code.google.com/p/googletest/wiki/AdvancedGuide#Repeating_the_Tests.

This is useful to detect memory leak and in general checking that resources are correctly managed. (File closed as expected, no shadow child process or thread, etc...) Spawning several time using a bash script is not suitable in these case because cleanup will be performed by the OS.

In addition, as stated in this issue, the output of the bash script is not very user friendly.

Regards,

Lionel

**Comment by avit** [comment]
@lionelperrin the linked issue #1852 that duplicates this one also suggests running repeated tests out-of-process. I agree, this doesn't address the use case of testing for object allocations/memory leaks, or for repeatability between test suite setup & teardown.

**Comment by JonRowe** [comment]
If you want to check for object allocations / memory leaks you're better off writing a test that checks for that specifically by instantiating and measuring within that spec, that way you eliminate the extra noise that RSpec itself introduces into that environment.

**Comment by JonRowe** [comment]
Additionally you could also temporarily wrap a spec you wanted to repeat in a ruby iterator to repeat that spec, so theres another easy way to do it...

e.g.
```Ruby
ENV.fetch('REPEAT',1).to_i.times do |i|
  specify 'flakey spec' { ... }
end
```

Or implement with an around hook:

```Ruby
around(:example, flakey: true) do |ex|
  ENV.fetch('REPEAT',1).to_i.times do |i|
    ex.run
  end
end
```

**Comment by lionelperrin** [comment]
Thank you for these ideas. It is true that it is possible to test allocations/leaks with a workaround.
I understand that I can't expect an implementation of a standard 'repeat' option in future versions.
I'll go for a simple repeat loop then...

**Comment by avit** [comment]
> you're better off writing a test that checks for that specifically by instantiating and measuring within that spec

That's assuming one knows where the problem is happening. What I was suggesting could make test suites more helpful as a way to narrow that down.

An `around :all` block is helpful for one example group. I guess what I would be looking for is something like `around :suite`.

**Comment by JonRowe** [comment]
Wouldn't really help, too much noise, adding a spec would increase the allocations each time, you need to measure per example, you could use an `around :example` to achieve that for all examples if you really must of course.

**Comment by duane** [comment]
This would be highly useful for profiling memory and performance issues.

**Comment by cconstantine** [comment]
I could use this as well for memory testing

**Comment by JonRowe** [comment]
As previously stated, you're better off profiling directly, or having one test that does things multiple times to look for memory leaks and performance issues. Running specs multiple times on our side would introduce a lot of extra noise from our own instantiation.

**Comment by cconstantine** [comment]
I disagree.

I just spent 2 days attempting to find a memory leak that didn't have a clear origin.  I was hoping to add memory profiling code to the global rspec (in before/after/around callbacks), but that is really only useful if the test code runs multiple times.  I could spend time adding a `N.times {test_stuff}` to each individual test, or I could add a flag to the command line.  

It would also be really helpful for finding flaky tests, which is a constant struggle.

You may disagree (and, as an owner, you have final say), but I'd really rather my test framework have a useful feature than be forced to hack another solution up.

**Comment by dchelimsky** [comment]
Just curious @cconstantine - have you checked out https://github.com/dblock/rspec-rerun? I have no idea if it's still usable, but it might give you what you want.

**Comment by cconstantine** [comment]
That might work if I wanted to force every test to fail.  

What I want is almost an inverse of that gem; keep running tests (up to N times) until it fails.

**Comment by JonRowe** [comment]
If you're setting up your memory profiling code in around hooks it's also possible to run the examples as many times as you like.

```Ruby
around(:example) do |example|
  MyMemoryProfiler.do
    n.times { example.run }
  end
end
```

If you want to run until failure something like:

```Ruby
around(:example) do |example|
  failed = false
  until failed
    example.run rescue failed = true
  end
   # whatever logic you want to run to make it "refail etc"
end
```

**Comment by lumpidu** [comment]
I don't understand the hesitation here to accept a really useful addition to rspec. Using a command line parameter `-n` gives us the possibility to run _every_ spec multiple times or a combination of specs without changing the specs via an `around` hook in foresight. We use rspec to test device firmware and to automatically download logs from the device in case of a failure. It is an important part of the test process to repeat tests that sometimes show failures and depending on the changes inside the firmware under test, we repeat different specs differently. it's rather hacky to require  passing envirionment variables to specs or changing a single line of a spec just to add such an important feature to an otherwise excellent tool. Also repeating a complete spec via a shell for loop is a bummer: we copy ssh keys, remove data and logs from the device, etc. in the `before(:suite)` hook.

**Comment by JonRowe** [comment]
> I don't understand the hesitation here to accept a really useful addition to rspec. 

* Maintenance burden.
* Forseen internal changes required to do it.
* Unforseen internal changes required to do it.
* Formatter changes to handle new output status for a spec that passed and failed
* It's simply not a previously design use case of RSpec. It will be hacky to implement.

**Comment by xaviershay** [comment]
I'll also add:

- We already have a very wide configuration API. The further we expand it the more unwieldy it becomes for users.
- At this point we generally require new features to be implemented first as extension gems, and then to see support, before considering including them in core.

**Comment by myronmarston** [comment]
> At this point we generally require new features to be implemented first as extension gems, and then to see support, before considering including them in core.

To @xaviershay's point, does someone want to take a stab at implementing this as an extension gem?  If there are any APIs you'd need to do so, let us know.

**Comment by roberts1000** [comment]
I created a gem called [rspec_n](https://github.com/roberts1000/rspec_n) that installs an executable that will do this.   It will re-run the test suite N times by default.  You can make it stop as soon as it hits a failing suite via the `-s` cli option.  It'll spit out other stats about the iterations as well.

**Comment by BChesbrough** [comment]
Beyond memory leaks, it's also really useful to be able to re-run a test many times to help with tracking down intermittence failure and race conditions.

**Comment by JonRowe** [comment]
@BChesbrough see rspec-retry for intermittent failures
