### ISSUE TITLE
Is there an after(:each) that is invoked before reset_sessions!?

### ISSUE THREAD

**Issue by jmuheim** [rspec/rspec-core#810]
Hi!

I'm using this nice gem pry-rescue which automatically opens a pry console whenever an spec fails so I can inspect it right away.

Sadly, `reset_sessions!` is called before pry-rescue kicks in, so I'm not able to (e.g.) inspect the opened Chrome visually anymore, as it has already been blacked out.

pry-rescue does the following to inject its functionality into RSpec:

``` ruby
require 'pry-rescue'
RSpec.configure do |c|
  c.around(:each) do |example|
    Pry::rescue do
      example.binding.eval('@exception = nil')
      example.run
      if e = example.binding.eval('@exception')
        Pry::rescued(e)
      end
    end
  end
end
```

I wanted to ask if there's a way to prevent RSpec from calling `reset_sessions!` and call it manually after the pry console is closed?

Thanks a lot for help,
Josh

**Comment by pachonk** [comment]
@jmuheim What was your solution?

**Comment by jmuheim** [comment]
I have no idea, I'm not using pry-rescue anymore.

**Comment by pachonk** [comment]
Sounds good, thanks.
