### ISSUE TITLE
Shared Examples: context prevents "it" blocks from being executed when trying to execute them using a line number

### ISSUE THREAD

**Issue by jmuheim** [rspec/rspec-core#835]
Just noticed that my shared examples' `it` blocks were not executed when I ran them with an exact line number like so:

`rspec spec/my_spec.rb:123`

But when I ran them as the whole file, the `it` blocks were executed as expected:

`rspec spec/my_spec.rb`

After some debugging, I found that my shared examples' `it` blocks were in a `context` block - when I removed them, I could successfully execute them using a line number.

Is this a known bug/feature? Should I avoid contexts in shared examples?

**Comment by myronmarston** [comment]
Sorry for taking so long to fix this, but I have a fix for it now in #1837 if anyone wants to try it out.
