### ISSUE TITLE
Cannot run specs in desired order.

### ISSUE THREAD

**Issue by phuongnd08** [rspec/rspec-core#881]
I'm having a problem with a spec 2.13.0. It runs fine when being run alone, but failed when being run in a suite.  Another spec should be interfering with it.

I want to run the suspect interfering spec before that spec without any other specs to debug the problem, so I run:
rspec path/to/suspect/troublesome_spec.rb path/to/my/failed_spec.rb

However, rspec is not hornoring the order. It always run the /path/to/my/failed_spec.rb first. Even if I swap the order of the spec passing into the arguments.

My spec_helper.rb is as follow:

```
# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
Bundler.require(:rspec)
Dir[Rails.root.join("test/support/**/*.rb")].each {|f| require f}
Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}

RSpec.configure do |config|

  config.mock_with :rspec
  config.use_transactional_fixtures = false
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.infer_base_class_for_anonymous_controllers = false

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  #config.order = "random"
end
```

**Comment by graysonwright** [comment]
Update for @myronmarston's now-broken link:
https://www.relishapp.com/rspec/rspec-core/docs/configuration/overriding-global-ordering

It looks like if you pass `--order random:1`, and then a list of files, RSpec will run those files in order.

**Comment by myronmarston** [comment]
> It looks like if you pass `--order random:1`, and then a list of files, RSpec will run those files in order.

What leads you to think that? (If our docs suggest that I'd like to correct them).

RSpec always loads spec files in alphabetical order (but does not run the specs at the time it is loading the spec files).  Then it runs the top level example groups according to the global ordering, then those recursively run their examples and sub-groups according to the selected ordering, etc.
