### ISSUE TITLE
RSpec ignores other files when line numbers are specified

### ISSUE THREAD

**Issue by garybernhardt** [rspec/rspec-core#952]
I have a simple spec:

```
$ cat temp_spec.rb
describe "something" do
  it "example 1" do end
  it "example 2" do end
end
```

Running by line number works just fine:

```
$ rspec -fd temp_spec.rb:2
Run options: include {:locations=>{"./temp_spec.rb"=>[2]}}

something
  example 1

Finished in 0.0004 seconds
1 example, 0 failures
```

But if I want to run just that line, then the rest of the file, RSpec disregards the second path:

```
$ rspec -fd temp_spec.rb:2 temp_spec.rb
Run options: include {:locations=>{"./temp_spec.rb"=>[2]}}

something
  example 1

Finished in 0.00035 seconds
1 example, 0 failures
```

This command makes sense in conjunction with --fail-fast: it means "run this example, then the whole file, assuming the example passed". Well, I think it should mean that, at least!

The same thing happens even if the second filename is different from the first. I create a second spec file:

```
$ rspec -fd other_spec_file.rb

other thing
  example 3

Finished in 0.00039 seconds
1 example, 0 failures
```

and try to run one line from the first file, then the entire second file:

```
$ rspec -fd temp_spec.rb:2 other_spec_file.rb
Run options: include {:locations=>{"./temp_spec.rb"=>[2]}}

something
  example 1

Finished in 0.00034 seconds
1 example, 0 failures
```

No joy. :(

**Comment by myronmarston** [comment]
Sorry for the long delay in addressing this, @garybernhardt, but there's a fix in #1839 if you want to give that a shot.  Note that we haven't implemented the ordering semantic you mentioned you would like as the `file:num` form is only meant to provide filtering, but it will allow you to mix filtered and unfiltered files, which wasn't possible before as you noted.
